// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package dbq

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_log (actor_user_id, actor_ip, action, target_type, target_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditParams struct {
	ActorUserID pgtype.UUID
	ActorIp     *netip.Addr
	Action      string
	TargetType  string
	TargetID    string
	Metadata    []byte
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ActorUserID,
		arg.ActorIp,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT a.id, a.at, a.actor_user_id, a.actor_ip, a.action, a.target_type, a.target_id, a.metadata, u.name AS actor_name, u.email AS actor_email
FROM audit_log a
LEFT JOIN users u ON u.id = a.actor_user_id
WHERE ($1::bigint = 0 OR a.id < $1::bigint)
  AND ($2::text = '' OR a.action LIKE $2::text || '%')
  AND ($3::uuid IS NULL OR a.actor_user_id = $3::uuid)
  AND ($4::timestamptz IS NULL OR a.at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR a.at < $5::timestamptz)
ORDER BY a.id DESC
LIMIT $6::integer
`

type ListAuditParams struct {
	BeforeID     int64
	ActionPrefix string
	ActorID      pgtype.UUID
	FromAt       pgtype.Timestamptz
	ToAt         pgtype.Timestamptz
	PageSize     int32
}

type ListAuditRow struct {
	AuditLog   AuditLog
	ActorName  pgtype.Text
	ActorEmail pgtype.Text
}

// Keyset pagination: pass before_id = 0 for the first page. action_prefix must already be
// LIKE-escaped; the other filters are optional.
func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]ListAuditRow, error) {
	rows, err := q.db.Query(ctx, listAudit,
		arg.BeforeID,
		arg.ActionPrefix,
		arg.ActorID,
		arg.FromAt,
		arg.ToAt,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditRow{}
	for rows.Next() {
		var i ListAuditRow
		if err := rows.Scan(
			&i.AuditLog.ID,
			&i.AuditLog.At,
			&i.AuditLog.ActorUserID,
			&i.AuditLog.ActorIp,
			&i.AuditLog.Action,
			&i.AuditLog.TargetType,
			&i.AuditLog.TargetID,
			&i.AuditLog.Metadata,
			&i.ActorName,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
