// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocklist.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBlockedSender = `-- name: DeleteBlockedSender :one
DELETE FROM blocked_senders WHERE id = $1 AND mailbox_id = ANY($2::uuid[])
RETURNING mailbox_id, pattern
`

type DeleteBlockedSenderParams struct {
	ID         pgtype.UUID
	MailboxIds []pgtype.UUID
}

type DeleteBlockedSenderRow struct {
	MailboxID pgtype.UUID
	Pattern   string
}

func (q *Queries) DeleteBlockedSender(ctx context.Context, arg DeleteBlockedSenderParams) (DeleteBlockedSenderRow, error) {
	row := q.db.QueryRow(ctx, deleteBlockedSender, arg.ID, arg.MailboxIds)
	var i DeleteBlockedSenderRow
	err := row.Scan(&i.MailboxID, &i.Pattern)
	return i, err
}

const getBlockedSender = `-- name: GetBlockedSender :one
SELECT b.id, b.pattern, b.created_at, mailboxes.id AS mailbox_id, mailboxes.name AS mailbox_name,
    users.id AS created_by_id, users.name AS created_by_name
FROM blocked_senders b
JOIN mailboxes ON mailboxes.id = b.mailbox_id
LEFT JOIN users ON users.id = b.created_by
WHERE b.id = $1
`

type GetBlockedSenderRow struct {
	ID            pgtype.UUID
	Pattern       string
	CreatedAt     pgtype.Timestamptz
	MailboxID     pgtype.UUID
	MailboxName   string
	CreatedByID   pgtype.UUID
	CreatedByName pgtype.Text
}

func (q *Queries) GetBlockedSender(ctx context.Context, id pgtype.UUID) (GetBlockedSenderRow, error) {
	row := q.db.QueryRow(ctx, getBlockedSender, id)
	var i GetBlockedSenderRow
	err := row.Scan(
		&i.ID,
		&i.Pattern,
		&i.CreatedAt,
		&i.MailboxID,
		&i.MailboxName,
		&i.CreatedByID,
		&i.CreatedByName,
	)
	return i, err
}

const ingestSenderBlocked = `-- name: IngestSenderBlocked :one
SELECT EXISTS (
    SELECT 1 FROM blocked_senders
    WHERE mailbox_id = $1 AND pattern IN (lower($2::text), split_part(lower($2::text), '@', 2))
)::boolean AS blocked
`

type IngestSenderBlockedParams struct {
	MailboxID pgtype.UUID
	Address   string
}

// A pattern matches the whole address or its domain.
func (q *Queries) IngestSenderBlocked(ctx context.Context, arg IngestSenderBlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, ingestSenderBlocked, arg.MailboxID, arg.Address)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}

const insertBlockedSender = `-- name: InsertBlockedSender :one
WITH inserted AS (
    INSERT INTO blocked_senders (mailbox_id, pattern, created_by)
    VALUES ($1, $2, $3)
    ON CONFLICT (mailbox_id, pattern) DO NOTHING
    RETURNING id
)
SELECT COALESCE((SELECT id FROM inserted), (SELECT existing.id FROM blocked_senders existing WHERE existing.mailbox_id = $1 AND existing.pattern = $2))::uuid AS id,
    EXISTS (SELECT 1 FROM inserted)::boolean AS created
`

type InsertBlockedSenderParams struct {
	MailboxID pgtype.UUID
	Pattern   string
	CreatedBy pgtype.UUID
}

type InsertBlockedSenderRow struct {
	ID      pgtype.UUID
	Created bool
}

// created is false when the pattern was already blocked; the existing row is returned then.
func (q *Queries) InsertBlockedSender(ctx context.Context, arg InsertBlockedSenderParams) (InsertBlockedSenderRow, error) {
	row := q.db.QueryRow(ctx, insertBlockedSender, arg.MailboxID, arg.Pattern, arg.CreatedBy)
	var i InsertBlockedSenderRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}

const listBlockedSenders = `-- name: ListBlockedSenders :many
SELECT b.id, b.pattern, b.created_at, mailboxes.id AS mailbox_id, mailboxes.name AS mailbox_name,
    users.id AS created_by_id, users.name AS created_by_name
FROM blocked_senders b
JOIN mailboxes ON mailboxes.id = b.mailbox_id
LEFT JOIN users ON users.id = b.created_by
WHERE b.mailbox_id = ANY($1::uuid[])
ORDER BY lower(mailboxes.name), mailboxes.id, b.pattern
`

type ListBlockedSendersRow struct {
	ID            pgtype.UUID
	Pattern       string
	CreatedAt     pgtype.Timestamptz
	MailboxID     pgtype.UUID
	MailboxName   string
	CreatedByID   pgtype.UUID
	CreatedByName pgtype.Text
}

func (q *Queries) ListBlockedSenders(ctx context.Context, mailboxIds []pgtype.UUID) ([]ListBlockedSendersRow, error) {
	rows, err := q.db.Query(ctx, listBlockedSenders, mailboxIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlockedSendersRow{}
	for rows.Next() {
		var i ListBlockedSendersRow
		if err := rows.Scan(
			&i.ID,
			&i.Pattern,
			&i.CreatedAt,
			&i.MailboxID,
			&i.MailboxName,
			&i.CreatedByID,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailboxRefs = `-- name: ListMailboxRefs :many
SELECT id, name FROM mailboxes WHERE id = ANY($1::uuid[]) ORDER BY lower(name), id
`

type ListMailboxRefsRow struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) ListMailboxRefs(ctx context.Context, ids []pgtype.UUID) ([]ListMailboxRefsRow, error) {
	rows, err := q.db.Query(ctx, listMailboxRefs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMailboxRefsRow{}
	for rows.Next() {
		var i ListMailboxRefsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
