// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaigns.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const campaignBegin = `-- name: CampaignBegin :exec
UPDATE campaigns SET status = 'sending', started_at = coalesce(started_at, $1), updated_at = $1 WHERE id = $2
`

type CampaignBeginParams struct {
	Now pgtype.Timestamptz
	ID  pgtype.UUID
}

func (q *Queries) CampaignBegin(ctx context.Context, arg CampaignBeginParams) error {
	_, err := q.db.Exec(ctx, campaignBegin, arg.Now, arg.ID)
	return err
}

const campaignCancel = `-- name: CampaignCancel :execrows
UPDATE campaigns SET status = 'cancelled', finished_at = $1, updated_at = $1
WHERE id = $2 AND status IN ('scheduled', 'sending', 'paused')
`

type CampaignCancelParams struct {
	Now pgtype.Timestamptz
	ID  pgtype.UUID
}

func (q *Queries) CampaignCancel(ctx context.Context, arg CampaignCancelParams) (int64, error) {
	result, err := q.db.Exec(ctx, campaignCancel, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const campaignCancelOutbound = `-- name: CampaignCancelOutbound :execrows
WITH stopped AS (
    UPDATE outbound o SET status = 'cancelled', updated_at = $1
    FROM campaign_recipients r
    WHERE r.campaign_id = $2 AND r.state = 'queued' AND o.message_id = r.message_id
      AND o.status IN ('queued', 'retry')
    RETURNING o.message_id
)
UPDATE campaign_recipients r
SET state = 'skipped', skip_reason = 'cancelled', finished_at = $1
WHERE r.message_id IN (SELECT message_id FROM stopped)
`

type CampaignCancelOutboundParams struct {
	Now        pgtype.Timestamptz
	CampaignID pgtype.UUID
}

// Stops the messages that have not left yet. Messages already being delivered cannot be
// called back; the dispatcher records how they end.
func (q *Queries) CampaignCancelOutbound(ctx context.Context, arg CampaignCancelOutboundParams) (int64, error) {
	result, err := q.db.Exec(ctx, campaignCancelOutbound, arg.Now, arg.CampaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const campaignCandidates = `-- name: CampaignCandidates :many
SELECT c.id, c.name, c.unsubscribed_at, c.erased_at,
       coalesce(a.email, '')::text AS email,
       (a.email IS NOT NULL)::boolean AS has_address,
       (a.bounced_at IS NOT NULL)::boolean AS bounced
FROM contacts c
LEFT JOIN LATERAL (
    SELECT email, bounced_at FROM contact_addresses
    WHERE contact_id = c.id
    ORDER BY (bounced_at IS NOT NULL), is_primary DESC, email
    LIMIT 1
) a ON true
WHERE c.id = ANY ($1::uuid[])
ORDER BY c.id
`

type CampaignCandidatesRow struct {
	ID             pgtype.UUID
	Name           string
	UnsubscribedAt pgtype.Timestamptz
	ErasedAt       pgtype.Timestamptz
	Email          string
	HasAddress     bool
	Bounced        bool
}

// The address a contact is written to: the primary one, unless it bounced and another does not.
func (q *Queries) CampaignCandidates(ctx context.Context, ids []pgtype.UUID) ([]CampaignCandidatesRow, error) {
	rows, err := q.db.Query(ctx, campaignCandidates, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignCandidatesRow{}
	for rows.Next() {
		var i CampaignCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UnsubscribedAt,
			&i.ErasedAt,
			&i.Email,
			&i.HasAddress,
			&i.Bounced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const campaignClaimPending = `-- name: CampaignClaimPending :many
SELECT r.id, r.contact_id, r.email, r.name, r.unsubscribe_secret,
       (c.unsubscribed_at IS NOT NULL)::boolean AS unsubscribed,
       EXISTS (SELECT 1 FROM contact_addresses a WHERE a.email = r.email AND a.bounced_at IS NOT NULL) AS bounced
FROM campaign_recipients r
LEFT JOIN contacts c ON c.id = r.contact_id
WHERE r.campaign_id = $1 AND r.state = 'pending'
ORDER BY r.id
LIMIT $2
FOR UPDATE OF r SKIP LOCKED
`

type CampaignClaimPendingParams struct {
	CampaignID pgtype.UUID
	Batch      int32
}

type CampaignClaimPendingRow struct {
	ID                pgtype.UUID
	ContactID         pgtype.UUID
	Email             string
	Name              string
	UnsubscribeSecret pgtype.UUID
	Unsubscribed      bool
	Bounced           bool
}

func (q *Queries) CampaignClaimPending(ctx context.Context, arg CampaignClaimPendingParams) ([]CampaignClaimPendingRow, error) {
	rows, err := q.db.Query(ctx, campaignClaimPending, arg.CampaignID, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignClaimPendingRow{}
	for rows.Next() {
		var i CampaignClaimPendingRow
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Email,
			&i.Name,
			&i.UnsubscribeSecret,
			&i.Unsubscribed,
			&i.Bounced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const campaignCountOpen = `-- name: CampaignCountOpen :one
SELECT count(*) FILTER (WHERE state = 'pending')::bigint AS pending,
       count(*) FILTER (WHERE state = 'queued')::bigint AS queued
FROM campaign_recipients WHERE campaign_id = $1
`

type CampaignCountOpenRow struct {
	Pending int64
	Queued  int64
}

func (q *Queries) CampaignCountOpen(ctx context.Context, campaignID pgtype.UUID) (CampaignCountOpenRow, error) {
	row := q.db.QueryRow(ctx, campaignCountOpen, campaignID)
	var i CampaignCountOpenRow
	err := row.Scan(&i.Pending, &i.Queued)
	return i, err
}

const campaignCountQueuedSince = `-- name: CampaignCountQueuedSince :one
SELECT count(*)::bigint
FROM campaign_recipients r
JOIN campaigns c ON c.id = r.campaign_id
WHERE c.mailbox_id = $1 AND r.queued_at > $2
`

type CampaignCountQueuedSinceParams struct {
	MailboxID pgtype.UUID
	Since     pgtype.Timestamptz
}

// Messages sent in the last window from the mailbox, by any campaign. The pacing budget is
// what is left of the rate after these.
func (q *Queries) CampaignCountQueuedSince(ctx context.Context, arg CampaignCountQueuedSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, campaignCountQueuedSince, arg.MailboxID, arg.Since)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const campaignCounts = `-- name: CampaignCounts :many
SELECT campaign_id, state, skip_reason, count(*)::bigint AS n
FROM campaign_recipients
WHERE campaign_id = ANY ($1::uuid[])
GROUP BY campaign_id, state, skip_reason
`

type CampaignCountsRow struct {
	CampaignID pgtype.UUID
	State      string
	SkipReason string
	N          int64
}

func (q *Queries) CampaignCounts(ctx context.Context, ids []pgtype.UUID) ([]CampaignCountsRow, error) {
	rows, err := q.db.Query(ctx, campaignCounts, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignCountsRow{}
	for rows.Next() {
		var i CampaignCountsRow
		if err := rows.Scan(
			&i.CampaignID,
			&i.State,
			&i.SkipReason,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const campaignCreateConversation = `-- name: CampaignCreateConversation :one
INSERT INTO conversations (mailbox_id, subject, subject_normalized, contact_id, status)
VALUES ($1, $2, $3, $4, 'closed')
RETURNING id
`

type CampaignCreateConversationParams struct {
	MailboxID         pgtype.UUID
	Subject           string
	SubjectNormalized string
	ContactID         pgtype.UUID
}

func (q *Queries) CampaignCreateConversation(ctx context.Context, arg CampaignCreateConversationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, campaignCreateConversation,
		arg.MailboxID,
		arg.Subject,
		arg.SubjectNormalized,
		arg.ContactID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const campaignDelete = `-- name: CampaignDelete :execrows
DELETE FROM campaigns WHERE id = $1 AND status IN ('draft', 'done', 'cancelled')
`

func (q *Queries) CampaignDelete(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, campaignDelete, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const campaignFailOrphans = `-- name: CampaignFailOrphans :execrows
UPDATE campaign_recipients
SET state = 'failed', error = 'message removed', finished_at = $1
WHERE campaign_id = $2 AND state = 'queued' AND message_id IS NULL
`

type CampaignFailOrphansParams struct {
	Now        pgtype.Timestamptz
	CampaignID pgtype.UUID
}

// Recipients whose message row is gone (retention) can no longer be followed.
func (q *Queries) CampaignFailOrphans(ctx context.Context, arg CampaignFailOrphansParams) (int64, error) {
	result, err := q.db.Exec(ctx, campaignFailOrphans, arg.Now, arg.CampaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const campaignFailRecipient = `-- name: CampaignFailRecipient :exec
UPDATE campaign_recipients SET state = 'failed', error = $1, finished_at = $2 WHERE id = $3
`

type CampaignFailRecipientParams struct {
	Error string
	Now   pgtype.Timestamptz
	ID    pgtype.UUID
}

func (q *Queries) CampaignFailRecipient(ctx context.Context, arg CampaignFailRecipientParams) error {
	_, err := q.db.Exec(ctx, campaignFailRecipient, arg.Error, arg.Now, arg.ID)
	return err
}

const campaignFinish = `-- name: CampaignFinish :exec
UPDATE campaigns SET status = 'done', finished_at = $1, updated_at = $1 WHERE id = $2
`

type CampaignFinishParams struct {
	Now pgtype.Timestamptz
	ID  pgtype.UUID
}

func (q *Queries) CampaignFinish(ctx context.Context, arg CampaignFinishParams) error {
	_, err := q.db.Exec(ctx, campaignFinish, arg.Now, arg.ID)
	return err
}

const campaignGet = `-- name: CampaignGet :one
SELECT c.id, c.name, c.mailbox_id, c.segment_id, c.segment_name, c.subject, c.body_html, c.status, c.scheduled_at, c.rate_per_minute, c.created_by, c.materialized_at, c.started_at, c.finished_at, c.error, c.created_at, c.updated_at, c.started_by, m.name AS mailbox_name, m.email_address AS mailbox_address, u.name AS creator_name
FROM campaigns c
JOIN mailboxes m ON m.id = c.mailbox_id
LEFT JOIN users u ON u.id = c.created_by
WHERE c.id = $1
`

type CampaignGetRow struct {
	ID             pgtype.UUID
	Name           string
	MailboxID      pgtype.UUID
	SegmentID      pgtype.UUID
	SegmentName    string
	Subject        string
	BodyHtml       string
	Status         string
	ScheduledAt    pgtype.Timestamptz
	RatePerMinute  int32
	CreatedBy      pgtype.UUID
	MaterializedAt pgtype.Timestamptz
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	Error          string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	StartedBy      pgtype.UUID
	MailboxName    string
	MailboxAddress string
	CreatorName    pgtype.Text
}

func (q *Queries) CampaignGet(ctx context.Context, id pgtype.UUID) (CampaignGetRow, error) {
	row := q.db.QueryRow(ctx, campaignGet, id)
	var i CampaignGetRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MailboxID,
		&i.SegmentID,
		&i.SegmentName,
		&i.Subject,
		&i.BodyHtml,
		&i.Status,
		&i.ScheduledAt,
		&i.RatePerMinute,
		&i.CreatedBy,
		&i.MaterializedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedBy,
		&i.MailboxName,
		&i.MailboxAddress,
		&i.CreatorName,
	)
	return i, err
}

const campaignInsert = `-- name: CampaignInsert :one

INSERT INTO campaigns (name, mailbox_id, segment_id, segment_name, subject, body_html, rate_per_minute, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CampaignInsertParams struct {
	Name          string
	MailboxID     pgtype.UUID
	SegmentID     pgtype.UUID
	SegmentName   string
	Subject       string
	BodyHtml      string
	RatePerMinute int32
	CreatedBy     pgtype.UUID
}

// One-off email campaigns to contact segments.
func (q *Queries) CampaignInsert(ctx context.Context, arg CampaignInsertParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, campaignInsert,
		arg.Name,
		arg.MailboxID,
		arg.SegmentID,
		arg.SegmentName,
		arg.Subject,
		arg.BodyHtml,
		arg.RatePerMinute,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const campaignInsertRecipients = `-- name: CampaignInsertRecipients :exec
INSERT INTO campaign_recipients (campaign_id, contact_id, email, name, state, skip_reason)
SELECT $1::uuid, unnest($2::uuid[]), unnest($3::text[]), unnest($4::text[]),
       unnest($5::text[]), unnest($6::text[])
`

type CampaignInsertRecipientsParams struct {
	CampaignID pgtype.UUID
	ContactIds []pgtype.UUID
	Emails     []string
	Names      []string
	States     []string
	Reasons    []string
}

func (q *Queries) CampaignInsertRecipients(ctx context.Context, arg CampaignInsertRecipientsParams) error {
	_, err := q.db.Exec(ctx, campaignInsertRecipients,
		arg.CampaignID,
		arg.ContactIds,
		arg.Emails,
		arg.Names,
		arg.States,
		arg.Reasons,
	)
	return err
}

const campaignList = `-- name: CampaignList :many
SELECT c.id, c.name, c.mailbox_id, c.segment_id, c.segment_name, c.subject, c.body_html, c.status, c.scheduled_at, c.rate_per_minute, c.created_by, c.materialized_at, c.started_at, c.finished_at, c.error, c.created_at, c.updated_at, c.started_by, m.name AS mailbox_name, m.email_address AS mailbox_address, u.name AS creator_name
FROM campaigns c
JOIN mailboxes m ON m.id = c.mailbox_id
LEFT JOIN users u ON u.id = c.created_by
ORDER BY c.created_at DESC, c.id DESC
LIMIT 200
`

type CampaignListRow struct {
	ID             pgtype.UUID
	Name           string
	MailboxID      pgtype.UUID
	SegmentID      pgtype.UUID
	SegmentName    string
	Subject        string
	BodyHtml       string
	Status         string
	ScheduledAt    pgtype.Timestamptz
	RatePerMinute  int32
	CreatedBy      pgtype.UUID
	MaterializedAt pgtype.Timestamptz
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	Error          string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	StartedBy      pgtype.UUID
	MailboxName    string
	MailboxAddress string
	CreatorName    pgtype.Text
}

func (q *Queries) CampaignList(ctx context.Context) ([]CampaignListRow, error) {
	rows, err := q.db.Query(ctx, campaignList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignListRow{}
	for rows.Next() {
		var i CampaignListRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MailboxID,
			&i.SegmentID,
			&i.SegmentName,
			&i.Subject,
			&i.BodyHtml,
			&i.Status,
			&i.ScheduledAt,
			&i.RatePerMinute,
			&i.CreatedBy,
			&i.MaterializedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedBy,
			&i.MailboxName,
			&i.MailboxAddress,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const campaignListActive = `-- name: CampaignListActive :many
SELECT id FROM campaigns c
WHERE c.status = 'sending'
   OR (c.status = 'scheduled' AND c.scheduled_at <= $1)
   OR (c.status IN ('paused', 'cancelled') AND EXISTS (
        SELECT 1 FROM campaign_recipients r WHERE r.campaign_id = c.id AND r.state = 'queued'))
ORDER BY c.created_at, c.id
`

// Campaigns the dispatcher has to look at: due, running, or with deliveries still open.
func (q *Queries) CampaignListActive(ctx context.Context, now pgtype.Timestamptz) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, campaignListActive, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const campaignListRecipients = `-- name: CampaignListRecipients :many
SELECT r.id, r.contact_id, r.email, r.name, r.state, r.skip_reason, r.error, r.queued_at, r.finished_at,
       r.conversation_id, coalesce(o.status, '')::text AS delivery
FROM campaign_recipients r
LEFT JOIN outbound o ON o.message_id = r.message_id
WHERE r.campaign_id = $1
  AND ($2::text = '' OR r.state = $2)
  AND r.id > $3
  AND ($4::boolean OR (r.contact_id IS NOT NULL AND contact_visible(r.contact_id, $5::uuid, false, $6::uuid[])))
ORDER BY r.id
LIMIT $7
`

type CampaignListRecipientsParams struct {
	CampaignID pgtype.UUID
	State      string
	After      pgtype.UUID
	Admin      bool
	UserID     pgtype.UUID
	MailboxIds []pgtype.UUID
	Batch      int32
}

type CampaignListRecipientsRow struct {
	ID             pgtype.UUID
	ContactID      pgtype.UUID
	Email          string
	Name           string
	State          string
	SkipReason     string
	Error          string
	QueuedAt       pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	ConversationID pgtype.UUID
	Delivery       string
}

// The report. Keyset paging on the recipient id; @state filters when set. The delivery column
// follows the send queue while a message is open. Only recipients whose contact the viewer may
// see are listed; a recipient without a contact (erased, merged away) is for admins only.
func (q *Queries) CampaignListRecipients(ctx context.Context, arg CampaignListRecipientsParams) ([]CampaignListRecipientsRow, error) {
	rows, err := q.db.Query(ctx, campaignListRecipients,
		arg.CampaignID,
		arg.State,
		arg.After,
		arg.Admin,
		arg.UserID,
		arg.MailboxIds,
		arg.Batch,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignListRecipientsRow{}
	for rows.Next() {
		var i CampaignListRecipientsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Email,
			&i.Name,
			&i.State,
			&i.SkipReason,
			&i.Error,
			&i.QueuedAt,
			&i.FinishedAt,
			&i.ConversationID,
			&i.Delivery,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const campaignLock = `-- name: CampaignLock :one
SELECT id, name, mailbox_id, segment_id, segment_name, subject, body_html, status, scheduled_at, rate_per_minute, created_by, materialized_at, started_at, finished_at, error, created_at, updated_at, started_by FROM campaigns WHERE id = $1 FOR UPDATE SKIP LOCKED
`

// SKIP LOCKED: a second dispatcher run, or a pause waiting behind this one, never works on
// the same campaign at the same time.
func (q *Queries) CampaignLock(ctx context.Context, id pgtype.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, campaignLock, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MailboxID,
		&i.SegmentID,
		&i.SegmentName,
		&i.Subject,
		&i.BodyHtml,
		&i.Status,
		&i.ScheduledAt,
		&i.RatePerMinute,
		&i.CreatedBy,
		&i.MaterializedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedBy,
	)
	return i, err
}

const campaignMarkBounced = `-- name: CampaignMarkBounced :exec
WITH campaign_row AS (
    UPDATE campaign_recipients
    SET state = 'failed', error = 'bounced: ' || $3::text, finished_at = coalesce(finished_at, $1)
    WHERE message_id = $4 AND state IN ('queued', 'sent')
    RETURNING email
)
UPDATE contact_addresses SET bounced_at = $1
WHERE bounced_at IS NULL
  AND (email = lower($2::text) OR email IN (SELECT email FROM campaign_row))
`

type CampaignMarkBouncedParams struct {
	Now        pgtype.Timestamptz
	Address    string
	Diagnostic string
	MessageID  pgtype.UUID
}

// Called when a permanent bounce comes in for one of our messages. The address that failed and
// the address a campaign wrote to are both marked, so a later campaign skips them.
func (q *Queries) CampaignMarkBounced(ctx context.Context, arg CampaignMarkBouncedParams) error {
	_, err := q.db.Exec(ctx, campaignMarkBounced,
		arg.Now,
		arg.Address,
		arg.Diagnostic,
		arg.MessageID,
	)
	return err
}

const campaignPause = `-- name: CampaignPause :execrows
UPDATE campaigns SET status = 'paused', updated_at = now() WHERE id = $1 AND status = 'sending'
`

func (q *Queries) CampaignPause(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, campaignPause, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const campaignQueueRecipient = `-- name: CampaignQueueRecipient :exec
UPDATE campaign_recipients
SET state = 'queued', message_id = $1, conversation_id = $2, queued_at = $3
WHERE id = $4
`

type CampaignQueueRecipientParams struct {
	MessageID      pgtype.UUID
	ConversationID pgtype.UUID
	Now            pgtype.Timestamptz
	ID             pgtype.UUID
}

func (q *Queries) CampaignQueueRecipient(ctx context.Context, arg CampaignQueueRecipientParams) error {
	_, err := q.db.Exec(ctx, campaignQueueRecipient,
		arg.MessageID,
		arg.ConversationID,
		arg.Now,
		arg.ID,
	)
	return err
}

const campaignRecipientForToken = `-- name: CampaignRecipientForToken :one
SELECT r.id, coalesce(r.contact_id, (SELECT a.contact_id FROM contact_addresses a WHERE a.email = r.email AND r.email <> ''))::uuid AS contact_id,
       r.email, r.unsubscribe_secret, c.name AS campaign_name,
       coalesce(nullif(m.display_name, ''), m.name)::text AS brand
FROM campaign_recipients r
JOIN campaigns c ON c.id = r.campaign_id
JOIN mailboxes m ON m.id = c.mailbox_id
WHERE r.id = $1
`

type CampaignRecipientForTokenRow struct {
	ID                pgtype.UUID
	ContactID         pgtype.UUID
	Email             string
	UnsubscribeSecret pgtype.UUID
	CampaignName      string
	Brand             string
}

// The contact is found through the address when the recipient lost its contact_id, which a
// merge does: the unsubscribe must still land on whoever owns the address now.
func (q *Queries) CampaignRecipientForToken(ctx context.Context, id pgtype.UUID) (CampaignRecipientForTokenRow, error) {
	row := q.db.QueryRow(ctx, campaignRecipientForToken, id)
	var i CampaignRecipientForTokenRow
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Email,
		&i.UnsubscribeSecret,
		&i.CampaignName,
		&i.Brand,
	)
	return i, err
}

const campaignResume = `-- name: CampaignResume :execrows
UPDATE campaigns SET status = 'sending', error = '', updated_at = now() WHERE id = $1 AND status = 'paused'
`

func (q *Queries) CampaignResume(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, campaignResume, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const campaignScrubRecipients = `-- name: CampaignScrubRecipients :exec
UPDATE campaign_recipients SET email = '', name = '' WHERE contact_id = $1
`

func (q *Queries) CampaignScrubRecipients(ctx context.Context, contactID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, campaignScrubRecipients, contactID)
	return err
}

const campaignSegmentName = `-- name: CampaignSegmentName :one
SELECT name FROM contact_segments WHERE id = $1
`

func (q *Queries) CampaignSegmentName(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, campaignSegmentName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const campaignSetMaterialized = `-- name: CampaignSetMaterialized :exec
UPDATE campaigns SET materialized_at = $1, updated_at = $1 WHERE id = $2
`

type CampaignSetMaterializedParams struct {
	Now pgtype.Timestamptz
	ID  pgtype.UUID
}

func (q *Queries) CampaignSetMaterialized(ctx context.Context, arg CampaignSetMaterializedParams) error {
	_, err := q.db.Exec(ctx, campaignSetMaterialized, arg.Now, arg.ID)
	return err
}

const campaignSkipPending = `-- name: CampaignSkipPending :execrows
UPDATE campaign_recipients SET state = 'skipped', skip_reason = 'cancelled', finished_at = $1
WHERE campaign_id = $2 AND state = 'pending'
`

type CampaignSkipPendingParams struct {
	Now        pgtype.Timestamptz
	CampaignID pgtype.UUID
}

func (q *Queries) CampaignSkipPending(ctx context.Context, arg CampaignSkipPendingParams) (int64, error) {
	result, err := q.db.Exec(ctx, campaignSkipPending, arg.Now, arg.CampaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const campaignSkipRecipient = `-- name: CampaignSkipRecipient :exec
UPDATE campaign_recipients SET state = 'skipped', skip_reason = $1, finished_at = $2 WHERE id = $3
`

type CampaignSkipRecipientParams struct {
	Reason string
	Now    pgtype.Timestamptz
	ID     pgtype.UUID
}

func (q *Queries) CampaignSkipRecipient(ctx context.Context, arg CampaignSkipRecipientParams) error {
	_, err := q.db.Exec(ctx, campaignSkipRecipient, arg.Reason, arg.Now, arg.ID)
	return err
}

const campaignStart = `-- name: CampaignStart :execrows
UPDATE campaigns
SET status = $1, scheduled_at = $2, started_at = $3, started_by = $4, error = '', updated_at = now()
WHERE id = $5 AND status = 'draft'
`

type CampaignStartParams struct {
	Status      string
	ScheduledAt pgtype.Timestamptz
	StartedAt   pgtype.Timestamptz
	StartedBy   pgtype.UUID
	ID          pgtype.UUID
}

func (q *Queries) CampaignStart(ctx context.Context, arg CampaignStartParams) (int64, error) {
	result, err := q.db.Exec(ctx, campaignStart,
		arg.Status,
		arg.ScheduledAt,
		arg.StartedAt,
		arg.StartedBy,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const campaignStop = `-- name: CampaignStop :exec
UPDATE campaigns
SET status = $1, error = $2, finished_at = CASE WHEN $1::text = 'paused' THEN NULL ELSE $3::timestamptz END, updated_at = $3
WHERE id = $4
`

type CampaignStopParams struct {
	Status string
	Error  string
	Now    pgtype.Timestamptz
	ID     pgtype.UUID
}

func (q *Queries) CampaignStop(ctx context.Context, arg CampaignStopParams) error {
	_, err := q.db.Exec(ctx, campaignStop,
		arg.Status,
		arg.Error,
		arg.Now,
		arg.ID,
	)
	return err
}

const campaignSyncResults = `-- name: CampaignSyncResults :execrows
UPDATE campaign_recipients r
SET state = CASE WHEN o.status = 'sent' THEN 'sent' ELSE 'failed' END,
    error = CASE o.status
                WHEN 'sent' THEN ''
                WHEN 'bounced' THEN 'bounced: ' || o.error
                WHEN 'uncertain' THEN 'uncertain: ' || o.error
                WHEN 'cancelled' THEN 'cancelled'
                ELSE o.error
            END,
    finished_at = $1
FROM outbound o
WHERE r.campaign_id = $2 AND r.state = 'queued' AND o.message_id = r.message_id
  AND o.status IN ('sent', 'failed', 'uncertain', 'bounced', 'cancelled')
`

type CampaignSyncResultsParams struct {
	Now        pgtype.Timestamptz
	CampaignID pgtype.UUID
}

// Copies the final outcome of the send queue onto the recipients. A message the send worker
// reports as uncertain is not resent: it counts as failed and says so.
func (q *Queries) CampaignSyncResults(ctx context.Context, arg CampaignSyncResultsParams) (int64, error) {
	result, err := q.db.Exec(ctx, campaignSyncResults, arg.Now, arg.CampaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const campaignUpdateDraft = `-- name: CampaignUpdateDraft :execrows
UPDATE campaigns
SET name = $1, mailbox_id = $2, segment_id = $3, segment_name = $4,
    subject = $5, body_html = $6, rate_per_minute = $7, updated_at = now()
WHERE id = $8 AND status = 'draft'
`

type CampaignUpdateDraftParams struct {
	Name          string
	MailboxID     pgtype.UUID
	SegmentID     pgtype.UUID
	SegmentName   string
	Subject       string
	BodyHtml      string
	RatePerMinute int32
	ID            pgtype.UUID
}

func (q *Queries) CampaignUpdateDraft(ctx context.Context, arg CampaignUpdateDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, campaignUpdateDraft,
		arg.Name,
		arg.MailboxID,
		arg.SegmentID,
		arg.SegmentName,
		arg.Subject,
		arg.BodyHtml,
		arg.RatePerMinute,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const contactClearBounce = `-- name: ContactClearBounce :execrows
UPDATE contact_addresses SET bounced_at = NULL
WHERE contact_id = $1 AND email = $2 AND bounced_at IS NOT NULL
`

type ContactClearBounceParams struct {
	ContactID pgtype.UUID
	Email     string
}

func (q *Queries) ContactClearBounce(ctx context.Context, arg ContactClearBounceParams) (int64, error) {
	result, err := q.db.Exec(ctx, contactClearBounce, arg.ContactID, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const contactIsUnsubscribed = `-- name: ContactIsUnsubscribed :one
SELECT (unsubscribed_at IS NOT NULL)::boolean FROM contacts WHERE id = $1
`

func (q *Queries) ContactIsUnsubscribed(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, contactIsUnsubscribed, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const contactResubscribe = `-- name: ContactResubscribe :execrows
UPDATE contacts SET unsubscribed_at = NULL WHERE id = $1 AND unsubscribed_at IS NOT NULL
`

// Undo an unsubscription or a bounce by hand. Like ContactUnsubscribe they report whether they
// changed anything, so a repeated click is not audited again.
func (q *Queries) ContactResubscribe(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, contactResubscribe, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const contactUnsubscribe = `-- name: ContactUnsubscribe :execrows
UPDATE contacts SET unsubscribed_at = $1 WHERE id = $2 AND unsubscribed_at IS NULL
`

type ContactUnsubscribeParams struct {
	Now pgtype.Timestamptz
	ID  pgtype.UUID
}

// Reports whether this call did the unsubscribing, so a repeated click is not audited again.
func (q *Queries) ContactUnsubscribe(ctx context.Context, arg ContactUnsubscribeParams) (int64, error) {
	result, err := q.db.Exec(ctx, contactUnsubscribe, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
