// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compose.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const composeCountUnreadNotifications = `-- name: ComposeCountUnreadNotifications :one
SELECT count(*)::integer
FROM notifications
JOIN conversations ON conversations.id = notifications.conversation_id AND conversations.deleted_at IS NULL
WHERE notifications.user_id = $1 AND notifications.read_at IS NULL
    AND conversations.mailbox_id = ANY($2::uuid[])
`

type ComposeCountUnreadNotificationsParams struct {
	UserID     pgtype.UUID
	MailboxIds []pgtype.UUID
}

func (q *Queries) ComposeCountUnreadNotifications(ctx context.Context, arg ComposeCountUnreadNotificationsParams) (int32, error) {
	row := q.db.QueryRow(ctx, composeCountUnreadNotifications, arg.UserID, arg.MailboxIds)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const composeCreateConversation = `-- name: ComposeCreateConversation :one
INSERT INTO conversations (mailbox_id, subject, subject_normalized, contact_id)
VALUES ($1, $2, $3, $4)
RETURNING id, number
`

type ComposeCreateConversationParams struct {
	MailboxID         pgtype.UUID
	Subject           string
	SubjectNormalized string
	ContactID         pgtype.UUID
}

type ComposeCreateConversationRow struct {
	ID     pgtype.UUID
	Number int64
}

func (q *Queries) ComposeCreateConversation(ctx context.Context, arg ComposeCreateConversationParams) (ComposeCreateConversationRow, error) {
	row := q.db.QueryRow(ctx, composeCreateConversation,
		arg.MailboxID,
		arg.Subject,
		arg.SubjectNormalized,
		arg.ContactID,
	)
	var i ComposeCreateConversationRow
	err := row.Scan(&i.ID, &i.Number)
	return i, err
}

const composeDeleteDraft = `-- name: ComposeDeleteDraft :exec
DELETE FROM drafts WHERE conversation_id = $1 AND user_id = $2
`

type ComposeDeleteDraftParams struct {
	ConversationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) ComposeDeleteDraft(ctx context.Context, arg ComposeDeleteDraftParams) error {
	_, err := q.db.Exec(ctx, composeDeleteDraft, arg.ConversationID, arg.UserID)
	return err
}

const composeDeleteMailboxSignature = `-- name: ComposeDeleteMailboxSignature :exec
DELETE FROM signatures WHERE mailbox_id = $1 AND user_id IS NULL
`

func (q *Queries) ComposeDeleteMailboxSignature(ctx context.Context, mailboxID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, composeDeleteMailboxSignature, mailboxID)
	return err
}

const composeDeleteTemplate = `-- name: ComposeDeleteTemplate :exec
DELETE FROM templates WHERE id = $1
`

func (q *Queries) ComposeDeleteTemplate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, composeDeleteTemplate, id)
	return err
}

const composeDeleteUpload = `-- name: ComposeDeleteUpload :many
DELETE FROM uploads WHERE id = $1 AND user_id = $2 RETURNING blob_key
`

type ComposeDeleteUploadParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// Returns the file's key so the caller can queue it for the reference-checked deletion.
func (q *Queries) ComposeDeleteUpload(ctx context.Context, arg ComposeDeleteUploadParams) ([]string, error) {
	rows, err := q.db.Query(ctx, composeDeleteUpload, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blob_key string
		if err := rows.Scan(&blob_key); err != nil {
			return nil, err
		}
		items = append(items, blob_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const composeDeleteUploads = `-- name: ComposeDeleteUploads :exec
DELETE FROM uploads WHERE id = ANY($1::uuid[]) AND user_id = $2
`

type ComposeDeleteUploadsParams struct {
	Ids    []pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) ComposeDeleteUploads(ctx context.Context, arg ComposeDeleteUploadsParams) error {
	_, err := q.db.Exec(ctx, composeDeleteUploads, arg.Ids, arg.UserID)
	return err
}

const composeDeleteUserSignature = `-- name: ComposeDeleteUserSignature :exec
DELETE FROM signatures
WHERE user_id = $1 AND mailbox_id IS NOT DISTINCT FROM $2::uuid
`

type ComposeDeleteUserSignatureParams struct {
	UserID    pgtype.UUID
	MailboxID pgtype.UUID
}

func (q *Queries) ComposeDeleteUserSignature(ctx context.Context, arg ComposeDeleteUserSignatureParams) error {
	_, err := q.db.Exec(ctx, composeDeleteUserSignature, arg.UserID, arg.MailboxID)
	return err
}

const composeGetContact = `-- name: ComposeGetContact :one
SELECT contacts.name,
    COALESCE((SELECT contact_addresses.email FROM contact_addresses
        WHERE contact_addresses.contact_id = contacts.id
        ORDER BY contact_addresses.is_primary DESC, contact_addresses.email LIMIT 1), '')::text AS email
FROM contacts
WHERE contacts.id = $1
`

type ComposeGetContactRow struct {
	Name  string
	Email string
}

func (q *Queries) ComposeGetContact(ctx context.Context, id pgtype.UUID) (ComposeGetContactRow, error) {
	row := q.db.QueryRow(ctx, composeGetContact, id)
	var i ComposeGetContactRow
	err := row.Scan(&i.Name, &i.Email)
	return i, err
}

const composeGetConversation = `-- name: ComposeGetConversation :one

SELECT id, number, mailbox_id, subject, status, contact_id
FROM conversations
WHERE id = $1 AND mailbox_id = ANY($2::uuid[]) AND deleted_at IS NULL
`

type ComposeGetConversationParams struct {
	ID         pgtype.UUID
	MailboxIds []pgtype.UUID
}

type ComposeGetConversationRow struct {
	ID        pgtype.UUID
	Number    int64
	MailboxID pgtype.UUID
	Subject   string
	Status    string
	ContactID pgtype.UUID
}

// Composer: replies, notes, uploads, drafts, templates, signatures and notifications.
// Conversation lookups take the caller's readable mailbox ids, so out-of-scope rows are never
// selected; write access is decided by the caller from the same scope.
func (q *Queries) ComposeGetConversation(ctx context.Context, arg ComposeGetConversationParams) (ComposeGetConversationRow, error) {
	row := q.db.QueryRow(ctx, composeGetConversation, arg.ID, arg.MailboxIds)
	var i ComposeGetConversationRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.MailboxID,
		&i.Subject,
		&i.Status,
		&i.ContactID,
	)
	return i, err
}

const composeGetDraft = `-- name: ComposeGetDraft :one
SELECT id, conversation_id, user_id, to_addrs, cc_addrs, bcc_addrs, subject, body_html, attachment_ids, updated_at FROM drafts WHERE conversation_id = $1 AND user_id = $2
`

type ComposeGetDraftParams struct {
	ConversationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) ComposeGetDraft(ctx context.Context, arg ComposeGetDraftParams) (Draft, error) {
	row := q.db.QueryRow(ctx, composeGetDraft, arg.ConversationID, arg.UserID)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.ToAddrs,
		&i.CcAddrs,
		&i.BccAddrs,
		&i.Subject,
		&i.BodyHtml,
		&i.AttachmentIds,
		&i.UpdatedAt,
	)
	return i, err
}

const composeGetEmail = `-- name: ComposeGetEmail :one
SELECT id, conversation_id, mailbox_id, direction, raw_message_id, from_addr, from_name, to_addrs, cc_addrs,
    subject, body_text, sent_at, received_at
FROM messages
WHERE id = $1 AND conversation_id = $2 AND kind = 'email' AND deleted_at IS NULL
`

type ComposeGetEmailParams struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
}

type ComposeGetEmailRow struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	MailboxID      pgtype.UUID
	Direction      pgtype.Text
	RawMessageID   pgtype.UUID
	FromAddr       string
	FromName       string
	ToAddrs        []byte
	CcAddrs        []byte
	Subject        string
	BodyText       string
	SentAt         pgtype.Timestamptz
	ReceivedAt     pgtype.Timestamptz
}

func (q *Queries) ComposeGetEmail(ctx context.Context, arg ComposeGetEmailParams) (ComposeGetEmailRow, error) {
	row := q.db.QueryRow(ctx, composeGetEmail, arg.ID, arg.ConversationID)
	var i ComposeGetEmailRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.MailboxID,
		&i.Direction,
		&i.RawMessageID,
		&i.FromAddr,
		&i.FromName,
		&i.ToAddrs,
		&i.CcAddrs,
		&i.Subject,
		&i.BodyText,
		&i.SentAt,
		&i.ReceivedAt,
	)
	return i, err
}

const composeGetMailboxSignature = `-- name: ComposeGetMailboxSignature :one
SELECT body_html FROM signatures WHERE mailbox_id = $1 AND user_id IS NULL
`

func (q *Queries) ComposeGetMailboxSignature(ctx context.Context, mailboxID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, composeGetMailboxSignature, mailboxID)
	var body_html string
	err := row.Scan(&body_html)
	return body_html, err
}

const composeGetMessageView = `-- name: ComposeGetMessageView :one
SELECT
    messages.id, messages.kind, messages.direction, messages.from_name, messages.from_addr,
    messages.to_addrs, messages.cc_addrs, messages.subject, messages.body_text,
    messages.sent_at, messages.received_at,
    users.id AS author_id, users.name AS author_name,
    outbound.status AS outbound_status, outbound.error AS outbound_error, outbound.scheduled_at AS undo_until
FROM messages
LEFT JOIN users ON users.id = messages.author_user_id
LEFT JOIN outbound ON outbound.message_id = messages.id
WHERE messages.id = $1 AND messages.deleted_at IS NULL
`

type ComposeGetMessageViewRow struct {
	ID             pgtype.UUID
	Kind           string
	Direction      pgtype.Text
	FromName       string
	FromAddr       string
	ToAddrs        []byte
	CcAddrs        []byte
	Subject        string
	BodyText       string
	SentAt         pgtype.Timestamptz
	ReceivedAt     pgtype.Timestamptz
	AuthorID       pgtype.UUID
	AuthorName     pgtype.Text
	OutboundStatus pgtype.Text
	OutboundError  pgtype.Text
	UndoUntil      pgtype.Timestamptz
}

func (q *Queries) ComposeGetMessageView(ctx context.Context, id pgtype.UUID) (ComposeGetMessageViewRow, error) {
	row := q.db.QueryRow(ctx, composeGetMessageView, id)
	var i ComposeGetMessageViewRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Direction,
		&i.FromName,
		&i.FromAddr,
		&i.ToAddrs,
		&i.CcAddrs,
		&i.Subject,
		&i.BodyText,
		&i.SentAt,
		&i.ReceivedAt,
		&i.AuthorID,
		&i.AuthorName,
		&i.OutboundStatus,
		&i.OutboundError,
		&i.UndoUntil,
	)
	return i, err
}

const composeGetOutgoing = `-- name: ComposeGetOutgoing :one
SELECT messages.id, messages.conversation_id, messages.mailbox_id, o.created_by, o.status, o.scheduled_at
FROM messages
JOIN outbound o ON o.message_id = messages.id
WHERE messages.id = $1 AND messages.conversation_id = $2
    AND messages.kind = 'email' AND messages.direction = 'out' AND messages.deleted_at IS NULL
`

type ComposeGetOutgoingParams struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
}

type ComposeGetOutgoingRow struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	MailboxID      pgtype.UUID
	CreatedBy      pgtype.UUID
	Status         string
	ScheduledAt    pgtype.Timestamptz
}

func (q *Queries) ComposeGetOutgoing(ctx context.Context, arg ComposeGetOutgoingParams) (ComposeGetOutgoingRow, error) {
	row := q.db.QueryRow(ctx, composeGetOutgoing, arg.ID, arg.ConversationID)
	var i ComposeGetOutgoingRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.MailboxID,
		&i.CreatedBy,
		&i.Status,
		&i.ScheduledAt,
	)
	return i, err
}

const composeGetOutgoingByID = `-- name: ComposeGetOutgoingByID :one
SELECT messages.conversation_id, o.created_by
FROM messages JOIN outbound o ON o.message_id = messages.id
WHERE messages.id = $1
`

type ComposeGetOutgoingByIDRow struct {
	ConversationID pgtype.UUID
	CreatedBy      pgtype.UUID
}

func (q *Queries) ComposeGetOutgoingByID(ctx context.Context, id pgtype.UUID) (ComposeGetOutgoingByIDRow, error) {
	row := q.db.QueryRow(ctx, composeGetOutgoingByID, id)
	var i ComposeGetOutgoingByIDRow
	err := row.Scan(&i.ConversationID, &i.CreatedBy)
	return i, err
}

const composeGetRawBlob = `-- name: ComposeGetRawBlob :one
SELECT sha256, size_bytes, blob_key FROM raw_messages WHERE id = $1
`

type ComposeGetRawBlobRow struct {
	Sha256    []byte
	SizeBytes int32
	BlobKey   string
}

func (q *Queries) ComposeGetRawBlob(ctx context.Context, id pgtype.UUID) (ComposeGetRawBlobRow, error) {
	row := q.db.QueryRow(ctx, composeGetRawBlob, id)
	var i ComposeGetRawBlobRow
	err := row.Scan(&i.Sha256, &i.SizeBytes, &i.BlobKey)
	return i, err
}

const composeGetTemplate = `-- name: ComposeGetTemplate :one
SELECT id, name, shortcode, scope, owner_user_id, team_id, mailbox_id, subject, body_html, created_at, updated_at FROM templates WHERE id = $1
`

func (q *Queries) ComposeGetTemplate(ctx context.Context, id pgtype.UUID) (Template, error) {
	row := q.db.QueryRow(ctx, composeGetTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Shortcode,
		&i.Scope,
		&i.OwnerUserID,
		&i.TeamID,
		&i.MailboxID,
		&i.Subject,
		&i.BodyHtml,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const composeInsertEvent = `-- name: ComposeInsertEvent :exec
INSERT INTO conversation_events (conversation_id, mailbox_id, actor_user_id, type, data)
VALUES ($1, $2, $3, $4, $5)
`

type ComposeInsertEventParams struct {
	ConversationID pgtype.UUID
	MailboxID      pgtype.UUID
	ActorUserID    pgtype.UUID
	Type           string
	Data           []byte
}

func (q *Queries) ComposeInsertEvent(ctx context.Context, arg ComposeInsertEventParams) error {
	_, err := q.db.Exec(ctx, composeInsertEvent,
		arg.ConversationID,
		arg.MailboxID,
		arg.ActorUserID,
		arg.Type,
		arg.Data,
	)
	return err
}

const composeInsertMentions = `-- name: ComposeInsertMentions :exec
INSERT INTO mentions (message_id, user_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type ComposeInsertMentionsParams struct {
	MessageID pgtype.UUID
	UserIds   []pgtype.UUID
}

func (q *Queries) ComposeInsertMentions(ctx context.Context, arg ComposeInsertMentionsParams) error {
	_, err := q.db.Exec(ctx, composeInsertMentions, arg.MessageID, arg.UserIds)
	return err
}

const composeInsertNote = `-- name: ComposeInsertNote :one
INSERT INTO messages (conversation_id, mailbox_id, kind, from_addr, from_name, body_text, body_html, author_user_id)
VALUES ($1, $2, 'note', $3, $4, $5, $6, $7)
RETURNING id
`

type ComposeInsertNoteParams struct {
	ConversationID pgtype.UUID
	MailboxID      pgtype.UUID
	FromAddr       string
	FromName       string
	BodyText       string
	BodyHtml       string
	AuthorUserID   pgtype.UUID
}

func (q *Queries) ComposeInsertNote(ctx context.Context, arg ComposeInsertNoteParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, composeInsertNote,
		arg.ConversationID,
		arg.MailboxID,
		arg.FromAddr,
		arg.FromName,
		arg.BodyText,
		arg.BodyHtml,
		arg.AuthorUserID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const composeInsertNotification = `-- name: ComposeInsertNotification :one
INSERT INTO notifications (user_id, kind, conversation_id, message_id, actor_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type ComposeInsertNotificationParams struct {
	UserID         pgtype.UUID
	Kind           string
	ConversationID pgtype.UUID
	MessageID      pgtype.UUID
	ActorID        pgtype.UUID
}

func (q *Queries) ComposeInsertNotification(ctx context.Context, arg ComposeInsertNotificationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, composeInsertNotification,
		arg.UserID,
		arg.Kind,
		arg.ConversationID,
		arg.MessageID,
		arg.ActorID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const composeInsertTemplate = `-- name: ComposeInsertTemplate :one
INSERT INTO templates (name, shortcode, scope, owner_user_id, team_id, mailbox_id, subject, body_html)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, shortcode, scope, owner_user_id, team_id, mailbox_id, subject, body_html, created_at, updated_at
`

type ComposeInsertTemplateParams struct {
	Name        string
	Shortcode   string
	Scope       string
	OwnerUserID pgtype.UUID
	TeamID      pgtype.UUID
	MailboxID   pgtype.UUID
	Subject     string
	BodyHtml    string
}

func (q *Queries) ComposeInsertTemplate(ctx context.Context, arg ComposeInsertTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, composeInsertTemplate,
		arg.Name,
		arg.Shortcode,
		arg.Scope,
		arg.OwnerUserID,
		arg.TeamID,
		arg.MailboxID,
		arg.Subject,
		arg.BodyHtml,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Shortcode,
		&i.Scope,
		&i.OwnerUserID,
		&i.TeamID,
		&i.MailboxID,
		&i.Subject,
		&i.BodyHtml,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const composeInsertUpload = `-- name: ComposeInsertUpload :one
INSERT INTO uploads (user_id, filename, content_type, size_bytes, sha256, blob_key, content_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, filename, content_type, size_bytes, sha256, blob_key, content_id, created_at, expires_at
`

type ComposeInsertUploadParams struct {
	UserID      pgtype.UUID
	Filename    string
	ContentType string
	SizeBytes   int64
	Sha256      []byte
	BlobKey     string
	ContentID   string
}

func (q *Queries) ComposeInsertUpload(ctx context.Context, arg ComposeInsertUploadParams) (Upload, error) {
	row := q.db.QueryRow(ctx, composeInsertUpload,
		arg.UserID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.Sha256,
		arg.BlobKey,
		arg.ContentID,
	)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.BlobKey,
		&i.ContentID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const composeKnownAddresses = `-- name: ComposeKnownAddresses :many
WITH first_in AS (
    SELECT id FROM messages
    WHERE messages.conversation_id = $1 AND kind = 'email' AND direction = 'in' AND deleted_at IS NULL
    ORDER BY received_at, id LIMIT 1
), sel AS (
    SELECT from_addr, to_addrs || cc_addrs || reply_to AS others FROM messages
    WHERE messages.conversation_id = $1 AND kind = 'email' AND deleted_at IS NULL
        AND (direction = 'out' OR id IN (SELECT id FROM first_in))
)
SELECT lower(from_addr)::text AS address FROM sel
UNION SELECT lower(e ->> 'address') FROM sel, jsonb_array_elements(sel.others) AS e
UNION SELECT lower(ca.email) FROM contact_addresses ca JOIN conversations cv ON cv.contact_id = ca.contact_id
WHERE cv.id = $1
`

// Who counts as a participant of the conversation: the contact, everyone we wrote to or from, and
// the parties of the first inbound message. Later inbound senders are not included, so a stranger
// who injected a message into the thread does not become known by having written to it.
func (q *Queries) ComposeKnownAddresses(ctx context.Context, conversationID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, composeKnownAddresses, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var address string
		if err := rows.Scan(&address); err != nil {
			return nil, err
		}
		items = append(items, address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const composeLastEmail = `-- name: ComposeLastEmail :one
SELECT id, direction, from_addr, from_name, to_addrs, cc_addrs, reply_to, message_id_header, references_hdr
FROM messages
WHERE conversation_id = $1 AND kind = 'email' AND deleted_at IS NULL
    AND NOT (direction = 'out' AND subject ~* '^\s*(fwd?|wg|doorst|doorgestuurd)\s*:')
    AND ($2::text IS NULL OR direction = $2::text)
    AND ($3::text[] IS NULL
         OR (lower(from_addr) = ANY ($3::text[])
             AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(reply_to) e
                             WHERE lower(e ->> 'address') <> ALL ($3::text[]))))
ORDER BY received_at DESC, id DESC
LIMIT 1
`

type ComposeLastEmailParams struct {
	ConversationID pgtype.UUID
	Direction      pgtype.Text
	KnownCustomers []string
}

type ComposeLastEmailRow struct {
	ID              pgtype.UUID
	Direction       pgtype.Text
	FromAddr        string
	FromName        string
	ToAddrs         []byte
	CcAddrs         []byte
	ReplyTo         []byte
	MessageIDHeader string
	ReferencesHdr   []string
}

// Our own forwards are skipped: their recipients are not part of the conversation with the customer.
// With known_customers set, inbound mail only counts when its From and every Reply-To address are one of them.
func (q *Queries) ComposeLastEmail(ctx context.Context, arg ComposeLastEmailParams) (ComposeLastEmailRow, error) {
	row := q.db.QueryRow(ctx, composeLastEmail, arg.ConversationID, arg.Direction, arg.KnownCustomers)
	var i ComposeLastEmailRow
	err := row.Scan(
		&i.ID,
		&i.Direction,
		&i.FromAddr,
		&i.FromName,
		&i.ToAddrs,
		&i.CcAddrs,
		&i.ReplyTo,
		&i.MessageIDHeader,
		&i.ReferencesHdr,
	)
	return i, err
}

const composeListMentionable = `-- name: ComposeListMentionable :many
SELECT users.id, users.name, users.email
FROM users
WHERE users.deactivated_at IS NULL
    AND (users.role IN ('owner', 'admin') OR EXISTS (
        SELECT 1 FROM team_members
        JOIN mailbox_access ON mailbox_access.team_id = team_members.team_id
        WHERE team_members.user_id = users.id AND mailbox_access.mailbox_id = $1))
ORDER BY lower(users.name), users.id
`

type ComposeListMentionableRow struct {
	ID    pgtype.UUID
	Name  string
	Email string
}

// Everyone who can read the mailbox: owners and admins, plus members of a team it was shared with.
func (q *Queries) ComposeListMentionable(ctx context.Context, mailboxID pgtype.UUID) ([]ComposeListMentionableRow, error) {
	rows, err := q.db.Query(ctx, composeListMentionable, mailboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComposeListMentionableRow{}
	for rows.Next() {
		var i ComposeListMentionableRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const composeListNotifications = `-- name: ComposeListNotifications :many
SELECT notifications.id, notifications.kind, notifications.conversation_id, notifications.message_id,
    notifications.created_at, notifications.read_at,
    conversations.number AS conversation_number, conversations.subject AS conversation_subject,
    actors.id AS actor_id, actors.name AS actor_name
FROM notifications
JOIN conversations ON conversations.id = notifications.conversation_id AND conversations.deleted_at IS NULL
LEFT JOIN users AS actors ON actors.id = notifications.actor_id
WHERE notifications.user_id = $1
    AND conversations.mailbox_id = ANY($2::uuid[])
    AND (NOT $3::boolean OR notifications.read_at IS NULL)
ORDER BY notifications.created_at DESC, notifications.id DESC
LIMIT $4::integer
`

type ComposeListNotificationsParams struct {
	UserID     pgtype.UUID
	MailboxIds []pgtype.UUID
	UnreadOnly bool
	PageSize   int32
}

type ComposeListNotificationsRow struct {
	ID                  pgtype.UUID
	Kind                string
	ConversationID      pgtype.UUID
	MessageID           pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	ReadAt              pgtype.Timestamptz
	ConversationNumber  int64
	ConversationSubject string
	ActorID             pgtype.UUID
	ActorName           pgtype.Text
}

// Hidden conversations are left out, so a notification never reveals one.
func (q *Queries) ComposeListNotifications(ctx context.Context, arg ComposeListNotificationsParams) ([]ComposeListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, composeListNotifications,
		arg.UserID,
		arg.MailboxIds,
		arg.UnreadOnly,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComposeListNotificationsRow{}
	for rows.Next() {
		var i ComposeListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ConversationID,
			&i.MessageID,
			&i.CreatedAt,
			&i.ReadAt,
			&i.ConversationNumber,
			&i.ConversationSubject,
			&i.ActorID,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const composeListTemplates = `-- name: ComposeListTemplates :many
SELECT id, name, shortcode, scope, owner_user_id, team_id, mailbox_id, subject, body_html, created_at, updated_at FROM templates
WHERE (scope = 'personal' AND owner_user_id = $1)
    OR (NOT $2::boolean AND (
        scope = 'global'
        OR (scope = 'team' AND team_id IN (SELECT team_members.team_id FROM team_members WHERE team_members.user_id = $1))
        OR (scope = 'mailbox' AND mailbox_id = ANY($3::uuid[]))))
    OR ($2::boolean AND scope <> 'personal')
ORDER BY lower(name), id
`

type ComposeListTemplatesParams struct {
	UserID     pgtype.UUID
	Manage     bool
	MailboxIds []pgtype.UUID
}

// Visible to the caller: their own personal templates, those of their teams, of mailboxes they can
// read, and global ones. Admins managing the workspace see every non-personal template.
func (q *Queries) ComposeListTemplates(ctx context.Context, arg ComposeListTemplatesParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, composeListTemplates, arg.UserID, arg.Manage, arg.MailboxIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Shortcode,
			&i.Scope,
			&i.OwnerUserID,
			&i.TeamID,
			&i.MailboxID,
			&i.Subject,
			&i.BodyHtml,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const composeListUploads = `-- name: ComposeListUploads :many
SELECT id, user_id, filename, content_type, size_bytes, sha256, blob_key, content_id, created_at, expires_at FROM uploads
WHERE id = ANY($1::uuid[]) AND user_id = $2 AND expires_at > now()
ORDER BY created_at, id
`

type ComposeListUploadsParams struct {
	Ids    []pgtype.UUID
	UserID pgtype.UUID
}

// Only the uploader's unexpired files; anything else is treated as not existing.
func (q *Queries) ComposeListUploads(ctx context.Context, arg ComposeListUploadsParams) ([]Upload, error) {
	rows, err := q.db.Query(ctx, composeListUploads, arg.Ids, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Upload{}
	for rows.Next() {
		var i Upload
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256,
			&i.BlobKey,
			&i.ContentID,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const composeListUserSignatures = `-- name: ComposeListUserSignatures :many
SELECT id, mailbox_id, body_html FROM signatures WHERE user_id = $1 ORDER BY mailbox_id NULLS FIRST
`

type ComposeListUserSignaturesRow struct {
	ID        pgtype.UUID
	MailboxID pgtype.UUID
	BodyHtml  string
}

func (q *Queries) ComposeListUserSignatures(ctx context.Context, userID pgtype.UUID) ([]ComposeListUserSignaturesRow, error) {
	rows, err := q.db.Query(ctx, composeListUserSignatures, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComposeListUserSignaturesRow{}
	for rows.Next() {
		var i ComposeListUserSignaturesRow
		if err := rows.Scan(&i.ID, &i.MailboxID, &i.BodyHtml); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const composeLockConversation = `-- name: ComposeLockConversation :one
SELECT id, mailbox_id, status FROM conversations WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

type ComposeLockConversationRow struct {
	ID        pgtype.UUID
	MailboxID pgtype.UUID
	Status    string
}

func (q *Queries) ComposeLockConversation(ctx context.Context, id pgtype.UUID) (ComposeLockConversationRow, error) {
	row := q.db.QueryRow(ctx, composeLockConversation, id)
	var i ComposeLockConversationRow
	err := row.Scan(&i.ID, &i.MailboxID, &i.Status)
	return i, err
}

const composeMailboxAddresses = `-- name: ComposeMailboxAddresses :many
SELECT email_address FROM mailboxes
`

func (q *Queries) ComposeMailboxAddresses(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, composeMailboxAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var email_address string
		if err := rows.Scan(&email_address); err != nil {
			return nil, err
		}
		items = append(items, email_address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const composeMailboxExists = `-- name: ComposeMailboxExists :one
SELECT EXISTS (SELECT 1 FROM mailboxes WHERE id = $1)
`

func (q *Queries) ComposeMailboxExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, composeMailboxExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const composeMarkNotificationsRead = `-- name: ComposeMarkNotificationsRead :exec
UPDATE notifications SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL
    AND ($2::boolean OR id = ANY($3::uuid[]))
`

type ComposeMarkNotificationsReadParams struct {
	UserID  pgtype.UUID
	MarkAll bool
	Ids     []pgtype.UUID
}

func (q *Queries) ComposeMarkNotificationsRead(ctx context.Context, arg ComposeMarkNotificationsReadParams) error {
	_, err := q.db.Exec(ctx, composeMarkNotificationsRead, arg.UserID, arg.MarkAll, arg.Ids)
	return err
}

const composeRecordStatusChange = `-- name: ComposeRecordStatusChange :exec
INSERT INTO reply_status_changes (message_id, from_status, to_status) VALUES ($1, $2, $3)
`

type ComposeRecordStatusChangeParams struct {
	MessageID  pgtype.UUID
	FromStatus string
	ToStatus   string
}

func (q *Queries) ComposeRecordStatusChange(ctx context.Context, arg ComposeRecordStatusChangeParams) error {
	_, err := q.db.Exec(ctx, composeRecordStatusChange, arg.MessageID, arg.FromStatus, arg.ToStatus)
	return err
}

const composeResolveSignature = `-- name: ComposeResolveSignature :one
SELECT body_html,
    CASE WHEN user_id IS NOT NULL AND mailbox_id IS NOT NULL THEN 'user_mailbox'
         WHEN user_id IS NOT NULL THEN 'user'
         ELSE 'mailbox' END::text AS source
FROM signatures
WHERE (user_id = $1 AND (mailbox_id = $2 OR mailbox_id IS NULL))
    OR (user_id IS NULL AND mailbox_id = $2)
ORDER BY (user_id IS NOT NULL AND mailbox_id IS NOT NULL) DESC, (user_id IS NOT NULL) DESC
LIMIT 1
`

type ComposeResolveSignatureParams struct {
	UserID    pgtype.UUID
	MailboxID pgtype.UUID
}

type ComposeResolveSignatureRow struct {
	BodyHtml string
	Source   string
}

// user+mailbox beats user default beats mailbox default.
func (q *Queries) ComposeResolveSignature(ctx context.Context, arg ComposeResolveSignatureParams) (ComposeResolveSignatureRow, error) {
	row := q.db.QueryRow(ctx, composeResolveSignature, arg.UserID, arg.MailboxID)
	var i ComposeResolveSignatureRow
	err := row.Scan(&i.BodyHtml, &i.Source)
	return i, err
}

const composeRestoreUploads = `-- name: ComposeRestoreUploads :many
INSERT INTO uploads (user_id, filename, content_type, size_bytes, sha256, blob_key, content_id)
SELECT $1, filename, declared_type, size_bytes, sha256, blob_key,
    COALESCE(NULLIF(content_id, ''), md5(random()::text || id::text) || '@echoo.upload')
FROM attachments
WHERE message_id = $2
ORDER BY created_at, id
RETURNING id, user_id, filename, content_type, size_bytes, sha256, blob_key, content_id, created_at, expires_at
`

type ComposeRestoreUploadsParams struct {
	UserID    pgtype.UUID
	MessageID pgtype.UUID
}

// Undo send gives the attachments of a cancelled message back to its author as fresh uploads.
func (q *Queries) ComposeRestoreUploads(ctx context.Context, arg ComposeRestoreUploadsParams) ([]Upload, error) {
	rows, err := q.db.Query(ctx, composeRestoreUploads, arg.UserID, arg.MessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Upload{}
	for rows.Next() {
		var i Upload
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256,
			&i.BlobKey,
			&i.ContentID,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const composeSoftDeleteMessage = `-- name: ComposeSoftDeleteMessage :exec
UPDATE messages SET deleted_at = now() WHERE id = $1
`

func (q *Queries) ComposeSoftDeleteMessage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, composeSoftDeleteMessage, id)
	return err
}

const composeTakeStatusChange = `-- name: ComposeTakeStatusChange :one
DELETE FROM reply_status_changes WHERE message_id = $1 RETURNING from_status, to_status
`

type ComposeTakeStatusChangeRow struct {
	FromStatus string
	ToStatus   string
}

func (q *Queries) ComposeTakeStatusChange(ctx context.Context, messageID pgtype.UUID) (ComposeTakeStatusChangeRow, error) {
	row := q.db.QueryRow(ctx, composeTakeStatusChange, messageID)
	var i ComposeTakeStatusChangeRow
	err := row.Scan(&i.FromStatus, &i.ToStatus)
	return i, err
}

const composeTemplateVisible = `-- name: ComposeTemplateVisible :one
SELECT EXISTS (
    SELECT 1 FROM templates
    WHERE id = $1 AND (
        (scope = 'personal' AND owner_user_id = $2)
        OR scope = 'global'
        OR (scope = 'team' AND team_id IN (SELECT team_members.team_id FROM team_members WHERE team_members.user_id = $2))
        OR (scope = 'mailbox' AND mailbox_id = ANY($3::uuid[])))
)
`

type ComposeTemplateVisibleParams struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	MailboxIds []pgtype.UUID
}

func (q *Queries) ComposeTemplateVisible(ctx context.Context, arg ComposeTemplateVisibleParams) (bool, error) {
	row := q.db.QueryRow(ctx, composeTemplateVisible, arg.ID, arg.UserID, arg.MailboxIds)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const composeTouchConversation = `-- name: ComposeTouchConversation :one
UPDATE conversations
SET has_attachments = has_attachments OR $1::boolean,
    version = version + 1, updated_at = now()
WHERE id = $2
RETURNING version
`

type ComposeTouchConversationParams struct {
	HasAttachments bool
	ID             pgtype.UUID
}

// Bumps the version so clients refetch; message_count and preview follow when the send worker
// delivers the message.
func (q *Queries) ComposeTouchConversation(ctx context.Context, arg ComposeTouchConversationParams) (int32, error) {
	row := q.db.QueryRow(ctx, composeTouchConversation, arg.HasAttachments, arg.ID)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const composeUpdateTemplate = `-- name: ComposeUpdateTemplate :one
UPDATE templates
SET name = $1, shortcode = $2, subject = $3, body_html = $4, updated_at = now()
WHERE id = $5
RETURNING id, name, shortcode, scope, owner_user_id, team_id, mailbox_id, subject, body_html, created_at, updated_at
`

type ComposeUpdateTemplateParams struct {
	Name      string
	Shortcode string
	Subject   string
	BodyHtml  string
	ID        pgtype.UUID
}

func (q *Queries) ComposeUpdateTemplate(ctx context.Context, arg ComposeUpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, composeUpdateTemplate,
		arg.Name,
		arg.Shortcode,
		arg.Subject,
		arg.BodyHtml,
		arg.ID,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Shortcode,
		&i.Scope,
		&i.OwnerUserID,
		&i.TeamID,
		&i.MailboxID,
		&i.Subject,
		&i.BodyHtml,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const composeUpsertDraft = `-- name: ComposeUpsertDraft :one
INSERT INTO drafts (conversation_id, user_id, to_addrs, cc_addrs, bcc_addrs, subject, body_html, attachment_ids)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (conversation_id, user_id) DO UPDATE SET
    to_addrs = EXCLUDED.to_addrs, cc_addrs = EXCLUDED.cc_addrs, bcc_addrs = EXCLUDED.bcc_addrs,
    subject = EXCLUDED.subject, body_html = EXCLUDED.body_html, attachment_ids = EXCLUDED.attachment_ids,
    updated_at = now()
RETURNING id, conversation_id, user_id, to_addrs, cc_addrs, bcc_addrs, subject, body_html, attachment_ids, updated_at
`

type ComposeUpsertDraftParams struct {
	ConversationID pgtype.UUID
	UserID         pgtype.UUID
	ToAddrs        []byte
	CcAddrs        []byte
	BccAddrs       []byte
	Subject        string
	BodyHtml       string
	AttachmentIds  []pgtype.UUID
}

func (q *Queries) ComposeUpsertDraft(ctx context.Context, arg ComposeUpsertDraftParams) (Draft, error) {
	row := q.db.QueryRow(ctx, composeUpsertDraft,
		arg.ConversationID,
		arg.UserID,
		arg.ToAddrs,
		arg.CcAddrs,
		arg.BccAddrs,
		arg.Subject,
		arg.BodyHtml,
		arg.AttachmentIds,
	)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.ToAddrs,
		&i.CcAddrs,
		&i.BccAddrs,
		&i.Subject,
		&i.BodyHtml,
		&i.AttachmentIds,
		&i.UpdatedAt,
	)
	return i, err
}

const composeUpsertMailboxSignature = `-- name: ComposeUpsertMailboxSignature :exec
INSERT INTO signatures (mailbox_id, body_html) VALUES ($1, $2)
ON CONFLICT (mailbox_id) WHERE user_id IS NULL AND mailbox_id IS NOT NULL
    DO UPDATE SET body_html = EXCLUDED.body_html, updated_at = now()
`

type ComposeUpsertMailboxSignatureParams struct {
	MailboxID pgtype.UUID
	BodyHtml  string
}

func (q *Queries) ComposeUpsertMailboxSignature(ctx context.Context, arg ComposeUpsertMailboxSignatureParams) error {
	_, err := q.db.Exec(ctx, composeUpsertMailboxSignature, arg.MailboxID, arg.BodyHtml)
	return err
}

const composeUpsertUserDefaultSignature = `-- name: ComposeUpsertUserDefaultSignature :exec
INSERT INTO signatures (user_id, body_html) VALUES ($1, $2)
ON CONFLICT (user_id) WHERE user_id IS NOT NULL AND mailbox_id IS NULL
    DO UPDATE SET body_html = EXCLUDED.body_html, updated_at = now()
`

type ComposeUpsertUserDefaultSignatureParams struct {
	UserID   pgtype.UUID
	BodyHtml string
}

func (q *Queries) ComposeUpsertUserDefaultSignature(ctx context.Context, arg ComposeUpsertUserDefaultSignatureParams) error {
	_, err := q.db.Exec(ctx, composeUpsertUserDefaultSignature, arg.UserID, arg.BodyHtml)
	return err
}

const composeUpsertUserSignature = `-- name: ComposeUpsertUserSignature :exec
INSERT INTO signatures (user_id, mailbox_id, body_html) VALUES ($1, $2, $3)
ON CONFLICT (user_id, mailbox_id) WHERE user_id IS NOT NULL AND mailbox_id IS NOT NULL
    DO UPDATE SET body_html = EXCLUDED.body_html, updated_at = now()
`

type ComposeUpsertUserSignatureParams struct {
	UserID    pgtype.UUID
	MailboxID pgtype.UUID
	BodyHtml  string
}

func (q *Queries) ComposeUpsertUserSignature(ctx context.Context, arg ComposeUpsertUserSignatureParams) error {
	_, err := q.db.Exec(ctx, composeUpsertUserSignature, arg.UserID, arg.MailboxID, arg.BodyHtml)
	return err
}
