// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blankCSATComments = `-- name: BlankCSATComments :execrows
UPDATE csat_responses SET comment = '' WHERE conversation_id = ANY ($1::uuid[]) AND comment <> ''
`

func (q *Queries) BlankCSATComments(ctx context.Context, ids []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, blankCSATComments, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const blankConversations = `-- name: BlankConversations :execrows
UPDATE conversations
SET subject = '', subject_normalized = '', preview = '', custom_attributes = '{}',
    has_attachments = false, version = version + 1, updated_at = now()
WHERE id = ANY ($1::uuid[])
`

func (q *Queries) BlankConversations(ctx context.Context, ids []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, blankConversations, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const blankMessagesOfConversations = `-- name: BlankMessagesOfConversations :many
UPDATE messages SET
    body_text = '', body_html = '', subject = '', auth_results = '',
    message_id_header = '', in_reply_to = '', references_hdr = '{}',
    to_addrs = '[]', cc_addrs = '[]', bcc_addrs = '[]', reply_to = '[]',
    from_name = CASE WHEN direction = 'in' OR kind <> 'email' THEN $1::text ELSE from_name END,
    from_addr = CASE WHEN direction = 'in' THEN $2::text ELSE from_addr END
WHERE conversation_id = ANY ($3::uuid[])
RETURNING id, raw_message_id
`

type BlankMessagesOfConversationsParams struct {
	TombstoneName   string
	TombstoneAddr   string
	ConversationIds []pgtype.UUID
}

type BlankMessagesOfConversationsRow struct {
	ID           pgtype.UUID
	RawMessageID pgtype.UUID
}

// Deletes what was said: bodies, subjects and the header values that name the other side.
func (q *Queries) BlankMessagesOfConversations(ctx context.Context, arg BlankMessagesOfConversationsParams) ([]BlankMessagesOfConversationsRow, error) {
	rows, err := q.db.Query(ctx, blankMessagesOfConversations, arg.TombstoneName, arg.TombstoneAddr, arg.ConversationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlankMessagesOfConversationsRow{}
	for rows.Next() {
		var i BlankMessagesOfConversationsRow
		if err := rows.Scan(&i.ID, &i.RawMessageID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const blobIsReferenced = `-- name: BlobIsReferenced :one

SELECT (EXISTS (SELECT 1 FROM attachments WHERE attachments.blob_key = $1::text)
     OR EXISTS (SELECT 1 FROM raw_messages WHERE raw_messages.blob_key = $1::text)
     OR EXISTS (SELECT 1 FROM uploads WHERE uploads.blob_key = $1::text)
     OR EXISTS (SELECT 1 FROM image_proxy_cache WHERE image_proxy_cache.blob_key = $1::text)
     OR EXISTS (SELECT 1 FROM contact_imports WHERE contact_imports.source_key = $1::text OR contact_imports.error_key = $1::text)
     OR EXISTS (SELECT 1 FROM data_exports WHERE data_exports.blob_key = $1::text)
     OR EXISTS (SELECT 1 FROM kb_images WHERE kb_images.blob_key = $1::text))::boolean
`

// Blob reference counting for erasure and purges
func (q *Queries) BlobIsReferenced(ctx context.Context, key string) (bool, error) {
	row := q.db.QueryRow(ctx, blobIsReferenced, key)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const claimDataExportDownload = `-- name: ClaimDataExportDownload :one
UPDATE data_exports SET status = 'downloaded'
WHERE id = $1 AND requested_by = $2 AND status = 'ready' AND expires_at > now()
RETURNING blob_key, size_bytes
`

type ClaimDataExportDownloadParams struct {
	ID          pgtype.UUID
	RequestedBy pgtype.UUID
}

type ClaimDataExportDownloadRow struct {
	BlobKey   string
	SizeBytes int64
}

func (q *Queries) ClaimDataExportDownload(ctx context.Context, arg ClaimDataExportDownloadParams) (ClaimDataExportDownloadRow, error) {
	row := q.db.QueryRow(ctx, claimDataExportDownload, arg.ID, arg.RequestedBy)
	var i ClaimDataExportDownloadRow
	err := row.Scan(&i.BlobKey, &i.SizeBytes)
	return i, err
}

const clearContactImportBlobs = `-- name: ClearContactImportBlobs :exec
UPDATE contact_imports SET source_key = '', error_key = '' WHERE id = $1
`

func (q *Queries) ClearContactImportBlobs(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearContactImportBlobs, id)
	return err
}

const clearDataExportBlob = `-- name: ClearDataExportBlob :exec
UPDATE data_exports SET blob_key = '' WHERE id = $1
`

func (q *Queries) ClearDataExportBlob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearDataExportBlob, id)
	return err
}

const clearOutboundResponses = `-- name: ClearOutboundResponses :exec
UPDATE outbound SET smtp_response = '', error = ''
WHERE message_id IN (SELECT id FROM messages WHERE conversation_id = ANY ($1::uuid[]))
`

func (q *Queries) ClearOutboundResponses(ctx context.Context, ids []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearOutboundResponses, ids)
	return err
}

const contactAddressEmails = `-- name: ContactAddressEmails :many
SELECT email FROM contact_addresses WHERE contact_id = $1 ORDER BY is_primary DESC, email
`

func (q *Queries) ContactAddressEmails(ctx context.Context, contactID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, contactAddressEmails, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contactIsVisible = `-- name: ContactIsVisible :one
SELECT contact_visible($1, $2::uuid, $3::boolean, $4::uuid[])::boolean
`

type ContactIsVisibleParams struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Admin      bool
	MailboxIds []pgtype.UUID
}

func (q *Queries) ContactIsVisible(ctx context.Context, arg ContactIsVisibleParams) (bool, error) {
	row := q.db.QueryRow(ctx, contactIsVisible,
		arg.ID,
		arg.UserID,
		arg.Admin,
		arg.MailboxIds,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const conversationsOfContact = `-- name: ConversationsOfContact :many

SELECT id FROM conversations WHERE contact_id = $1
`

// Erasure (docs/data-model.md, GDPR)
func (q *Queries) ConversationsOfContact(ctx context.Context, contactID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, conversationsOfContact, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const conversationsWithOtherParties = `-- name: ConversationsWithOtherParties :many
SELECT DISTINCT messages.conversation_id
FROM messages
CROSS JOIN LATERAL (
    SELECT lower(messages.from_addr) AS addr WHERE messages.direction = 'in'
    UNION ALL
    SELECT lower(a ->> 'address')
    FROM jsonb_array_elements(messages.to_addrs || messages.cc_addrs || messages.bcc_addrs || messages.reply_to) AS a
) AS party
WHERE messages.conversation_id = ANY ($1::uuid[]) AND messages.kind = 'email'
  AND party.addr <> '' AND NOT (party.addr = ANY ($2::text[]))
  AND NOT EXISTS (SELECT 1 FROM mailboxes WHERE lower(mailboxes.email_address) = party.addr)
`

type ConversationsWithOtherPartiesParams struct {
	Ids []pgtype.UUID
	Own []string
}

// Conversations among @ids that involve an external address other than the contact's own and
// the mailboxes' addresses: senders of inbound mail, recipients of every email.
func (q *Queries) ConversationsWithOtherParties(ctx context.Context, arg ConversationsWithOtherPartiesParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, conversationsWithOtherParties, arg.Ids, arg.Own)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var conversation_id pgtype.UUID
		if err := rows.Scan(&conversation_id); err != nil {
			return nil, err
		}
		items = append(items, conversation_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countContactNotes = `-- name: CountContactNotes :one
SELECT count(*)::integer FROM crm_notes WHERE contact_id = $1
`

func (q *Queries) CountContactNotes(ctx context.Context, contactID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countContactNotes, contactID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteAttachmentsOfConversations = `-- name: DeleteAttachmentsOfConversations :many
DELETE FROM attachments
WHERE message_id IN (SELECT id FROM messages WHERE conversation_id = ANY ($1::uuid[]))
RETURNING blob_key
`

func (q *Queries) DeleteAttachmentsOfConversations(ctx context.Context, ids []pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteAttachmentsOfConversations, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blob_key string
		if err := rows.Scan(&blob_key); err != nil {
			return nil, err
		}
		items = append(items, blob_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAttributeDef = `-- name: DeleteAttributeDef :one
DELETE FROM custom_attribute_defs WHERE id = $1 RETURNING entity, key
`

type DeleteAttributeDefRow struct {
	Entity string
	Key    string
}

func (q *Queries) DeleteAttributeDef(ctx context.Context, id pgtype.UUID) (DeleteAttributeDefRow, error) {
	row := q.db.QueryRow(ctx, deleteAttributeDef, id)
	var i DeleteAttributeDefRow
	err := row.Scan(&i.Entity, &i.Key)
	return i, err
}

const deleteAutomationRepliesOfAddresses = `-- name: DeleteAutomationRepliesOfAddresses :execrows
DELETE FROM automation_replies WHERE address = ANY ($1::text[])
`

func (q *Queries) DeleteAutomationRepliesOfAddresses(ctx context.Context, addrs []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAutomationRepliesOfAddresses, addrs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCRMNote = `-- name: DeleteCRMNote :exec
DELETE FROM crm_notes WHERE id = $1
`

func (q *Queries) DeleteCRMNote(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCRMNote, id)
	return err
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM contacts WHERE id = $1
`

func (q *Queries) DeleteContact(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteContact, id)
	return err
}

const deleteContactAddress = `-- name: DeleteContactAddress :exec
DELETE FROM contact_addresses WHERE contact_id = $1 AND email = $2
`

type DeleteContactAddressParams struct {
	ContactID pgtype.UUID
	Email     string
}

func (q *Queries) DeleteContactAddress(ctx context.Context, arg DeleteContactAddressParams) error {
	_, err := q.db.Exec(ctx, deleteContactAddress, arg.ContactID, arg.Email)
	return err
}

const deleteContactWebhookEvents = `-- name: DeleteContactWebhookEvents :exec
DELETE FROM webhook_events WHERE contact_id = $1 AND fanned_out_at IS NULL
`

func (q *Queries) DeleteContactWebhookEvents(ctx context.Context, contactID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteContactWebhookEvents, contactID)
	return err
}

const deleteDataExportsOfContact = `-- name: DeleteDataExportsOfContact :many
DELETE FROM data_exports WHERE contact_id = $1 AND blob_key <> '' RETURNING blob_key
`

func (q *Queries) DeleteDataExportsOfContact(ctx context.Context, contactID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteDataExportsOfContact, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blob_key string
		if err := rows.Scan(&blob_key); err != nil {
			return nil, err
		}
		items = append(items, blob_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDraftsOfConversations = `-- name: DeleteDraftsOfConversations :exec
DELETE FROM drafts WHERE conversation_id = ANY ($1::uuid[])
`

func (q *Queries) DeleteDraftsOfConversations(ctx context.Context, ids []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDraftsOfConversations, ids)
	return err
}

const deleteImageAllowlistOfAddresses = `-- name: DeleteImageAllowlistOfAddresses :execrows
DELETE FROM sender_image_allowlist WHERE pattern = ANY ($1::text[])
`

func (q *Queries) DeleteImageAllowlistOfAddresses(ctx context.Context, addrs []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteImageAllowlistOfAddresses, addrs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePendingBlobDeletion = `-- name: DeletePendingBlobDeletion :exec
DELETE FROM pending_blob_deletions WHERE blob_key = $1
`

func (q *Queries) DeletePendingBlobDeletion(ctx context.Context, blobKey string) error {
	_, err := q.db.Exec(ctx, deletePendingBlobDeletion, blobKey)
	return err
}

const deleteSegment = `-- name: DeleteSegment :exec
DELETE FROM contact_segments WHERE id = $1
`

func (q *Queries) DeleteSegment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSegment, id)
	return err
}

const deleteThreadRefsOfConversations = `-- name: DeleteThreadRefsOfConversations :exec
DELETE FROM thread_refs WHERE conversation_id = ANY ($1::uuid[])
`

func (q *Queries) DeleteThreadRefsOfConversations(ctx context.Context, ids []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteThreadRefsOfConversations, ids)
	return err
}

const dropRawMessages = `-- name: DropRawMessages :exec
UPDATE raw_messages
SET blob_key = '', size_bytes = 0, parse_status = 'skipped', parse_error = 'erased'
WHERE id = ANY ($1::uuid[])
`

// The .eml copy still holds the address and body. The row stays so IMAP sync does not fetch
// the message again.
func (q *Queries) DropRawMessages(ctx context.Context, ids []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, dropRawMessages, ids)
	return err
}

const expiredContactImports = `-- name: ExpiredContactImports :many
SELECT id, source_key, error_key FROM contact_imports
WHERE (finished_at IS NOT NULL AND finished_at < $1::timestamptz AND error_key <> '')
   OR (finished_at IS NULL AND created_at < $1::timestamptz AND source_key <> '')
`

type ExpiredContactImportsRow struct {
	ID        pgtype.UUID
	SourceKey string
	ErrorKey  string
}

func (q *Queries) ExpiredContactImports(ctx context.Context, before pgtype.Timestamptz) ([]ExpiredContactImportsRow, error) {
	rows, err := q.db.Query(ctx, expiredContactImports, before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpiredContactImportsRow{}
	for rows.Next() {
		var i ExpiredContactImportsRow
		if err := rows.Scan(&i.ID, &i.SourceKey, &i.ErrorKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expiredDataExports = `-- name: ExpiredDataExports :many
SELECT id, blob_key FROM data_exports
WHERE blob_key <> '' AND (status = 'downloaded' OR expires_at < now())
`

type ExpiredDataExportsRow struct {
	ID      pgtype.UUID
	BlobKey string
}

func (q *Queries) ExpiredDataExports(ctx context.Context) ([]ExpiredDataExportsRow, error) {
	rows, err := q.db.Query(ctx, expiredDataExports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpiredDataExportsRow{}
	for rows.Next() {
		var i ExpiredDataExportsRow
		if err := rows.Scan(&i.ID, &i.BlobKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportCSATResponses = `-- name: ExportCSATResponses :many
SELECT conversation_id, rating, comment, created_at FROM csat_responses WHERE conversation_id = ANY ($1::uuid[])
`

type ExportCSATResponsesRow struct {
	ConversationID pgtype.UUID
	Rating         int16
	Comment        string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) ExportCSATResponses(ctx context.Context, ids []pgtype.UUID) ([]ExportCSATResponsesRow, error) {
	rows, err := q.db.Query(ctx, exportCSATResponses, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportCSATResponsesRow{}
	for rows.Next() {
		var i ExportCSATResponsesRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportContactConversations = `-- name: ExportContactConversations :many

SELECT conversations.id, conversations.number, conversations.subject, conversations.status,
       conversations.custom_attributes, conversations.created_at, mailboxes.name AS mailbox_name
FROM conversations JOIN mailboxes ON mailboxes.id = conversations.mailbox_id
WHERE conversations.contact_id = $1 AND conversations.mailbox_id = ANY ($2::uuid[])
  AND conversations.deleted_at IS NULL
ORDER BY conversations.created_at, conversations.id
`

type ExportContactConversationsParams struct {
	ContactID  pgtype.UUID
	MailboxIds []pgtype.UUID
}

type ExportContactConversationsRow struct {
	ID               pgtype.UUID
	Number           int64
	Subject          string
	Status           string
	CustomAttributes []byte
	CreatedAt        pgtype.Timestamptz
	MailboxName      string
}

// GDPR export data
func (q *Queries) ExportContactConversations(ctx context.Context, arg ExportContactConversationsParams) ([]ExportContactConversationsRow, error) {
	rows, err := q.db.Query(ctx, exportContactConversations, arg.ContactID, arg.MailboxIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportContactConversationsRow{}
	for rows.Next() {
		var i ExportContactConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Subject,
			&i.Status,
			&i.CustomAttributes,
			&i.CreatedAt,
			&i.MailboxName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportContactNotes = `-- name: ExportContactNotes :many
SELECT crm_notes.body, crm_notes.created_at, users.name AS author_name
FROM crm_notes LEFT JOIN users ON users.id = crm_notes.author_user_id
WHERE crm_notes.contact_id = $1 ORDER BY crm_notes.created_at, crm_notes.id
`

type ExportContactNotesRow struct {
	Body       string
	CreatedAt  pgtype.Timestamptz
	AuthorName pgtype.Text
}

func (q *Queries) ExportContactNotes(ctx context.Context, contactID pgtype.UUID) ([]ExportContactNotesRow, error) {
	rows, err := q.db.Query(ctx, exportContactNotes, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportContactNotesRow{}
	for rows.Next() {
		var i ExportContactNotesRow
		if err := rows.Scan(&i.Body, &i.CreatedAt, &i.AuthorName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportContactRow = `-- name: ExportContactRow :one
SELECT contacts.id, contacts.name, contacts.phone, contacts.custom_attributes, contacts.created_at,
       contacts.updated_at, organizations.name AS organization_name, organizations.domains AS organization_domains
FROM contacts LEFT JOIN organizations ON organizations.id = contacts.organization_id
WHERE contacts.id = $1
`

type ExportContactRowRow struct {
	ID                  pgtype.UUID
	Name                string
	Phone               string
	CustomAttributes    []byte
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	OrganizationName    pgtype.Text
	OrganizationDomains []string
}

func (q *Queries) ExportContactRow(ctx context.Context, id pgtype.UUID) (ExportContactRowRow, error) {
	row := q.db.QueryRow(ctx, exportContactRow, id)
	var i ExportContactRowRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.CustomAttributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationName,
		&i.OrganizationDomains,
	)
	return i, err
}

const exportConversationMessages = `-- name: ExportConversationMessages :many
SELECT messages.id, messages.conversation_id, messages.kind, messages.direction, messages.from_name,
       messages.from_addr, messages.to_addrs, messages.cc_addrs, messages.subject, messages.body_text,
       messages.sent_at, messages.received_at, users.name AS author_name
FROM messages LEFT JOIN users ON users.id = messages.author_user_id
WHERE messages.conversation_id = ANY ($1::uuid[]) AND messages.deleted_at IS NULL
ORDER BY messages.conversation_id, messages.received_at, messages.id
`

type ExportConversationMessagesRow struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Kind           string
	Direction      pgtype.Text
	FromName       string
	FromAddr       string
	ToAddrs        []byte
	CcAddrs        []byte
	Subject        string
	BodyText       string
	SentAt         pgtype.Timestamptz
	ReceivedAt     pgtype.Timestamptz
	AuthorName     pgtype.Text
}

func (q *Queries) ExportConversationMessages(ctx context.Context, ids []pgtype.UUID) ([]ExportConversationMessagesRow, error) {
	rows, err := q.db.Query(ctx, exportConversationMessages, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportConversationMessagesRow{}
	for rows.Next() {
		var i ExportConversationMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Kind,
			&i.Direction,
			&i.FromName,
			&i.FromAddr,
			&i.ToAddrs,
			&i.CcAddrs,
			&i.Subject,
			&i.BodyText,
			&i.SentAt,
			&i.ReceivedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportMessageAttachments = `-- name: ExportMessageAttachments :many
SELECT id, message_id, filename, blob_key, size_bytes FROM attachments
WHERE message_id = ANY ($1::uuid[]) ORDER BY message_id, created_at, id
`

type ExportMessageAttachmentsRow struct {
	ID        pgtype.UUID
	MessageID pgtype.UUID
	Filename  string
	BlobKey   string
	SizeBytes int64
}

func (q *Queries) ExportMessageAttachments(ctx context.Context, ids []pgtype.UUID) ([]ExportMessageAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, exportMessageAttachments, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportMessageAttachmentsRow{}
	for rows.Next() {
		var i ExportMessageAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Filename,
			&i.BlobKey,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findContactByEmail = `-- name: FindContactByEmail :one
SELECT contact_id FROM contact_addresses WHERE email = $1
`

func (q *Queries) FindContactByEmail(ctx context.Context, email string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findContactByEmail, email)
	var contact_id pgtype.UUID
	err := row.Scan(&contact_id)
	return contact_id, err
}

const findOrganizationByName = `-- name: FindOrganizationByName :one
SELECT id FROM organizations WHERE lower(name) = lower($1::text) ORDER BY created_at, id LIMIT 1
`

func (q *Queries) FindOrganizationByName(ctx context.Context, name string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findOrganizationByName, name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const finishContactImport = `-- name: FinishContactImport :exec
UPDATE contact_imports
SET status = $1, error = $2, error_key = $3, source_key = '', finished_at = now(),
    processed_rows = $4, created_count = $5, updated_count = $6,
    skipped_count = $7, failed_count = $8
WHERE id = $9
`

type FinishContactImportParams struct {
	Status        string
	Error         string
	ErrorKey      string
	ProcessedRows int32
	CreatedCount  int32
	UpdatedCount  int32
	SkippedCount  int32
	FailedCount   int32
	ID            pgtype.UUID
}

func (q *Queries) FinishContactImport(ctx context.Context, arg FinishContactImportParams) error {
	_, err := q.db.Exec(ctx, finishContactImport,
		arg.Status,
		arg.Error,
		arg.ErrorKey,
		arg.ProcessedRows,
		arg.CreatedCount,
		arg.UpdatedCount,
		arg.SkippedCount,
		arg.FailedCount,
		arg.ID,
	)
	return err
}

const getAttributeDef = `-- name: GetAttributeDef :one
SELECT id, entity, key, label, type, options, created_at FROM custom_attribute_defs WHERE id = $1
`

func (q *Queries) GetAttributeDef(ctx context.Context, id pgtype.UUID) (CustomAttributeDef, error) {
	row := q.db.QueryRow(ctx, getAttributeDef, id)
	var i CustomAttributeDef
	err := row.Scan(
		&i.ID,
		&i.Entity,
		&i.Key,
		&i.Label,
		&i.Type,
		&i.Options,
		&i.CreatedAt,
	)
	return i, err
}

const getCRMNote = `-- name: GetCRMNote :one
SELECT id, contact_id, organization_id, author_user_id FROM crm_notes WHERE id = $1
`

type GetCRMNoteRow struct {
	ID             pgtype.UUID
	ContactID      pgtype.UUID
	OrganizationID pgtype.UUID
	AuthorUserID   pgtype.UUID
}

func (q *Queries) GetCRMNote(ctx context.Context, id pgtype.UUID) (GetCRMNoteRow, error) {
	row := q.db.QueryRow(ctx, getCRMNote, id)
	var i GetCRMNoteRow
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.OrganizationID,
		&i.AuthorUserID,
	)
	return i, err
}

const getCRMNoteView = `-- name: GetCRMNoteView :one
SELECT crm_notes.id, crm_notes.body, crm_notes.created_at, crm_notes.updated_at,
       users.id AS author_id, users.name AS author_name
FROM crm_notes LEFT JOIN users ON users.id = crm_notes.author_user_id
WHERE crm_notes.id = $1
`

type GetCRMNoteViewRow struct {
	ID         pgtype.UUID
	Body       string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	AuthorID   pgtype.UUID
	AuthorName pgtype.Text
}

func (q *Queries) GetCRMNoteView(ctx context.Context, id pgtype.UUID) (GetCRMNoteViewRow, error) {
	row := q.db.QueryRow(ctx, getCRMNoteView, id)
	var i GetCRMNoteViewRow
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.AuthorName,
	)
	return i, err
}

const getContactImport = `-- name: GetContactImport :one
SELECT id, created_by, filename, status, dedupe, delimiter, mapping, source_key, error_key, total_rows,
       processed_rows, created_count, updated_count, skipped_count, failed_count, error, created_at, finished_at
FROM contact_imports WHERE id = $1
`

func (q *Queries) GetContactImport(ctx context.Context, id pgtype.UUID) (ContactImport, error) {
	row := q.db.QueryRow(ctx, getContactImport, id)
	var i ContactImport
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Filename,
		&i.Status,
		&i.Dedupe,
		&i.Delimiter,
		&i.Mapping,
		&i.SourceKey,
		&i.ErrorKey,
		&i.TotalRows,
		&i.ProcessedRows,
		&i.CreatedCount,
		&i.UpdatedCount,
		&i.SkippedCount,
		&i.FailedCount,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getConversationAttributes = `-- name: GetConversationAttributes :one
SELECT id, custom_attributes FROM conversations
WHERE id = $1 AND mailbox_id = ANY ($2::uuid[]) AND deleted_at IS NULL
`

type GetConversationAttributesParams struct {
	ID         pgtype.UUID
	MailboxIds []pgtype.UUID
}

type GetConversationAttributesRow struct {
	ID               pgtype.UUID
	CustomAttributes []byte
}

func (q *Queries) GetConversationAttributes(ctx context.Context, arg GetConversationAttributesParams) (GetConversationAttributesRow, error) {
	row := q.db.QueryRow(ctx, getConversationAttributes, arg.ID, arg.MailboxIds)
	var i GetConversationAttributesRow
	err := row.Scan(&i.ID, &i.CustomAttributes)
	return i, err
}

const getDataExport = `-- name: GetDataExport :one
SELECT id, contact_id, requested_by, status, blob_key, size_bytes, error, created_at, expires_at
FROM data_exports WHERE id = $1
`

func (q *Queries) GetDataExport(ctx context.Context, id pgtype.UUID) (DataExport, error) {
	row := q.db.QueryRow(ctx, getDataExport, id)
	var i DataExport
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.RequestedBy,
		&i.Status,
		&i.BlobKey,
		&i.SizeBytes,
		&i.Error,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSegment = `-- name: GetSegment :one
SELECT id, name, owner_user_id, shared, filter, created_at, updated_at FROM contact_segments WHERE id = $1
`

func (q *Queries) GetSegment(ctx context.Context, id pgtype.UUID) (ContactSegment, error) {
	row := q.db.QueryRow(ctx, getSegment, id)
	var i ContactSegment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.Shared,
		&i.Filter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVisibleContact = `-- name: GetVisibleContact :one

SELECT contacts.id, contacts.name, contacts.phone, contacts.custom_attributes, contacts.created_at,
       contacts.updated_at, contacts.last_activity_at, contacts.created_by, contacts.unsubscribed_at,
       organizations.id AS organization_id, organizations.name AS organization_name,
       (SELECT count(*) FROM conversations
        WHERE conversations.contact_id = contacts.id AND conversations.deleted_at IS NULL
          AND ($1::boolean OR conversations.mailbox_id = ANY ($2::uuid[])))::integer AS conversation_count
FROM contacts
LEFT JOIN organizations ON organizations.id = contacts.organization_id
WHERE contacts.id = $3 AND contact_visible(contacts.id, $4::uuid, $1::boolean, $2::uuid[])
`

type GetVisibleContactParams struct {
	Admin      bool
	MailboxIds []pgtype.UUID
	ID         pgtype.UUID
	UserID     pgtype.UUID
}

type GetVisibleContactRow struct {
	ID                pgtype.UUID
	Name              string
	Phone             string
	CustomAttributes  []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	LastActivityAt    pgtype.Timestamptz
	CreatedBy         pgtype.UUID
	UnsubscribedAt    pgtype.Timestamptz
	OrganizationID    pgtype.UUID
	OrganizationName  pgtype.Text
	ConversationCount int32
}

// Contacts, organizations, notes, custom attributes, segments, imports and GDPR.
// Visibility is decided by contact_visible / organization_visible (migration 00015); every
// query that takes a user-supplied contact or organization id goes through them.
func (q *Queries) GetVisibleContact(ctx context.Context, arg GetVisibleContactParams) (GetVisibleContactRow, error) {
	row := q.db.QueryRow(ctx, getVisibleContact,
		arg.Admin,
		arg.MailboxIds,
		arg.ID,
		arg.UserID,
	)
	var i GetVisibleContactRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.CustomAttributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivityAt,
		&i.CreatedBy,
		&i.UnsubscribedAt,
		&i.OrganizationID,
		&i.OrganizationName,
		&i.ConversationCount,
	)
	return i, err
}

const getVisibleOrganization = `-- name: GetVisibleOrganization :one
SELECT organizations.id, organizations.name, organizations.domains, organizations.custom_attributes,
       organizations.created_at, organizations.updated_at,
       (SELECT count(*) FROM contacts
        WHERE contacts.organization_id = organizations.id
          AND contact_visible(contacts.id, $1::uuid, $2::boolean, $3::uuid[]))::integer AS contact_count
FROM organizations
WHERE organizations.id = $4 AND organization_visible(organizations.id, $1::uuid, $2::boolean, $3::uuid[])
`

type GetVisibleOrganizationParams struct {
	UserID     pgtype.UUID
	Admin      bool
	MailboxIds []pgtype.UUID
	ID         pgtype.UUID
}

type GetVisibleOrganizationRow struct {
	ID               pgtype.UUID
	Name             string
	Domains          []string
	CustomAttributes []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ContactCount     int32
}

func (q *Queries) GetVisibleOrganization(ctx context.Context, arg GetVisibleOrganizationParams) (GetVisibleOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getVisibleOrganization,
		arg.UserID,
		arg.Admin,
		arg.MailboxIds,
		arg.ID,
	)
	var i GetVisibleOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domains,
		&i.CustomAttributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContactCount,
	)
	return i, err
}

const insertAttributeDef = `-- name: InsertAttributeDef :one
INSERT INTO custom_attribute_defs (entity, key, label, type, options)
VALUES ($1, $2, $3, $4, $5::text[])
RETURNING id, entity, key, label, type, options, created_at
`

type InsertAttributeDefParams struct {
	Entity  string
	Key     string
	Label   string
	Type    string
	Options []string
}

func (q *Queries) InsertAttributeDef(ctx context.Context, arg InsertAttributeDefParams) (CustomAttributeDef, error) {
	row := q.db.QueryRow(ctx, insertAttributeDef,
		arg.Entity,
		arg.Key,
		arg.Label,
		arg.Type,
		arg.Options,
	)
	var i CustomAttributeDef
	err := row.Scan(
		&i.ID,
		&i.Entity,
		&i.Key,
		&i.Label,
		&i.Type,
		&i.Options,
		&i.CreatedAt,
	)
	return i, err
}

const insertCRMNote = `-- name: InsertCRMNote :one
INSERT INTO crm_notes (contact_id, organization_id, author_user_id, body)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertCRMNoteParams struct {
	ContactID      pgtype.UUID
	OrganizationID pgtype.UUID
	AuthorUserID   pgtype.UUID
	Body           string
}

func (q *Queries) InsertCRMNote(ctx context.Context, arg InsertCRMNoteParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertCRMNote,
		arg.ContactID,
		arg.OrganizationID,
		arg.AuthorUserID,
		arg.Body,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertContact = `-- name: InsertContact :one
INSERT INTO contacts (name, phone, organization_id, custom_attributes, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertContactParams struct {
	Name             string
	Phone            string
	OrganizationID   pgtype.UUID
	CustomAttributes []byte
	CreatedBy        pgtype.UUID
}

func (q *Queries) InsertContact(ctx context.Context, arg InsertContactParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertContact,
		arg.Name,
		arg.Phone,
		arg.OrganizationID,
		arg.CustomAttributes,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertContactAddress = `-- name: InsertContactAddress :exec
INSERT INTO contact_addresses (contact_id, email, is_primary) VALUES ($1, $2, $3)
`

type InsertContactAddressParams struct {
	ContactID pgtype.UUID
	Email     string
	IsPrimary bool
}

func (q *Queries) InsertContactAddress(ctx context.Context, arg InsertContactAddressParams) error {
	_, err := q.db.Exec(ctx, insertContactAddress, arg.ContactID, arg.Email, arg.IsPrimary)
	return err
}

const insertContactImport = `-- name: InsertContactImport :one

INSERT INTO contact_imports (created_by, filename, dedupe, delimiter, mapping, source_key, total_rows)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertContactImportParams struct {
	CreatedBy pgtype.UUID
	Filename  string
	Dedupe    string
	Delimiter string
	Mapping   []byte
	SourceKey string
	TotalRows int32
}

// Imports
func (q *Queries) InsertContactImport(ctx context.Context, arg InsertContactImportParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertContactImport,
		arg.CreatedBy,
		arg.Filename,
		arg.Dedupe,
		arg.Delimiter,
		arg.Mapping,
		arg.SourceKey,
		arg.TotalRows,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertContactMergedEvent = `-- name: InsertContactMergedEvent :exec
INSERT INTO conversation_events (conversation_id, mailbox_id, actor_user_id, type, data)
VALUES ($1, $2, $3, 'contact_merged',
        jsonb_build_object('contact_id', $4::text, 'merged_contact_id', $5::text))
`

type InsertContactMergedEventParams struct {
	ConversationID pgtype.UUID
	MailboxID      pgtype.UUID
	ActorUserID    pgtype.UUID
	PrimaryID      string
	SecondaryID    string
}

func (q *Queries) InsertContactMergedEvent(ctx context.Context, arg InsertContactMergedEventParams) error {
	_, err := q.db.Exec(ctx, insertContactMergedEvent,
		arg.ConversationID,
		arg.MailboxID,
		arg.ActorUserID,
		arg.PrimaryID,
		arg.SecondaryID,
	)
	return err
}

const insertDataExport = `-- name: InsertDataExport :one

INSERT INTO data_exports (contact_id, requested_by) VALUES ($1, $2) RETURNING id
`

type InsertDataExportParams struct {
	ContactID   pgtype.UUID
	RequestedBy pgtype.UUID
}

// Data exports (GDPR)
func (q *Queries) InsertDataExport(ctx context.Context, arg InsertDataExportParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertDataExport, arg.ContactID, arg.RequestedBy)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertOrganization = `-- name: InsertOrganization :one
INSERT INTO organizations (name, domains, custom_attributes, created_by)
VALUES ($1, $2::text[], $3, $4)
RETURNING id
`

type InsertOrganizationParams struct {
	Name             string
	Domains          []string
	CustomAttributes []byte
	CreatedBy        pgtype.UUID
}

func (q *Queries) InsertOrganization(ctx context.Context, arg InsertOrganizationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertOrganization,
		arg.Name,
		arg.Domains,
		arg.CustomAttributes,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertSegment = `-- name: InsertSegment :one
INSERT INTO contact_segments (name, owner_user_id, shared, filter)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertSegmentParams struct {
	Name        string
	OwnerUserID pgtype.UUID
	Shared      bool
	Filter      []byte
}

func (q *Queries) InsertSegment(ctx context.Context, arg InsertSegmentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertSegment,
		arg.Name,
		arg.OwnerUserID,
		arg.Shared,
		arg.Filter,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listAddressesOfContacts = `-- name: ListAddressesOfContacts :many
SELECT contact_id, email, is_primary, bounced_at FROM contact_addresses
WHERE contact_id = ANY ($1::uuid[])
ORDER BY contact_id, is_primary DESC, email
`

func (q *Queries) ListAddressesOfContacts(ctx context.Context, ids []pgtype.UUID) ([]ContactAddress, error) {
	rows, err := q.db.Query(ctx, listAddressesOfContacts, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactAddress{}
	for rows.Next() {
		var i ContactAddress
		if err := rows.Scan(
			&i.ContactID,
			&i.Email,
			&i.IsPrimary,
			&i.BouncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttributeDefs = `-- name: ListAttributeDefs :many

SELECT id, entity, key, label, type, options, created_at FROM custom_attribute_defs
WHERE ($1::text IS NULL OR entity = $1::text)
ORDER BY entity, created_at, id
`

// Custom attribute definitions
func (q *Queries) ListAttributeDefs(ctx context.Context, entity pgtype.Text) ([]CustomAttributeDef, error) {
	rows, err := q.db.Query(ctx, listAttributeDefs, entity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomAttributeDef{}
	for rows.Next() {
		var i CustomAttributeDef
		if err := rows.Scan(
			&i.ID,
			&i.Entity,
			&i.Key,
			&i.Label,
			&i.Type,
			&i.Options,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactConversationPage = `-- name: ListContactConversationPage :many
SELECT conversations.id, conversations.last_message_at,
       CASE WHEN conversations.status IN ('open', 'waiting') THEN 0 ELSE 1 END::integer AS rank
FROM conversations
WHERE conversations.contact_id = $1 AND conversations.deleted_at IS NULL
  AND ($2::boolean OR conversations.mailbox_id = ANY ($3::uuid[]))
  AND ($4::uuid IS NULL
       OR CASE WHEN conversations.status IN ('open', 'waiting') THEN 0 ELSE 1 END > $5::integer
       OR (CASE WHEN conversations.status IN ('open', 'waiting') THEN 0 ELSE 1 END = $5::integer
           AND (conversations.last_message_at, conversations.id) < ($6::timestamptz, $4::uuid)))
ORDER BY rank, conversations.last_message_at DESC, conversations.id DESC
LIMIT $7::integer
`

type ListContactConversationPageParams struct {
	ContactID  pgtype.UUID
	Admin      bool
	MailboxIds []pgtype.UUID
	CursorID   pgtype.UUID
	CursorRank int32
	CursorAt   pgtype.Timestamptz
	PageSize   int32
}

type ListContactConversationPageRow struct {
	ID            pgtype.UUID
	LastMessageAt pgtype.Timestamptz
	Rank          int32
}

// Open and waiting conversations first, then by recency. Only conversations the caller can read.
func (q *Queries) ListContactConversationPage(ctx context.Context, arg ListContactConversationPageParams) ([]ListContactConversationPageRow, error) {
	rows, err := q.db.Query(ctx, listContactConversationPage,
		arg.ContactID,
		arg.Admin,
		arg.MailboxIds,
		arg.CursorID,
		arg.CursorRank,
		arg.CursorAt,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactConversationPageRow{}
	for rows.Next() {
		var i ListContactConversationPageRow
		if err := rows.Scan(&i.ID, &i.LastMessageAt, &i.Rank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactNotes = `-- name: ListContactNotes :many

SELECT crm_notes.id, crm_notes.body, crm_notes.created_at, crm_notes.updated_at,
       users.id AS author_id, users.name AS author_name
FROM crm_notes LEFT JOIN users ON users.id = crm_notes.author_user_id
WHERE crm_notes.contact_id = $1
ORDER BY crm_notes.created_at DESC, crm_notes.id DESC
LIMIT $2::integer
`

type ListContactNotesParams struct {
	ContactID pgtype.UUID
	RowLimit  int32
}

type ListContactNotesRow struct {
	ID         pgtype.UUID
	Body       string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	AuthorID   pgtype.UUID
	AuthorName pgtype.Text
}

// Notes
func (q *Queries) ListContactNotes(ctx context.Context, arg ListContactNotesParams) ([]ListContactNotesRow, error) {
	rows, err := q.db.Query(ctx, listContactNotes, arg.ContactID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactNotesRow{}
	for rows.Next() {
		var i ListContactNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactTimeline = `-- name: ListContactTimeline :many
SELECT id, kind, type, at, conversation_id, conversation_number, conversation_subject, actor_name, body, data, target_id, target_name FROM (
    SELECT conversation_events.id, 'event'::text AS kind, conversation_events.type, conversation_events.created_at AS at,
           conversation_events.conversation_id, conversations.number AS conversation_number,
           conversations.subject AS conversation_subject, actor.name AS actor_name, ''::text AS body,
           conversation_events.data, target.id AS target_id, target.name AS target_name
    FROM conversation_events
    JOIN conversations ON conversations.id = conversation_events.conversation_id
    LEFT JOIN users AS actor ON actor.id = conversation_events.actor_user_id
    LEFT JOIN users AS target ON target.id = NULLIF(conversation_events.data ->> 'user_id', '')::uuid
    WHERE conversations.contact_id = $1 AND conversations.deleted_at IS NULL
      AND ($2::boolean OR conversations.mailbox_id = ANY ($3::uuid[]))
    UNION ALL
    SELECT crm_notes.id, 'note'::text, 'note', crm_notes.created_at,
           NULL::uuid, 0::bigint, ''::text, author.name, crm_notes.body, '{}'::jsonb, NULL::uuid, NULL::text
    FROM crm_notes
    LEFT JOIN users AS author ON author.id = crm_notes.author_user_id
    WHERE crm_notes.contact_id = $1
) AS timeline
WHERE ($4::uuid IS NULL
       OR (timeline.at, timeline.id) < ($5::timestamptz, $4::uuid))
ORDER BY timeline.at DESC, timeline.id DESC
LIMIT $6::integer
`

type ListContactTimelineParams struct {
	ContactID  pgtype.UUID
	Admin      bool
	MailboxIds []pgtype.UUID
	CursorID   pgtype.UUID
	CursorAt   pgtype.Timestamptz
	PageSize   int32
}

type ListContactTimelineRow struct {
	ID                  pgtype.UUID
	Kind                string
	Type                string
	At                  pgtype.Timestamptz
	ConversationID      pgtype.UUID
	ConversationNumber  int64
	ConversationSubject string
	ActorName           pgtype.Text
	Body                string
	Data                []byte
	TargetID            pgtype.UUID
	TargetName          pgtype.Text
}

// Conversation events of readable conversations plus the contact's notes, newest first.
func (q *Queries) ListContactTimeline(ctx context.Context, arg ListContactTimelineParams) ([]ListContactTimelineRow, error) {
	rows, err := q.db.Query(ctx, listContactTimeline,
		arg.ContactID,
		arg.Admin,
		arg.MailboxIds,
		arg.CursorID,
		arg.CursorAt,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactTimelineRow{}
	for rows.Next() {
		var i ListContactTimelineRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Type,
			&i.At,
			&i.ConversationID,
			&i.ConversationNumber,
			&i.ConversationSubject,
			&i.ActorName,
			&i.Body,
			&i.Data,
			&i.TargetID,
			&i.TargetName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationContacts = `-- name: ListOrganizationContacts :many
SELECT contacts.id, contacts.name, contacts.last_activity_at,
       COALESCE((SELECT email FROM contact_addresses WHERE contact_id = contacts.id
                 ORDER BY is_primary DESC, email LIMIT 1), '')::text AS email
FROM contacts
WHERE contacts.organization_id = $1
  AND contact_visible(contacts.id, $2::uuid, $3::boolean, $4::uuid[])
ORDER BY contacts.last_activity_at DESC, contacts.id DESC
LIMIT $5::integer
`

type ListOrganizationContactsParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Admin          bool
	MailboxIds     []pgtype.UUID
	RowLimit       int32
}

type ListOrganizationContactsRow struct {
	ID             pgtype.UUID
	Name           string
	LastActivityAt pgtype.Timestamptz
	Email          string
}

func (q *Queries) ListOrganizationContacts(ctx context.Context, arg ListOrganizationContactsParams) ([]ListOrganizationContactsRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationContacts,
		arg.OrganizationID,
		arg.UserID,
		arg.Admin,
		arg.MailboxIds,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationContactsRow{}
	for rows.Next() {
		var i ListOrganizationContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LastActivityAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationConversationPage = `-- name: ListOrganizationConversationPage :many
SELECT conversations.id, conversations.last_message_at,
       CASE WHEN conversations.status IN ('open', 'waiting') THEN 0 ELSE 1 END::integer AS rank
FROM conversations
JOIN contacts ON contacts.id = conversations.contact_id
WHERE contacts.organization_id = $1 AND conversations.deleted_at IS NULL
  AND ($2::boolean OR conversations.mailbox_id = ANY ($3::uuid[]))
  AND ($4::uuid IS NULL
       OR CASE WHEN conversations.status IN ('open', 'waiting') THEN 0 ELSE 1 END > $5::integer
       OR (CASE WHEN conversations.status IN ('open', 'waiting') THEN 0 ELSE 1 END = $5::integer
           AND (conversations.last_message_at, conversations.id) < ($6::timestamptz, $4::uuid)))
ORDER BY rank, conversations.last_message_at DESC, conversations.id DESC
LIMIT $7::integer
`

type ListOrganizationConversationPageParams struct {
	OrganizationID pgtype.UUID
	Admin          bool
	MailboxIds     []pgtype.UUID
	CursorID       pgtype.UUID
	CursorRank     int32
	CursorAt       pgtype.Timestamptz
	PageSize       int32
}

type ListOrganizationConversationPageRow struct {
	ID            pgtype.UUID
	LastMessageAt pgtype.Timestamptz
	Rank          int32
}

func (q *Queries) ListOrganizationConversationPage(ctx context.Context, arg ListOrganizationConversationPageParams) ([]ListOrganizationConversationPageRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationConversationPage,
		arg.OrganizationID,
		arg.Admin,
		arg.MailboxIds,
		arg.CursorID,
		arg.CursorRank,
		arg.CursorAt,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationConversationPageRow{}
	for rows.Next() {
		var i ListOrganizationConversationPageRow
		if err := rows.Scan(&i.ID, &i.LastMessageAt, &i.Rank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationNotes = `-- name: ListOrganizationNotes :many
SELECT crm_notes.id, crm_notes.body, crm_notes.created_at, crm_notes.updated_at,
       users.id AS author_id, users.name AS author_name
FROM crm_notes LEFT JOIN users ON users.id = crm_notes.author_user_id
WHERE crm_notes.organization_id = $1
ORDER BY crm_notes.created_at DESC, crm_notes.id DESC
LIMIT $2::integer
`

type ListOrganizationNotesParams struct {
	OrganizationID pgtype.UUID
	RowLimit       int32
}

type ListOrganizationNotesRow struct {
	ID         pgtype.UUID
	Body       string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	AuthorID   pgtype.UUID
	AuthorName pgtype.Text
}

func (q *Queries) ListOrganizationNotes(ctx context.Context, arg ListOrganizationNotesParams) ([]ListOrganizationNotesRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationNotes, arg.OrganizationID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationNotesRow{}
	for rows.Next() {
		var i ListOrganizationNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingBlobDeletions = `-- name: ListPendingBlobDeletions :many
SELECT blob_key FROM pending_blob_deletions ORDER BY queued_at, blob_key LIMIT $1::integer
`

func (q *Queries) ListPendingBlobDeletions(ctx context.Context, rowLimit int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listPendingBlobDeletions, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blob_key string
		if err := rows.Scan(&blob_key); err != nil {
			return nil, err
		}
		items = append(items, blob_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSegments = `-- name: ListSegments :many

SELECT contact_segments.id, contact_segments.name, contact_segments.owner_user_id, contact_segments.shared,
       contact_segments.filter, contact_segments.created_at, contact_segments.updated_at, users.name AS owner_name
FROM contact_segments JOIN users ON users.id = contact_segments.owner_user_id
WHERE contact_segments.owner_user_id = $1 OR contact_segments.shared
ORDER BY lower(contact_segments.name), contact_segments.id
`

type ListSegmentsRow struct {
	ID          pgtype.UUID
	Name        string
	OwnerUserID pgtype.UUID
	Shared      bool
	Filter      []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	OwnerName   string
}

// Segments
func (q *Queries) ListSegments(ctx context.Context, userID pgtype.UUID) ([]ListSegmentsRow, error) {
	rows, err := q.db.Query(ctx, listSegments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSegmentsRow{}
	for rows.Next() {
		var i ListSegmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerUserID,
			&i.Shared,
			&i.Filter,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleOrganizations = `-- name: ListVisibleOrganizations :many

SELECT organizations.id, organizations.name, organizations.domains, organizations.created_at,
       lower(organizations.name)::text AS sort_name,
       (SELECT count(*) FROM contacts
        WHERE contacts.organization_id = organizations.id
          AND contact_visible(contacts.id, $1::uuid, $2::boolean, $3::uuid[]))::integer AS contact_count
FROM organizations
WHERE organization_visible(organizations.id, $1::uuid, $2::boolean, $3::uuid[])
  AND ($4::text IS NULL OR organizations.name ILIKE '%' || $4::text || '%'
       OR EXISTS (SELECT 1 FROM unnest(organizations.domains) AS domain WHERE domain ILIKE '%' || $4::text || '%'))
  AND (lower(organizations.name), organizations.id) > (
        COALESCE($5::text, ''),
        COALESCE($6::uuid, '00000000-0000-0000-0000-000000000000'::uuid))
ORDER BY lower(organizations.name), organizations.id
LIMIT $7::integer
`

type ListVisibleOrganizationsParams struct {
	UserID     pgtype.UUID
	Admin      bool
	MailboxIds []pgtype.UUID
	Search     pgtype.Text
	CursorName pgtype.Text
	CursorID   pgtype.UUID
	PageSize   int32
}

type ListVisibleOrganizationsRow struct {
	ID           pgtype.UUID
	Name         string
	Domains      []string
	CreatedAt    pgtype.Timestamptz
	SortName     string
	ContactCount int32
}

// Organizations
func (q *Queries) ListVisibleOrganizations(ctx context.Context, arg ListVisibleOrganizationsParams) ([]ListVisibleOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listVisibleOrganizations,
		arg.UserID,
		arg.Admin,
		arg.MailboxIds,
		arg.Search,
		arg.CursorName,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleOrganizationsRow{}
	for rows.Next() {
		var i ListVisibleOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domains,
			&i.CreatedAt,
			&i.SortName,
			&i.ContactCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockContact = `-- name: LockContact :one
SELECT id, name, phone, organization_id, custom_attributes FROM contacts WHERE id = $1 FOR UPDATE
`

type LockContactRow struct {
	ID               pgtype.UUID
	Name             string
	Phone            string
	OrganizationID   pgtype.UUID
	CustomAttributes []byte
}

func (q *Queries) LockContact(ctx context.Context, id pgtype.UUID) (LockContactRow, error) {
	row := q.db.QueryRow(ctx, lockContact, id)
	var i LockContactRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.OrganizationID,
		&i.CustomAttributes,
	)
	return i, err
}

const lockConversationAttributes = `-- name: LockConversationAttributes :one
SELECT id, mailbox_id, custom_attributes FROM conversations
WHERE id = $1 AND mailbox_id = ANY ($2::uuid[]) AND deleted_at IS NULL
FOR UPDATE
`

type LockConversationAttributesParams struct {
	ID         pgtype.UUID
	MailboxIds []pgtype.UUID
}

type LockConversationAttributesRow struct {
	ID               pgtype.UUID
	MailboxID        pgtype.UUID
	CustomAttributes []byte
}

func (q *Queries) LockConversationAttributes(ctx context.Context, arg LockConversationAttributesParams) (LockConversationAttributesRow, error) {
	row := q.db.QueryRow(ctx, lockConversationAttributes, arg.ID, arg.MailboxIds)
	var i LockConversationAttributesRow
	err := row.Scan(&i.ID, &i.MailboxID, &i.CustomAttributes)
	return i, err
}

const lockOrganization = `-- name: LockOrganization :one
SELECT id, name, domains, custom_attributes FROM organizations WHERE id = $1 FOR UPDATE
`

type LockOrganizationRow struct {
	ID               pgtype.UUID
	Name             string
	Domains          []string
	CustomAttributes []byte
}

func (q *Queries) LockOrganization(ctx context.Context, id pgtype.UUID) (LockOrganizationRow, error) {
	row := q.db.QueryRow(ctx, lockOrganization, id)
	var i LockOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domains,
		&i.CustomAttributes,
	)
	return i, err
}

const markDataExportExpired = `-- name: MarkDataExportExpired :exec
UPDATE data_exports SET blob_key = '', status = CASE WHEN status = 'downloaded' THEN status ELSE 'expired' END WHERE id = $1
`

func (q *Queries) MarkDataExportExpired(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markDataExportExpired, id)
	return err
}

const markDataExportFailed = `-- name: MarkDataExportFailed :exec
UPDATE data_exports SET status = 'failed', error = $1 WHERE id = $2
`

type MarkDataExportFailedParams struct {
	Error string
	ID    pgtype.UUID
}

func (q *Queries) MarkDataExportFailed(ctx context.Context, arg MarkDataExportFailedParams) error {
	_, err := q.db.Exec(ctx, markDataExportFailed, arg.Error, arg.ID)
	return err
}

const markDataExportReady = `-- name: MarkDataExportReady :exec
UPDATE data_exports SET status = 'ready', blob_key = $1, size_bytes = $2 WHERE id = $3
`

type MarkDataExportReadyParams struct {
	BlobKey   string
	SizeBytes int64
	ID        pgtype.UUID
}

func (q *Queries) MarkDataExportReady(ctx context.Context, arg MarkDataExportReadyParams) error {
	_, err := q.db.Exec(ctx, markDataExportReady, arg.BlobKey, arg.SizeBytes, arg.ID)
	return err
}

const mergeContactFields = `-- name: MergeContactFields :exec
UPDATE contacts AS primary_contact
SET name = CASE WHEN primary_contact.name = '' THEN secondary.name ELSE primary_contact.name END,
    phone = CASE WHEN primary_contact.phone = '' THEN secondary.phone ELSE primary_contact.phone END,
    organization_id = COALESCE(primary_contact.organization_id, secondary.organization_id),
    custom_attributes = secondary.custom_attributes || primary_contact.custom_attributes,
    last_activity_at = GREATEST(primary_contact.last_activity_at, secondary.last_activity_at),
    unsubscribed_at = COALESCE(primary_contact.unsubscribed_at, secondary.unsubscribed_at),
    updated_at = now()
FROM contacts AS secondary
WHERE primary_contact.id = $1 AND secondary.id = $2
`

type MergeContactFieldsParams struct {
	PrimaryID   pgtype.UUID
	SecondaryID pgtype.UUID
}

func (q *Queries) MergeContactFields(ctx context.Context, arg MergeContactFieldsParams) error {
	_, err := q.db.Exec(ctx, mergeContactFields, arg.PrimaryID, arg.SecondaryID)
	return err
}

const moveContactAddresses = `-- name: MoveContactAddresses :execrows

UPDATE contact_addresses SET contact_id = $1, is_primary = false WHERE contact_id = $2
`

type MoveContactAddressesParams struct {
	PrimaryID   pgtype.UUID
	SecondaryID pgtype.UUID
}

// Merge
func (q *Queries) MoveContactAddresses(ctx context.Context, arg MoveContactAddressesParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveContactAddresses, arg.PrimaryID, arg.SecondaryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveContactConversations = `-- name: MoveContactConversations :many
UPDATE conversations SET contact_id = $1 WHERE contact_id = $2 RETURNING id, mailbox_id
`

type MoveContactConversationsParams struct {
	PrimaryID   pgtype.UUID
	SecondaryID pgtype.UUID
}

type MoveContactConversationsRow struct {
	ID        pgtype.UUID
	MailboxID pgtype.UUID
}

func (q *Queries) MoveContactConversations(ctx context.Context, arg MoveContactConversationsParams) ([]MoveContactConversationsRow, error) {
	rows, err := q.db.Query(ctx, moveContactConversations, arg.PrimaryID, arg.SecondaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MoveContactConversationsRow{}
	for rows.Next() {
		var i MoveContactConversationsRow
		if err := rows.Scan(&i.ID, &i.MailboxID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveContactNotes = `-- name: MoveContactNotes :execrows
UPDATE crm_notes SET contact_id = $1 WHERE contact_id = $2
`

type MoveContactNotesParams struct {
	PrimaryID   pgtype.UUID
	SecondaryID pgtype.UUID
}

func (q *Queries) MoveContactNotes(ctx context.Context, arg MoveContactNotesParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveContactNotes, arg.PrimaryID, arg.SecondaryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const organizationIsVisible = `-- name: OrganizationIsVisible :one
SELECT organization_visible($1, $2::uuid, $3::boolean, $4::uuid[])::boolean
`

type OrganizationIsVisibleParams struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Admin      bool
	MailboxIds []pgtype.UUID
}

func (q *Queries) OrganizationIsVisible(ctx context.Context, arg OrganizationIsVisibleParams) (bool, error) {
	row := q.db.QueryRow(ctx, organizationIsVisible,
		arg.ID,
		arg.UserID,
		arg.Admin,
		arg.MailboxIds,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const organizationsOwningDomains = `-- name: OrganizationsOwningDomains :many
SELECT id, domains FROM organizations
WHERE domains && $1::text[] AND id <> COALESCE($2::uuid, '00000000-0000-0000-0000-000000000000'::uuid)
`

type OrganizationsOwningDomainsParams struct {
	Domains  []string
	ExceptID pgtype.UUID
}

type OrganizationsOwningDomainsRow struct {
	ID      pgtype.UUID
	Domains []string
}

func (q *Queries) OrganizationsOwningDomains(ctx context.Context, arg OrganizationsOwningDomainsParams) ([]OrganizationsOwningDomainsRow, error) {
	rows, err := q.db.Query(ctx, organizationsOwningDomains, arg.Domains, arg.ExceptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationsOwningDomainsRow{}
	for rows.Next() {
		var i OrganizationsOwningDomainsRow
		if err := rows.Scan(&i.ID, &i.Domains); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueBlobDeletions = `-- name: QueueBlobDeletions :exec
INSERT INTO pending_blob_deletions (blob_key)
SELECT DISTINCT key FROM unnest($1::text[]) AS key WHERE key <> ''
ON CONFLICT DO NOTHING
`

func (q *Queries) QueueBlobDeletions(ctx context.Context, keys []string) error {
	_, err := q.db.Exec(ctx, queueBlobDeletions, keys)
	return err
}

const rawBlobKeys = `-- name: RawBlobKeys :many
SELECT blob_key FROM raw_messages WHERE id = ANY ($1::uuid[]) AND blob_key <> ''
`

func (q *Queries) RawBlobKeys(ctx context.Context, ids []pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, rawBlobKeys, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blob_key string
		if err := rows.Scan(&blob_key); err != nil {
			return nil, err
		}
		items = append(items, blob_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPrimaryContactAddress = `-- name: SetPrimaryContactAddress :exec
UPDATE contact_addresses SET is_primary = (email = $1::text) WHERE contact_id = $2
`

type SetPrimaryContactAddressParams struct {
	Email     string
	ContactID pgtype.UUID
}

func (q *Queries) SetPrimaryContactAddress(ctx context.Context, arg SetPrimaryContactAddressParams) error {
	_, err := q.db.Exec(ctx, setPrimaryContactAddress, arg.Email, arg.ContactID)
	return err
}

const startContactImport = `-- name: StartContactImport :exec
UPDATE contact_imports SET status = 'running' WHERE id = $1
`

func (q *Queries) StartContactImport(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, startContactImport, id)
	return err
}

const stripContactAttribute = `-- name: StripContactAttribute :execrows
UPDATE contacts SET custom_attributes = custom_attributes - $1::text WHERE custom_attributes ? $1::text
`

func (q *Queries) StripContactAttribute(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, stripContactAttribute, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stripConversationAttribute = `-- name: StripConversationAttribute :execrows
UPDATE conversations SET custom_attributes = custom_attributes - $1::text WHERE custom_attributes ? $1::text
`

func (q *Queries) StripConversationAttribute(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, stripConversationAttribute, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stripOrganizationAttribute = `-- name: StripOrganizationAttribute :execrows
UPDATE organizations SET custom_attributes = custom_attributes - $1::text WHERE custom_attributes ? $1::text
`

func (q *Queries) StripOrganizationAttribute(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, stripOrganizationAttribute, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tombstoneMessagesOfAddresses = `-- name: TombstoneMessagesOfAddresses :many
UPDATE messages SET
    from_name = CASE WHEN lower(from_addr) = ANY ($1::text[]) THEN $2::text ELSE from_name END,
    from_addr = CASE WHEN lower(from_addr) = ANY ($1::text[]) THEN $3::text ELSE from_addr END,
    to_addrs = (SELECT COALESCE(jsonb_agg(CASE WHEN lower(a ->> 'address') = ANY ($1::text[])
                    THEN jsonb_build_object('name', $2::text, 'address', $3::text) ELSE a END), '[]'::jsonb)
                FROM jsonb_array_elements(messages.to_addrs) AS a),
    cc_addrs = (SELECT COALESCE(jsonb_agg(CASE WHEN lower(a ->> 'address') = ANY ($1::text[])
                    THEN jsonb_build_object('name', $2::text, 'address', $3::text) ELSE a END), '[]'::jsonb)
                FROM jsonb_array_elements(messages.cc_addrs) AS a),
    bcc_addrs = (SELECT COALESCE(jsonb_agg(CASE WHEN lower(a ->> 'address') = ANY ($1::text[])
                    THEN jsonb_build_object('name', $2::text, 'address', $3::text) ELSE a END), '[]'::jsonb)
                FROM jsonb_array_elements(messages.bcc_addrs) AS a),
    reply_to = (SELECT COALESCE(jsonb_agg(CASE WHEN lower(a ->> 'address') = ANY ($1::text[])
                    THEN jsonb_build_object('name', $2::text, 'address', $3::text) ELSE a END), '[]'::jsonb)
                FROM jsonb_array_elements(messages.reply_to) AS a)
WHERE (messages.conversation_id = ANY ($4::uuid[]) OR lower(messages.from_addr) = ANY ($1::text[]))
  AND messages.kind = 'email'
  AND (lower(messages.from_addr) = ANY ($1::text[])
       OR EXISTS (SELECT 1 FROM jsonb_array_elements(messages.to_addrs || messages.cc_addrs || messages.bcc_addrs || messages.reply_to) AS a
                  WHERE lower(a ->> 'address') = ANY ($1::text[])))
RETURNING messages.id, messages.raw_message_id
`

type TombstoneMessagesOfAddressesParams struct {
	Addrs           []string
	TombstoneName   string
	TombstoneAddr   string
	ConversationIds []pgtype.UUID
}

type TombstoneMessagesOfAddressesRow struct {
	ID           pgtype.UUID
	RawMessageID pgtype.UUID
}

// Replaces the contact's address and name on messages they sent or received, in the
// conversations passed and anywhere they appear as sender. Returns the raw messages and ids
// so the raw copies (which still hold the address) can be dropped.
func (q *Queries) TombstoneMessagesOfAddresses(ctx context.Context, arg TombstoneMessagesOfAddressesParams) ([]TombstoneMessagesOfAddressesRow, error) {
	rows, err := q.db.Query(ctx, tombstoneMessagesOfAddresses,
		arg.Addrs,
		arg.TombstoneName,
		arg.TombstoneAddr,
		arg.ConversationIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TombstoneMessagesOfAddressesRow{}
	for rows.Next() {
		var i TombstoneMessagesOfAddressesRow
		if err := rows.Scan(&i.ID, &i.RawMessageID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttributeDef = `-- name: UpdateAttributeDef :one
UPDATE custom_attribute_defs SET label = $1, options = $2::text[] WHERE id = $3
RETURNING id, entity, key, label, type, options, created_at
`

type UpdateAttributeDefParams struct {
	Label   string
	Options []string
	ID      pgtype.UUID
}

func (q *Queries) UpdateAttributeDef(ctx context.Context, arg UpdateAttributeDefParams) (CustomAttributeDef, error) {
	row := q.db.QueryRow(ctx, updateAttributeDef, arg.Label, arg.Options, arg.ID)
	var i CustomAttributeDef
	err := row.Scan(
		&i.ID,
		&i.Entity,
		&i.Key,
		&i.Label,
		&i.Type,
		&i.Options,
		&i.CreatedAt,
	)
	return i, err
}

const updateCRMNote = `-- name: UpdateCRMNote :exec
UPDATE crm_notes SET body = $1, updated_at = now() WHERE id = $2
`

type UpdateCRMNoteParams struct {
	Body string
	ID   pgtype.UUID
}

func (q *Queries) UpdateCRMNote(ctx context.Context, arg UpdateCRMNoteParams) error {
	_, err := q.db.Exec(ctx, updateCRMNote, arg.Body, arg.ID)
	return err
}

const updateContact = `-- name: UpdateContact :exec
UPDATE contacts
SET name = $1, phone = $2, organization_id = $3,
    custom_attributes = $4, updated_at = now()
WHERE id = $5
`

type UpdateContactParams struct {
	Name             string
	Phone            string
	OrganizationID   pgtype.UUID
	CustomAttributes []byte
	ID               pgtype.UUID
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) error {
	_, err := q.db.Exec(ctx, updateContact,
		arg.Name,
		arg.Phone,
		arg.OrganizationID,
		arg.CustomAttributes,
		arg.ID,
	)
	return err
}

const updateContactImportProgress = `-- name: UpdateContactImportProgress :exec
UPDATE contact_imports
SET processed_rows = $1, created_count = $2, updated_count = $3,
    skipped_count = $4, failed_count = $5
WHERE id = $6
`

type UpdateContactImportProgressParams struct {
	ProcessedRows int32
	CreatedCount  int32
	UpdatedCount  int32
	SkippedCount  int32
	FailedCount   int32
	ID            pgtype.UUID
}

func (q *Queries) UpdateContactImportProgress(ctx context.Context, arg UpdateContactImportProgressParams) error {
	_, err := q.db.Exec(ctx, updateContactImportProgress,
		arg.ProcessedRows,
		arg.CreatedCount,
		arg.UpdatedCount,
		arg.SkippedCount,
		arg.FailedCount,
		arg.ID,
	)
	return err
}

const updateConversationAttributes = `-- name: UpdateConversationAttributes :exec
UPDATE conversations SET custom_attributes = $1, updated_at = now() WHERE id = $2
`

type UpdateConversationAttributesParams struct {
	CustomAttributes []byte
	ID               pgtype.UUID
}

func (q *Queries) UpdateConversationAttributes(ctx context.Context, arg UpdateConversationAttributesParams) error {
	_, err := q.db.Exec(ctx, updateConversationAttributes, arg.CustomAttributes, arg.ID)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :exec
UPDATE organizations
SET name = $1, domains = $2::text[], custom_attributes = $3, updated_at = now()
WHERE id = $4
`

type UpdateOrganizationParams struct {
	Name             string
	Domains          []string
	CustomAttributes []byte
	ID               pgtype.UUID
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error {
	_, err := q.db.Exec(ctx, updateOrganization,
		arg.Name,
		arg.Domains,
		arg.CustomAttributes,
		arg.ID,
	)
	return err
}

const updateSegment = `-- name: UpdateSegment :exec
UPDATE contact_segments SET name = $1, shared = $2, filter = $3, updated_at = now() WHERE id = $4
`

type UpdateSegmentParams struct {
	Name   string
	Shared bool
	Filter []byte
	ID     pgtype.UUID
}

func (q *Queries) UpdateSegment(ctx context.Context, arg UpdateSegmentParams) error {
	_, err := q.db.Exec(ctx, updateSegment,
		arg.Name,
		arg.Shared,
		arg.Filter,
		arg.ID,
	)
	return err
}
