// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation_actions.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationLabels = `-- name: AddConversationLabels :exec
INSERT INTO conversation_labels (conversation_id, label_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type AddConversationLabelsParams struct {
	ConversationID pgtype.UUID
	LabelIds       []pgtype.UUID
}

func (q *Queries) AddConversationLabels(ctx context.Context, arg AddConversationLabelsParams) error {
	_, err := q.db.Exec(ctx, addConversationLabels, arg.ConversationID, arg.LabelIds)
	return err
}

const canAssignMailbox = `-- name: CanAssignMailbox :one
SELECT EXISTS (
    SELECT 1 FROM users
    WHERE users.id = $1 AND users.deactivated_at IS NULL AND users.role <> 'readonly' AND (users.role <> 'custom' OR 'conversations.write' = ANY(users.permissions))
        AND (users.role IN ('owner', 'admin') OR EXISTS (
            SELECT 1 FROM team_members
            JOIN mailbox_access ON mailbox_access.team_id = team_members.team_id
            WHERE team_members.user_id = users.id AND mailbox_access.mailbox_id = $2
                AND mailbox_access.level = 'write'))
)::boolean AS allowed
`

type CanAssignMailboxParams struct {
	UserID    pgtype.UUID
	MailboxID pgtype.UUID
}

// Same rule as policy.MailboxScope for write access, for one user and one mailbox.
func (q *Queries) CanAssignMailbox(ctx context.Context, arg CanAssignMailboxParams) (bool, error) {
	row := q.db.QueryRow(ctx, canAssignMailbox, arg.UserID, arg.MailboxID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const conversationInScope = `-- name: ConversationInScope :one
SELECT EXISTS (
    SELECT 1 FROM conversations
    WHERE id = $1 AND mailbox_id = ANY($2::uuid[]) AND deleted_at IS NULL
)::boolean AS readable
`

type ConversationInScopeParams struct {
	ID         pgtype.UUID
	MailboxIds []pgtype.UUID
}

func (q *Queries) ConversationInScope(ctx context.Context, arg ConversationInScopeParams) (bool, error) {
	row := q.db.QueryRow(ctx, conversationInScope, arg.ID, arg.MailboxIds)
	var readable bool
	err := row.Scan(&readable)
	return readable, err
}

const deleteLabel = `-- name: DeleteLabel :one
DELETE FROM labels WHERE id = $1 RETURNING name
`

func (q *Queries) DeleteLabel(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, deleteLabel, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getTeamName = `-- name: GetTeamName :one
SELECT name FROM teams WHERE id = $1
`

func (q *Queries) GetTeamName(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTeamName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const insertConversationEvent = `-- name: InsertConversationEvent :exec
INSERT INTO conversation_events (conversation_id, mailbox_id, actor_user_id, type, data)
VALUES ($1, $2, $3, $4, $5)
`

type InsertConversationEventParams struct {
	ConversationID pgtype.UUID
	MailboxID      pgtype.UUID
	ActorUserID    pgtype.UUID
	Type           string
	Data           []byte
}

func (q *Queries) InsertConversationEvent(ctx context.Context, arg InsertConversationEventParams) error {
	_, err := q.db.Exec(ctx, insertConversationEvent,
		arg.ConversationID,
		arg.MailboxID,
		arg.ActorUserID,
		arg.Type,
		arg.Data,
	)
	return err
}

const insertLabel = `-- name: InsertLabel :one
INSERT INTO labels (name, color_token, description) VALUES ($1, $2, $3)
RETURNING id, name, color_token, description, created_at
`

type InsertLabelParams struct {
	Name        string
	ColorToken  string
	Description string
}

func (q *Queries) InsertLabel(ctx context.Context, arg InsertLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, insertLabel, arg.Name, arg.ColorToken, arg.Description)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ColorToken,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listConversationEvents = `-- name: ListConversationEvents :many
SELECT
    conversation_events.id, conversation_events.type, conversation_events.data, conversation_events.created_at,
    actor.id AS actor_id, actor.name AS actor_name,
    target.id AS user_id, target.name AS user_name
FROM conversation_events
LEFT JOIN users AS actor ON actor.id = conversation_events.actor_user_id
LEFT JOIN users AS target ON target.id = NULLIF(conversation_events.data ->> 'user_id', '')::uuid
WHERE conversation_events.conversation_id = $1
ORDER BY conversation_events.created_at, conversation_events.id
`

type ListConversationEventsRow struct {
	ID        pgtype.UUID
	Type      string
	Data      []byte
	CreatedAt pgtype.Timestamptz
	ActorID   pgtype.UUID
	ActorName pgtype.Text
	UserID    pgtype.UUID
	UserName  pgtype.Text
}

func (q *Queries) ListConversationEvents(ctx context.Context, conversationID pgtype.UUID) ([]ListConversationEventsRow, error) {
	rows, err := q.db.Query(ctx, listConversationEvents, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationEventsRow{}
	for rows.Next() {
		var i ListConversationEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Data,
			&i.CreatedAt,
			&i.ActorID,
			&i.ActorName,
			&i.UserID,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationLabelIDs = `-- name: ListConversationLabelIDs :many
SELECT label_id FROM conversation_labels WHERE conversation_id = $1
`

func (q *Queries) ListConversationLabelIDs(ctx context.Context, conversationID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listConversationLabelIDs, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var label_id pgtype.UUID
		if err := rows.Scan(&label_id); err != nil {
			return nil, err
		}
		items = append(items, label_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabels = `-- name: ListLabels :many
SELECT id, name, color_token, description, created_at FROM labels ORDER BY lower(name), id
`

func (q *Queries) ListLabels(ctx context.Context) ([]Label, error) {
	rows, err := q.db.Query(ctx, listLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Label{}
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ColorToken,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelsByID = `-- name: ListLabelsByID :many
SELECT id, name FROM labels WHERE id = ANY($1::uuid[])
`

type ListLabelsByIDRow struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) ListLabelsByID(ctx context.Context, ids []pgtype.UUID) ([]ListLabelsByIDRow, error) {
	rows, err := q.db.Query(ctx, listLabelsByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabelsByIDRow{}
	for rows.Next() {
		var i ListLabelsByIDRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelsForConversations = `-- name: ListLabelsForConversations :many
SELECT conversation_labels.conversation_id, labels.id, labels.name, labels.color_token
FROM conversation_labels
JOIN labels ON labels.id = conversation_labels.label_id
WHERE conversation_labels.conversation_id = ANY($1::uuid[])
ORDER BY lower(labels.name), labels.id
`

type ListLabelsForConversationsRow struct {
	ConversationID pgtype.UUID
	ID             pgtype.UUID
	Name           string
	ColorToken     string
}

func (q *Queries) ListLabelsForConversations(ctx context.Context, conversationIds []pgtype.UUID) ([]ListLabelsForConversationsRow, error) {
	rows, err := q.db.Query(ctx, listLabelsForConversations, conversationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabelsForConversationsRow{}
	for rows.Next() {
		var i ListLabelsForConversationsRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.ID,
			&i.Name,
			&i.ColorToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailboxAssignees = `-- name: ListMailboxAssignees :many
SELECT users.id, users.name
FROM users
WHERE users.deactivated_at IS NULL AND users.role <> 'readonly' AND (users.role <> 'custom' OR 'conversations.write' = ANY(users.permissions))
    AND (users.role IN ('owner', 'admin') OR EXISTS (
        SELECT 1 FROM team_members
        JOIN mailbox_access ON mailbox_access.team_id = team_members.team_id
        WHERE team_members.user_id = users.id AND mailbox_access.mailbox_id = $1
            AND mailbox_access.level = 'write'))
ORDER BY lower(users.name), users.id
`

type ListMailboxAssigneesRow struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) ListMailboxAssignees(ctx context.Context, mailboxID pgtype.UUID) ([]ListMailboxAssigneesRow, error) {
	rows, err := q.db.Query(ctx, listMailboxAssignees, mailboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMailboxAssigneesRow{}
	for rows.Next() {
		var i ListMailboxAssigneesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailboxTeams = `-- name: ListMailboxTeams :many
SELECT teams.id, teams.name
FROM mailbox_access
JOIN teams ON teams.id = mailbox_access.team_id
WHERE mailbox_access.mailbox_id = $1
ORDER BY lower(teams.name), teams.id
`

type ListMailboxTeamsRow struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) ListMailboxTeams(ctx context.Context, mailboxID pgtype.UUID) ([]ListMailboxTeamsRow, error) {
	rows, err := q.db.Query(ctx, listMailboxTeams, mailboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMailboxTeamsRow{}
	for rows.Next() {
		var i ListMailboxTeamsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConversationForUpdate = `-- name: LockConversationForUpdate :one

SELECT id, mailbox_id, status, priority, assignee_user_id, assignee_team_id, snoozed_until, resolved_at, version
FROM conversations
WHERE id = $1 AND mailbox_id = ANY($2::uuid[]) AND deleted_at IS NULL
FOR UPDATE
`

type LockConversationForUpdateParams struct {
	ID         pgtype.UUID
	MailboxIds []pgtype.UUID
}

type LockConversationForUpdateRow struct {
	ID             pgtype.UUID
	MailboxID      pgtype.UUID
	Status         string
	Priority       string
	AssigneeUserID pgtype.UUID
	AssigneeTeamID pgtype.UUID
	SnoozedUntil   pgtype.Timestamptz
	ResolvedAt     pgtype.Timestamptz
	Version        int32
}

// Mutations lock the row inside the caller's readable mailboxes, so an out-of-scope id is
// indistinguishable from a missing one. Whether the mailbox is writable is decided by the caller.
func (q *Queries) LockConversationForUpdate(ctx context.Context, arg LockConversationForUpdateParams) (LockConversationForUpdateRow, error) {
	row := q.db.QueryRow(ctx, lockConversationForUpdate, arg.ID, arg.MailboxIds)
	var i LockConversationForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.MailboxID,
		&i.Status,
		&i.Priority,
		&i.AssigneeUserID,
		&i.AssigneeTeamID,
		&i.SnoozedUntil,
		&i.ResolvedAt,
		&i.Version,
	)
	return i, err
}

const notifyEvent = `-- name: NotifyEvent :exec
SELECT pg_notify($1::text, $2::text)
`

type NotifyEventParams struct {
	Channel string
	Payload string
}

func (q *Queries) NotifyEvent(ctx context.Context, arg NotifyEventParams) error {
	_, err := q.db.Exec(ctx, notifyEvent, arg.Channel, arg.Payload)
	return err
}

const removeConversationLabels = `-- name: RemoveConversationLabels :exec
DELETE FROM conversation_labels
WHERE conversation_id = $1 AND label_id = ANY($2::uuid[])
`

type RemoveConversationLabelsParams struct {
	ConversationID pgtype.UUID
	LabelIds       []pgtype.UUID
}

func (q *Queries) RemoveConversationLabels(ctx context.Context, arg RemoveConversationLabelsParams) error {
	_, err := q.db.Exec(ctx, removeConversationLabels, arg.ConversationID, arg.LabelIds)
	return err
}

const teamHasMailboxAccess = `-- name: TeamHasMailboxAccess :one
SELECT EXISTS (
    SELECT 1 FROM mailbox_access WHERE team_id = $1 AND mailbox_id = $2
)::boolean AS allowed
`

type TeamHasMailboxAccessParams struct {
	TeamID    pgtype.UUID
	MailboxID pgtype.UUID
}

func (q *Queries) TeamHasMailboxAccess(ctx context.Context, arg TeamHasMailboxAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, teamHasMailboxAccess, arg.TeamID, arg.MailboxID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const updateConversationState = `-- name: UpdateConversationState :one
UPDATE conversations SET
    status = $1, priority = $2,
    assignee_user_id = $3, assignee_team_id = $4,
    snoozed_until = $5, resolved_at = $6,
    version = version + 1, updated_at = now()
WHERE id = $7
RETURNING version
`

type UpdateConversationStateParams struct {
	Status         string
	Priority       string
	AssigneeUserID pgtype.UUID
	AssigneeTeamID pgtype.UUID
	SnoozedUntil   pgtype.Timestamptz
	ResolvedAt     pgtype.Timestamptz
	ID             pgtype.UUID
}

func (q *Queries) UpdateConversationState(ctx context.Context, arg UpdateConversationStateParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateConversationState,
		arg.Status,
		arg.Priority,
		arg.AssigneeUserID,
		arg.AssigneeTeamID,
		arg.SnoozedUntil,
		arg.ResolvedAt,
		arg.ID,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const updateLabel = `-- name: UpdateLabel :one
UPDATE labels SET
    name = COALESCE($1, name),
    color_token = COALESCE($2, color_token),
    description = COALESCE($3, description)
WHERE id = $4
RETURNING id, name, color_token, description, created_at
`

type UpdateLabelParams struct {
	Name        pgtype.Text
	ColorToken  pgtype.Text
	Description pgtype.Text
	ID          pgtype.UUID
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, updateLabel,
		arg.Name,
		arg.ColorToken,
		arg.Description,
		arg.ID,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ColorToken,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const wakeSnoozedConversations = `-- name: WakeSnoozedConversations :many
WITH due AS (
    SELECT id FROM conversations
    WHERE snoozed_until <= now() AND deleted_at IS NULL
    ORDER BY snoozed_until
    LIMIT $1::integer
    FOR UPDATE SKIP LOCKED
), woken AS (
    UPDATE conversations SET snoozed_until = NULL, version = version + 1, updated_at = now()
    FROM due WHERE conversations.id = due.id
    RETURNING conversations.id, conversations.mailbox_id, conversations.version
), logged AS (
    INSERT INTO conversation_events (conversation_id, mailbox_id, type)
    SELECT id, mailbox_id, 'woke' FROM woken
)
SELECT id, mailbox_id, version FROM woken
`

type WakeSnoozedConversationsRow struct {
	ID        pgtype.UUID
	MailboxID pgtype.UUID
	Version   int32
}

// SKIP LOCKED lets overlapping runs and concurrent agent edits go past each other.
func (q *Queries) WakeSnoozedConversations(ctx context.Context, batchSize int32) ([]WakeSnoozedConversationsRow, error) {
	rows, err := q.db.Query(ctx, wakeSnoozedConversations, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WakeSnoozedConversationsRow{}
	for rows.Next() {
		var i WakeSnoozedConversationsRow
		if err := rows.Scan(&i.ID, &i.MailboxID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
