// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConversationContact = `-- name: GetConversationContact :one
SELECT
    contacts.id, contacts.name, COALESCE(contact_address.email, '')::text AS email,
    organizations.id AS organization_id, organizations.name AS organization_name,
    (SELECT count(*) FROM conversations
        WHERE conversations.contact_id = contacts.id AND conversations.deleted_at IS NULL
            AND conversations.mailbox_id = ANY($1::uuid[]))::integer AS conversation_count
FROM contacts
LEFT JOIN organizations ON organizations.id = contacts.organization_id
LEFT JOIN LATERAL (
    SELECT contact_addresses.email FROM contact_addresses
    WHERE contact_addresses.contact_id = contacts.id
    ORDER BY contact_addresses.is_primary DESC, contact_addresses.email
    LIMIT 1
) AS contact_address ON true
WHERE contacts.id = $2
`

type GetConversationContactParams struct {
	MailboxIds []pgtype.UUID
	ID         pgtype.UUID
}

type GetConversationContactRow struct {
	ID                pgtype.UUID
	Name              string
	Email             string
	OrganizationID    pgtype.UUID
	OrganizationName  pgtype.Text
	ConversationCount int32
}

// The conversation count only covers mailboxes the caller can read.
func (q *Queries) GetConversationContact(ctx context.Context, arg GetConversationContactParams) (GetConversationContactRow, error) {
	row := q.db.QueryRow(ctx, getConversationContact, arg.MailboxIds, arg.ID)
	var i GetConversationContactRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.OrganizationID,
		&i.OrganizationName,
		&i.ConversationCount,
	)
	return i, err
}

const inboxMailboxCounts = `-- name: InboxMailboxCounts :many

SELECT mailboxes.id, mailboxes.name, mailboxes.email_address, count(conversations.id)::integer AS open_count
FROM mailboxes
LEFT JOIN conversations ON conversations.mailbox_id = mailboxes.id
    AND conversations.status = 'open' AND conversations.deleted_at IS NULL
    AND (conversations.snoozed_until IS NULL OR conversations.snoozed_until <= now())
WHERE mailboxes.id = ANY($1::uuid[]) AND mailboxes.disabled_at IS NULL
GROUP BY mailboxes.id
ORDER BY lower(mailboxes.name), mailboxes.id
`

type InboxMailboxCountsRow struct {
	ID           pgtype.UUID
	Name         string
	EmailAddress string
	OpenCount    int32
}

// Every query here takes the caller's readable mailbox ids as a parameter, so out-of-scope
// rows are never selected. Deleted conversations and messages are always excluded.
func (q *Queries) InboxMailboxCounts(ctx context.Context, mailboxIds []pgtype.UUID) ([]InboxMailboxCountsRow, error) {
	rows, err := q.db.Query(ctx, inboxMailboxCounts, mailboxIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxMailboxCountsRow{}
	for rows.Next() {
		var i InboxMailboxCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EmailAddress,
			&i.OpenCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inboxOpenCounts = `-- name: InboxOpenCounts :one
SELECT
    count(*) FILTER (WHERE assignee_user_id = $1)::integer AS mine,
    count(*) FILTER (WHERE assignee_user_id IS NULL)::integer AS unassigned,
    count(*)::integer AS total
FROM conversations
WHERE mailbox_id = ANY($2::uuid[]) AND status = 'open' AND deleted_at IS NULL
    AND (snoozed_until IS NULL OR snoozed_until <= now())
`

type InboxOpenCountsParams struct {
	UserID     pgtype.UUID
	MailboxIds []pgtype.UUID
}

type InboxOpenCountsRow struct {
	Mine       int32
	Unassigned int32
	Total      int32
}

func (q *Queries) InboxOpenCounts(ctx context.Context, arg InboxOpenCountsParams) (InboxOpenCountsRow, error) {
	row := q.db.QueryRow(ctx, inboxOpenCounts, arg.UserID, arg.MailboxIds)
	var i InboxOpenCountsRow
	err := row.Scan(&i.Mine, &i.Unassigned, &i.Total)
	return i, err
}

const inboxTeamCounts = `-- name: InboxTeamCounts :many
SELECT teams.id, teams.name, count(conversations.id)::integer AS open_count
FROM teams
LEFT JOIN conversations ON conversations.assignee_team_id = teams.id
    AND conversations.mailbox_id = ANY($1::uuid[])
    AND conversations.status = 'open' AND conversations.deleted_at IS NULL
    AND (conversations.snoozed_until IS NULL OR conversations.snoozed_until <= now())
WHERE $2::boolean
    OR teams.id IN (SELECT team_members.team_id FROM team_members WHERE team_members.user_id = $3)
GROUP BY teams.id
ORDER BY lower(teams.name), teams.id
`

type InboxTeamCountsParams struct {
	MailboxIds []pgtype.UUID
	AllTeams   bool
	UserID     pgtype.UUID
}

type InboxTeamCountsRow struct {
	ID        pgtype.UUID
	Name      string
	OpenCount int32
}

func (q *Queries) InboxTeamCounts(ctx context.Context, arg InboxTeamCountsParams) ([]InboxTeamCountsRow, error) {
	rows, err := q.db.Query(ctx, inboxTeamCounts, arg.MailboxIds, arg.AllTeams, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxTeamCountsRow{}
	for rows.Next() {
		var i InboxTeamCountsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.OpenCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationMessages = `-- name: ListConversationMessages :many
SELECT
    messages.id, messages.kind, messages.direction, messages.from_name, messages.from_addr,
    messages.to_addrs, messages.cc_addrs, messages.subject, messages.body_text,
    messages.sent_at, messages.received_at,
    users.id AS author_id, users.name AS author_name,
    outbound.status AS outbound_status, outbound.error AS outbound_error
FROM messages
LEFT JOIN users ON users.id = messages.author_user_id
LEFT JOIN outbound ON outbound.message_id = messages.id
WHERE messages.conversation_id = $1 AND messages.deleted_at IS NULL
ORDER BY messages.received_at, messages.id
`

type ListConversationMessagesRow struct {
	ID             pgtype.UUID
	Kind           string
	Direction      pgtype.Text
	FromName       string
	FromAddr       string
	ToAddrs        []byte
	CcAddrs        []byte
	Subject        string
	BodyText       string
	SentAt         pgtype.Timestamptz
	ReceivedAt     pgtype.Timestamptz
	AuthorID       pgtype.UUID
	AuthorName     pgtype.Text
	OutboundStatus pgtype.Text
	OutboundError  pgtype.Text
}

// body_html is deliberately not selected: it is only ever served sanitized, in a sandboxed iframe.
func (q *Queries) ListConversationMessages(ctx context.Context, conversationID pgtype.UUID) ([]ListConversationMessagesRow, error) {
	rows, err := q.db.Query(ctx, listConversationMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationMessagesRow{}
	for rows.Next() {
		var i ListConversationMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Direction,
			&i.FromName,
			&i.FromAddr,
			&i.ToAddrs,
			&i.CcAddrs,
			&i.Subject,
			&i.BodyText,
			&i.SentAt,
			&i.ReceivedAt,
			&i.AuthorID,
			&i.AuthorName,
			&i.OutboundStatus,
			&i.OutboundError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationPageAssigned = `-- name: ListConversationPageAssigned :many
SELECT conversations.id, conversations.last_message_at
FROM conversations
WHERE conversations.assignee_user_id = $1
    AND conversations.status = ANY($2::text[])
    AND COALESCE(conversations.snoozed_until > now(), false) = $3::boolean
    AND ($4::uuid IS NULL OR EXISTS (
        SELECT 1 FROM conversation_labels
        WHERE conversation_labels.conversation_id = conversations.id AND conversation_labels.label_id = $4::uuid))
    AND conversations.deleted_at IS NULL
    AND conversations.mailbox_id = ANY($5::uuid[])
    AND (conversations.last_message_at, conversations.id) < (
        COALESCE($6::timestamptz, 'infinity'::timestamptz),
        COALESCE($7::uuid, 'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid))
    AND ($8::uuid IS NULL OR conversations.assignee_team_id = $8::uuid)
ORDER BY conversations.last_message_at DESC, conversations.id DESC
LIMIT $9::integer
`

type ListConversationPageAssignedParams struct {
	UserID     pgtype.UUID
	Statuses   []string
	Snoozed    bool
	LabelID    pgtype.UUID
	MailboxIds []pgtype.UUID
	CursorAt   pgtype.Timestamptz
	CursorID   pgtype.UUID
	TeamID     pgtype.UUID
	PageSize   int32
}

type ListConversationPageAssignedRow struct {
	ID            pgtype.UUID
	LastMessageAt pgtype.Timestamptz
}

func (q *Queries) ListConversationPageAssigned(ctx context.Context, arg ListConversationPageAssignedParams) ([]ListConversationPageAssignedRow, error) {
	rows, err := q.db.Query(ctx, listConversationPageAssigned,
		arg.UserID,
		arg.Statuses,
		arg.Snoozed,
		arg.LabelID,
		arg.MailboxIds,
		arg.CursorAt,
		arg.CursorID,
		arg.TeamID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationPageAssignedRow{}
	for rows.Next() {
		var i ListConversationPageAssignedRow
		if err := rows.Scan(&i.ID, &i.LastMessageAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationPageByMailbox = `-- name: ListConversationPageByMailbox :many

SELECT page.id, page.last_message_at
FROM unnest($1::uuid[]) AS mailbox(id)
CROSS JOIN LATERAL (
    SELECT conversations.id, conversations.last_message_at
    FROM conversations
    WHERE conversations.mailbox_id = mailbox.id
        AND conversations.status = ANY($2::text[])
        AND COALESCE(conversations.snoozed_until > now(), false) = $3::boolean
        AND ($4::uuid IS NULL OR EXISTS (
            SELECT 1 FROM conversation_labels
            WHERE conversation_labels.conversation_id = conversations.id AND conversation_labels.label_id = $4::uuid))
        AND conversations.deleted_at IS NULL
        AND (conversations.last_message_at, conversations.id) < (
            COALESCE($5::timestamptz, 'infinity'::timestamptz),
            COALESCE($6::uuid, 'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid))
        AND (NOT $7::boolean OR conversations.assignee_user_id IS NULL)
        AND ($8::uuid IS NULL OR conversations.assignee_team_id = $8::uuid)
    ORDER BY conversations.last_message_at DESC, conversations.id DESC
    LIMIT $9::integer
) AS page
ORDER BY page.last_message_at DESC, page.id DESC
LIMIT $9::integer
`

type ListConversationPageByMailboxParams struct {
	MailboxIds     []pgtype.UUID
	Statuses       []string
	Snoozed        bool
	LabelID        pgtype.UUID
	CursorAt       pgtype.Timestamptz
	CursorID       pgtype.UUID
	UnassignedOnly bool
	TeamID         pgtype.UUID
	PageSize       int32
}

type ListConversationPageByMailboxRow struct {
	ID            pgtype.UUID
	LastMessageAt pgtype.Timestamptz
}

// The page queries only pick ids in keyset order; ListConversationsByID hydrates them.
// The cursor defaults sort after every real row, so the first page needs no OR branch that
// would keep the planner from using the list indexes.
// One index scan per mailbox, each stopping after page_size rows, merged and cut again.
func (q *Queries) ListConversationPageByMailbox(ctx context.Context, arg ListConversationPageByMailboxParams) ([]ListConversationPageByMailboxRow, error) {
	rows, err := q.db.Query(ctx, listConversationPageByMailbox,
		arg.MailboxIds,
		arg.Statuses,
		arg.Snoozed,
		arg.LabelID,
		arg.CursorAt,
		arg.CursorID,
		arg.UnassignedOnly,
		arg.TeamID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationPageByMailboxRow{}
	for rows.Next() {
		var i ListConversationPageByMailboxRow
		if err := rows.Scan(&i.ID, &i.LastMessageAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsByID = `-- name: ListConversationsByID :many
SELECT
    conversations.id, conversations.number, conversations.subject, conversations.status, conversations.priority,
    conversations.preview, conversations.last_message_at, conversations.message_count, conversations.has_attachments,
    conversations.snoozed_until, conversations.version,
    conversations.created_at, conversations.first_responded_at, conversations.resolved_at,
    conversations.sla_policy_id, conversations.sla_state, conversations.first_response_due_at,
    conversations.first_response_met_at, conversations.resolution_due_at,
    (SELECT messages.direction FROM messages
        WHERE messages.conversation_id = conversations.id AND messages.kind = 'email' AND messages.deleted_at IS NULL
        ORDER BY messages.received_at DESC, messages.id DESC LIMIT 1) AS last_direction,
    mailboxes.id AS mailbox_id, mailboxes.name AS mailbox_name,
    contacts.id AS contact_id, contacts.name AS contact_name, COALESCE(contact_address.email, '')::text AS contact_email,
    users.id AS assignee_id, users.name AS assignee_name,
    teams.id AS team_id, teams.name AS team_name
FROM conversations
JOIN mailboxes ON mailboxes.id = conversations.mailbox_id
LEFT JOIN contacts ON contacts.id = conversations.contact_id
LEFT JOIN LATERAL (
    SELECT contact_addresses.email FROM contact_addresses
    WHERE contact_addresses.contact_id = contacts.id
    ORDER BY contact_addresses.is_primary DESC, contact_addresses.email
    LIMIT 1
) AS contact_address ON true
LEFT JOIN users ON users.id = conversations.assignee_user_id
LEFT JOIN teams ON teams.id = conversations.assignee_team_id
WHERE conversations.id = ANY($1::uuid[])
    AND conversations.mailbox_id = ANY($2::uuid[])
    AND conversations.deleted_at IS NULL
ORDER BY conversations.last_message_at DESC, conversations.id DESC
`

type ListConversationsByIDParams struct {
	Ids        []pgtype.UUID
	MailboxIds []pgtype.UUID
}

type ListConversationsByIDRow struct {
	ID                 pgtype.UUID
	Number             int64
	Subject            string
	Status             string
	Priority           string
	Preview            string
	LastMessageAt      pgtype.Timestamptz
	MessageCount       int32
	HasAttachments     bool
	SnoozedUntil       pgtype.Timestamptz
	Version            int32
	CreatedAt          pgtype.Timestamptz
	FirstRespondedAt   pgtype.Timestamptz
	ResolvedAt         pgtype.Timestamptz
	SlaPolicyID        pgtype.UUID
	SlaState           string
	FirstResponseDueAt pgtype.Timestamptz
	FirstResponseMetAt pgtype.Timestamptz
	ResolutionDueAt    pgtype.Timestamptz
	LastDirection      pgtype.Text
	MailboxID          pgtype.UUID
	MailboxName        string
	ContactID          pgtype.UUID
	ContactName        pgtype.Text
	ContactEmail       string
	AssigneeID         pgtype.UUID
	AssigneeName       pgtype.Text
	TeamID             pgtype.UUID
	TeamName           pgtype.Text
}

func (q *Queries) ListConversationsByID(ctx context.Context, arg ListConversationsByIDParams) ([]ListConversationsByIDRow, error) {
	rows, err := q.db.Query(ctx, listConversationsByID, arg.Ids, arg.MailboxIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationsByIDRow{}
	for rows.Next() {
		var i ListConversationsByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Subject,
			&i.Status,
			&i.Priority,
			&i.Preview,
			&i.LastMessageAt,
			&i.MessageCount,
			&i.HasAttachments,
			&i.SnoozedUntil,
			&i.Version,
			&i.CreatedAt,
			&i.FirstRespondedAt,
			&i.ResolvedAt,
			&i.SlaPolicyID,
			&i.SlaState,
			&i.FirstResponseDueAt,
			&i.FirstResponseMetAt,
			&i.ResolutionDueAt,
			&i.LastDirection,
			&i.MailboxID,
			&i.MailboxName,
			&i.ContactID,
			&i.ContactName,
			&i.ContactEmail,
			&i.AssigneeID,
			&i.AssigneeName,
			&i.TeamID,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageAttachments = `-- name: ListMessageAttachments :many
SELECT id, message_id, filename, size_bytes, sniffed_type, disposition, scan_status
FROM attachments
WHERE message_id = ANY($1::uuid[])
ORDER BY created_at, id
`

type ListMessageAttachmentsRow struct {
	ID          pgtype.UUID
	MessageID   pgtype.UUID
	Filename    string
	SizeBytes   int64
	SniffedType string
	Disposition string
	ScanStatus  string
}

func (q *Queries) ListMessageAttachments(ctx context.Context, messageIds []pgtype.UUID) ([]ListMessageAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listMessageAttachments, messageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessageAttachmentsRow{}
	for rows.Next() {
		var i ListMessageAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Filename,
			&i.SizeBytes,
			&i.SniffedType,
			&i.Disposition,
			&i.ScanStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
