// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: csat.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const csatAssignee = `-- name: CsatAssignee :one
SELECT assignee_user_id FROM conversations WHERE id = $1
`

func (q *Queries) CsatAssignee(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, csatAssignee, id)
	var assignee_user_id pgtype.UUID
	err := row.Scan(&assignee_user_id)
	return assignee_user_id, err
}

const csatClaimRequest = `-- name: CsatClaimRequest :one
INSERT INTO csat_requests (conversation_id, mailbox_id, token_hash, sent_at, expires_at, skipped_reason)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (conversation_id) DO NOTHING
RETURNING conversation_id
`

type CsatClaimRequestParams struct {
	ConversationID pgtype.UUID
	MailboxID      pgtype.UUID
	TokenHash      []byte
	SentAt         pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	SkippedReason  string
}

// Inserts the survey row; nothing comes back when the conversation already has one.
func (q *Queries) CsatClaimRequest(ctx context.Context, arg CsatClaimRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, csatClaimRequest,
		arg.ConversationID,
		arg.MailboxID,
		arg.TokenHash,
		arg.SentAt,
		arg.ExpiresAt,
		arg.SkippedReason,
	)
	var conversation_id pgtype.UUID
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const csatConversationRating = `-- name: CsatConversationRating :one
SELECT p.rating, p.comment, p.updated_at
FROM csat_responses p
JOIN conversations c ON c.id = p.conversation_id
WHERE p.conversation_id = $1 AND c.mailbox_id = ANY($2::uuid[]) AND c.deleted_at IS NULL
`

type CsatConversationRatingParams struct {
	ID         pgtype.UUID
	MailboxIds []pgtype.UUID
}

type CsatConversationRatingRow struct {
	Rating    int16
	Comment   string
	UpdatedAt pgtype.Timestamptz
}

// The rating shown in the conversation, scoped to the caller's mailboxes.
func (q *Queries) CsatConversationRating(ctx context.Context, arg CsatConversationRatingParams) (CsatConversationRatingRow, error) {
	row := q.db.QueryRow(ctx, csatConversationRating, arg.ID, arg.MailboxIds)
	var i CsatConversationRatingRow
	err := row.Scan(&i.Rating, &i.Comment, &i.UpdatedAt)
	return i, err
}

const csatDueConversations = `-- name: CsatDueConversations :many
SELECT c.id
FROM csat_settings s
JOIN conversations c ON c.mailbox_id = s.mailbox_id
WHERE s.enabled AND c.status = 'closed' AND c.deleted_at IS NULL
    AND c.resolved_at >= s.enabled_at
    AND c.resolved_at <= now() - make_interval(hours => s.delay_hours)
    AND c.resolved_at > now() - make_interval(hours => s.delay_hours) - interval '3 days'
    AND NOT EXISTS (SELECT 1 FROM csat_requests r WHERE r.conversation_id = c.id)
ORDER BY c.resolved_at
LIMIT $1::integer
`

// Closed conversations whose delay has passed and that have no survey row yet. Only recent
// resolutions qualify, so a long outage of the sweep does not send stale surveys.
func (q *Queries) CsatDueConversations(ctx context.Context, batchSize int32) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, csatDueConversations, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const csatGetRequest = `-- name: CsatGetRequest :one
SELECT r.conversation_id, r.mailbox_id, r.token_hash, r.sent_at, r.expires_at,
       m.name AS mailbox_name, m.display_name AS mailbox_display_name
FROM csat_requests r
JOIN mailboxes m ON m.id = r.mailbox_id
WHERE r.conversation_id = $1 AND r.sent_at IS NOT NULL
`

type CsatGetRequestRow struct {
	ConversationID     pgtype.UUID
	MailboxID          pgtype.UUID
	TokenHash          []byte
	SentAt             pgtype.Timestamptz
	ExpiresAt          pgtype.Timestamptz
	MailboxName        string
	MailboxDisplayName string
}

func (q *Queries) CsatGetRequest(ctx context.Context, conversationID pgtype.UUID) (CsatGetRequestRow, error) {
	row := q.db.QueryRow(ctx, csatGetRequest, conversationID)
	var i CsatGetRequestRow
	err := row.Scan(
		&i.ConversationID,
		&i.MailboxID,
		&i.TokenHash,
		&i.SentAt,
		&i.ExpiresAt,
		&i.MailboxName,
		&i.MailboxDisplayName,
	)
	return i, err
}

const csatGetResponse = `-- name: CsatGetResponse :one
SELECT rating, comment, created_at, updated_at FROM csat_responses WHERE conversation_id = $1
`

type CsatGetResponseRow struct {
	Rating    int16
	Comment   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CsatGetResponse(ctx context.Context, conversationID pgtype.UUID) (CsatGetResponseRow, error) {
	row := q.db.QueryRow(ctx, csatGetResponse, conversationID)
	var i CsatGetResponseRow
	err := row.Scan(
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const csatGetSettings = `-- name: CsatGetSettings :one
SELECT mailbox_id, enabled, delay_hours, enabled_at FROM csat_settings WHERE mailbox_id = $1
`

type CsatGetSettingsRow struct {
	MailboxID  pgtype.UUID
	Enabled    bool
	DelayHours int32
	EnabledAt  pgtype.Timestamptz
}

func (q *Queries) CsatGetSettings(ctx context.Context, mailboxID pgtype.UUID) (CsatGetSettingsRow, error) {
	row := q.db.QueryRow(ctx, csatGetSettings, mailboxID)
	var i CsatGetSettingsRow
	err := row.Scan(
		&i.MailboxID,
		&i.Enabled,
		&i.DelayHours,
		&i.EnabledAt,
	)
	return i, err
}

const csatLatestInbound = `-- name: CsatLatestInbound :one
SELECT id, from_addr, from_name, auto_submitted, is_bounce, is_bulk, message_id_header, references_hdr
FROM messages
WHERE conversation_id = $1 AND kind = 'email' AND direction = 'in' AND deleted_at IS NULL
    AND lower(from_addr) = ANY ($2::text[])
ORDER BY received_at DESC, id DESC
LIMIT 1
`

type CsatLatestInboundParams struct {
	ConversationID pgtype.UUID
	KnownCustomers []string
}

type CsatLatestInboundRow struct {
	ID              pgtype.UUID
	FromAddr        string
	FromName        string
	AutoSubmitted   bool
	IsBounce        bool
	IsBulk          bool
	MessageIDHeader string
	ReferencesHdr   []string
}

func (q *Queries) CsatLatestInbound(ctx context.Context, arg CsatLatestInboundParams) (CsatLatestInboundRow, error) {
	row := q.db.QueryRow(ctx, csatLatestInbound, arg.ConversationID, arg.KnownCustomers)
	var i CsatLatestInboundRow
	err := row.Scan(
		&i.ID,
		&i.FromAddr,
		&i.FromName,
		&i.AutoSubmitted,
		&i.IsBounce,
		&i.IsBulk,
		&i.MessageIDHeader,
		&i.ReferencesHdr,
	)
	return i, err
}

const csatLockConversation = `-- name: CsatLockConversation :one
SELECT c.id, c.mailbox_id, c.number, c.subject, c.status, c.resolved_at, c.assignee_user_id, c.contact_id,
       m.name AS mailbox_name, m.display_name AS mailbox_display_name
FROM conversations c
JOIN mailboxes m ON m.id = c.mailbox_id
WHERE c.id = $1 AND c.deleted_at IS NULL
FOR UPDATE OF c
`

type CsatLockConversationRow struct {
	ID                 pgtype.UUID
	MailboxID          pgtype.UUID
	Number             int64
	Subject            string
	Status             string
	ResolvedAt         pgtype.Timestamptz
	AssigneeUserID     pgtype.UUID
	ContactID          pgtype.UUID
	MailboxName        string
	MailboxDisplayName string
}

func (q *Queries) CsatLockConversation(ctx context.Context, id pgtype.UUID) (CsatLockConversationRow, error) {
	row := q.db.QueryRow(ctx, csatLockConversation, id)
	var i CsatLockConversationRow
	err := row.Scan(
		&i.ID,
		&i.MailboxID,
		&i.Number,
		&i.Subject,
		&i.Status,
		&i.ResolvedAt,
		&i.AssigneeUserID,
		&i.ContactID,
		&i.MailboxName,
		&i.MailboxDisplayName,
	)
	return i, err
}

const csatSetRequestMessage = `-- name: CsatSetRequestMessage :exec
UPDATE csat_requests SET message_id = $2 WHERE conversation_id = $1
`

type CsatSetRequestMessageParams struct {
	ConversationID pgtype.UUID
	MessageID      pgtype.UUID
}

func (q *Queries) CsatSetRequestMessage(ctx context.Context, arg CsatSetRequestMessageParams) error {
	_, err := q.db.Exec(ctx, csatSetRequestMessage, arg.ConversationID, arg.MessageID)
	return err
}

const csatUpsertResponse = `-- name: CsatUpsertResponse :one
INSERT INTO csat_responses (conversation_id, mailbox_id, rating, comment, token_hash)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (conversation_id) DO UPDATE
SET rating = EXCLUDED.rating, comment = EXCLUDED.comment, updated_at = now()
WHERE csat_responses.created_at > now() - interval '7 days'
RETURNING (xmax = 0)::boolean AS inserted, rating, created_at
`

type CsatUpsertResponseParams struct {
	ConversationID pgtype.UUID
	MailboxID      pgtype.UUID
	Rating         int16
	Comment        string
	TokenHash      []byte
}

type CsatUpsertResponseRow struct {
	Inserted  bool
	Rating    int16
	CreatedAt pgtype.Timestamptz
}

// A rating can be changed for seven days after the first answer; later attempts match no row.
func (q *Queries) CsatUpsertResponse(ctx context.Context, arg CsatUpsertResponseParams) (CsatUpsertResponseRow, error) {
	row := q.db.QueryRow(ctx, csatUpsertResponse,
		arg.ConversationID,
		arg.MailboxID,
		arg.Rating,
		arg.Comment,
		arg.TokenHash,
	)
	var i CsatUpsertResponseRow
	err := row.Scan(&i.Inserted, &i.Rating, &i.CreatedAt)
	return i, err
}

const csatUpsertSettings = `-- name: CsatUpsertSettings :one
INSERT INTO csat_settings (mailbox_id, enabled, delay_hours, enabled_at)
VALUES ($1, $2, $3, CASE WHEN $2::boolean THEN now() END)
ON CONFLICT (mailbox_id) DO UPDATE SET
    enabled = EXCLUDED.enabled, delay_hours = EXCLUDED.delay_hours, updated_at = now(),
    enabled_at = CASE WHEN EXCLUDED.enabled AND NOT csat_settings.enabled THEN now()
                      WHEN EXCLUDED.enabled THEN csat_settings.enabled_at END
RETURNING mailbox_id, enabled, delay_hours, enabled_at
`

type CsatUpsertSettingsParams struct {
	MailboxID  pgtype.UUID
	Enabled    bool
	DelayHours int32
}

type CsatUpsertSettingsRow struct {
	MailboxID  pgtype.UUID
	Enabled    bool
	DelayHours int32
	EnabledAt  pgtype.Timestamptz
}

// enabled_at restarts whenever the survey is switched on, so switching it off and on again
// never surveys conversations that were resolved in between.
func (q *Queries) CsatUpsertSettings(ctx context.Context, arg CsatUpsertSettingsParams) (CsatUpsertSettingsRow, error) {
	row := q.db.QueryRow(ctx, csatUpsertSettings, arg.MailboxID, arg.Enabled, arg.DelayHours)
	var i CsatUpsertSettingsRow
	err := row.Scan(
		&i.MailboxID,
		&i.Enabled,
		&i.DelayHours,
		&i.EnabledAt,
	)
	return i, err
}
