// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: helpcenter.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const kbCategoryUsage = `-- name: KbCategoryUsage :one
SELECT (SELECT count(*) FROM kb_categories WHERE parent_id = $1)::integer AS children,
       (SELECT count(*) FROM kb_articles WHERE category_id = $1)::integer AS articles
`

type KbCategoryUsageRow struct {
	Children int32
	Articles int32
}

func (q *Queries) KbCategoryUsage(ctx context.Context, id pgtype.UUID) (KbCategoryUsageRow, error) {
	row := q.db.QueryRow(ctx, kbCategoryUsage, id)
	var i KbCategoryUsageRow
	err := row.Scan(&i.Children, &i.Articles)
	return i, err
}

const kbClearArticleImages = `-- name: KbClearArticleImages :exec
DELETE FROM kb_article_images WHERE article_id = $1
`

func (q *Queries) KbClearArticleImages(ctx context.Context, articleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, kbClearArticleImages, articleID)
	return err
}

const kbCountView = `-- name: KbCountView :exec
UPDATE kb_articles SET view_count = view_count + 1 WHERE slug = $1 AND status = 'published'
`

func (q *Queries) KbCountView(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, kbCountView, slug)
	return err
}

const kbDeleteArticle = `-- name: KbDeleteArticle :execrows
DELETE FROM kb_articles WHERE id = $1
`

func (q *Queries) KbDeleteArticle(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, kbDeleteArticle, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const kbDeleteCategory = `-- name: KbDeleteCategory :execrows
DELETE FROM kb_categories WHERE id = $1
`

func (q *Queries) KbDeleteCategory(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, kbDeleteCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const kbDeleteRedirect = `-- name: KbDeleteRedirect :exec
DELETE FROM kb_slug_redirects WHERE slug = $1
`

func (q *Queries) KbDeleteRedirect(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, kbDeleteRedirect, slug)
	return err
}

const kbDeleteUnusedImages = `-- name: KbDeleteUnusedImages :exec
DELETE FROM kb_images
WHERE created_at < now() - interval '24 hours'
  AND NOT EXISTS (SELECT 1 FROM kb_article_images ai WHERE ai.image_id = kb_images.id)
`

func (q *Queries) KbDeleteUnusedImages(ctx context.Context) error {
	_, err := q.db.Exec(ctx, kbDeleteUnusedImages)
	return err
}

const kbExistingImages = `-- name: KbExistingImages :many
SELECT id FROM kb_images WHERE id = ANY ($1::uuid[])
`

func (q *Queries) KbExistingImages(ctx context.Context, ids []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, kbExistingImages, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const kbFindRedirect = `-- name: KbFindRedirect :one
SELECT a.slug FROM kb_slug_redirects r JOIN kb_articles a ON a.id = r.article_id
WHERE r.slug = $1 AND a.status = 'published'
`

func (q *Queries) KbFindRedirect(ctx context.Context, slug string) (string, error) {
	row := q.db.QueryRow(ctx, kbFindRedirect, slug)
	var slug_2 string
	err := row.Scan(&slug_2)
	return slug_2, err
}

const kbGetArticle = `-- name: KbGetArticle :one
SELECT id, category_id, title, slug, body_html, body_text, excerpt, status, author_id, updated_by, version, position, view_count, helpful_yes, helpful_no, created_at, updated_at, published_at, fts FROM kb_articles WHERE id = $1
`

func (q *Queries) KbGetArticle(ctx context.Context, id pgtype.UUID) (KbArticle, error) {
	row := q.db.QueryRow(ctx, kbGetArticle, id)
	var i KbArticle
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Slug,
		&i.BodyHtml,
		&i.BodyText,
		&i.Excerpt,
		&i.Status,
		&i.AuthorID,
		&i.UpdatedBy,
		&i.Version,
		&i.Position,
		&i.ViewCount,
		&i.HelpfulYes,
		&i.HelpfulNo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.Fts,
	)
	return i, err
}

const kbGetCategory = `-- name: KbGetCategory :one
SELECT id, parent_id, name, slug, description, position, created_at, updated_at FROM kb_categories WHERE id = $1
`

func (q *Queries) KbGetCategory(ctx context.Context, id pgtype.UUID) (KbCategory, error) {
	row := q.db.QueryRow(ctx, kbGetCategory, id)
	var i KbCategory
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const kbGetImage = `-- name: KbGetImage :one
SELECT id, uploader_id, filename, content_type, size_bytes, blob_key, created_at FROM kb_images WHERE id = $1
`

func (q *Queries) KbGetImage(ctx context.Context, id pgtype.UUID) (KbImage, error) {
	row := q.db.QueryRow(ctx, kbGetImage, id)
	var i KbImage
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.BlobKey,
		&i.CreatedAt,
	)
	return i, err
}

const kbGetPortal = `-- name: KbGetPortal :one

SELECT name, title, intro, logo_text, custom_domain, updated_at FROM kb_portal
`

type KbGetPortalRow struct {
	Name         string
	Title        string
	Intro        string
	LogoText     string
	CustomDomain string
	UpdatedAt    pgtype.Timestamptz
}

// Knowledge base: portal settings, categories, articles, revisions, images, and the public
// reads behind /hulp. Public reads only ever return published articles.
func (q *Queries) KbGetPortal(ctx context.Context) (KbGetPortalRow, error) {
	row := q.db.QueryRow(ctx, kbGetPortal)
	var i KbGetPortalRow
	err := row.Scan(
		&i.Name,
		&i.Title,
		&i.Intro,
		&i.LogoText,
		&i.CustomDomain,
		&i.UpdatedAt,
	)
	return i, err
}

const kbGetRevision = `-- name: KbGetRevision :one
SELECT id, article_id, title, excerpt, body_html, edited_by, created_at FROM kb_article_revisions WHERE id = $1 AND article_id = $2
`

type KbGetRevisionParams struct {
	ID        pgtype.UUID
	ArticleID pgtype.UUID
}

func (q *Queries) KbGetRevision(ctx context.Context, arg KbGetRevisionParams) (KbArticleRevision, error) {
	row := q.db.QueryRow(ctx, kbGetRevision, arg.ID, arg.ArticleID)
	var i KbArticleRevision
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.Title,
		&i.Excerpt,
		&i.BodyHtml,
		&i.EditedBy,
		&i.CreatedAt,
	)
	return i, err
}

const kbImageIsPublished = `-- name: KbImageIsPublished :one
SELECT EXISTS (
    SELECT 1 FROM kb_article_images ai JOIN kb_articles a ON a.id = ai.article_id
    WHERE ai.image_id = $1 AND a.status = 'published'
)::boolean
`

func (q *Queries) KbImageIsPublished(ctx context.Context, imageID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, kbImageIsPublished, imageID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const kbInsertArticle = `-- name: KbInsertArticle :one
INSERT INTO kb_articles (category_id, title, slug, body_html, body_text, excerpt, author_id, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
RETURNING id, category_id, title, slug, body_html, body_text, excerpt, status, author_id, updated_by, version, position, view_count, helpful_yes, helpful_no, created_at, updated_at, published_at, fts
`

type KbInsertArticleParams struct {
	CategoryID pgtype.UUID
	Title      string
	Slug       string
	BodyHtml   string
	BodyText   string
	Excerpt    string
	UserID     pgtype.UUID
}

func (q *Queries) KbInsertArticle(ctx context.Context, arg KbInsertArticleParams) (KbArticle, error) {
	row := q.db.QueryRow(ctx, kbInsertArticle,
		arg.CategoryID,
		arg.Title,
		arg.Slug,
		arg.BodyHtml,
		arg.BodyText,
		arg.Excerpt,
		arg.UserID,
	)
	var i KbArticle
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Slug,
		&i.BodyHtml,
		&i.BodyText,
		&i.Excerpt,
		&i.Status,
		&i.AuthorID,
		&i.UpdatedBy,
		&i.Version,
		&i.Position,
		&i.ViewCount,
		&i.HelpfulYes,
		&i.HelpfulNo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.Fts,
	)
	return i, err
}

const kbInsertCategory = `-- name: KbInsertCategory :one
INSERT INTO kb_categories (parent_id, name, slug, description, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, parent_id, name, slug, description, position, created_at, updated_at
`

type KbInsertCategoryParams struct {
	ParentID    pgtype.UUID
	Name        string
	Slug        string
	Description string
	Position    int32
}

func (q *Queries) KbInsertCategory(ctx context.Context, arg KbInsertCategoryParams) (KbCategory, error) {
	row := q.db.QueryRow(ctx, kbInsertCategory,
		arg.ParentID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Position,
	)
	var i KbCategory
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const kbInsertImage = `-- name: KbInsertImage :one
INSERT INTO kb_images (uploader_id, filename, content_type, size_bytes, blob_key)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, uploader_id, filename, content_type, size_bytes, blob_key, created_at
`

type KbInsertImageParams struct {
	UploaderID  pgtype.UUID
	Filename    string
	ContentType string
	SizeBytes   int64
	BlobKey     string
}

func (q *Queries) KbInsertImage(ctx context.Context, arg KbInsertImageParams) (KbImage, error) {
	row := q.db.QueryRow(ctx, kbInsertImage,
		arg.UploaderID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.BlobKey,
	)
	var i KbImage
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.BlobKey,
		&i.CreatedAt,
	)
	return i, err
}

const kbInsertRedirect = `-- name: KbInsertRedirect :exec
INSERT INTO kb_slug_redirects (slug, article_id) VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE SET article_id = EXCLUDED.article_id
`

type KbInsertRedirectParams struct {
	Slug      string
	ArticleID pgtype.UUID
}

func (q *Queries) KbInsertRedirect(ctx context.Context, arg KbInsertRedirectParams) error {
	_, err := q.db.Exec(ctx, kbInsertRedirect, arg.Slug, arg.ArticleID)
	return err
}

const kbInsertRevision = `-- name: KbInsertRevision :exec
INSERT INTO kb_article_revisions (article_id, title, excerpt, body_html, edited_by)
SELECT a.id, a.title, a.excerpt, a.body_html, $1 FROM kb_articles a WHERE a.id = $2
`

type KbInsertRevisionParams struct {
	UserID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) KbInsertRevision(ctx context.Context, arg KbInsertRevisionParams) error {
	_, err := q.db.Exec(ctx, kbInsertRevision, arg.UserID, arg.ID)
	return err
}

const kbListArticles = `-- name: KbListArticles :many
SELECT a.id, a.category_id, a.title, a.slug, COALESCE(NULLIF(a.excerpt, ''), left(a.body_text, 300))::text AS excerpt, a.status, a.author_id, a.updated_by, a.version,
       a.view_count, a.helpful_yes, a.helpful_no, a.created_at, a.updated_at, a.published_at,
       c.name AS category_name, c.slug AS category_slug, u.name AS updated_by_name
FROM kb_articles a
LEFT JOIN kb_categories c ON c.id = a.category_id
LEFT JOIN users u ON u.id = a.updated_by
WHERE (NOT $1::boolean OR a.status = 'published')
  AND ($2::text IS NULL OR a.status = $2::text)
  AND ($3::uuid IS NULL OR a.category_id = $3::uuid)
  AND ($4::text IS NULL
       OR a.title ILIKE $5::text
       OR a.fts @@ (websearch_to_tsquery('dutch', $4::text) || websearch_to_tsquery('echoo_simple', $4::text)))
ORDER BY a.updated_at DESC, a.id DESC
LIMIT $6::integer
`

type KbListArticlesParams struct {
	PublishedOnly bool
	Status        pgtype.Text
	CategoryID    pgtype.UUID
	Text          pgtype.Text
	TitlePattern  pgtype.Text
	PageSize      int32
}

type KbListArticlesRow struct {
	ID            pgtype.UUID
	CategoryID    pgtype.UUID
	Title         string
	Slug          string
	Excerpt       string
	Status        string
	AuthorID      pgtype.UUID
	UpdatedBy     pgtype.UUID
	Version       int32
	ViewCount     int64
	HelpfulYes    int32
	HelpfulNo     int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	PublishedAt   pgtype.Timestamptz
	CategoryName  pgtype.Text
	CategorySlug  pgtype.Text
	UpdatedByName pgtype.Text
}

// Agents see every status; published_only is set for readonly users. title_pattern is an
// ILIKE pattern the caller already escaped, so a title fragment finds drafts that full text
// (which only stems whole words) would miss.
func (q *Queries) KbListArticles(ctx context.Context, arg KbListArticlesParams) ([]KbListArticlesRow, error) {
	rows, err := q.db.Query(ctx, kbListArticles,
		arg.PublishedOnly,
		arg.Status,
		arg.CategoryID,
		arg.Text,
		arg.TitlePattern,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KbListArticlesRow{}
	for rows.Next() {
		var i KbListArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Status,
			&i.AuthorID,
			&i.UpdatedBy,
			&i.Version,
			&i.ViewCount,
			&i.HelpfulYes,
			&i.HelpfulNo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.CategoryName,
			&i.CategorySlug,
			&i.UpdatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const kbListCategories = `-- name: KbListCategories :many
SELECT c.id, c.parent_id, c.name, c.slug, c.description, c.position, c.updated_at,
       (SELECT count(*) FROM kb_articles a WHERE a.category_id = c.id)::integer AS article_count,
       (SELECT count(*) FROM kb_articles a WHERE a.category_id = c.id AND a.status = 'published')::integer AS published_count
FROM kb_categories c
ORDER BY c.position, c.name, c.id
`

type KbListCategoriesRow struct {
	ID             pgtype.UUID
	ParentID       pgtype.UUID
	Name           string
	Slug           string
	Description    string
	Position       int32
	UpdatedAt      pgtype.Timestamptz
	ArticleCount   int32
	PublishedCount int32
}

func (q *Queries) KbListCategories(ctx context.Context) ([]KbListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, kbListCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KbListCategoriesRow{}
	for rows.Next() {
		var i KbListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Position,
			&i.UpdatedAt,
			&i.ArticleCount,
			&i.PublishedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const kbListRevisions = `-- name: KbListRevisions :many
SELECT r.id, r.title, r.created_at, u.name AS edited_by_name
FROM kb_article_revisions r
LEFT JOIN users u ON u.id = r.edited_by
WHERE r.article_id = $1
ORDER BY r.created_at DESC, r.id DESC
`

type KbListRevisionsRow struct {
	ID           pgtype.UUID
	Title        string
	CreatedAt    pgtype.Timestamptz
	EditedByName pgtype.Text
}

func (q *Queries) KbListRevisions(ctx context.Context, articleID pgtype.UUID) ([]KbListRevisionsRow, error) {
	rows, err := q.db.Query(ctx, kbListRevisions, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KbListRevisionsRow{}
	for rows.Next() {
		var i KbListRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.EditedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const kbLockArticle = `-- name: KbLockArticle :one
SELECT id, category_id, title, slug, body_html, body_text, excerpt, status, author_id, updated_by, version, position, view_count, helpful_yes, helpful_no, created_at, updated_at, published_at, fts FROM kb_articles WHERE id = $1 FOR UPDATE
`

func (q *Queries) KbLockArticle(ctx context.Context, id pgtype.UUID) (KbArticle, error) {
	row := q.db.QueryRow(ctx, kbLockArticle, id)
	var i KbArticle
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Slug,
		&i.BodyHtml,
		&i.BodyText,
		&i.Excerpt,
		&i.Status,
		&i.AuthorID,
		&i.UpdatedBy,
		&i.Version,
		&i.Position,
		&i.ViewCount,
		&i.HelpfulYes,
		&i.HelpfulNo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.Fts,
	)
	return i, err
}

const kbLockCategory = `-- name: KbLockCategory :one
SELECT id, parent_id, name, slug, description, position, created_at, updated_at FROM kb_categories WHERE id = $1 FOR UPDATE
`

func (q *Queries) KbLockCategory(ctx context.Context, id pgtype.UUID) (KbCategory, error) {
	row := q.db.QueryRow(ctx, kbLockCategory, id)
	var i KbCategory
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const kbPopularArticles = `-- name: KbPopularArticles :many
SELECT a.title, a.slug, COALESCE(NULLIF(a.excerpt, ''), left(a.body_text, 300))::text AS excerpt, c.name AS category_name
FROM kb_articles a JOIN kb_categories c ON c.id = a.category_id
WHERE a.status = 'published'
ORDER BY a.view_count DESC, a.updated_at DESC, a.id
LIMIT $1::integer
`

type KbPopularArticlesRow struct {
	Title        string
	Slug         string
	Excerpt      string
	CategoryName string
}

func (q *Queries) KbPopularArticles(ctx context.Context, pageSize int32) ([]KbPopularArticlesRow, error) {
	rows, err := q.db.Query(ctx, kbPopularArticles, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KbPopularArticlesRow{}
	for rows.Next() {
		var i KbPopularArticlesRow
		if err := rows.Scan(
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const kbPublicArticleBySlug = `-- name: KbPublicArticleBySlug :one
SELECT a.id, a.title, a.slug, a.body_html, COALESCE(NULLIF(a.excerpt, ''), left(a.body_text, 300))::text AS excerpt, a.updated_at,
       c.id AS category_id, c.name AS category_name, c.slug AS category_slug, c.updated_at AS category_updated_at,
       p.name AS parent_name, p.slug AS parent_slug
FROM kb_articles a
JOIN kb_categories c ON c.id = a.category_id
LEFT JOIN kb_categories p ON p.id = c.parent_id
WHERE a.slug = $1 AND a.status = 'published'
`

type KbPublicArticleBySlugRow struct {
	ID                pgtype.UUID
	Title             string
	Slug              string
	BodyHtml          string
	Excerpt           string
	UpdatedAt         pgtype.Timestamptz
	CategoryID        pgtype.UUID
	CategoryName      string
	CategorySlug      string
	CategoryUpdatedAt pgtype.Timestamptz
	ParentName        pgtype.Text
	ParentSlug        pgtype.Text
}

func (q *Queries) KbPublicArticleBySlug(ctx context.Context, slug string) (KbPublicArticleBySlugRow, error) {
	row := q.db.QueryRow(ctx, kbPublicArticleBySlug, slug)
	var i KbPublicArticleBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.BodyHtml,
		&i.Excerpt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.CategoryName,
		&i.CategorySlug,
		&i.CategoryUpdatedAt,
		&i.ParentName,
		&i.ParentSlug,
	)
	return i, err
}

const kbPublicCategories = `-- name: KbPublicCategories :many
SELECT c.id, c.name, c.slug, c.description,
       (SELECT count(*) FROM kb_articles a
        WHERE a.status = 'published' AND (a.category_id = c.id OR a.category_id IN (SELECT ch.id FROM kb_categories ch WHERE ch.parent_id = c.id)))::integer AS article_count
FROM kb_categories c
WHERE c.parent_id IS NULL
ORDER BY c.position, c.name, c.id
`

type KbPublicCategoriesRow struct {
	ID           pgtype.UUID
	Name         string
	Slug         string
	Description  string
	ArticleCount int32
}

// Top-level categories that hold at least one published article, counting their children's.
func (q *Queries) KbPublicCategories(ctx context.Context) ([]KbPublicCategoriesRow, error) {
	rows, err := q.db.Query(ctx, kbPublicCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KbPublicCategoriesRow{}
	for rows.Next() {
		var i KbPublicCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ArticleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const kbPublicCategoryArticles = `-- name: KbPublicCategoryArticles :many
SELECT a.id, a.title, a.slug, COALESCE(NULLIF(a.excerpt, ''), left(a.body_text, 300))::text AS excerpt, a.updated_at
FROM kb_articles a
WHERE a.category_id = $1 AND a.status = 'published'
ORDER BY a.position, a.title, a.id
`

type KbPublicCategoryArticlesRow struct {
	ID        pgtype.UUID
	Title     string
	Slug      string
	Excerpt   string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) KbPublicCategoryArticles(ctx context.Context, categoryID pgtype.UUID) ([]KbPublicCategoryArticlesRow, error) {
	rows, err := q.db.Query(ctx, kbPublicCategoryArticles, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KbPublicCategoryArticlesRow{}
	for rows.Next() {
		var i KbPublicCategoryArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const kbPublicCategoryBySlug = `-- name: KbPublicCategoryBySlug :one
SELECT c.id, c.parent_id, c.name, c.slug, c.description, c.updated_at,
       p.name AS parent_name, p.slug AS parent_slug
FROM kb_categories c
LEFT JOIN kb_categories p ON p.id = c.parent_id
WHERE c.slug = $1
`

type KbPublicCategoryBySlugRow struct {
	ID          pgtype.UUID
	ParentID    pgtype.UUID
	Name        string
	Slug        string
	Description string
	UpdatedAt   pgtype.Timestamptz
	ParentName  pgtype.Text
	ParentSlug  pgtype.Text
}

func (q *Queries) KbPublicCategoryBySlug(ctx context.Context, slug string) (KbPublicCategoryBySlugRow, error) {
	row := q.db.QueryRow(ctx, kbPublicCategoryBySlug, slug)
	var i KbPublicCategoryBySlugRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.UpdatedAt,
		&i.ParentName,
		&i.ParentSlug,
	)
	return i, err
}

const kbPublicChildCategories = `-- name: KbPublicChildCategories :many
SELECT c.id, c.name, c.slug, c.description,
       (SELECT count(*) FROM kb_articles a WHERE a.category_id = c.id AND a.status = 'published')::integer AS article_count
FROM kb_categories c
WHERE c.parent_id = $1
ORDER BY c.position, c.name, c.id
`

type KbPublicChildCategoriesRow struct {
	ID           pgtype.UUID
	Name         string
	Slug         string
	Description  string
	ArticleCount int32
}

func (q *Queries) KbPublicChildCategories(ctx context.Context, parentID pgtype.UUID) ([]KbPublicChildCategoriesRow, error) {
	rows, err := q.db.Query(ctx, kbPublicChildCategories, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KbPublicChildCategoriesRow{}
	for rows.Next() {
		var i KbPublicChildCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ArticleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const kbPublicRelatedArticles = `-- name: KbPublicRelatedArticles :many
SELECT a.title, a.slug
FROM kb_articles a
WHERE a.category_id = $1 AND a.status = 'published' AND a.id <> $2
ORDER BY a.position, a.title, a.id
LIMIT 5
`

type KbPublicRelatedArticlesParams struct {
	CategoryID pgtype.UUID
	ID         pgtype.UUID
}

type KbPublicRelatedArticlesRow struct {
	Title string
	Slug  string
}

func (q *Queries) KbPublicRelatedArticles(ctx context.Context, arg KbPublicRelatedArticlesParams) ([]KbPublicRelatedArticlesRow, error) {
	rows, err := q.db.Query(ctx, kbPublicRelatedArticles, arg.CategoryID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KbPublicRelatedArticlesRow{}
	for rows.Next() {
		var i KbPublicRelatedArticlesRow
		if err := rows.Scan(&i.Title, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const kbRecordFeedback = `-- name: KbRecordFeedback :execrows
UPDATE kb_articles
SET helpful_yes = helpful_yes + ($1::boolean)::integer,
    helpful_no = helpful_no + (NOT $1::boolean)::integer
WHERE id = $2 AND status = 'published'
`

type KbRecordFeedbackParams struct {
	Helpful bool
	ID      pgtype.UUID
}

func (q *Queries) KbRecordFeedback(ctx context.Context, arg KbRecordFeedbackParams) (int64, error) {
	result, err := q.db.Exec(ctx, kbRecordFeedback, arg.Helpful, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const kbSearchPublished = `-- name: KbSearchPublished :many
SELECT a.title, a.slug, c.name AS category_name,
       ts_rank_cd(a.fts, q.query, 32)::float8 AS rank,
       ts_headline('dutch', CASE WHEN a.body_text = '' THEN a.title ELSE a.body_text END, q.query, $1::text) AS snippet
FROM kb_articles a
JOIN kb_categories c ON c.id = a.category_id
CROSS JOIN LATERAL (SELECT websearch_to_tsquery('dutch', $2::text) || websearch_to_tsquery('echoo_simple', $2::text) AS query) q
WHERE a.status = 'published' AND a.fts @@ q.query
ORDER BY rank DESC, a.title, a.id
LIMIT $3::integer
`

type KbSearchPublishedParams struct {
	HeadlineOptions string
	Text            string
	PageSize        int32
}

type KbSearchPublishedRow struct {
	Title        string
	Slug         string
	CategoryName string
	Rank         float64
	Snippet      []byte
}

// headline_options carries private-use marker characters as StartSel/StopSel; the caller
// escapes the snippet and only then turns the markers into <mark>.
func (q *Queries) KbSearchPublished(ctx context.Context, arg KbSearchPublishedParams) ([]KbSearchPublishedRow, error) {
	rows, err := q.db.Query(ctx, kbSearchPublished, arg.HeadlineOptions, arg.Text, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KbSearchPublishedRow{}
	for rows.Next() {
		var i KbSearchPublishedRow
		if err := rows.Scan(
			&i.Title,
			&i.Slug,
			&i.CategoryName,
			&i.Rank,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const kbSetArticleImages = `-- name: KbSetArticleImages :exec
INSERT INTO kb_article_images (article_id, image_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type KbSetArticleImagesParams struct {
	ArticleID pgtype.UUID
	ImageIds  []pgtype.UUID
}

func (q *Queries) KbSetArticleImages(ctx context.Context, arg KbSetArticleImagesParams) error {
	_, err := q.db.Exec(ctx, kbSetArticleImages, arg.ArticleID, arg.ImageIds)
	return err
}

const kbSetArticleStatus = `-- name: KbSetArticleStatus :one
UPDATE kb_articles
SET status = $1::text, updated_by = $2, version = version + 1, updated_at = now(),
    published_at = CASE WHEN $1::text = 'published' AND published_at IS NULL THEN now() ELSE published_at END
WHERE id = $3
RETURNING id, category_id, title, slug, body_html, body_text, excerpt, status, author_id, updated_by, version, position, view_count, helpful_yes, helpful_no, created_at, updated_at, published_at, fts
`

type KbSetArticleStatusParams struct {
	Status string
	UserID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) KbSetArticleStatus(ctx context.Context, arg KbSetArticleStatusParams) (KbArticle, error) {
	row := q.db.QueryRow(ctx, kbSetArticleStatus, arg.Status, arg.UserID, arg.ID)
	var i KbArticle
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Slug,
		&i.BodyHtml,
		&i.BodyText,
		&i.Excerpt,
		&i.Status,
		&i.AuthorID,
		&i.UpdatedBy,
		&i.Version,
		&i.Position,
		&i.ViewCount,
		&i.HelpfulYes,
		&i.HelpfulNo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.Fts,
	)
	return i, err
}

const kbSitemapArticles = `-- name: KbSitemapArticles :many
SELECT slug, updated_at FROM kb_articles WHERE status = 'published' ORDER BY slug
`

type KbSitemapArticlesRow struct {
	Slug      string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) KbSitemapArticles(ctx context.Context) ([]KbSitemapArticlesRow, error) {
	rows, err := q.db.Query(ctx, kbSitemapArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KbSitemapArticlesRow{}
	for rows.Next() {
		var i KbSitemapArticlesRow
		if err := rows.Scan(&i.Slug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const kbSitemapCategories = `-- name: KbSitemapCategories :many
SELECT c.slug, c.updated_at FROM kb_categories c
WHERE EXISTS (SELECT 1 FROM kb_articles a WHERE a.status = 'published'
              AND (a.category_id = c.id OR a.category_id IN (SELECT ch.id FROM kb_categories ch WHERE ch.parent_id = c.id)))
ORDER BY c.slug
`

type KbSitemapCategoriesRow struct {
	Slug      string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) KbSitemapCategories(ctx context.Context) ([]KbSitemapCategoriesRow, error) {
	rows, err := q.db.Query(ctx, kbSitemapCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KbSitemapCategoriesRow{}
	for rows.Next() {
		var i KbSitemapCategoriesRow
		if err := rows.Scan(&i.Slug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const kbSlugOwner = `-- name: KbSlugOwner :one
SELECT a.id AS article_id FROM kb_articles a WHERE a.slug = $1
UNION ALL
SELECT r.article_id FROM kb_slug_redirects r WHERE r.slug = $1
LIMIT 1
`

// The article that uses a slug now or used to (its redirect keeps the old link alive).
func (q *Queries) KbSlugOwner(ctx context.Context, slug string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, kbSlugOwner, slug)
	var article_id pgtype.UUID
	err := row.Scan(&article_id)
	return article_id, err
}

const kbTrimRevisions = `-- name: KbTrimRevisions :exec
DELETE FROM kb_article_revisions AS rev
WHERE rev.article_id = $1
  AND rev.id NOT IN (SELECT r.id FROM kb_article_revisions r WHERE r.article_id = $1
                 ORDER BY r.created_at DESC, r.id DESC LIMIT $2::integer)
`

type KbTrimRevisionsParams struct {
	ArticleID pgtype.UUID
	Keep      int32
}

func (q *Queries) KbTrimRevisions(ctx context.Context, arg KbTrimRevisionsParams) error {
	_, err := q.db.Exec(ctx, kbTrimRevisions, arg.ArticleID, arg.Keep)
	return err
}

const kbUpdateArticle = `-- name: KbUpdateArticle :one
UPDATE kb_articles
SET category_id = $1, title = $2, slug = $3, body_html = $4,
    body_text = $5, excerpt = $6, updated_by = $7,
    version = version + 1, updated_at = now()
WHERE id = $8
RETURNING id, category_id, title, slug, body_html, body_text, excerpt, status, author_id, updated_by, version, position, view_count, helpful_yes, helpful_no, created_at, updated_at, published_at, fts
`

type KbUpdateArticleParams struct {
	CategoryID pgtype.UUID
	Title      string
	Slug       string
	BodyHtml   string
	BodyText   string
	Excerpt    string
	UserID     pgtype.UUID
	ID         pgtype.UUID
}

func (q *Queries) KbUpdateArticle(ctx context.Context, arg KbUpdateArticleParams) (KbArticle, error) {
	row := q.db.QueryRow(ctx, kbUpdateArticle,
		arg.CategoryID,
		arg.Title,
		arg.Slug,
		arg.BodyHtml,
		arg.BodyText,
		arg.Excerpt,
		arg.UserID,
		arg.ID,
	)
	var i KbArticle
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Slug,
		&i.BodyHtml,
		&i.BodyText,
		&i.Excerpt,
		&i.Status,
		&i.AuthorID,
		&i.UpdatedBy,
		&i.Version,
		&i.Position,
		&i.ViewCount,
		&i.HelpfulYes,
		&i.HelpfulNo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.Fts,
	)
	return i, err
}

const kbUpdateCategory = `-- name: KbUpdateCategory :one
UPDATE kb_categories
SET parent_id = $1, name = $2, slug = $3, description = $4,
    position = $5, updated_at = now()
WHERE id = $6
RETURNING id, parent_id, name, slug, description, position, created_at, updated_at
`

type KbUpdateCategoryParams struct {
	ParentID    pgtype.UUID
	Name        string
	Slug        string
	Description string
	Position    int32
	ID          pgtype.UUID
}

func (q *Queries) KbUpdateCategory(ctx context.Context, arg KbUpdateCategoryParams) (KbCategory, error) {
	row := q.db.QueryRow(ctx, kbUpdateCategory,
		arg.ParentID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Position,
		arg.ID,
	)
	var i KbCategory
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const kbUpdatePortal = `-- name: KbUpdatePortal :one
UPDATE kb_portal
SET name = $1, title = $2, intro = $3, logo_text = $4, custom_domain = $5, updated_at = now()
RETURNING name, title, intro, logo_text, custom_domain, updated_at
`

type KbUpdatePortalParams struct {
	Name         string
	Title        string
	Intro        string
	LogoText     string
	CustomDomain string
}

type KbUpdatePortalRow struct {
	Name         string
	Title        string
	Intro        string
	LogoText     string
	CustomDomain string
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) KbUpdatePortal(ctx context.Context, arg KbUpdatePortalParams) (KbUpdatePortalRow, error) {
	row := q.db.QueryRow(ctx, kbUpdatePortal,
		arg.Name,
		arg.Title,
		arg.Intro,
		arg.LogoText,
		arg.CustomDomain,
	)
	var i KbUpdatePortalRow
	err := row.Scan(
		&i.Name,
		&i.Title,
		&i.Intro,
		&i.LogoText,
		&i.CustomDomain,
		&i.UpdatedAt,
	)
	return i, err
}
