// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imapsync.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceFolderCursor = `-- name: AdvanceFolderCursor :exec
UPDATE mailbox_folders
SET last_uid = GREATEST(last_uid, $1::bigint), last_synced_at = now()
WHERE id = $2
`

type AdvanceFolderCursorParams struct {
	LastUid int64
	ID      pgtype.UUID
}

func (q *Queries) AdvanceFolderCursor(ctx context.Context, arg AdvanceFolderCursorParams) error {
	_, err := q.db.Exec(ctx, advanceFolderCursor, arg.LastUid, arg.ID)
	return err
}

const getImapSyncMailbox = `-- name: GetImapSyncMailbox :one
SELECT id, name, email_address, display_name, transport, auth_type, imap_host, imap_port, imap_tls, imap_username, imap_secret_enc, smtp_host, smtp_port, smtp_tls, smtp_username, smtp_secret_enc, oauth_token_enc, oauth_expires_at, inbound_secret_enc, sent_folder, mark_seen, send_delay_seconds, sync_state, sync_error, sync_state_changed_at, last_synced_at, created_at, updated_at, disabled_at, allow_internal_host, oauth_connected_at, auto_assign_mode, default_sla_policy_id, business_hours_id FROM mailboxes
WHERE id = $1 AND disabled_at IS NULL AND transport = 'imap'
`

func (q *Queries) GetImapSyncMailbox(ctx context.Context, id pgtype.UUID) (Mailbox, error) {
	row := q.db.QueryRow(ctx, getImapSyncMailbox, id)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailAddress,
		&i.DisplayName,
		&i.Transport,
		&i.AuthType,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapTls,
		&i.ImapUsername,
		&i.ImapSecretEnc,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpTls,
		&i.SmtpUsername,
		&i.SmtpSecretEnc,
		&i.OauthTokenEnc,
		&i.OauthExpiresAt,
		&i.InboundSecretEnc,
		&i.SentFolder,
		&i.MarkSeen,
		&i.SendDelaySeconds,
		&i.SyncState,
		&i.SyncError,
		&i.SyncStateChangedAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
		&i.AllowInternalHost,
		&i.OauthConnectedAt,
		&i.AutoAssignMode,
		&i.DefaultSlaPolicyID,
		&i.BusinessHoursID,
	)
	return i, err
}

const insertImapRawMessage = `-- name: InsertImapRawMessage :one
INSERT INTO raw_messages (mailbox_id, folder_id, source, uidvalidity, uid, sha256, size_bytes, blob_key)
VALUES ($1, $2, 'imap', $3, $4, $5, $6, $7)
ON CONFLICT (mailbox_id, folder_id, uidvalidity, uid) WHERE source = 'imap' DO NOTHING
RETURNING id
`

type InsertImapRawMessageParams struct {
	MailboxID   pgtype.UUID
	FolderID    pgtype.UUID
	Uidvalidity pgtype.Int8
	Uid         pgtype.Int8
	Sha256      []byte
	SizeBytes   int32
	BlobKey     string
}

func (q *Queries) InsertImapRawMessage(ctx context.Context, arg InsertImapRawMessageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertImapRawMessage,
		arg.MailboxID,
		arg.FolderID,
		arg.Uidvalidity,
		arg.Uid,
		arg.Sha256,
		arg.SizeBytes,
		arg.BlobKey,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertSkippedImapRawMessage = `-- name: InsertSkippedImapRawMessage :one
INSERT INTO raw_messages (mailbox_id, folder_id, source, uidvalidity, uid, sha256, size_bytes, blob_key, parse_status, parse_error)
VALUES ($1, $2, 'imap', $3, $4, $5, $6, $7, 'skipped', $8)
ON CONFLICT (mailbox_id, folder_id, uidvalidity, uid) WHERE source = 'imap' DO NOTHING
RETURNING id
`

type InsertSkippedImapRawMessageParams struct {
	MailboxID   pgtype.UUID
	FolderID    pgtype.UUID
	Uidvalidity pgtype.Int8
	Uid         pgtype.Int8
	Sha256      []byte
	SizeBytes   int32
	BlobKey     string
	ParseError  string
}

func (q *Queries) InsertSkippedImapRawMessage(ctx context.Context, arg InsertSkippedImapRawMessageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertSkippedImapRawMessage,
		arg.MailboxID,
		arg.FolderID,
		arg.Uidvalidity,
		arg.Uid,
		arg.Sha256,
		arg.SizeBytes,
		arg.BlobKey,
		arg.ParseError,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listImapSyncMailboxes = `-- name: ListImapSyncMailboxes :many
SELECT id, name, email_address, display_name, transport, auth_type, imap_host, imap_port, imap_tls, imap_username, imap_secret_enc, smtp_host, smtp_port, smtp_tls, smtp_username, smtp_secret_enc, oauth_token_enc, oauth_expires_at, inbound_secret_enc, sent_folder, mark_seen, send_delay_seconds, sync_state, sync_error, sync_state_changed_at, last_synced_at, created_at, updated_at, disabled_at, allow_internal_host, oauth_connected_at, auto_assign_mode, default_sla_policy_id, business_hours_id FROM mailboxes
WHERE disabled_at IS NULL AND transport = 'imap'
ORDER BY id
`

func (q *Queries) ListImapSyncMailboxes(ctx context.Context) ([]Mailbox, error) {
	rows, err := q.db.Query(ctx, listImapSyncMailboxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mailbox{}
	for rows.Next() {
		var i Mailbox
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EmailAddress,
			&i.DisplayName,
			&i.Transport,
			&i.AuthType,
			&i.ImapHost,
			&i.ImapPort,
			&i.ImapTls,
			&i.ImapUsername,
			&i.ImapSecretEnc,
			&i.SmtpHost,
			&i.SmtpPort,
			&i.SmtpTls,
			&i.SmtpUsername,
			&i.SmtpSecretEnc,
			&i.OauthTokenEnc,
			&i.OauthExpiresAt,
			&i.InboundSecretEnc,
			&i.SentFolder,
			&i.MarkSeen,
			&i.SendDelaySeconds,
			&i.SyncState,
			&i.SyncError,
			&i.SyncStateChangedAt,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisabledAt,
			&i.AllowInternalHost,
			&i.OauthConnectedAt,
			&i.AutoAssignMode,
			&i.DefaultSlaPolicyID,
			&i.BusinessHoursID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMailboxSyncDisabled = `-- name: MarkMailboxSyncDisabled :exec
UPDATE mailboxes
SET sync_state = 'disabled', sync_error = '', sync_state_changed_at = now()
WHERE id = $1 AND disabled_at IS NOT NULL AND sync_state <> 'disabled'
`

func (q *Queries) MarkMailboxSyncDisabled(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markMailboxSyncDisabled, id)
	return err
}

const resetFolderUIDValidity = `-- name: ResetFolderUIDValidity :exec
UPDATE mailbox_folders SET uidvalidity = $2, last_uid = 0 WHERE id = $1
`

type ResetFolderUIDValidityParams struct {
	ID          pgtype.UUID
	Uidvalidity int64
}

func (q *Queries) ResetFolderUIDValidity(ctx context.Context, arg ResetFolderUIDValidityParams) error {
	_, err := q.db.Exec(ctx, resetFolderUIDValidity, arg.ID, arg.Uidvalidity)
	return err
}

const setMailboxSyncState = `-- name: SetMailboxSyncState :exec
UPDATE mailboxes
SET sync_state = $1::text,
    sync_error = $2::text,
    sync_state_changed_at = CASE WHEN sync_state = $1::text THEN sync_state_changed_at ELSE now() END
WHERE id = $3
`

type SetMailboxSyncStateParams struct {
	SyncState string
	SyncError string
	ID        pgtype.UUID
}

func (q *Queries) SetMailboxSyncState(ctx context.Context, arg SetMailboxSyncStateParams) error {
	_, err := q.db.Exec(ctx, setMailboxSyncState, arg.SyncState, arg.SyncError, arg.ID)
	return err
}

const touchMailboxSynced = `-- name: TouchMailboxSynced :exec
UPDATE mailboxes SET last_synced_at = now() WHERE id = $1
`

func (q *Queries) TouchMailboxSynced(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchMailboxSynced, id)
	return err
}

const upsertInboxFolder = `-- name: UpsertInboxFolder :one
INSERT INTO mailbox_folders (mailbox_id, name, role)
VALUES ($1, 'INBOX', 'inbox')
ON CONFLICT (mailbox_id, name) DO UPDATE SET role = EXCLUDED.role
RETURNING id, mailbox_id, name, role, uidvalidity, last_uid, last_synced_at
`

func (q *Queries) UpsertInboxFolder(ctx context.Context, mailboxID pgtype.UUID) (MailboxFolder, error) {
	row := q.db.QueryRow(ctx, upsertInboxFolder, mailboxID)
	var i MailboxFolder
	err := row.Scan(
		&i.ID,
		&i.MailboxID,
		&i.Name,
		&i.Role,
		&i.Uidvalidity,
		&i.LastUid,
		&i.LastSyncedAt,
	)
	return i, err
}
