// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ingestAdvisoryLock = `-- name: IngestAdvisoryLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) IngestAdvisoryLock(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, ingestAdvisoryLock, key)
	return err
}

const ingestCreateContact = `-- name: IngestCreateContact :one
INSERT INTO contacts (name, organization_id) VALUES ($1, $2) RETURNING id
`

type IngestCreateContactParams struct {
	Name           string
	OrganizationID pgtype.UUID
}

func (q *Queries) IngestCreateContact(ctx context.Context, arg IngestCreateContactParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, ingestCreateContact, arg.Name, arg.OrganizationID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const ingestCreateContactAddress = `-- name: IngestCreateContactAddress :exec
INSERT INTO contact_addresses (contact_id, email, is_primary) VALUES ($1, $2, true)
`

type IngestCreateContactAddressParams struct {
	ContactID pgtype.UUID
	Email     string
}

func (q *Queries) IngestCreateContactAddress(ctx context.Context, arg IngestCreateContactAddressParams) error {
	_, err := q.db.Exec(ctx, ingestCreateContactAddress, arg.ContactID, arg.Email)
	return err
}

const ingestCreateConversation = `-- name: IngestCreateConversation :one
INSERT INTO conversations (mailbox_id, subject, subject_normalized, contact_id, last_message_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type IngestCreateConversationParams struct {
	MailboxID         pgtype.UUID
	Subject           string
	SubjectNormalized string
	ContactID         pgtype.UUID
	LastMessageAt     pgtype.Timestamptz
}

func (q *Queries) IngestCreateConversation(ctx context.Context, arg IngestCreateConversationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, ingestCreateConversation,
		arg.MailboxID,
		arg.Subject,
		arg.SubjectNormalized,
		arg.ContactID,
		arg.LastMessageAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const ingestCreateOrganization = `-- name: IngestCreateOrganization :one
INSERT INTO organizations (name, domains) VALUES ($1::text, ARRAY[$1::text]) RETURNING id
`

func (q *Queries) IngestCreateOrganization(ctx context.Context, domain string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, ingestCreateOrganization, domain)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const ingestFillContact = `-- name: IngestFillContact :exec
UPDATE contacts
SET name = CASE WHEN name = '' THEN $1::text ELSE name END,
    organization_id = COALESCE(organization_id, $2),
    updated_at = now()
WHERE id = $3
  AND ((name = '' AND $1::text <> '') OR (organization_id IS NULL AND $2::uuid IS NOT NULL))
`

type IngestFillContactParams struct {
	Name           string
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
}

func (q *Queries) IngestFillContact(ctx context.Context, arg IngestFillContactParams) error {
	_, err := q.db.Exec(ctx, ingestFillContact, arg.Name, arg.OrganizationID, arg.ID)
	return err
}

const ingestFindOrganizationByDomain = `-- name: IngestFindOrganizationByDomain :one
SELECT id FROM organizations WHERE domains @> ARRAY[$1::text] ORDER BY created_at, id LIMIT 1
`

func (q *Queries) IngestFindOrganizationByDomain(ctx context.Context, domain string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, ingestFindOrganizationByDomain, domain)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const ingestFindOutbound = `-- name: IngestFindOutbound :one
SELECT m.id AS message_id, m.conversation_id, o.status
FROM messages m
JOIN outbound o ON o.message_id = m.id
WHERE m.mailbox_id = $1 AND m.message_id_hash = $2 AND m.kind = 'email' AND m.direction = 'out'
ORDER BY m.created_at
LIMIT 1
FOR UPDATE OF o
`

type IngestFindOutboundParams struct {
	MailboxID     pgtype.UUID
	MessageIDHash []byte
}

type IngestFindOutboundRow struct {
	MessageID      pgtype.UUID
	ConversationID pgtype.UUID
	Status         string
}

func (q *Queries) IngestFindOutbound(ctx context.Context, arg IngestFindOutboundParams) (IngestFindOutboundRow, error) {
	row := q.db.QueryRow(ctx, ingestFindOutbound, arg.MailboxID, arg.MessageIDHash)
	var i IngestFindOutboundRow
	err := row.Scan(&i.MessageID, &i.ConversationID, &i.Status)
	return i, err
}

const ingestGetContactByEmail = `-- name: IngestGetContactByEmail :one
SELECT contact_id FROM contact_addresses WHERE email = $1
`

func (q *Queries) IngestGetContactByEmail(ctx context.Context, email string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, ingestGetContactByEmail, email)
	var contact_id pgtype.UUID
	err := row.Scan(&contact_id)
	return contact_id, err
}

const ingestGetMailbox = `-- name: IngestGetMailbox :one
SELECT id, email_address FROM mailboxes WHERE id = $1
`

type IngestGetMailboxRow struct {
	ID           pgtype.UUID
	EmailAddress string
}

func (q *Queries) IngestGetMailbox(ctx context.Context, id pgtype.UUID) (IngestGetMailboxRow, error) {
	row := q.db.QueryRow(ctx, ingestGetMailbox, id)
	var i IngestGetMailboxRow
	err := row.Scan(&i.ID, &i.EmailAddress)
	return i, err
}

const ingestGetRaw = `-- name: IngestGetRaw :one
SELECT id, mailbox_id, folder_id, source, uidvalidity, uid, sha256, size_bytes, blob_key, received_at, parse_status, parse_error, created_at FROM raw_messages WHERE id = $1
`

func (q *Queries) IngestGetRaw(ctx context.Context, id pgtype.UUID) (RawMessage, error) {
	row := q.db.QueryRow(ctx, ingestGetRaw, id)
	var i RawMessage
	err := row.Scan(
		&i.ID,
		&i.MailboxID,
		&i.FolderID,
		&i.Source,
		&i.Uidvalidity,
		&i.Uid,
		&i.Sha256,
		&i.SizeBytes,
		&i.BlobKey,
		&i.ReceivedAt,
		&i.ParseStatus,
		&i.ParseError,
		&i.CreatedAt,
	)
	return i, err
}

const ingestInsertAttachment = `-- name: IngestInsertAttachment :exec
INSERT INTO attachments (message_id, filename, declared_type, sniffed_type, size_bytes, sha256, blob_key, content_id, disposition, scan_status, scan_detail)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type IngestInsertAttachmentParams struct {
	MessageID    pgtype.UUID
	Filename     string
	DeclaredType string
	SniffedType  string
	SizeBytes    int64
	Sha256       []byte
	BlobKey      string
	ContentID    string
	Disposition  string
	ScanStatus   string
	ScanDetail   string
}

func (q *Queries) IngestInsertAttachment(ctx context.Context, arg IngestInsertAttachmentParams) error {
	_, err := q.db.Exec(ctx, ingestInsertAttachment,
		arg.MessageID,
		arg.Filename,
		arg.DeclaredType,
		arg.SniffedType,
		arg.SizeBytes,
		arg.Sha256,
		arg.BlobKey,
		arg.ContentID,
		arg.Disposition,
		arg.ScanStatus,
		arg.ScanDetail,
	)
	return err
}

const ingestInsertEvent = `-- name: IngestInsertEvent :exec
INSERT INTO conversation_events (conversation_id, mailbox_id, type, data)
VALUES ($1, $2, $3, $4)
`

type IngestInsertEventParams struct {
	ConversationID pgtype.UUID
	MailboxID      pgtype.UUID
	Type           string
	Data           []byte
}

func (q *Queries) IngestInsertEvent(ctx context.Context, arg IngestInsertEventParams) error {
	_, err := q.db.Exec(ctx, ingestInsertEvent,
		arg.ConversationID,
		arg.MailboxID,
		arg.Type,
		arg.Data,
	)
	return err
}

const ingestInsertMessage = `-- name: IngestInsertMessage :one
INSERT INTO messages (
    conversation_id, mailbox_id, kind, direction, raw_message_id, raw_sha256,
    message_id_header, message_id_hash, in_reply_to, references_hdr, from_addr, from_name,
    to_addrs, cc_addrs, bcc_addrs, reply_to, subject, sent_at, received_at,
    body_text, body_html, auto_submitted, is_bounce, auth_results, is_bulk
) VALUES (
    $1, $2, 'email', 'in', $3, $4,
    $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17,
    $18, $19, $20, false, $21, $22
)
ON CONFLICT (mailbox_id, message_id_hash, raw_sha256)
    WHERE message_id_hash IS NOT NULL AND raw_sha256 IS NOT NULL DO NOTHING
RETURNING id
`

type IngestInsertMessageParams struct {
	ConversationID  pgtype.UUID
	MailboxID       pgtype.UUID
	RawMessageID    pgtype.UUID
	RawSha256       []byte
	MessageIDHeader string
	MessageIDHash   []byte
	InReplyTo       string
	ReferencesHdr   []string
	FromAddr        string
	FromName        string
	ToAddrs         []byte
	CcAddrs         []byte
	BccAddrs        []byte
	ReplyTo         []byte
	Subject         string
	SentAt          pgtype.Timestamptz
	ReceivedAt      pgtype.Timestamptz
	BodyText        string
	BodyHtml        string
	AutoSubmitted   bool
	AuthResults     string
	IsBulk          bool
}

func (q *Queries) IngestInsertMessage(ctx context.Context, arg IngestInsertMessageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, ingestInsertMessage,
		arg.ConversationID,
		arg.MailboxID,
		arg.RawMessageID,
		arg.RawSha256,
		arg.MessageIDHeader,
		arg.MessageIDHash,
		arg.InReplyTo,
		arg.ReferencesHdr,
		arg.FromAddr,
		arg.FromName,
		arg.ToAddrs,
		arg.CcAddrs,
		arg.BccAddrs,
		arg.ReplyTo,
		arg.Subject,
		arg.SentAt,
		arg.ReceivedAt,
		arg.BodyText,
		arg.BodyHtml,
		arg.AutoSubmitted,
		arg.AuthResults,
		arg.IsBulk,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const ingestInsertThreadRefs = `-- name: IngestInsertThreadRefs :exec
INSERT INTO thread_refs (mailbox_id, message_id_hash, conversation_id)
SELECT $1, h, $2 FROM unnest($3::bytea[]) AS h
ON CONFLICT (mailbox_id, message_id_hash) DO NOTHING
`

type IngestInsertThreadRefsParams struct {
	MailboxID      pgtype.UUID
	ConversationID pgtype.UUID
	Hashes         [][]byte
}

func (q *Queries) IngestInsertThreadRefs(ctx context.Context, arg IngestInsertThreadRefsParams) error {
	_, err := q.db.Exec(ctx, ingestInsertThreadRefs, arg.MailboxID, arg.ConversationID, arg.Hashes)
	return err
}

const ingestLockConversation = `-- name: IngestLockConversation :one
SELECT id, status, snoozed_until FROM conversations
WHERE id = $1 AND mailbox_id = $2 AND deleted_at IS NULL
FOR UPDATE
`

type IngestLockConversationParams struct {
	ID        pgtype.UUID
	MailboxID pgtype.UUID
}

type IngestLockConversationRow struct {
	ID           pgtype.UUID
	Status       string
	SnoozedUntil pgtype.Timestamptz
}

func (q *Queries) IngestLockConversation(ctx context.Context, arg IngestLockConversationParams) (IngestLockConversationRow, error) {
	row := q.db.QueryRow(ctx, ingestLockConversation, arg.ID, arg.MailboxID)
	var i IngestLockConversationRow
	err := row.Scan(&i.ID, &i.Status, &i.SnoozedUntil)
	return i, err
}

const ingestLockRaw = `-- name: IngestLockRaw :one
SELECT id, parse_status FROM raw_messages WHERE id = $1 FOR UPDATE
`

type IngestLockRawRow struct {
	ID          pgtype.UUID
	ParseStatus string
}

func (q *Queries) IngestLockRaw(ctx context.Context, id pgtype.UUID) (IngestLockRawRow, error) {
	row := q.db.QueryRow(ctx, ingestLockRaw, id)
	var i IngestLockRawRow
	err := row.Scan(&i.ID, &i.ParseStatus)
	return i, err
}

const ingestMarkOutboundBounced = `-- name: IngestMarkOutboundBounced :execrows
UPDATE outbound
SET status = 'bounced', dsn_status = $1::text, error = $2::text, updated_at = now()
WHERE message_id = $3 AND status IN ('sent', 'uncertain')
`

type IngestMarkOutboundBouncedParams struct {
	DsnStatus  string
	Diagnostic string
	MessageID  pgtype.UUID
}

func (q *Queries) IngestMarkOutboundBounced(ctx context.Context, arg IngestMarkOutboundBouncedParams) (int64, error) {
	result, err := q.db.Exec(ctx, ingestMarkOutboundBounced, arg.DsnStatus, arg.Diagnostic, arg.MessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ingestMessageExists = `-- name: IngestMessageExists :one
SELECT EXISTS (
    SELECT 1 FROM messages
    WHERE mailbox_id = $1 AND message_id_hash = $2 AND raw_sha256 = $3
)
`

type IngestMessageExistsParams struct {
	MailboxID     pgtype.UUID
	MessageIDHash []byte
	RawSha256     []byte
}

func (q *Queries) IngestMessageExists(ctx context.Context, arg IngestMessageExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, ingestMessageExists, arg.MailboxID, arg.MessageIDHash, arg.RawSha256)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ingestSetRawStatus = `-- name: IngestSetRawStatus :exec
UPDATE raw_messages
SET parse_status = $1::text, parse_error = $2::text
WHERE id = $3
`

type IngestSetRawStatusParams struct {
	ParseStatus string
	ParseError  string
	ID          pgtype.UUID
}

func (q *Queries) IngestSetRawStatus(ctx context.Context, arg IngestSetRawStatusParams) error {
	_, err := q.db.Exec(ctx, ingestSetRawStatus, arg.ParseStatus, arg.ParseError, arg.ID)
	return err
}

const ingestUpdateConversation = `-- name: IngestUpdateConversation :exec
UPDATE conversations
SET message_count = message_count + 1,
    last_message_at = GREATEST(last_message_at, $1::timestamptz),
    last_inbound_at = GREATEST(COALESCE(last_inbound_at, $1::timestamptz), $1::timestamptz),
    preview = CASE WHEN $1::timestamptz >= last_message_at THEN $2::text ELSE preview END,
    has_attachments = has_attachments OR $3::boolean,
    status = CASE WHEN $4::boolean THEN 'open' ELSE status END,
    resolved_at = CASE WHEN $4::boolean THEN NULL ELSE resolved_at END,
    snoozed_until = CASE WHEN $5::boolean THEN NULL ELSE snoozed_until END,
    contact_id = COALESCE(contact_id, $6),
    version = version + 1,
    updated_at = now()
WHERE id = $7
`

type IngestUpdateConversationParams struct {
	ReceivedAt     pgtype.Timestamptz
	Preview        string
	HasAttachments bool
	Reopen         bool
	Wake           bool
	ContactID      pgtype.UUID
	ID             pgtype.UUID
}

func (q *Queries) IngestUpdateConversation(ctx context.Context, arg IngestUpdateConversationParams) error {
	_, err := q.db.Exec(ctx, ingestUpdateConversation,
		arg.ReceivedAt,
		arg.Preview,
		arg.HasAttachments,
		arg.Reopen,
		arg.Wake,
		arg.ContactID,
		arg.ID,
	)
	return err
}
