// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mailboxes.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMailboxAccess = `-- name: AddMailboxAccess :exec
INSERT INTO mailbox_access (mailbox_id, team_id, level)
SELECT $1, unnest($2::uuid[]), unnest($3::text[])
`

type AddMailboxAccessParams struct {
	MailboxID pgtype.UUID
	TeamIds   []pgtype.UUID
	Levels    []string
}

func (q *Queries) AddMailboxAccess(ctx context.Context, arg AddMailboxAccessParams) error {
	_, err := q.db.Exec(ctx, addMailboxAccess, arg.MailboxID, arg.TeamIds, arg.Levels)
	return err
}

const deleteMailboxAccess = `-- name: DeleteMailboxAccess :exec
DELETE FROM mailbox_access WHERE mailbox_id = $1
`

func (q *Queries) DeleteMailboxAccess(ctx context.Context, mailboxID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMailboxAccess, mailboxID)
	return err
}

const getMailbox = `-- name: GetMailbox :one
SELECT id, name, email_address, display_name, transport, auth_type, imap_host, imap_port, imap_tls, imap_username, imap_secret_enc, smtp_host, smtp_port, smtp_tls, smtp_username, smtp_secret_enc, oauth_token_enc, oauth_expires_at, inbound_secret_enc, sent_folder, mark_seen, send_delay_seconds, sync_state, sync_error, sync_state_changed_at, last_synced_at, created_at, updated_at, disabled_at, allow_internal_host, oauth_connected_at, auto_assign_mode, default_sla_policy_id, business_hours_id FROM mailboxes WHERE id = $1
`

func (q *Queries) GetMailbox(ctx context.Context, id pgtype.UUID) (Mailbox, error) {
	row := q.db.QueryRow(ctx, getMailbox, id)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailAddress,
		&i.DisplayName,
		&i.Transport,
		&i.AuthType,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapTls,
		&i.ImapUsername,
		&i.ImapSecretEnc,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpTls,
		&i.SmtpUsername,
		&i.SmtpSecretEnc,
		&i.OauthTokenEnc,
		&i.OauthExpiresAt,
		&i.InboundSecretEnc,
		&i.SentFolder,
		&i.MarkSeen,
		&i.SendDelaySeconds,
		&i.SyncState,
		&i.SyncError,
		&i.SyncStateChangedAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
		&i.AllowInternalHost,
		&i.OauthConnectedAt,
		&i.AutoAssignMode,
		&i.DefaultSlaPolicyID,
		&i.BusinessHoursID,
	)
	return i, err
}

const getMailboxForUpdate = `-- name: GetMailboxForUpdate :one
SELECT id, name, email_address, display_name, transport, auth_type, imap_host, imap_port, imap_tls, imap_username, imap_secret_enc, smtp_host, smtp_port, smtp_tls, smtp_username, smtp_secret_enc, oauth_token_enc, oauth_expires_at, inbound_secret_enc, sent_folder, mark_seen, send_delay_seconds, sync_state, sync_error, sync_state_changed_at, last_synced_at, created_at, updated_at, disabled_at, allow_internal_host, oauth_connected_at, auto_assign_mode, default_sla_policy_id, business_hours_id FROM mailboxes WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetMailboxForUpdate(ctx context.Context, id pgtype.UUID) (Mailbox, error) {
	row := q.db.QueryRow(ctx, getMailboxForUpdate, id)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailAddress,
		&i.DisplayName,
		&i.Transport,
		&i.AuthType,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapTls,
		&i.ImapUsername,
		&i.ImapSecretEnc,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpTls,
		&i.SmtpUsername,
		&i.SmtpSecretEnc,
		&i.OauthTokenEnc,
		&i.OauthExpiresAt,
		&i.InboundSecretEnc,
		&i.SentFolder,
		&i.MarkSeen,
		&i.SendDelaySeconds,
		&i.SyncState,
		&i.SyncError,
		&i.SyncStateChangedAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
		&i.AllowInternalHost,
		&i.OauthConnectedAt,
		&i.AutoAssignMode,
		&i.DefaultSlaPolicyID,
		&i.BusinessHoursID,
	)
	return i, err
}

const insertMailbox = `-- name: InsertMailbox :one
INSERT INTO mailboxes (
    name, email_address, display_name,
    imap_host, imap_port, imap_tls, imap_username,
    smtp_host, smtp_port, smtp_tls, smtp_username,
    sent_folder, send_delay_seconds, allow_internal_host
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14
) RETURNING id, name, email_address, display_name, transport, auth_type, imap_host, imap_port, imap_tls, imap_username, imap_secret_enc, smtp_host, smtp_port, smtp_tls, smtp_username, smtp_secret_enc, oauth_token_enc, oauth_expires_at, inbound_secret_enc, sent_folder, mark_seen, send_delay_seconds, sync_state, sync_error, sync_state_changed_at, last_synced_at, created_at, updated_at, disabled_at, allow_internal_host, oauth_connected_at, auto_assign_mode, default_sla_policy_id, business_hours_id
`

type InsertMailboxParams struct {
	Name              string
	EmailAddress      string
	DisplayName       string
	ImapHost          string
	ImapPort          int32
	ImapTls           string
	ImapUsername      string
	SmtpHost          string
	SmtpPort          int32
	SmtpTls           string
	SmtpUsername      string
	SentFolder        string
	SendDelaySeconds  int32
	AllowInternalHost bool
}

func (q *Queries) InsertMailbox(ctx context.Context, arg InsertMailboxParams) (Mailbox, error) {
	row := q.db.QueryRow(ctx, insertMailbox,
		arg.Name,
		arg.EmailAddress,
		arg.DisplayName,
		arg.ImapHost,
		arg.ImapPort,
		arg.ImapTls,
		arg.ImapUsername,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SmtpTls,
		arg.SmtpUsername,
		arg.SentFolder,
		arg.SendDelaySeconds,
		arg.AllowInternalHost,
	)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailAddress,
		&i.DisplayName,
		&i.Transport,
		&i.AuthType,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapTls,
		&i.ImapUsername,
		&i.ImapSecretEnc,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpTls,
		&i.SmtpUsername,
		&i.SmtpSecretEnc,
		&i.OauthTokenEnc,
		&i.OauthExpiresAt,
		&i.InboundSecretEnc,
		&i.SentFolder,
		&i.MarkSeen,
		&i.SendDelaySeconds,
		&i.SyncState,
		&i.SyncError,
		&i.SyncStateChangedAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
		&i.AllowInternalHost,
		&i.OauthConnectedAt,
		&i.AutoAssignMode,
		&i.DefaultSlaPolicyID,
		&i.BusinessHoursID,
	)
	return i, err
}

const listAllMailboxIDs = `-- name: ListAllMailboxIDs :many
SELECT id FROM mailboxes ORDER BY id
`

func (q *Queries) ListAllMailboxIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAllMailboxIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailboxAccess = `-- name: ListMailboxAccess :many
SELECT mailbox_id, team_id, level FROM mailbox_access WHERE mailbox_id = $1 ORDER BY team_id
`

func (q *Queries) ListMailboxAccess(ctx context.Context, mailboxID pgtype.UUID) ([]MailboxAccess, error) {
	rows, err := q.db.Query(ctx, listMailboxAccess, mailboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MailboxAccess{}
	for rows.Next() {
		var i MailboxAccess
		if err := rows.Scan(&i.MailboxID, &i.TeamID, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailboxes = `-- name: ListMailboxes :many
SELECT id, name, email_address, display_name, transport, auth_type, imap_host, imap_port, imap_tls, imap_username, imap_secret_enc, smtp_host, smtp_port, smtp_tls, smtp_username, smtp_secret_enc, oauth_token_enc, oauth_expires_at, inbound_secret_enc, sent_folder, mark_seen, send_delay_seconds, sync_state, sync_error, sync_state_changed_at, last_synced_at, created_at, updated_at, disabled_at, allow_internal_host, oauth_connected_at, auto_assign_mode, default_sla_policy_id, business_hours_id FROM mailboxes ORDER BY lower(name), id
`

func (q *Queries) ListMailboxes(ctx context.Context) ([]Mailbox, error) {
	rows, err := q.db.Query(ctx, listMailboxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mailbox{}
	for rows.Next() {
		var i Mailbox
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EmailAddress,
			&i.DisplayName,
			&i.Transport,
			&i.AuthType,
			&i.ImapHost,
			&i.ImapPort,
			&i.ImapTls,
			&i.ImapUsername,
			&i.ImapSecretEnc,
			&i.SmtpHost,
			&i.SmtpPort,
			&i.SmtpTls,
			&i.SmtpUsername,
			&i.SmtpSecretEnc,
			&i.OauthTokenEnc,
			&i.OauthExpiresAt,
			&i.InboundSecretEnc,
			&i.SentFolder,
			&i.MarkSeen,
			&i.SendDelaySeconds,
			&i.SyncState,
			&i.SyncError,
			&i.SyncStateChangedAt,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisabledAt,
			&i.AllowInternalHost,
			&i.OauthConnectedAt,
			&i.AutoAssignMode,
			&i.DefaultSlaPolicyID,
			&i.BusinessHoursID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMailboxAccess = `-- name: ListUserMailboxAccess :many
SELECT mailbox_access.mailbox_id, bool_or(mailbox_access.level = 'write')::boolean AS can_write
FROM mailbox_access
JOIN team_members ON team_members.team_id = mailbox_access.team_id
WHERE team_members.user_id = $1
GROUP BY mailbox_access.mailbox_id
ORDER BY mailbox_access.mailbox_id
`

type ListUserMailboxAccessRow struct {
	MailboxID pgtype.UUID
	CanWrite  bool
}

func (q *Queries) ListUserMailboxAccess(ctx context.Context, userID pgtype.UUID) ([]ListUserMailboxAccessRow, error) {
	rows, err := q.db.Query(ctx, listUserMailboxAccess, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserMailboxAccessRow{}
	for rows.Next() {
		var i ListUserMailboxAccessRow
		if err := rows.Scan(&i.MailboxID, &i.CanWrite); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMailboxDisabled = `-- name: SetMailboxDisabled :one
UPDATE mailboxes SET
    disabled_at = CASE WHEN $1::boolean THEN now() ELSE NULL END,
    updated_at = now()
WHERE id = $2
RETURNING id, name, email_address, display_name, transport, auth_type, imap_host, imap_port, imap_tls, imap_username, imap_secret_enc, smtp_host, smtp_port, smtp_tls, smtp_username, smtp_secret_enc, oauth_token_enc, oauth_expires_at, inbound_secret_enc, sent_folder, mark_seen, send_delay_seconds, sync_state, sync_error, sync_state_changed_at, last_synced_at, created_at, updated_at, disabled_at, allow_internal_host, oauth_connected_at, auto_assign_mode, default_sla_policy_id, business_hours_id
`

type SetMailboxDisabledParams struct {
	Disabled bool
	ID       pgtype.UUID
}

func (q *Queries) SetMailboxDisabled(ctx context.Context, arg SetMailboxDisabledParams) (Mailbox, error) {
	row := q.db.QueryRow(ctx, setMailboxDisabled, arg.Disabled, arg.ID)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailAddress,
		&i.DisplayName,
		&i.Transport,
		&i.AuthType,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapTls,
		&i.ImapUsername,
		&i.ImapSecretEnc,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpTls,
		&i.SmtpUsername,
		&i.SmtpSecretEnc,
		&i.OauthTokenEnc,
		&i.OauthExpiresAt,
		&i.InboundSecretEnc,
		&i.SentFolder,
		&i.MarkSeen,
		&i.SendDelaySeconds,
		&i.SyncState,
		&i.SyncError,
		&i.SyncStateChangedAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
		&i.AllowInternalHost,
		&i.OauthConnectedAt,
		&i.AutoAssignMode,
		&i.DefaultSlaPolicyID,
		&i.BusinessHoursID,
	)
	return i, err
}

const setMailboxSecrets = `-- name: SetMailboxSecrets :one
UPDATE mailboxes SET
    imap_secret_enc = COALESCE($1, imap_secret_enc),
    smtp_secret_enc = COALESCE($2, smtp_secret_enc),
    updated_at = now()
WHERE id = $3
RETURNING id, name, email_address, display_name, transport, auth_type, imap_host, imap_port, imap_tls, imap_username, imap_secret_enc, smtp_host, smtp_port, smtp_tls, smtp_username, smtp_secret_enc, oauth_token_enc, oauth_expires_at, inbound_secret_enc, sent_folder, mark_seen, send_delay_seconds, sync_state, sync_error, sync_state_changed_at, last_synced_at, created_at, updated_at, disabled_at, allow_internal_host, oauth_connected_at, auto_assign_mode, default_sla_policy_id, business_hours_id
`

type SetMailboxSecretsParams struct {
	ImapSecretEnc []byte
	SmtpSecretEnc []byte
	ID            pgtype.UUID
}

func (q *Queries) SetMailboxSecrets(ctx context.Context, arg SetMailboxSecretsParams) (Mailbox, error) {
	row := q.db.QueryRow(ctx, setMailboxSecrets, arg.ImapSecretEnc, arg.SmtpSecretEnc, arg.ID)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailAddress,
		&i.DisplayName,
		&i.Transport,
		&i.AuthType,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapTls,
		&i.ImapUsername,
		&i.ImapSecretEnc,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpTls,
		&i.SmtpUsername,
		&i.SmtpSecretEnc,
		&i.OauthTokenEnc,
		&i.OauthExpiresAt,
		&i.InboundSecretEnc,
		&i.SentFolder,
		&i.MarkSeen,
		&i.SendDelaySeconds,
		&i.SyncState,
		&i.SyncError,
		&i.SyncStateChangedAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
		&i.AllowInternalHost,
		&i.OauthConnectedAt,
		&i.AutoAssignMode,
		&i.DefaultSlaPolicyID,
		&i.BusinessHoursID,
	)
	return i, err
}

const updateMailbox = `-- name: UpdateMailbox :one
UPDATE mailboxes SET
    name = $1, email_address = $2, display_name = $3,
    imap_host = $4, imap_port = $5, imap_tls = $6, imap_username = $7,
    smtp_host = $8, smtp_port = $9, smtp_tls = $10, smtp_username = $11,
    sent_folder = $12, send_delay_seconds = $13,
    allow_internal_host = $14, updated_at = now()
WHERE id = $15
RETURNING id, name, email_address, display_name, transport, auth_type, imap_host, imap_port, imap_tls, imap_username, imap_secret_enc, smtp_host, smtp_port, smtp_tls, smtp_username, smtp_secret_enc, oauth_token_enc, oauth_expires_at, inbound_secret_enc, sent_folder, mark_seen, send_delay_seconds, sync_state, sync_error, sync_state_changed_at, last_synced_at, created_at, updated_at, disabled_at, allow_internal_host, oauth_connected_at, auto_assign_mode, default_sla_policy_id, business_hours_id
`

type UpdateMailboxParams struct {
	Name              string
	EmailAddress      string
	DisplayName       string
	ImapHost          string
	ImapPort          int32
	ImapTls           string
	ImapUsername      string
	SmtpHost          string
	SmtpPort          int32
	SmtpTls           string
	SmtpUsername      string
	SentFolder        string
	SendDelaySeconds  int32
	AllowInternalHost bool
	ID                pgtype.UUID
}

func (q *Queries) UpdateMailbox(ctx context.Context, arg UpdateMailboxParams) (Mailbox, error) {
	row := q.db.QueryRow(ctx, updateMailbox,
		arg.Name,
		arg.EmailAddress,
		arg.DisplayName,
		arg.ImapHost,
		arg.ImapPort,
		arg.ImapTls,
		arg.ImapUsername,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SmtpTls,
		arg.SmtpUsername,
		arg.SentFolder,
		arg.SendDelaySeconds,
		arg.AllowInternalHost,
		arg.ID,
	)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailAddress,
		&i.DisplayName,
		&i.Transport,
		&i.AuthType,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapTls,
		&i.ImapUsername,
		&i.ImapSecretEnc,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpTls,
		&i.SmtpUsername,
		&i.SmtpSecretEnc,
		&i.OauthTokenEnc,
		&i.OauthExpiresAt,
		&i.InboundSecretEnc,
		&i.SentFolder,
		&i.MarkSeen,
		&i.SendDelaySeconds,
		&i.SyncState,
		&i.SyncError,
		&i.SyncStateChangedAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
		&i.AllowInternalHost,
		&i.OauthConnectedAt,
		&i.AutoAssignMode,
		&i.DefaultSlaPolicyID,
		&i.BusinessHoursID,
	)
	return i, err
}
