// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Purpose   string
	TokenHash []byte
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

type ApiToken struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Name       string
	Prefix     string
	TokenHash  []byte
	Scopes     []string
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type Attachment struct {
	ID           pgtype.UUID
	MessageID    pgtype.UUID
	Filename     string
	DeclaredType string
	SniffedType  string
	SizeBytes    int64
	Sha256       []byte
	BlobKey      string
	ContentID    string
	Disposition  string
	ScanStatus   string
	ScanDetail   string
	CreatedAt    pgtype.Timestamptz
}

type AuditLog struct {
	ID          int64
	At          pgtype.Timestamptz
	ActorUserID pgtype.UUID
	ActorIp     *netip.Addr
	Action      string
	TargetType  string
	TargetID    string
	Metadata    []byte
}

type AutomationReply struct {
	RuleID  pgtype.UUID
	Address string
	SentAt  pgtype.Timestamptz
}

type BlockedSender struct {
	ID        pgtype.UUID
	MailboxID pgtype.UUID
	Pattern   string
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type BusinessHour struct {
	ID        pgtype.UUID
	Name      string
	Timezone  string
	Weekly    []byte
	Holidays  []pgtype.Date
	IsDefault bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Campaign struct {
	ID             pgtype.UUID
	Name           string
	MailboxID      pgtype.UUID
	SegmentID      pgtype.UUID
	SegmentName    string
	Subject        string
	BodyHtml       string
	Status         string
	ScheduledAt    pgtype.Timestamptz
	RatePerMinute  int32
	CreatedBy      pgtype.UUID
	MaterializedAt pgtype.Timestamptz
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	Error          string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	StartedBy      pgtype.UUID
}

type CampaignRecipient struct {
	ID                pgtype.UUID
	CampaignID        pgtype.UUID
	ContactID         pgtype.UUID
	Email             string
	Name              string
	State             string
	SkipReason        string
	MessageID         pgtype.UUID
	ConversationID    pgtype.UUID
	Error             string
	UnsubscribeSecret pgtype.UUID
	QueuedAt          pgtype.Timestamptz
	FinishedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

type Contact struct {
	ID               pgtype.UUID
	Name             string
	OrganizationID   pgtype.UUID
	Notes            string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ErasedAt         pgtype.Timestamptz
	Phone            string
	CustomAttributes []byte
	CreatedBy        pgtype.UUID
	LastActivityAt   pgtype.Timestamptz
	UnsubscribedAt   pgtype.Timestamptz
}

type ContactAddress struct {
	ContactID pgtype.UUID
	Email     string
	IsPrimary bool
	BouncedAt pgtype.Timestamptz
}

type ContactImport struct {
	ID            pgtype.UUID
	CreatedBy     pgtype.UUID
	Filename      string
	Status        string
	Dedupe        string
	Delimiter     string
	Mapping       []byte
	SourceKey     string
	ErrorKey      string
	TotalRows     int32
	ProcessedRows int32
	CreatedCount  int32
	UpdatedCount  int32
	SkippedCount  int32
	FailedCount   int32
	Error         string
	CreatedAt     pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
}

type ContactSegment struct {
	ID          pgtype.UUID
	Name        string
	OwnerUserID pgtype.UUID
	Shared      bool
	Filter      []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Conversation struct {
	ID                 pgtype.UUID
	Number             int64
	MailboxID          pgtype.UUID
	Subject            string
	SubjectNormalized  string
	Status             string
	Priority           string
	AssigneeUserID     pgtype.UUID
	AssigneeTeamID     pgtype.UUID
	ContactID          pgtype.UUID
	SnoozedUntil       pgtype.Timestamptz
	LastMessageAt      pgtype.Timestamptz
	LastInboundAt      pgtype.Timestamptz
	LastOutboundAt     pgtype.Timestamptz
	FirstRespondedAt   pgtype.Timestamptz
	ResolvedAt         pgtype.Timestamptz
	MessageCount       int32
	HasAttachments     bool
	Preview            string
	Version            int32
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
	SlaPolicyID        pgtype.UUID
	SlaStartedAt       pgtype.Timestamptz
	FirstResponseDueAt pgtype.Timestamptz
	FirstResponseMetAt pgtype.Timestamptz
	ResolutionDueAt    pgtype.Timestamptz
	SlaState           string
	SlaPausedAt        pgtype.Timestamptz
	SlaResumedAt       pgtype.Timestamptz
	SlaFinalizedAt     pgtype.Timestamptz
	CustomAttributes   []byte
	DeletedBy          pgtype.UUID
}

type ConversationEvent struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	MailboxID      pgtype.UUID
	ActorUserID    pgtype.UUID
	Type           string
	Data           []byte
	CreatedAt      pgtype.Timestamptz
}

type ConversationLabel struct {
	ConversationID pgtype.UUID
	LabelID        pgtype.UUID
}

type ConversationRead struct {
	UserID         pgtype.UUID
	ConversationID pgtype.UUID
	LastReadAt     pgtype.Timestamptz
	MarkedUnread   bool
}

type CrmNote struct {
	ID             pgtype.UUID
	ContactID      pgtype.UUID
	OrganizationID pgtype.UUID
	AuthorUserID   pgtype.UUID
	Body           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type CsatRequest struct {
	ConversationID pgtype.UUID
	MailboxID      pgtype.UUID
	TokenHash      []byte
	MessageID      pgtype.UUID
	SentAt         pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	SkippedReason  string
	CreatedAt      pgtype.Timestamptz
}

type CsatResponse struct {
	ConversationID pgtype.UUID
	MailboxID      pgtype.UUID
	Rating         int16
	Comment        string
	TokenHash      []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type CsatSetting struct {
	MailboxID  pgtype.UUID
	Enabled    bool
	DelayHours int32
	EnabledAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type CustomAttributeDef struct {
	ID        pgtype.UUID
	Entity    string
	Key       string
	Label     string
	Type      string
	Options   []string
	CreatedAt pgtype.Timestamptz
}

type CustomRole struct {
	ID          pgtype.UUID
	Name        string
	Description string
	Permissions []string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type DataExport struct {
	ID          pgtype.UUID
	ContactID   pgtype.UUID
	RequestedBy pgtype.UUID
	Status      string
	BlobKey     string
	SizeBytes   int64
	Error       string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

type Draft struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	UserID         pgtype.UUID
	ToAddrs        []byte
	CcAddrs        []byte
	BccAddrs       []byte
	Subject        string
	BodyHtml       string
	AttachmentIds  []pgtype.UUID
	UpdatedAt      pgtype.Timestamptz
}

type ImageProxyCache struct {
	UrlHash     []byte
	BlobKey     string
	ContentType string
	SizeBytes   int64
	FetchedAt   pgtype.Timestamptz
}

type KbArticle struct {
	ID          pgtype.UUID
	CategoryID  pgtype.UUID
	Title       string
	Slug        string
	BodyHtml    string
	BodyText    string
	Excerpt     string
	Status      string
	AuthorID    pgtype.UUID
	UpdatedBy   pgtype.UUID
	Version     int32
	Position    int32
	ViewCount   int64
	HelpfulYes  int32
	HelpfulNo   int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
	Fts         interface{}
}

type KbArticleImage struct {
	ArticleID pgtype.UUID
	ImageID   pgtype.UUID
}

type KbArticleRevision struct {
	ID        pgtype.UUID
	ArticleID pgtype.UUID
	Title     string
	Excerpt   string
	BodyHtml  string
	EditedBy  pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type KbCategory struct {
	ID          pgtype.UUID
	ParentID    pgtype.UUID
	Name        string
	Slug        string
	Description string
	Position    int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type KbImage struct {
	ID          pgtype.UUID
	UploaderID  pgtype.UUID
	Filename    string
	ContentType string
	SizeBytes   int64
	BlobKey     string
	CreatedAt   pgtype.Timestamptz
}

type KbPortal struct {
	Singleton    bool
	Name         string
	Title        string
	Intro        string
	LogoText     string
	CustomDomain string
	UpdatedAt    pgtype.Timestamptz
}

type KbSlugRedirect struct {
	Slug      string
	ArticleID pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Label struct {
	ID          pgtype.UUID
	Name        string
	ColorToken  string
	Description string
	CreatedAt   pgtype.Timestamptz
}

type Macro struct {
	ID          pgtype.UUID
	Name        string
	Scope       string
	OwnerUserID pgtype.UUID
	Actions     []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Mailbox struct {
	ID                 pgtype.UUID
	Name               string
	EmailAddress       string
	DisplayName        string
	Transport          string
	AuthType           string
	ImapHost           string
	ImapPort           int32
	ImapTls            string
	ImapUsername       string
	ImapSecretEnc      []byte
	SmtpHost           string
	SmtpPort           int32
	SmtpTls            string
	SmtpUsername       string
	SmtpSecretEnc      []byte
	OauthTokenEnc      []byte
	OauthExpiresAt     pgtype.Timestamptz
	InboundSecretEnc   []byte
	SentFolder         string
	MarkSeen           bool
	SendDelaySeconds   int32
	SyncState          string
	SyncError          string
	SyncStateChangedAt pgtype.Timestamptz
	LastSyncedAt       pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DisabledAt         pgtype.Timestamptz
	AllowInternalHost  bool
	OauthConnectedAt   pgtype.Timestamptz
	AutoAssignMode     string
	DefaultSlaPolicyID pgtype.UUID
	BusinessHoursID    pgtype.UUID
}

type MailboxAccess struct {
	MailboxID pgtype.UUID
	TeamID    pgtype.UUID
	Level     string
}

type MailboxFolder struct {
	ID           pgtype.UUID
	MailboxID    pgtype.UUID
	Name         string
	Role         string
	Uidvalidity  int64
	LastUid      int64
	LastSyncedAt pgtype.Timestamptz
}

type Mention struct {
	MessageID pgtype.UUID
	UserID    pgtype.UUID
}

type Message struct {
	ID              pgtype.UUID
	ConversationID  pgtype.UUID
	MailboxID       pgtype.UUID
	Kind            string
	Direction       pgtype.Text
	RawMessageID    pgtype.UUID
	RawSha256       []byte
	MessageIDHeader string
	MessageIDHash   []byte
	InReplyTo       string
	ReferencesHdr   []string
	FromAddr        string
	FromName        string
	ToAddrs         []byte
	CcAddrs         []byte
	BccAddrs        []byte
	ReplyTo         []byte
	Subject         string
	SentAt          pgtype.Timestamptz
	ReceivedAt      pgtype.Timestamptz
	BodyText        string
	BodyHtml        string
	AutoSubmitted   bool
	IsBounce        bool
	AuthorUserID    pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	Fts             interface{}
	AuthResults     string
	IsBulk          bool
}

type Notification struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Kind           string
	ConversationID pgtype.UUID
	MessageID      pgtype.UUID
	ActorID        pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	ReadAt         pgtype.Timestamptz
	EmailHandledAt pgtype.Timestamptz
	PushHandledAt  pgtype.Timestamptz
}

type Organization struct {
	ID               pgtype.UUID
	Name             string
	Domains          []string
	Notes            string
	CreatedAt        pgtype.Timestamptz
	CustomAttributes []byte
	CreatedBy        pgtype.UUID
	UpdatedAt        pgtype.Timestamptz
}

type Outbound struct {
	MessageID      pgtype.UUID
	IdempotencyKey pgtype.UUID
	Status         string
	ScheduledAt    pgtype.Timestamptz
	Attempt        int32
	LastAttemptAt  pgtype.Timestamptz
	NextAttemptAt  pgtype.Timestamptz
	SmtpResponse   string
	Error          string
	DsnStatus      string
	SentAt         pgtype.Timestamptz
	CreatedBy      pgtype.UUID
	UpdatedAt      pgtype.Timestamptz
	ExtraHeaders   []byte
}

type PendingBlobDeletion struct {
	BlobKey  string
	QueuedAt pgtype.Timestamptz
}

type PushDevice struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	SessionID  pgtype.UUID
	Kind       string
	Endpoint   string
	P256dh     []byte
	Auth       []byte
	Label      string
	CreatedAt  pgtype.Timestamptz
	LastPushAt pgtype.Timestamptz
}

type PushVapid struct {
	Singleton     bool
	PublicKey     []byte
	PrivateKeyEnc []byte
	CreatedAt     pgtype.Timestamptz
}

type RawMessage struct {
	ID          pgtype.UUID
	MailboxID   pgtype.UUID
	FolderID    pgtype.UUID
	Source      string
	Uidvalidity pgtype.Int8
	Uid         pgtype.Int8
	Sha256      []byte
	SizeBytes   int32
	BlobKey     string
	ReceivedAt  pgtype.Timestamptz
	ParseStatus string
	ParseError  string
	CreatedAt   pgtype.Timestamptz
}

type RecoveryCode struct {
	UserID   pgtype.UUID
	CodeHash []byte
	UsedAt   pgtype.Timestamptz
}

type ReplyStatusChange struct {
	MessageID  pgtype.UUID
	FromStatus string
	ToStatus   string
}

type RetentionPolicy struct {
	MailboxID                pgtype.UUID
	ClosedConversationMonths pgtype.Int4
	AttachmentMonths         pgtype.Int4
	SpamDays                 pgtype.Int4
	UpdatedBy                pgtype.UUID
	UpdatedAt                pgtype.Timestamptz
	TrashDays                pgtype.Int4
}

type Rule struct {
	ID             pgtype.UUID
	Name           string
	MailboxID      pgtype.UUID
	Trigger        string
	IdleHours      pgtype.Int4
	Conditions     []byte
	Actions        []byte
	StopProcessing bool
	Position       int32
	Enabled        bool
	CreatedBy      pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type RuleRun struct {
	ID             pgtype.UUID
	RuleID         pgtype.UUID
	ConversationID pgtype.UUID
	Trigger        string
	Matched        bool
	ActionsApplied []byte
	Error          string
	CreatedAt      pgtype.Timestamptz
}

type SavedView struct {
	ID          pgtype.UUID
	Name        string
	OwnerUserID pgtype.UUID
	TeamID      pgtype.UUID
	CreatedBy   pgtype.UUID
	Filters     []byte
	Sort        string
	Position    int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type SenderImageAllowlist struct {
	ID        pgtype.UUID
	MailboxID pgtype.UUID
	Pattern   string
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	TokenHash     []byte
	CsrfToken     string
	MfaPending    bool
	CreatedAt     pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
	IdleExpiresAt pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	Ip            *netip.Addr
	UserAgent     string
	RevokedAt     pgtype.Timestamptz
	IdpMfa        bool
}

type Setting struct {
	Key       string
	Value     []byte
	UpdatedBy pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

type Signature struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	MailboxID pgtype.UUID
	BodyHtml  string
	UpdatedAt pgtype.Timestamptz
}

type SlaPolicy struct {
	ID                   pgtype.UUID
	Name                 string
	FirstResponseMinutes pgtype.Int4
	ResolutionMinutes    pgtype.Int4
	AtRiskPercent        int32
	BusinessHoursID      pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type SsoSetting struct {
	Singleton                 bool
	Enabled                   bool
	IssuerUrl                 string
	ClientID                  string
	ClientSecretEnc           []byte
	AllowedDomains            []string
	ButtonLabel               string
	Required                  bool
	AutoProvision             bool
	DefaultRole               string
	DefaultCustomRoleID       pgtype.UUID
	TrustIdpMfa               bool
	TrustMissingEmailVerified bool
	AllowInternalIssuer       bool
	UpdatedBy                 pgtype.UUID
	UpdatedAt                 pgtype.Timestamptz
}

type Team struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type TeamMember struct {
	TeamID pgtype.UUID
	UserID pgtype.UUID
}

type Template struct {
	ID          pgtype.UUID
	Name        string
	Shortcode   string
	Scope       string
	OwnerUserID pgtype.UUID
	TeamID      pgtype.UUID
	MailboxID   pgtype.UUID
	Subject     string
	BodyHtml    string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ThreadRef struct {
	MailboxID      pgtype.UUID
	MessageIDHash  []byte
	ConversationID pgtype.UUID
}

type Upload struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Filename    string
	ContentType string
	SizeBytes   int64
	Sha256      []byte
	BlobKey     string
	ContentID   string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

type User struct {
	ID                     pgtype.UUID
	Email                  string
	Name                   string
	Role                   string
	PasswordHash           string
	PasswordChangedAt      pgtype.Timestamptz
	PasswordMustChange     bool
	TotpSecretEnc          []byte
	TotpEnabledAt          pgtype.Timestamptz
	TotpLastStep           int64
	FailedLoginCount       int32
	LockedUntil            pgtype.Timestamptz
	LastLoginAt            pgtype.Timestamptz
	Theme                  string
	DeactivatedAt          pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	TempPasswordExpiresAt  pgtype.Timestamptz
	InvitedAt              pgtype.Timestamptz
	EmailNotifyMentions    bool
	EmailNotifyAssignments bool
	MaxOpen                pgtype.Int4
	Availability           string
	LastAutoAssignedAt     pgtype.Timestamptz
	CustomRoleID           pgtype.UUID
	Permissions            []string
	UnreadSince            pgtype.Timestamptz
	EmailNotifyReplies     bool
	PushNotifyMentions     bool
	PushNotifyAssignments  bool
	PushNotifyReplies      bool
	PushNotifySla          bool
}

type Webhook struct {
	ID                  pgtype.UUID
	Url                 string
	SecretEnc           []byte
	Events              []string
	IncludeContent      bool
	AllowHttp           bool
	Enabled             bool
	DisabledReason      string
	ConsecutiveFailures int32
	CreatedBy           pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type WebhookDelivery struct {
	ID          pgtype.UUID
	WebhookID   pgtype.UUID
	EventID     int64
	Event       string
	PayloadHash []byte
	Status      string
	StatusCode  pgtype.Int4
	Error       string
	DurationMs  pgtype.Int4
	Attempt     int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type WebhookEvent struct {
	ID             int64
	Type           string
	MailboxID      pgtype.UUID
	ConversationID pgtype.UUID
	MessageID      pgtype.UUID
	ContactID      pgtype.UUID
	OccurredAt     pgtype.Timestamptz
	FannedOutAt    pgtype.Timestamptz
}
