// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const connectMailboxOAuth = `-- name: ConnectMailboxOAuth :one
UPDATE mailboxes SET
    auth_type = $1,
    imap_host = $2, imap_port = $3, imap_tls = $4, imap_username = $5,
    smtp_host = $6, smtp_port = $7, smtp_tls = $8, smtp_username = $5,
    imap_secret_enc = NULL, smtp_secret_enc = NULL,
    oauth_token_enc = $9, oauth_expires_at = $10, oauth_connected_at = now(),
    sync_state = 'disabled', sync_error = '', sync_state_changed_at = now(),
    updated_at = now()
WHERE id = $11
RETURNING id, name, email_address, display_name, transport, auth_type, imap_host, imap_port, imap_tls, imap_username, imap_secret_enc, smtp_host, smtp_port, smtp_tls, smtp_username, smtp_secret_enc, oauth_token_enc, oauth_expires_at, inbound_secret_enc, sent_folder, mark_seen, send_delay_seconds, sync_state, sync_error, sync_state_changed_at, last_synced_at, created_at, updated_at, disabled_at, allow_internal_host, oauth_connected_at, auto_assign_mode, default_sla_policy_id, business_hours_id
`

type ConnectMailboxOAuthParams struct {
	AuthType       string
	ImapHost       string
	ImapPort       int32
	ImapTls        string
	EmailAddress   string
	SmtpHost       string
	SmtpPort       int32
	SmtpTls        string
	OauthTokenEnc  []byte
	OauthExpiresAt pgtype.Timestamptz
	ID             pgtype.UUID
}

// The token is encrypted with the row id in its AAD, so a new mailbox gets its token in a
// second statement.
func (q *Queries) ConnectMailboxOAuth(ctx context.Context, arg ConnectMailboxOAuthParams) (Mailbox, error) {
	row := q.db.QueryRow(ctx, connectMailboxOAuth,
		arg.AuthType,
		arg.ImapHost,
		arg.ImapPort,
		arg.ImapTls,
		arg.EmailAddress,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SmtpTls,
		arg.OauthTokenEnc,
		arg.OauthExpiresAt,
		arg.ID,
	)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailAddress,
		&i.DisplayName,
		&i.Transport,
		&i.AuthType,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapTls,
		&i.ImapUsername,
		&i.ImapSecretEnc,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpTls,
		&i.SmtpUsername,
		&i.SmtpSecretEnc,
		&i.OauthTokenEnc,
		&i.OauthExpiresAt,
		&i.InboundSecretEnc,
		&i.SentFolder,
		&i.MarkSeen,
		&i.SendDelaySeconds,
		&i.SyncState,
		&i.SyncError,
		&i.SyncStateChangedAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
		&i.AllowInternalHost,
		&i.OauthConnectedAt,
		&i.AutoAssignMode,
		&i.DefaultSlaPolicyID,
		&i.BusinessHoursID,
	)
	return i, err
}

const getMailboxOAuth = `-- name: GetMailboxOAuth :one
SELECT id, auth_type, oauth_token_enc, oauth_expires_at FROM mailboxes WHERE id = $1
`

type GetMailboxOAuthRow struct {
	ID             pgtype.UUID
	AuthType       string
	OauthTokenEnc  []byte
	OauthExpiresAt pgtype.Timestamptz
}

func (q *Queries) GetMailboxOAuth(ctx context.Context, id pgtype.UUID) (GetMailboxOAuthRow, error) {
	row := q.db.QueryRow(ctx, getMailboxOAuth, id)
	var i GetMailboxOAuthRow
	err := row.Scan(
		&i.ID,
		&i.AuthType,
		&i.OauthTokenEnc,
		&i.OauthExpiresAt,
	)
	return i, err
}

const insertOAuthMailbox = `-- name: InsertOAuthMailbox :one

INSERT INTO mailboxes (
    name, email_address, auth_type,
    imap_host, imap_port, imap_tls, imap_username,
    smtp_host, smtp_port, smtp_tls, smtp_username,
    oauth_token_enc, oauth_expires_at, oauth_connected_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $2,
    $7, $8, $9, $2,
    $10, $11, now()
) RETURNING id, name, email_address, display_name, transport, auth_type, imap_host, imap_port, imap_tls, imap_username, imap_secret_enc, smtp_host, smtp_port, smtp_tls, smtp_username, smtp_secret_enc, oauth_token_enc, oauth_expires_at, inbound_secret_enc, sent_folder, mark_seen, send_delay_seconds, sync_state, sync_error, sync_state_changed_at, last_synced_at, created_at, updated_at, disabled_at, allow_internal_host, oauth_connected_at, auto_assign_mode, default_sla_policy_id, business_hours_id
`

type InsertOAuthMailboxParams struct {
	Name           string
	EmailAddress   string
	AuthType       string
	ImapHost       string
	ImapPort       int32
	ImapTls        string
	SmtpHost       string
	SmtpPort       int32
	SmtpTls        string
	OauthTokenEnc  []byte
	OauthExpiresAt pgtype.Timestamptz
}

// OAuth2 mailboxes (Google Workspace, Microsoft 365).
func (q *Queries) InsertOAuthMailbox(ctx context.Context, arg InsertOAuthMailboxParams) (Mailbox, error) {
	row := q.db.QueryRow(ctx, insertOAuthMailbox,
		arg.Name,
		arg.EmailAddress,
		arg.AuthType,
		arg.ImapHost,
		arg.ImapPort,
		arg.ImapTls,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SmtpTls,
		arg.OauthTokenEnc,
		arg.OauthExpiresAt,
	)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailAddress,
		&i.DisplayName,
		&i.Transport,
		&i.AuthType,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapTls,
		&i.ImapUsername,
		&i.ImapSecretEnc,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpTls,
		&i.SmtpUsername,
		&i.SmtpSecretEnc,
		&i.OauthTokenEnc,
		&i.OauthExpiresAt,
		&i.InboundSecretEnc,
		&i.SentFolder,
		&i.MarkSeen,
		&i.SendDelaySeconds,
		&i.SyncState,
		&i.SyncError,
		&i.SyncStateChangedAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
		&i.AllowInternalHost,
		&i.OauthConnectedAt,
		&i.AutoAssignMode,
		&i.DefaultSlaPolicyID,
		&i.BusinessHoursID,
	)
	return i, err
}

const lockMailboxOAuth = `-- name: LockMailboxOAuth :exec
SELECT pg_advisory_xact_lock(hashtextextended('mailauth:' || $1::text, 0))
`

func (q *Queries) LockMailboxOAuth(ctx context.Context, mailboxID string) error {
	_, err := q.db.Exec(ctx, lockMailboxOAuth, mailboxID)
	return err
}

const markMailboxReauthRequired = `-- name: MarkMailboxReauthRequired :exec
UPDATE mailboxes
SET sync_state = 'auth_failed', sync_error = $1::text,
    sync_state_changed_at = CASE WHEN sync_state = 'auth_failed' THEN sync_state_changed_at ELSE now() END
WHERE id = $2
`

type MarkMailboxReauthRequiredParams struct {
	Reason string
	ID     pgtype.UUID
}

func (q *Queries) MarkMailboxReauthRequired(ctx context.Context, arg MarkMailboxReauthRequiredParams) error {
	_, err := q.db.Exec(ctx, markMailboxReauthRequired, arg.Reason, arg.ID)
	return err
}

const storeRefreshedOAuthToken = `-- name: StoreRefreshedOAuthToken :exec
UPDATE mailboxes SET oauth_token_enc = $1, oauth_expires_at = $2
WHERE id = $3 AND auth_type <> 'password'
`

type StoreRefreshedOAuthTokenParams struct {
	OauthTokenEnc  []byte
	OauthExpiresAt pgtype.Timestamptz
	ID             pgtype.UUID
}

func (q *Queries) StoreRefreshedOAuthToken(ctx context.Context, arg StoreRefreshedOAuthTokenParams) error {
	_, err := q.db.Exec(ctx, storeRefreshedOAuthToken, arg.OauthTokenEnc, arg.OauthExpiresAt, arg.ID)
	return err
}
