// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ops.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingBlobDeletions = `-- name: CountPendingBlobDeletions :one
SELECT count(*)::bigint FROM pending_blob_deletions
`

func (q *Queries) CountPendingBlobDeletions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingBlobDeletions)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const opsReferencedBlobKeys = `-- name: OpsReferencedBlobKeys :many
SELECT k::text FROM unnest($1::text[]) AS k
WHERE EXISTS (SELECT 1 FROM attachments WHERE blob_key = k)
   OR EXISTS (SELECT 1 FROM raw_messages WHERE blob_key = k)
   OR EXISTS (SELECT 1 FROM uploads WHERE blob_key = k)
   OR EXISTS (SELECT 1 FROM image_proxy_cache WHERE blob_key = k)
   OR EXISTS (SELECT 1 FROM contact_imports WHERE source_key = k OR error_key = k)
   OR EXISTS (SELECT 1 FROM data_exports WHERE blob_key = k)
   OR EXISTS (SELECT 1 FROM kb_images WHERE blob_key = k)
   OR EXISTS (SELECT 1 FROM pending_blob_deletions WHERE blob_key = k)
`

// Which of the given keys anything still points at. Keys queued for deletion count as
// referenced: they are on their way out and the drain job owns them.
func (q *Queries) OpsReferencedBlobKeys(ctx context.Context, keys []string) ([]string, error) {
	rows, err := q.db.Query(ctx, opsReferencedBlobKeys, keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var k string
		if err := rows.Scan(&k); err != nil {
			return nil, err
		}
		items = append(items, k)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retentionDeleteAttachments = `-- name: RetentionDeleteAttachments :exec
DELETE FROM attachments WHERE id = ANY ($1::uuid[])
`

func (q *Queries) RetentionDeleteAttachments(ctx context.Context, ids []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, retentionDeleteAttachments, ids)
	return err
}

const retentionDeleteConversations = `-- name: RetentionDeleteConversations :execrows
DELETE FROM conversations WHERE id = ANY ($1::uuid[])
`

func (q *Queries) RetentionDeleteConversations(ctx context.Context, ids []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, retentionDeleteConversations, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retentionDeletePolicies = `-- name: RetentionDeletePolicies :exec
DELETE FROM retention_policies
`

func (q *Queries) RetentionDeletePolicies(ctx context.Context) error {
	_, err := q.db.Exec(ctx, retentionDeletePolicies)
	return err
}

const retentionExpireUploads = `-- name: RetentionExpireUploads :many
DELETE FROM uploads WHERE id IN (
    SELECT id FROM uploads WHERE expires_at < now() ORDER BY expires_at LIMIT $1::integer FOR UPDATE SKIP LOCKED)
RETURNING blob_key
`

// Composer uploads that were never attached and passed their 24 hours. The rows go here; the
// files go through the reference-checked deletion queue, because content-addressed blobs are
// shared.
func (q *Queries) RetentionExpireUploads(ctx context.Context, batchSize int32) ([]string, error) {
	rows, err := q.db.Query(ctx, retentionExpireUploads, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blob_key string
		if err := rows.Scan(&blob_key); err != nil {
			return nil, err
		}
		items = append(items, blob_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retentionInsertPolicy = `-- name: RetentionInsertPolicy :exec
INSERT INTO retention_policies (mailbox_id, closed_conversation_months, attachment_months, spam_days, updated_by)
VALUES ($1, $2, $3, $4, $5)
`

type RetentionInsertPolicyParams struct {
	MailboxID                pgtype.UUID
	ClosedConversationMonths pgtype.Int4
	AttachmentMonths         pgtype.Int4
	SpamDays                 pgtype.Int4
	UpdatedBy                pgtype.UUID
}

func (q *Queries) RetentionInsertPolicy(ctx context.Context, arg RetentionInsertPolicyParams) error {
	_, err := q.db.Exec(ctx, retentionInsertPolicy,
		arg.MailboxID,
		arg.ClosedConversationMonths,
		arg.AttachmentMonths,
		arg.SpamDays,
		arg.UpdatedBy,
	)
	return err
}

const retentionListMailboxIDs = `-- name: RetentionListMailboxIDs :many

SELECT id FROM mailboxes ORDER BY id
`

// Operations: retention purges and upload hygiene.
func (q *Queries) RetentionListMailboxIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, retentionListMailboxIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retentionListPolicies = `-- name: RetentionListPolicies :many
SELECT mailbox_id, closed_conversation_months, attachment_months, spam_days FROM retention_policies
`

type RetentionListPoliciesRow struct {
	MailboxID                pgtype.UUID
	ClosedConversationMonths pgtype.Int4
	AttachmentMonths         pgtype.Int4
	SpamDays                 pgtype.Int4
}

func (q *Queries) RetentionListPolicies(ctx context.Context) ([]RetentionListPoliciesRow, error) {
	rows, err := q.db.Query(ctx, retentionListPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RetentionListPoliciesRow{}
	for rows.Next() {
		var i RetentionListPoliciesRow
		if err := rows.Scan(
			&i.MailboxID,
			&i.ClosedConversationMonths,
			&i.AttachmentMonths,
			&i.SpamDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retentionPickAttachments = `-- name: RetentionPickAttachments :many
SELECT a.id, a.message_id, a.blob_key, a.size_bytes
FROM attachments a JOIN messages m ON m.id = a.message_id
WHERE m.mailbox_id = $1 AND m.received_at < $2::timestamptz
  AND NOT EXISTS (SELECT 1 FROM outbound o WHERE o.message_id = m.id AND o.status IN ('queued', 'sending', 'retry'))
ORDER BY a.id
LIMIT $3::integer
FOR UPDATE OF a SKIP LOCKED
`

type RetentionPickAttachmentsParams struct {
	MailboxID pgtype.UUID
	Before    pgtype.Timestamptz
	BatchSize int32
}

type RetentionPickAttachmentsRow struct {
	ID        pgtype.UUID
	MessageID pgtype.UUID
	BlobKey   string
	SizeBytes int64
}

// Attachments of messages received before the cutoff. A message that is still being sent keeps
// its files, because the send job reads them.
func (q *Queries) RetentionPickAttachments(ctx context.Context, arg RetentionPickAttachmentsParams) ([]RetentionPickAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, retentionPickAttachments, arg.MailboxID, arg.Before, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RetentionPickAttachmentsRow{}
	for rows.Next() {
		var i RetentionPickAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.BlobKey,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retentionPickConversations = `-- name: RetentionPickConversations :many
SELECT c.id FROM conversations c
WHERE c.mailbox_id = $1 AND c.status = $2
  AND GREATEST(c.last_message_at, COALESCE(c.resolved_at, c.last_message_at)) < $3::timestamptz
  AND NOT EXISTS (
      SELECT 1 FROM outbound o JOIN messages m ON m.id = o.message_id
      WHERE m.conversation_id = c.id AND o.status IN ('queued', 'sending', 'retry', 'uncertain'))
ORDER BY c.id
LIMIT $4::integer
FOR UPDATE OF c SKIP LOCKED
`

type RetentionPickConversationsParams struct {
	MailboxID pgtype.UUID
	Status    string
	Before    pgtype.Timestamptz
	BatchSize int32
}

// Conversations of one mailbox in a status whose last activity (last message or, when later,
// the moment they were resolved) is older than the cutoff. Anything with mail still waiting to
// be sent stays. Locked rows are skipped so a purge never waits for an agent.
func (q *Queries) RetentionPickConversations(ctx context.Context, arg RetentionPickConversationsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, retentionPickConversations,
		arg.MailboxID,
		arg.Status,
		arg.Before,
		arg.BatchSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retentionPreviewAttachments = `-- name: RetentionPreviewAttachments :one
SELECT count(*)::bigint AS attachments, COALESCE(sum(a.size_bytes), 0)::bigint AS attachment_bytes
FROM attachments a JOIN messages m ON m.id = a.message_id
WHERE m.mailbox_id = $1 AND m.received_at < $2::timestamptz
  AND NOT EXISTS (SELECT 1 FROM outbound o WHERE o.message_id = m.id AND o.status IN ('queued', 'sending', 'retry'))
`

type RetentionPreviewAttachmentsParams struct {
	MailboxID pgtype.UUID
	Before    pgtype.Timestamptz
}

type RetentionPreviewAttachmentsRow struct {
	Attachments     int64
	AttachmentBytes int64
}

func (q *Queries) RetentionPreviewAttachments(ctx context.Context, arg RetentionPreviewAttachmentsParams) (RetentionPreviewAttachmentsRow, error) {
	row := q.db.QueryRow(ctx, retentionPreviewAttachments, arg.MailboxID, arg.Before)
	var i RetentionPreviewAttachmentsRow
	err := row.Scan(&i.Attachments, &i.AttachmentBytes)
	return i, err
}

const retentionPreviewAudit = `-- name: RetentionPreviewAudit :one
SELECT count(*)::bigint FROM audit_log WHERE at < $1::timestamptz
`

func (q *Queries) RetentionPreviewAudit(ctx context.Context, before pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, retentionPreviewAudit, before)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const retentionPreviewConversations = `-- name: RetentionPreviewConversations :one
WITH picked AS (
    SELECT c.id FROM conversations c
    WHERE c.mailbox_id = $1 AND c.status = $2
      AND GREATEST(c.last_message_at, COALESCE(c.resolved_at, c.last_message_at)) < $3::timestamptz
      AND NOT EXISTS (
          SELECT 1 FROM outbound o JOIN messages m ON m.id = o.message_id
          WHERE m.conversation_id = c.id AND o.status IN ('queued', 'sending', 'retry', 'uncertain'))
)
SELECT (SELECT count(*) FROM picked)::bigint AS conversations,
       (SELECT count(*) FROM messages WHERE conversation_id IN (SELECT id FROM picked))::bigint AS messages,
       (SELECT count(*) FROM attachments a JOIN messages m ON m.id = a.message_id
         WHERE m.conversation_id IN (SELECT id FROM picked))::bigint AS attachments,
       (SELECT COALESCE(sum(a.size_bytes), 0) FROM attachments a JOIN messages m ON m.id = a.message_id
         WHERE m.conversation_id IN (SELECT id FROM picked))::bigint AS attachment_bytes
`

type RetentionPreviewConversationsParams struct {
	MailboxID pgtype.UUID
	Status    string
	Before    pgtype.Timestamptz
}

type RetentionPreviewConversationsRow struct {
	Conversations   int64
	Messages        int64
	Attachments     int64
	AttachmentBytes int64
}

// The counting twin of RetentionPickConversations; keep the predicates identical.
func (q *Queries) RetentionPreviewConversations(ctx context.Context, arg RetentionPreviewConversationsParams) (RetentionPreviewConversationsRow, error) {
	row := q.db.QueryRow(ctx, retentionPreviewConversations, arg.MailboxID, arg.Status, arg.Before)
	var i RetentionPreviewConversationsRow
	err := row.Scan(
		&i.Conversations,
		&i.Messages,
		&i.Attachments,
		&i.AttachmentBytes,
	)
	return i, err
}

const retentionPurgeAuditBatch = `-- name: RetentionPurgeAuditBatch :one
SELECT audit_log_purge(make_interval(months => $1::integer), $2::integer)::integer
`

type RetentionPurgeAuditBatchParams struct {
	Months    int32
	BatchSize int32
}

func (q *Queries) RetentionPurgeAuditBatch(ctx context.Context, arg RetentionPurgeAuditBatchParams) (int32, error) {
	row := q.db.QueryRow(ctx, retentionPurgeAuditBatch, arg.Months, arg.BatchSize)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const retentionRawIDsOfConversations = `-- name: RetentionRawIDsOfConversations :many
SELECT DISTINCT raw_message_id FROM messages
WHERE conversation_id = ANY ($1::uuid[]) AND raw_message_id IS NOT NULL
`

func (q *Queries) RetentionRawIDsOfConversations(ctx context.Context, ids []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, retentionRawIDsOfConversations, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var raw_message_id pgtype.UUID
		if err := rows.Scan(&raw_message_id); err != nil {
			return nil, err
		}
		items = append(items, raw_message_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retentionRawIDsOfMessages = `-- name: RetentionRawIDsOfMessages :many
SELECT DISTINCT raw_message_id FROM messages WHERE id = ANY ($1::uuid[]) AND raw_message_id IS NOT NULL
`

func (q *Queries) RetentionRawIDsOfMessages(ctx context.Context, ids []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, retentionRawIDsOfMessages, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var raw_message_id pgtype.UUID
		if err := rows.Scan(&raw_message_id); err != nil {
			return nil, err
		}
		items = append(items, raw_message_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retentionRefreshHasAttachments = `-- name: RetentionRefreshHasAttachments :exec
UPDATE conversations SET has_attachments = EXISTS (
    SELECT 1 FROM attachments a JOIN messages m ON m.id = a.message_id WHERE m.conversation_id = conversations.id)
WHERE id IN (SELECT conversation_id FROM messages WHERE id = ANY ($1::uuid[]))
`

func (q *Queries) RetentionRefreshHasAttachments(ctx context.Context, messageIds []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, retentionRefreshHasAttachments, messageIds)
	return err
}

const retentionTotalsOfConversations = `-- name: RetentionTotalsOfConversations :one
SELECT (SELECT count(*) FROM messages WHERE conversation_id = ANY ($1::uuid[]))::bigint AS messages,
       (SELECT count(*) FROM attachments a JOIN messages m ON m.id = a.message_id
         WHERE m.conversation_id = ANY ($1::uuid[]))::bigint AS attachments
`

type RetentionTotalsOfConversationsRow struct {
	Messages    int64
	Attachments int64
}

func (q *Queries) RetentionTotalsOfConversations(ctx context.Context, ids []pgtype.UUID) (RetentionTotalsOfConversationsRow, error) {
	row := q.db.QueryRow(ctx, retentionTotalsOfConversations, ids)
	var i RetentionTotalsOfConversationsRow
	err := row.Scan(&i.Messages, &i.Attachments)
	return i, err
}
