// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimWebhookEvents = `-- name: ClaimWebhookEvents :many
SELECT id, type, mailbox_id, conversation_id, message_id, contact_id, occurred_at, fanned_out_at FROM webhook_events
WHERE fanned_out_at IS NULL
ORDER BY id
LIMIT $1::integer
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimWebhookEvents(ctx context.Context, batch int32) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, claimWebhookEvents, batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEvent{}
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.MailboxID,
			&i.ConversationID,
			&i.MessageID,
			&i.ContactID,
			&i.OccurredAt,
			&i.FannedOutAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAPIToken = `-- name: CreateAPIToken :one

INSERT INTO api_tokens (user_id, name, prefix, token_hash, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, prefix, token_hash, scopes, expires_at, last_used_at, created_at, revoked_at
`

type CreateAPITokenParams struct {
	UserID    pgtype.UUID
	Name      string
	Prefix    string
	TokenHash []byte
	Scopes    []string
	ExpiresAt pgtype.Timestamptz
}

// API tokens
func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.TokenHash,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.TokenHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :execrows
DELETE FROM webhooks WHERE id = $1
`

func (q *Queries) DeleteWebhook(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhook, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveAPIToken = `-- name: GetActiveAPIToken :one
SELECT api_tokens.id, api_tokens.user_id, api_tokens.name, api_tokens.prefix, api_tokens.token_hash, api_tokens.scopes, api_tokens.expires_at, api_tokens.last_used_at, api_tokens.created_at, api_tokens.revoked_at, users.id, users.email, users.name, users.role, users.password_hash, users.password_changed_at, users.password_must_change, users.totp_secret_enc, users.totp_enabled_at, users.totp_last_step, users.failed_login_count, users.locked_until, users.last_login_at, users.theme, users.deactivated_at, users.created_at, users.updated_at, users.temp_password_expires_at, users.invited_at, users.email_notify_mentions, users.email_notify_assignments, users.max_open, users.availability, users.last_auto_assigned_at, users.custom_role_id, users.permissions, users.unread_since, users.email_notify_replies, users.push_notify_mentions, users.push_notify_assignments, users.push_notify_replies, users.push_notify_sla
FROM api_tokens
JOIN users ON users.id = api_tokens.user_id
WHERE api_tokens.token_hash = $1
  AND api_tokens.revoked_at IS NULL
  AND (api_tokens.expires_at IS NULL OR api_tokens.expires_at > now())
  AND users.deactivated_at IS NULL
`

type GetActiveAPITokenRow struct {
	ApiToken ApiToken
	User     User
}

func (q *Queries) GetActiveAPIToken(ctx context.Context, tokenHash []byte) (GetActiveAPITokenRow, error) {
	row := q.db.QueryRow(ctx, getActiveAPIToken, tokenHash)
	var i GetActiveAPITokenRow
	err := row.Scan(
		&i.ApiToken.ID,
		&i.ApiToken.UserID,
		&i.ApiToken.Name,
		&i.ApiToken.Prefix,
		&i.ApiToken.TokenHash,
		&i.ApiToken.Scopes,
		&i.ApiToken.ExpiresAt,
		&i.ApiToken.LastUsedAt,
		&i.ApiToken.CreatedAt,
		&i.ApiToken.RevokedAt,
		&i.User.ID,
		&i.User.Email,
		&i.User.Name,
		&i.User.Role,
		&i.User.PasswordHash,
		&i.User.PasswordChangedAt,
		&i.User.PasswordMustChange,
		&i.User.TotpSecretEnc,
		&i.User.TotpEnabledAt,
		&i.User.TotpLastStep,
		&i.User.FailedLoginCount,
		&i.User.LockedUntil,
		&i.User.LastLoginAt,
		&i.User.Theme,
		&i.User.DeactivatedAt,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.TempPasswordExpiresAt,
		&i.User.InvitedAt,
		&i.User.EmailNotifyMentions,
		&i.User.EmailNotifyAssignments,
		&i.User.MaxOpen,
		&i.User.Availability,
		&i.User.LastAutoAssignedAt,
		&i.User.CustomRoleID,
		&i.User.Permissions,
		&i.User.UnreadSince,
		&i.User.EmailNotifyReplies,
		&i.User.PushNotifyMentions,
		&i.User.PushNotifyAssignments,
		&i.User.PushNotifyReplies,
		&i.User.PushNotifySla,
	)
	return i, err
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, url, secret_enc, events, include_content, allow_http, enabled, disabled_reason, consecutive_failures, created_by, created_at, updated_at FROM webhooks WHERE id = $1
`

func (q *Queries) GetWebhook(ctx context.Context, id pgtype.UUID) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhook, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.SecretEnc,
		&i.Events,
		&i.IncludeContent,
		&i.AllowHttp,
		&i.Enabled,
		&i.DisabledReason,
		&i.ConsecutiveFailures,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT id, webhook_id, event_id, event, payload_hash, status, status_code, error, duration_ms, attempt, created_at, updated_at FROM webhook_deliveries WHERE id = $1
`

func (q *Queries) GetWebhookDelivery(ctx context.Context, id pgtype.UUID) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDelivery, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventID,
		&i.Event,
		&i.PayloadHash,
		&i.Status,
		&i.StatusCode,
		&i.Error,
		&i.DurationMs,
		&i.Attempt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookEvent = `-- name: GetWebhookEvent :one
SELECT id, type, mailbox_id, conversation_id, message_id, contact_id, occurred_at, fanned_out_at FROM webhook_events WHERE id = $1
`

func (q *Queries) GetWebhookEvent(ctx context.Context, id int64) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, getWebhookEvent, id)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.MailboxID,
		&i.ConversationID,
		&i.MessageID,
		&i.ContactID,
		&i.OccurredAt,
		&i.FannedOutAt,
	)
	return i, err
}

const insertTestWebhookEvent = `-- name: InsertTestWebhookEvent :one
INSERT INTO webhook_events (type, fanned_out_at) VALUES ('webhook.test', now())
RETURNING id
`

func (q *Queries) InsertTestWebhookEvent(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, insertTestWebhookEvent)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertWebhook = `-- name: InsertWebhook :one

INSERT INTO webhooks (id, url, secret_enc, events, include_content, allow_http, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, url, secret_enc, events, include_content, allow_http, enabled, disabled_reason, consecutive_failures, created_by, created_at, updated_at
`

type InsertWebhookParams struct {
	ID             pgtype.UUID
	Url            string
	SecretEnc      []byte
	Events         []string
	IncludeContent bool
	AllowHttp      bool
	CreatedBy      pgtype.UUID
}

// Webhooks
func (q *Queries) InsertWebhook(ctx context.Context, arg InsertWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, insertWebhook,
		arg.ID,
		arg.Url,
		arg.SecretEnc,
		arg.Events,
		arg.IncludeContent,
		arg.AllowHttp,
		arg.CreatedBy,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.SecretEnc,
		&i.Events,
		&i.IncludeContent,
		&i.AllowHttp,
		&i.Enabled,
		&i.DisabledReason,
		&i.ConsecutiveFailures,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :one
INSERT INTO webhook_deliveries (webhook_id, event_id, event)
VALUES ($1, $2, $3)
RETURNING id, webhook_id, event_id, event, payload_hash, status, status_code, error, duration_ms, attempt, created_at, updated_at
`

type InsertWebhookDeliveryParams struct {
	WebhookID pgtype.UUID
	EventID   int64
	Event     string
}

func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, insertWebhookDelivery, arg.WebhookID, arg.EventID, arg.Event)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventID,
		&i.Event,
		&i.PayloadHash,
		&i.Status,
		&i.StatusCode,
		&i.Error,
		&i.DurationMs,
		&i.Attempt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllAPITokens = `-- name: ListAllAPITokens :many
SELECT api_tokens.id, api_tokens.user_id, api_tokens.name, api_tokens.prefix, api_tokens.token_hash, api_tokens.scopes, api_tokens.expires_at, api_tokens.last_used_at, api_tokens.created_at, api_tokens.revoked_at, users.name AS user_name, users.email AS user_email
FROM api_tokens
JOIN users ON users.id = api_tokens.user_id
WHERE api_tokens.revoked_at IS NULL
ORDER BY api_tokens.created_at DESC, api_tokens.id DESC
`

type ListAllAPITokensRow struct {
	ApiToken  ApiToken
	UserName  string
	UserEmail string
}

func (q *Queries) ListAllAPITokens(ctx context.Context) ([]ListAllAPITokensRow, error) {
	rows, err := q.db.Query(ctx, listAllAPITokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllAPITokensRow{}
	for rows.Next() {
		var i ListAllAPITokensRow
		if err := rows.Scan(
			&i.ApiToken.ID,
			&i.ApiToken.UserID,
			&i.ApiToken.Name,
			&i.ApiToken.Prefix,
			&i.ApiToken.TokenHash,
			&i.ApiToken.Scopes,
			&i.ApiToken.ExpiresAt,
			&i.ApiToken.LastUsedAt,
			&i.ApiToken.CreatedAt,
			&i.ApiToken.RevokedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemRawMessages = `-- name: ListProblemRawMessages :many

SELECT raw_messages.id, raw_messages.mailbox_id, mailboxes.name AS mailbox_name,
       raw_messages.parse_status, raw_messages.parse_error, raw_messages.size_bytes, raw_messages.received_at
FROM raw_messages
JOIN mailboxes ON mailboxes.id = raw_messages.mailbox_id
WHERE raw_messages.parse_status IN ('failed', 'skipped')
ORDER BY raw_messages.received_at DESC, raw_messages.id DESC
LIMIT 100
`

type ListProblemRawMessagesRow struct {
	ID          pgtype.UUID
	MailboxID   pgtype.UUID
	MailboxName string
	ParseStatus string
	ParseError  string
	SizeBytes   int32
	ReceivedAt  pgtype.Timestamptz
}

// Admin job viewer
func (q *Queries) ListProblemRawMessages(ctx context.Context) ([]ListProblemRawMessagesRow, error) {
	rows, err := q.db.Query(ctx, listProblemRawMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProblemRawMessagesRow{}
	for rows.Next() {
		var i ListProblemRawMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.MailboxID,
			&i.MailboxName,
			&i.ParseStatus,
			&i.ParseError,
			&i.SizeBytes,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscribedWebhookIDs = `-- name: ListSubscribedWebhookIDs :many
SELECT id FROM webhooks WHERE enabled AND $1::text = ANY (events)
`

func (q *Queries) ListSubscribedWebhookIDs(ctx context.Context, event string) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listSubscribedWebhookIDs, event)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAPITokens = `-- name: ListUserAPITokens :many
SELECT id, user_id, name, prefix, token_hash, scopes, expires_at, last_used_at, created_at, revoked_at FROM api_tokens
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListUserAPITokens(ctx context.Context, userID pgtype.UUID) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listUserAPITokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.TokenHash,
			&i.Scopes,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, webhook_id, event_id, event, payload_hash, status, status_code, error, duration_ms, attempt, created_at, updated_at FROM webhook_deliveries
WHERE webhook_id = $1
  AND ($2::uuid IS NULL OR id < $2::uuid)
ORDER BY id DESC
LIMIT $3::integer
`

type ListWebhookDeliveriesParams struct {
	WebhookID pgtype.UUID
	BeforeID  pgtype.UUID
	PageSize  int32
}

// Keyset pagination on the time-ordered UUID: pass a NULL before_id for the first page.
func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries, arg.WebhookID, arg.BeforeID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventID,
			&i.Event,
			&i.PayloadHash,
			&i.Status,
			&i.StatusCode,
			&i.Error,
			&i.DurationMs,
			&i.Attempt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, url, secret_enc, events, include_content, allow_http, enabled, disabled_reason, consecutive_failures, created_by, created_at, updated_at FROM webhooks ORDER BY created_at, id
`

func (q *Queries) ListWebhooks(ctx context.Context) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.SecretEnc,
			&i.Events,
			&i.IncludeContent,
			&i.AllowHttp,
			&i.Enabled,
			&i.DisabledReason,
			&i.ConsecutiveFailures,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookEventFannedOut = `-- name: MarkWebhookEventFannedOut :exec
UPDATE webhook_events SET fanned_out_at = now() WHERE id = $1
`

func (q *Queries) MarkWebhookEventFannedOut(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markWebhookEventFannedOut, id)
	return err
}

const newUUID = `-- name: NewUUID :one
SELECT uuidv7()::uuid
`

func (q *Queries) NewUUID(ctx context.Context) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, newUUID)
	var column_1 pgtype.UUID
	err := row.Scan(&column_1)
	return column_1, err
}

const purgeWebhookDeliveries = `-- name: PurgeWebhookDeliveries :execrows
DELETE FROM webhook_deliveries WHERE created_at < $1
`

func (q *Queries) PurgeWebhookDeliveries(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, purgeWebhookDeliveries, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeWebhookEvents = `-- name: PurgeWebhookEvents :execrows
DELETE FROM webhook_events WHERE occurred_at < $1 AND fanned_out_at IS NOT NULL
`

func (q *Queries) PurgeWebhookEvents(ctx context.Context, occurredAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, purgeWebhookEvents, occurredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordWebhookEvent = `-- name: RecordWebhookEvent :exec
INSERT INTO webhook_events (type, mailbox_id, conversation_id, message_id, contact_id)
SELECT $1::text, $2::uuid, $3::uuid,
       $4::uuid, $5::uuid
WHERE EXISTS (SELECT 1 FROM webhooks WHERE enabled AND $1::text = ANY (events))
`

type RecordWebhookEventParams struct {
	Type           string
	MailboxID      pgtype.UUID
	ConversationID pgtype.UUID
	MessageID      pgtype.UUID
	ContactID      pgtype.UUID
}

// Only records an event somebody would receive; without subscribers the outbox stays empty.
func (q *Queries) RecordWebhookEvent(ctx context.Context, arg RecordWebhookEventParams) error {
	_, err := q.db.Exec(ctx, recordWebhookEvent,
		arg.Type,
		arg.MailboxID,
		arg.ConversationID,
		arg.MessageID,
		arg.ContactID,
	)
	return err
}

const recordWebhookFailure = `-- name: RecordWebhookFailure :one
UPDATE webhooks SET
    consecutive_failures = consecutive_failures + 1,
    enabled = enabled AND consecutive_failures + 1 < $1::integer,
    disabled_reason = CASE
        WHEN enabled AND consecutive_failures + 1 >= $1::integer THEN 'too_many_failures'
        ELSE disabled_reason END,
    updated_at = now()
WHERE id = $2
RETURNING id, url, secret_enc, events, include_content, allow_http, enabled, disabled_reason, consecutive_failures, created_by, created_at, updated_at
`

type RecordWebhookFailureParams struct {
	Threshold int32
	ID        pgtype.UUID
}

func (q *Queries) RecordWebhookFailure(ctx context.Context, arg RecordWebhookFailureParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, recordWebhookFailure, arg.Threshold, arg.ID)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.SecretEnc,
		&i.Events,
		&i.IncludeContent,
		&i.AllowHttp,
		&i.Enabled,
		&i.DisabledReason,
		&i.ConsecutiveFailures,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordWebhookSuccess = `-- name: RecordWebhookSuccess :exec
UPDATE webhooks SET consecutive_failures = 0 WHERE id = $1 AND consecutive_failures <> 0
`

func (q *Queries) RecordWebhookSuccess(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, recordWebhookSuccess, id)
	return err
}

const resetRawMessage = `-- name: ResetRawMessage :execrows
UPDATE raw_messages SET parse_status = 'pending', parse_error = ''
WHERE id = $1 AND parse_status IN ('failed', 'skipped')
`

func (q *Queries) ResetRawMessage(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, resetRawMessage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :one
UPDATE api_tokens SET revoked_at = now()
WHERE id = $1
  AND revoked_at IS NULL
  AND ($2::uuid IS NULL OR user_id = $2::uuid)
RETURNING id, user_id, name, prefix, token_hash, scopes, expires_at, last_used_at, created_at, revoked_at
`

type RevokeAPITokenParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// Pass user_id to restrict revocation to the token's owner; leave it NULL for admins.
func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, revokeAPIToken, arg.ID, arg.UserID)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.TokenHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const setWebhookDeliveryResult = `-- name: SetWebhookDeliveryResult :exec
UPDATE webhook_deliveries SET
    status = $2, status_code = $3, error = $4, duration_ms = $5, attempt = $6,
    payload_hash = COALESCE($7, payload_hash), updated_at = now()
WHERE id = $1
`

type SetWebhookDeliveryResultParams struct {
	ID          pgtype.UUID
	Status      string
	StatusCode  pgtype.Int4
	Error       string
	DurationMs  pgtype.Int4
	Attempt     int32
	PayloadHash []byte
}

func (q *Queries) SetWebhookDeliveryResult(ctx context.Context, arg SetWebhookDeliveryResultParams) error {
	_, err := q.db.Exec(ctx, setWebhookDeliveryResult,
		arg.ID,
		arg.Status,
		arg.StatusCode,
		arg.Error,
		arg.DurationMs,
		arg.Attempt,
		arg.PayloadHash,
	)
	return err
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIToken, id)
	return err
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks SET
    url = $2, events = $3, include_content = $4, allow_http = $5, enabled = $6,
    disabled_reason = CASE WHEN $6 THEN '' ELSE disabled_reason END,
    consecutive_failures = CASE WHEN $6 AND NOT enabled THEN 0 ELSE consecutive_failures END,
    updated_at = now()
WHERE id = $1
RETURNING id, url, secret_enc, events, include_content, allow_http, enabled, disabled_reason, consecutive_failures, created_by, created_at, updated_at
`

type UpdateWebhookParams struct {
	ID             pgtype.UUID
	Url            string
	Events         []string
	IncludeContent bool
	AllowHttp      bool
	Enabled        bool
}

// Re-enabling clears the failure streak, so a fixed receiver gets a fresh budget.
func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, updateWebhook,
		arg.ID,
		arg.Url,
		arg.Events,
		arg.IncludeContent,
		arg.AllowHttp,
		arg.Enabled,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.SecretEnc,
		&i.Events,
		&i.IncludeContent,
		&i.AllowHttp,
		&i.Enabled,
		&i.DisabledReason,
		&i.ConsecutiveFailures,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const webhookContact = `-- name: WebhookContact :one
SELECT contacts.id, contacts.name,
       COALESCE((SELECT email FROM contact_addresses WHERE contact_id = contacts.id
                 ORDER BY is_primary DESC, email LIMIT 1), '')::text AS email
FROM contacts WHERE contacts.id = $1
`

type WebhookContactRow struct {
	ID    pgtype.UUID
	Name  string
	Email string
}

func (q *Queries) WebhookContact(ctx context.Context, id pgtype.UUID) (WebhookContactRow, error) {
	row := q.db.QueryRow(ctx, webhookContact, id)
	var i WebhookContactRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const webhookConversation = `-- name: WebhookConversation :one

SELECT id, number, mailbox_id, status, assignee_user_id, subject, (deleted_at IS NOT NULL)::boolean AS deleted FROM conversations WHERE id = $1
`

type WebhookConversationRow struct {
	ID             pgtype.UUID
	Number         int64
	MailboxID      pgtype.UUID
	Status         string
	AssigneeUserID pgtype.UUID
	Subject        string
	Deleted        bool
}

// Payload sources, read at delivery time.
func (q *Queries) WebhookConversation(ctx context.Context, id pgtype.UUID) (WebhookConversationRow, error) {
	row := q.db.QueryRow(ctx, webhookConversation, id)
	var i WebhookConversationRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.MailboxID,
		&i.Status,
		&i.AssigneeUserID,
		&i.Subject,
		&i.Deleted,
	)
	return i, err
}

const webhookMessage = `-- name: WebhookMessage :one
SELECT id, conversation_id, mailbox_id, kind, direction, subject, left(body_text, 2000)::text AS body_text
FROM messages WHERE id = $1
`

type WebhookMessageRow struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	MailboxID      pgtype.UUID
	Kind           string
	Direction      pgtype.Text
	Subject        string
	BodyText       string
}

func (q *Queries) WebhookMessage(ctx context.Context, id pgtype.UUID) (WebhookMessageRow, error) {
	row := q.db.QueryRow(ctx, webhookMessage, id)
	var i WebhookMessageRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.MailboxID,
		&i.Kind,
		&i.Direction,
		&i.Subject,
		&i.BodyText,
	)
	return i, err
}
