// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const pushClaimNotifications = `-- name: PushClaimNotifications :many
SELECT n.id, n.kind, n.user_id, n.conversation_id, c.mailbox_id AS conversation_mailbox_id,
       c.number AS conversation_number, c.subject AS conversation_subject,
       (c.deleted_at IS NOT NULL)::boolean AS conversation_deleted,
       u.deactivated_at AS recipient_deactivated_at,
       u.push_notify_mentions, u.push_notify_assignments, u.push_notify_replies, u.push_notify_sla,
       actor.name AS actor_name
FROM notifications n
JOIN users u ON u.id = n.user_id
JOIN conversations c ON c.id = n.conversation_id
LEFT JOIN users actor ON actor.id = n.actor_id
WHERE n.push_handled_at IS NULL
ORDER BY n.created_at, n.id
LIMIT 100
FOR UPDATE OF n
`

type PushClaimNotificationsRow struct {
	ID                     pgtype.UUID
	Kind                   string
	UserID                 pgtype.UUID
	ConversationID         pgtype.UUID
	ConversationMailboxID  pgtype.UUID
	ConversationNumber     int64
	ConversationSubject    string
	ConversationDeleted    bool
	RecipientDeactivatedAt pgtype.Timestamptz
	PushNotifyMentions     bool
	PushNotifyAssignments  bool
	PushNotifyReplies      bool
	PushNotifySla          bool
	ActorName              pgtype.Text
}

// Notifications to push, with what the message needs. Hidden conversations and deactivated
// users are claimed too, so they leave the queue, and skipped by the caller. The lock waits
// instead of skipping: the notification mail claims the same rows for a moment, and skipping
// would delay the push until the next sweep.
func (q *Queries) PushClaimNotifications(ctx context.Context) ([]PushClaimNotificationsRow, error) {
	rows, err := q.db.Query(ctx, pushClaimNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushClaimNotificationsRow{}
	for rows.Next() {
		var i PushClaimNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.UserID,
			&i.ConversationID,
			&i.ConversationMailboxID,
			&i.ConversationNumber,
			&i.ConversationSubject,
			&i.ConversationDeleted,
			&i.RecipientDeactivatedAt,
			&i.PushNotifyMentions,
			&i.PushNotifyAssignments,
			&i.PushNotifyReplies,
			&i.PushNotifySla,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pushDeleteDevice = `-- name: PushDeleteDevice :execrows
DELETE FROM push_devices WHERE id = $1 AND user_id = $2
`

type PushDeleteDeviceParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) PushDeleteDevice(ctx context.Context, arg PushDeleteDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, pushDeleteDevice, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pushDeleteDeviceByEndpoint = `-- name: PushDeleteDeviceByEndpoint :execrows
DELETE FROM push_devices WHERE user_id = $1 AND kind = $2 AND endpoint = $3
`

type PushDeleteDeviceByEndpointParams struct {
	UserID   pgtype.UUID
	Kind     string
	Endpoint string
}

func (q *Queries) PushDeleteDeviceByEndpoint(ctx context.Context, arg PushDeleteDeviceByEndpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, pushDeleteDeviceByEndpoint, arg.UserID, arg.Kind, arg.Endpoint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pushDevicesOfUsers = `-- name: PushDevicesOfUsers :many
SELECT id, user_id, kind, endpoint, p256dh, auth
FROM push_devices WHERE user_id = ANY($1::uuid[])
`

type PushDevicesOfUsersRow struct {
	ID       pgtype.UUID
	UserID   pgtype.UUID
	Kind     string
	Endpoint string
	P256dh   []byte
	Auth     []byte
}

func (q *Queries) PushDevicesOfUsers(ctx context.Context, userIds []pgtype.UUID) ([]PushDevicesOfUsersRow, error) {
	rows, err := q.db.Query(ctx, pushDevicesOfUsers, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushDevicesOfUsersRow{}
	for rows.Next() {
		var i PushDevicesOfUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pushDropDevice = `-- name: PushDropDevice :exec
DELETE FROM push_devices WHERE id = $1
`

// A push service said the device is gone for good.
func (q *Queries) PushDropDevice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, pushDropDevice, id)
	return err
}

const pushExpireStale = `-- name: PushExpireStale :execrows
UPDATE notifications SET push_handled_at = now()
WHERE push_handled_at IS NULL AND created_at < now() - interval '30 minutes'
`

// A notification that waited this long is no longer worth a push (the dispatcher was down).
func (q *Queries) PushExpireStale(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pushExpireStale)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pushGetVapid = `-- name: PushGetVapid :one
SELECT public_key, private_key_enc FROM push_vapid
`

type PushGetVapidRow struct {
	PublicKey     []byte
	PrivateKeyEnc []byte
}

func (q *Queries) PushGetVapid(ctx context.Context) (PushGetVapidRow, error) {
	row := q.db.QueryRow(ctx, pushGetVapid)
	var i PushGetVapidRow
	err := row.Scan(&i.PublicKey, &i.PrivateKeyEnc)
	return i, err
}

const pushInsertVapid = `-- name: PushInsertVapid :exec
INSERT INTO push_vapid (public_key, private_key_enc) VALUES ($1, $2)
ON CONFLICT (singleton) DO NOTHING
`

type PushInsertVapidParams struct {
	PublicKey     []byte
	PrivateKeyEnc []byte
}

// Two instances starting at once both try; the first one wins and the other reads it back.
func (q *Queries) PushInsertVapid(ctx context.Context, arg PushInsertVapidParams) error {
	_, err := q.db.Exec(ctx, pushInsertVapid, arg.PublicKey, arg.PrivateKeyEnc)
	return err
}

const pushListDevices = `-- name: PushListDevices :many
SELECT id, kind, label, created_at, last_push_at, session_id
FROM push_devices WHERE user_id = $1
ORDER BY created_at DESC, id
`

type PushListDevicesRow struct {
	ID         pgtype.UUID
	Kind       string
	Label      string
	CreatedAt  pgtype.Timestamptz
	LastPushAt pgtype.Timestamptz
	SessionID  pgtype.UUID
}

func (q *Queries) PushListDevices(ctx context.Context, userID pgtype.UUID) ([]PushListDevicesRow, error) {
	rows, err := q.db.Query(ctx, pushListDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushListDevicesRow{}
	for rows.Next() {
		var i PushListDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Label,
			&i.CreatedAt,
			&i.LastPushAt,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pushMarkHandled = `-- name: PushMarkHandled :exec
UPDATE notifications SET push_handled_at = now() WHERE id = ANY($1::uuid[])
`

func (q *Queries) PushMarkHandled(ctx context.Context, ids []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, pushMarkHandled, ids)
	return err
}

const pushSetPrefs = `-- name: PushSetPrefs :exec
UPDATE users SET push_notify_mentions = $1, push_notify_assignments = $2,
    push_notify_replies = $3, push_notify_sla = $4
WHERE id = $5
`

type PushSetPrefsParams struct {
	Mentions    bool
	Assignments bool
	Replies     bool
	Sla         bool
	ID          pgtype.UUID
}

func (q *Queries) PushSetPrefs(ctx context.Context, arg PushSetPrefsParams) error {
	_, err := q.db.Exec(ctx, pushSetPrefs,
		arg.Mentions,
		arg.Assignments,
		arg.Replies,
		arg.Sla,
		arg.ID,
	)
	return err
}

const pushTouchDevices = `-- name: PushTouchDevices :exec
UPDATE push_devices SET last_push_at = now() WHERE id = ANY($1::uuid[])
`

func (q *Queries) PushTouchDevices(ctx context.Context, ids []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, pushTouchDevices, ids)
	return err
}

const pushUpsertDevice = `-- name: PushUpsertDevice :one

INSERT INTO push_devices (user_id, session_id, kind, endpoint, p256dh, auth, label)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (kind, endpoint) DO UPDATE SET
    id = CASE WHEN push_devices.user_id = EXCLUDED.user_id THEN push_devices.id ELSE uuidv7() END,
    user_id = EXCLUDED.user_id, session_id = EXCLUDED.session_id, p256dh = EXCLUDED.p256dh,
    auth = EXCLUDED.auth, label = EXCLUDED.label, created_at = now()
RETURNING id, kind, label, created_at, last_push_at
`

type PushUpsertDeviceParams struct {
	UserID    pgtype.UUID
	SessionID pgtype.UUID
	Kind      string
	Endpoint  string
	P256dh    []byte
	Auth      []byte
	Label     string
}

type PushUpsertDeviceRow struct {
	ID         pgtype.UUID
	Kind       string
	Label      string
	CreatedAt  pgtype.Timestamptz
	LastPushAt pgtype.Timestamptz
}

// Push notifications: devices, the VAPID key and the dispatch queue.
// Registering the same endpoint again (the browser renewed its keys, or another user signed in
// on the device) moves it to the current user and session. A device that changes hands gets a
// new id, so a push or a "gone" answer meant for the previous user cannot touch it.
func (q *Queries) PushUpsertDevice(ctx context.Context, arg PushUpsertDeviceParams) (PushUpsertDeviceRow, error) {
	row := q.db.QueryRow(ctx, pushUpsertDevice,
		arg.UserID,
		arg.SessionID,
		arg.Kind,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.Label,
	)
	var i PushUpsertDeviceRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Label,
		&i.CreatedAt,
		&i.LastPushAt,
	)
	return i, err
}

const pushUsers = `-- name: PushUsers :many
SELECT id, email, name, role, password_hash, password_changed_at, password_must_change, totp_secret_enc, totp_enabled_at, totp_last_step, failed_login_count, locked_until, last_login_at, theme, deactivated_at, created_at, updated_at, temp_password_expires_at, invited_at, email_notify_mentions, email_notify_assignments, max_open, availability, last_auto_assigned_at, custom_role_id, permissions, unread_since, email_notify_replies, push_notify_mentions, push_notify_assignments, push_notify_replies, push_notify_sla FROM users WHERE id = ANY($1::uuid[])
`

func (q *Queries) PushUsers(ctx context.Context, ids []pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, pushUsers, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.PasswordHash,
			&i.PasswordChangedAt,
			&i.PasswordMustChange,
			&i.TotpSecretEnc,
			&i.TotpEnabledAt,
			&i.TotpLastStep,
			&i.FailedLoginCount,
			&i.LockedUntil,
			&i.LastLoginAt,
			&i.Theme,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TempPasswordExpiresAt,
			&i.InvitedAt,
			&i.EmailNotifyMentions,
			&i.EmailNotifyAssignments,
			&i.MaxOpen,
			&i.Availability,
			&i.LastAutoAssignedAt,
			&i.CustomRoleID,
			&i.Permissions,
			&i.UnreadSince,
			&i.EmailNotifyReplies,
			&i.PushNotifyMentions,
			&i.PushNotifyAssignments,
			&i.PushNotifyReplies,
			&i.PushNotifySla,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
