// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: realtime.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const realtimeConversationMailbox = `-- name: RealtimeConversationMailbox :one
SELECT mailbox_id FROM conversations
WHERE id = $1 AND deleted_at IS NULL AND mailbox_id = ANY($2::uuid[])
`

type RealtimeConversationMailboxParams struct {
	ID         pgtype.UUID
	MailboxIds []pgtype.UUID
}

// The mailbox filter is what keeps presence from confirming that a hidden conversation exists.
func (q *Queries) RealtimeConversationMailbox(ctx context.Context, arg RealtimeConversationMailboxParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, realtimeConversationMailbox, arg.ID, arg.MailboxIds)
	var mailbox_id pgtype.UUID
	err := row.Scan(&mailbox_id)
	return mailbox_id, err
}

const realtimeMessageRef = `-- name: RealtimeMessageRef :one
SELECT conversation_id, mailbox_id FROM messages WHERE id = $1
`

type RealtimeMessageRefRow struct {
	ConversationID pgtype.UUID
	MailboxID      pgtype.UUID
}

func (q *Queries) RealtimeMessageRef(ctx context.Context, id pgtype.UUID) (RealtimeMessageRefRow, error) {
	row := q.db.QueryRow(ctx, realtimeMessageRef, id)
	var i RealtimeMessageRefRow
	err := row.Scan(&i.ConversationID, &i.MailboxID)
	return i, err
}

const realtimeNotify = `-- name: RealtimeNotify :exec
SELECT pg_notify('echoo_events', $1::text)
`

func (q *Queries) RealtimeNotify(ctx context.Context, payload string) error {
	_, err := q.db.Exec(ctx, realtimeNotify, payload)
	return err
}
