// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomRole = `-- name: CreateCustomRole :one
INSERT INTO custom_roles (name, description, permissions) VALUES ($1, $2, $3) RETURNING id, name, description, permissions, created_at, updated_at
`

type CreateCustomRoleParams struct {
	Name        string
	Description string
	Permissions []string
}

func (q *Queries) CreateCustomRole(ctx context.Context, arg CreateCustomRoleParams) (CustomRole, error) {
	row := q.db.QueryRow(ctx, createCustomRole, arg.Name, arg.Description, arg.Permissions)
	var i CustomRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomRole = `-- name: DeleteCustomRole :execrows
DELETE FROM custom_roles WHERE id = $1
`

// Fails on the foreign keys while users or the SSO default still use the role.
func (q *Queries) DeleteCustomRole(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCustomRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCustomRole = `-- name: GetCustomRole :one
SELECT id, name, description, permissions, created_at, updated_at FROM custom_roles WHERE id = $1
`

func (q *Queries) GetCustomRole(ctx context.Context, id pgtype.UUID) (CustomRole, error) {
	row := q.db.QueryRow(ctx, getCustomRole, id)
	var i CustomRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomRoleForShare = `-- name: GetCustomRoleForShare :one
SELECT id, name, description, permissions, created_at, updated_at FROM custom_roles WHERE id = $1 FOR SHARE
`

// Held for the length of a transaction that hands the role to someone, so a concurrent edit of
// its permissions cannot leave the copy on the user behind.
func (q *Queries) GetCustomRoleForShare(ctx context.Context, id pgtype.UUID) (CustomRole, error) {
	row := q.db.QueryRow(ctx, getCustomRoleForShare, id)
	var i CustomRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomRoleForUpdate = `-- name: GetCustomRoleForUpdate :one
SELECT id, name, description, permissions, created_at, updated_at FROM custom_roles WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetCustomRoleForUpdate(ctx context.Context, id pgtype.UUID) (CustomRole, error) {
	row := q.db.QueryRow(ctx, getCustomRoleForUpdate, id)
	var i CustomRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomRoles = `-- name: ListCustomRoles :many
SELECT custom_roles.id, custom_roles.name, custom_roles.description, custom_roles.permissions, custom_roles.created_at, custom_roles.updated_at,
    (SELECT count(*) FROM users WHERE users.custom_role_id = custom_roles.id)::integer AS member_count
FROM custom_roles
ORDER BY lower(custom_roles.name), custom_roles.id
`

type ListCustomRolesRow struct {
	ID          pgtype.UUID
	Name        string
	Description string
	Permissions []string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	MemberCount int32
}

func (q *Queries) ListCustomRoles(ctx context.Context) ([]ListCustomRolesRow, error) {
	rows, err := q.db.Query(ctx, listCustomRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomRolesRow{}
	for rows.Next() {
		var i ListCustomRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Permissions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserCustomRole = `-- name: SetUserCustomRole :one
UPDATE users
SET role = 'custom', custom_role_id = $1,
    permissions = (SELECT custom_roles.permissions FROM custom_roles WHERE custom_roles.id = $1),
    updated_at = now()
WHERE users.id = $2
RETURNING id, email, name, role, password_hash, password_changed_at, password_must_change, totp_secret_enc, totp_enabled_at, totp_last_step, failed_login_count, locked_until, last_login_at, theme, deactivated_at, created_at, updated_at, temp_password_expires_at, invited_at, email_notify_mentions, email_notify_assignments, max_open, availability, last_auto_assigned_at, custom_role_id, permissions, unread_since, email_notify_replies, push_notify_mentions, push_notify_assignments, push_notify_replies, push_notify_sla
`

type SetUserCustomRoleParams struct {
	RoleID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) SetUserCustomRole(ctx context.Context, arg SetUserCustomRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserCustomRole, arg.RoleID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.PasswordMustChange,
		&i.TotpSecretEnc,
		&i.TotpEnabledAt,
		&i.TotpLastStep,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.Theme,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TempPasswordExpiresAt,
		&i.InvitedAt,
		&i.EmailNotifyMentions,
		&i.EmailNotifyAssignments,
		&i.MaxOpen,
		&i.Availability,
		&i.LastAutoAssignedAt,
		&i.CustomRoleID,
		&i.Permissions,
		&i.UnreadSince,
		&i.EmailNotifyReplies,
		&i.PushNotifyMentions,
		&i.PushNotifyAssignments,
		&i.PushNotifyReplies,
		&i.PushNotifySla,
	)
	return i, err
}

const syncCustomRoleMembers = `-- name: SyncCustomRoleMembers :exec
UPDATE users SET permissions = $2, updated_at = now() WHERE custom_role_id = $1
`

type SyncCustomRoleMembersParams struct {
	CustomRoleID pgtype.UUID
	Permissions  []string
}

func (q *Queries) SyncCustomRoleMembers(ctx context.Context, arg SyncCustomRoleMembersParams) error {
	_, err := q.db.Exec(ctx, syncCustomRoleMembers, arg.CustomRoleID, arg.Permissions)
	return err
}

const updateCustomRole = `-- name: UpdateCustomRole :one
UPDATE custom_roles SET name = $2, description = $3, permissions = $4, updated_at = now()
WHERE id = $1
RETURNING id, name, description, permissions, created_at, updated_at
`

type UpdateCustomRoleParams struct {
	ID          pgtype.UUID
	Name        string
	Description string
	Permissions []string
}

func (q *Queries) UpdateCustomRole(ctx context.Context, arg UpdateCustomRoleParams) (CustomRole, error) {
	row := q.db.QueryRow(ctx, updateCustomRole,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Permissions,
	)
	var i CustomRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
