// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSavedView = `-- name: GetSavedView :one
SELECT id, name, owner_user_id, team_id, created_by, filters, sort, position, created_at, updated_at
FROM saved_views WHERE id = $1
`

func (q *Queries) GetSavedView(ctx context.Context, id pgtype.UUID) (SavedView, error) {
	row := q.db.QueryRow(ctx, getSavedView, id)
	var i SavedView
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.TeamID,
		&i.CreatedBy,
		&i.Filters,
		&i.Sort,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSavedView = `-- name: InsertSavedView :one
INSERT INTO saved_views (name, owner_user_id, team_id, created_by, filters, position)
VALUES ($1, $2, $3, $4, $5,
    (SELECT COALESCE(max(position), 0) + 1 FROM saved_views
        WHERE owner_user_id IS NOT DISTINCT FROM $2))
RETURNING id, name, owner_user_id, team_id, created_by, filters, sort, position, created_at, updated_at
`

type InsertSavedViewParams struct {
	Name        string
	OwnerUserID pgtype.UUID
	TeamID      pgtype.UUID
	CreatedBy   pgtype.UUID
	Filters     []byte
}

func (q *Queries) InsertSavedView(ctx context.Context, arg InsertSavedViewParams) (SavedView, error) {
	row := q.db.QueryRow(ctx, insertSavedView,
		arg.Name,
		arg.OwnerUserID,
		arg.TeamID,
		arg.CreatedBy,
		arg.Filters,
	)
	var i SavedView
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.TeamID,
		&i.CreatedBy,
		&i.Filters,
		&i.Sort,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isTeamMember = `-- name: IsTeamMember :one
SELECT EXISTS (SELECT 1 FROM team_members WHERE team_id = $1 AND user_id = $2)
`

type IsTeamMemberParams struct {
	TeamID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) IsTeamMember(ctx context.Context, arg IsTeamMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTeamMember, arg.TeamID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listConversationPageFiltered = `-- name: ListConversationPageFiltered :many
SELECT page.id, page.last_message_at
FROM unnest($1::uuid[]) AS mailbox(id)
CROSS JOIN LATERAL (
    SELECT conversations.id, conversations.last_message_at
    FROM conversations
    WHERE conversations.mailbox_id = mailbox.id
        AND conversations.deleted_at IS NULL
        AND conversations.status = ANY($2::text[])
        AND ($3::text = 'include' OR ($3::text = 'only') = COALESCE(conversations.snoozed_until > now(), false))
        AND (conversations.last_message_at, conversations.id) < (
            COALESCE($4::timestamptz, 'infinity'::timestamptz),
            COALESCE($5::uuid, 'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid))
        AND (cardinality($6::uuid[]) = 0 OR EXISTS (
            SELECT 1 FROM conversation_labels
            WHERE conversation_labels.conversation_id = conversations.id AND conversation_labels.label_id = ANY($6::uuid[])))
        AND ((cardinality($7::uuid[]) = 0 AND NOT $8::boolean)
            OR conversations.assignee_user_id = ANY($7::uuid[])
            OR ($8::boolean AND conversations.assignee_user_id IS NULL))
        AND (cardinality($9::uuid[]) = 0 OR conversations.assignee_team_id = ANY($9::uuid[]))
        AND (cardinality($10::text[]) = 0 OR conversations.priority = ANY($10::text[]))
        AND (NOT $11::boolean OR conversations.has_attachments)
        AND ($12::timestamptz IS NULL OR conversations.last_message_at >= $12::timestamptz)
        AND ($13::timestamptz IS NULL OR conversations.last_message_at < $13::timestamptz)
        AND ($14::uuid IS NULL OR conversations.contact_id = $14::uuid)
        AND ($15::uuid IS NULL OR EXISTS (
            SELECT 1 FROM contacts
            WHERE contacts.id = conversations.contact_id AND contacts.organization_id = $15::uuid))
        AND ($16::bigint IS NULL OR conversations.number = $16::bigint)
        AND (cardinality($17::text[]) = 0 OR EXISTS (
            SELECT 1 FROM messages
            WHERE messages.conversation_id = conversations.id AND messages.deleted_at IS NULL AND messages.kind = 'email'
                AND lower(messages.from_addr) ILIKE ANY($17::text[])))
        AND (cardinality($18::text[]) = 0 OR EXISTS (
            SELECT 1 FROM messages, jsonb_array_elements(messages.to_addrs || messages.cc_addrs) AS recipient
            WHERE messages.conversation_id = conversations.id AND messages.deleted_at IS NULL AND messages.kind = 'email'
                AND lower(recipient ->> 'address') ILIKE ANY($18::text[])))
    ORDER BY conversations.last_message_at DESC, conversations.id DESC
    LIMIT $19::integer
) AS page
ORDER BY page.last_message_at DESC, page.id DESC
LIMIT $19::integer
`

type ListConversationPageFilteredParams struct {
	MailboxIds     []pgtype.UUID
	Statuses       []string
	SnoozedMode    string
	CursorAt       pgtype.Timestamptz
	CursorID       pgtype.UUID
	LabelIds       []pgtype.UUID
	AssigneeIds    []pgtype.UUID
	AssigneeNone   bool
	TeamIds        []pgtype.UUID
	Priorities     []string
	HasAttachment  bool
	After          pgtype.Timestamptz
	Before         pgtype.Timestamptz
	ContactID      pgtype.UUID
	OrganizationID pgtype.UUID
	Number         pgtype.Int8
	FromPatterns   []string
	ToPatterns     []string
	PageSize       int32
}

type ListConversationPageFilteredRow struct {
	ID            pgtype.UUID
	LastMessageAt pgtype.Timestamptz
}

// Same keyset order as the inbox list. One index scan per mailbox, each stopping after page_size rows.
func (q *Queries) ListConversationPageFiltered(ctx context.Context, arg ListConversationPageFilteredParams) ([]ListConversationPageFilteredRow, error) {
	rows, err := q.db.Query(ctx, listConversationPageFiltered,
		arg.MailboxIds,
		arg.Statuses,
		arg.SnoozedMode,
		arg.CursorAt,
		arg.CursorID,
		arg.LabelIds,
		arg.AssigneeIds,
		arg.AssigneeNone,
		arg.TeamIds,
		arg.Priorities,
		arg.HasAttachment,
		arg.After,
		arg.Before,
		arg.ContactID,
		arg.OrganizationID,
		arg.Number,
		arg.FromPatterns,
		arg.ToPatterns,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationPageFilteredRow{}
	for rows.Next() {
		var i ListConversationPageFilteredRow
		if err := rows.Scan(&i.ID, &i.LastMessageAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedViewsFor = `-- name: ListSavedViewsFor :many
SELECT id, name, owner_user_id, team_id, created_by, filters, sort, position, created_at, updated_at
FROM saved_views
WHERE owner_user_id = $1
    OR (owner_user_id IS NULL AND (
        team_id IS NULL OR $2::boolean
        OR team_id IN (SELECT team_members.team_id FROM team_members WHERE team_members.user_id = $1)))
ORDER BY (owner_user_id IS NULL), position, lower(name), id
`

type ListSavedViewsForParams struct {
	UserID   pgtype.UUID
	AllTeams bool
}

// Personal views of the caller plus shared views. Admins see every shared view; others only
// those shared with everyone or with one of their teams.
func (q *Queries) ListSavedViewsFor(ctx context.Context, arg ListSavedViewsForParams) ([]SavedView, error) {
	rows, err := q.db.Query(ctx, listSavedViewsFor, arg.UserID, arg.AllTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedView{}
	for rows.Next() {
		var i SavedView
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerUserID,
			&i.TeamID,
			&i.CreatedBy,
			&i.Filters,
			&i.Sort,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSavedView = `-- name: RemoveSavedView :execrows
DELETE FROM saved_views WHERE id = $1
`

func (q *Queries) RemoveSavedView(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, removeSavedView, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveLabelNames = `-- name: ResolveLabelNames :many
SELECT id FROM labels WHERE id = ANY($1::uuid[]) OR name ILIKE ANY($2::text[])
`

type ResolveLabelNamesParams struct {
	Ids      []pgtype.UUID
	Patterns []string
}

func (q *Queries) ResolveLabelNames(ctx context.Context, arg ResolveLabelNamesParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, resolveLabelNames, arg.Ids, arg.Patterns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveMailboxNames = `-- name: ResolveMailboxNames :many

SELECT id FROM mailboxes
WHERE id = ANY($1::uuid[]) AND (id = ANY($2::uuid[]) OR name ILIKE ANY($3::text[]))
`

type ResolveMailboxNamesParams struct {
	ScopeIds []pgtype.UUID
	Ids      []pgtype.UUID
	Patterns []string
}

// Search and advanced list filters. Every query takes the caller's readable mailbox ids, so
// out-of-scope rows are never selected. The filter conditions are repeated in the list and the
// search query on purpose: sqlc has no fragments and the list query needs its own plan shape.
func (q *Queries) ResolveMailboxNames(ctx context.Context, arg ResolveMailboxNamesParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, resolveMailboxNames, arg.ScopeIds, arg.Ids, arg.Patterns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveTeamNames = `-- name: ResolveTeamNames :many
SELECT id FROM teams WHERE id = ANY($1::uuid[]) OR name ILIKE ANY($2::text[])
`

type ResolveTeamNamesParams struct {
	Ids      []pgtype.UUID
	Patterns []string
}

func (q *Queries) ResolveTeamNames(ctx context.Context, arg ResolveTeamNamesParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, resolveTeamNames, arg.Ids, arg.Patterns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveUserNames = `-- name: ResolveUserNames :many
SELECT id FROM users WHERE deactivated_at IS NULL AND (id = ANY($1::uuid[]) OR name ILIKE ANY($2::text[]))
`

type ResolveUserNamesParams struct {
	Ids      []pgtype.UUID
	Patterns []string
}

func (q *Queries) ResolveUserNames(ctx context.Context, arg ResolveUserNamesParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, resolveUserNames, arg.Ids, arg.Patterns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchConversationPage = `-- name: SearchConversationPage :many
WITH hits AS MATERIALIZED (
    SELECT messages.id, messages.conversation_id, messages.received_at,
        GREATEST(
            CASE WHEN $18::boolean THEN 0 ELSE ts_rank_cd(messages.fts, websearch_to_tsquery('dutch', $19::text), 32) END,
            ts_rank_cd(messages.fts, websearch_to_tsquery('echoo_simple', $19::text), 32)
        ) AS rank
    FROM messages
    WHERE messages.mailbox_id = ANY($20::uuid[]) AND messages.deleted_at IS NULL
        AND ((NOT $18::boolean AND messages.fts @@ websearch_to_tsquery('dutch', $19::text))
            OR messages.fts @@ websearch_to_tsquery('echoo_simple', $19::text))
    ORDER BY messages.received_at DESC, messages.id DESC
    LIMIT 2000
),
msg AS (
    SELECT DISTINCT ON (hits.conversation_id) hits.conversation_id, hits.id AS message_id, hits.rank
    FROM hits
    ORDER BY hits.conversation_id, hits.rank DESC, hits.received_at DESC
),
subj AS (
    SELECT conversations.id FROM conversations
    WHERE conversations.mailbox_id = ANY($20::uuid[]) AND conversations.deleted_at IS NULL
        AND $21::text <% conversations.subject
    ORDER BY conversations.last_message_at DESC
    LIMIT 2000
),
contact_name AS (
    SELECT conversations.id FROM contacts
    JOIN conversations ON conversations.contact_id = contacts.id
    WHERE $21::text <% contacts.name
        AND conversations.mailbox_id = ANY($20::uuid[]) AND conversations.deleted_at IS NULL
    ORDER BY conversations.last_message_at DESC
    LIMIT 2000
),
contact_email AS (
    SELECT conversations.id FROM contact_addresses
    JOIN conversations ON conversations.contact_id = contact_addresses.contact_id
    WHERE $22::text IS NOT NULL AND contact_addresses.email ILIKE $22::text
        AND conversations.mailbox_id = ANY($20::uuid[]) AND conversations.deleted_at IS NULL
    ORDER BY conversations.last_message_at DESC
    LIMIT 2000
),
candidate AS (
    SELECT conversation_id AS id, rank, message_id, false AS in_subject, false AS in_contact FROM msg
    UNION ALL SELECT id, 0, NULL, true, false FROM subj
    UNION ALL SELECT id, 0, NULL, false, true FROM contact_name
    UNION ALL SELECT id, 0, NULL, false, true FROM contact_email
),
merged AS (
    SELECT candidate.id, max(candidate.rank) AS rank,
        (array_agg(candidate.message_id) FILTER (WHERE candidate.message_id IS NOT NULL))[1]::uuid AS message_id,
        bool_or(candidate.in_subject) AS in_subject, bool_or(candidate.in_contact) AS in_contact
    FROM candidate
    GROUP BY candidate.id
)
SELECT found.id, found.last_message_at, scored.score, merged.message_id AS best_message_id
FROM merged
CROSS JOIN LATERAL (
    SELECT conversations.id, conversations.last_message_at
    FROM conversations
    WHERE conversations.id = merged.id
        AND conversations.deleted_at IS NULL
        AND conversations.status = ANY($1::text[])
        AND ($2::text = 'include' OR ($2::text = 'only') = COALESCE(conversations.snoozed_until > now(), false))
        AND (cardinality($3::uuid[]) = 0 OR EXISTS (
            SELECT 1 FROM conversation_labels
            WHERE conversation_labels.conversation_id = conversations.id AND conversation_labels.label_id = ANY($3::uuid[])))
        AND ((cardinality($4::uuid[]) = 0 AND NOT $5::boolean)
            OR conversations.assignee_user_id = ANY($4::uuid[])
            OR ($5::boolean AND conversations.assignee_user_id IS NULL))
        AND (cardinality($6::uuid[]) = 0 OR conversations.assignee_team_id = ANY($6::uuid[]))
        AND (cardinality($7::text[]) = 0 OR conversations.priority = ANY($7::text[]))
        AND (NOT $8::boolean OR conversations.has_attachments)
        AND ($9::timestamptz IS NULL OR conversations.last_message_at >= $9::timestamptz)
        AND ($10::timestamptz IS NULL OR conversations.last_message_at < $10::timestamptz)
        AND ($11::bigint IS NULL OR conversations.number = $11::bigint)
        AND (cardinality($12::text[]) = 0 OR EXISTS (
            SELECT 1 FROM messages
            WHERE messages.conversation_id = conversations.id AND messages.deleted_at IS NULL AND messages.kind = 'email'
                AND lower(messages.from_addr) ILIKE ANY($12::text[])))
        AND (cardinality($13::text[]) = 0 OR EXISTS (
            SELECT 1 FROM messages, jsonb_array_elements(messages.to_addrs || messages.cc_addrs) AS recipient
            WHERE messages.conversation_id = conversations.id AND messages.deleted_at IS NULL AND messages.kind = 'email'
                AND lower(recipient ->> 'address') ILIKE ANY($13::text[])))
    OFFSET 0
) AS found
CROSS JOIN LATERAL (
    SELECT round((COALESCE(merged.rank, 0)
        + CASE WHEN merged.in_subject THEN 0.5 ELSE 0 END
        + CASE WHEN merged.in_contact THEN 0.25 ELSE 0 END)::numeric, 2)::float8 AS score
) AS scored
WHERE (scored.score, found.last_message_at, found.id) < (
    COALESCE($14::float8, 'Infinity'::float8),
    COALESCE($15::timestamptz, 'infinity'::timestamptz),
    COALESCE($16::uuid, 'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid))
ORDER BY scored.score DESC, found.last_message_at DESC, found.id DESC
LIMIT $17::integer
`

type SearchConversationPageParams struct {
	Statuses      []string
	SnoozedMode   string
	LabelIds      []pgtype.UUID
	AssigneeIds   []pgtype.UUID
	AssigneeNone  bool
	TeamIds       []pgtype.UUID
	Priorities    []string
	HasAttachment bool
	After         pgtype.Timestamptz
	Before        pgtype.Timestamptz
	Number        pgtype.Int8
	FromPatterns  []string
	ToPatterns    []string
	CursorScore   pgtype.Float8
	CursorAt      pgtype.Timestamptz
	CursorID      pgtype.UUID
	PageSize      int32
	Exact         bool
	Text          string
	MailboxIds    []pgtype.UUID
	PlainText     string
	EmailPattern  pgtype.Text
}

type SearchConversationPageRow struct {
	ID            pgtype.UUID
	LastMessageAt pgtype.Timestamptz
	Score         float64
	BestMessageID pgtype.UUID
}

// Candidates come from four separately indexed sources: message full text (best message per
// conversation), subject word similarity, contact name and contact address. Score is the message
// rank (0..1) plus 0.5 for a subject hit and 0.25 for a contact hit, rounded so that recency
// decides between near-equal scores. plain_text is the free text without quotes. With exact
// (the text has a quoted phrase) only the unstemmed config matches: the Dutch one drops stop
// words such as "niet", which would make a phrase match too much.
// Only the 2000 newest matching messages are ranked, so a term found in most of the mail costs
// as much as a rare one (messages_received_at serves that scan). Conversations are then fetched
// by primary key, one lookup per candidate (OFFSET 0 keeps the planner from flattening that
// lookup into a scan of every conversation).
func (q *Queries) SearchConversationPage(ctx context.Context, arg SearchConversationPageParams) ([]SearchConversationPageRow, error) {
	rows, err := q.db.Query(ctx, searchConversationPage,
		arg.Statuses,
		arg.SnoozedMode,
		arg.LabelIds,
		arg.AssigneeIds,
		arg.AssigneeNone,
		arg.TeamIds,
		arg.Priorities,
		arg.HasAttachment,
		arg.After,
		arg.Before,
		arg.Number,
		arg.FromPatterns,
		arg.ToPatterns,
		arg.CursorScore,
		arg.CursorAt,
		arg.CursorID,
		arg.PageSize,
		arg.Exact,
		arg.Text,
		arg.MailboxIds,
		arg.PlainText,
		arg.EmailPattern,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchConversationPageRow{}
	for rows.Next() {
		var i SearchConversationPageRow
		if err := rows.Scan(
			&i.ID,
			&i.LastMessageAt,
			&i.Score,
			&i.BestMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSnippets = `-- name: SearchSnippets :many
SELECT messages.id,
    ts_headline(
        (CASE WHEN $1::boolean THEN 'echoo_simple' ELSE 'dutch' END)::regconfig,
        left(translate(messages.body_text, '⟦⟧', ''), 50000),
        CASE WHEN $1::boolean THEN websearch_to_tsquery('echoo_simple', $2::text)
            ELSE websearch_to_tsquery('dutch', $2::text) || websearch_to_tsquery('echoo_simple', $2::text) END,
        'StartSel=⟦, StopSel=⟧, MaxFragments=1, MaxWords=30, MinWords=12, ShortWord=2')::text AS snippet
FROM messages
WHERE messages.id = ANY($3::uuid[]) AND messages.mailbox_id = ANY($4::uuid[])
`

type SearchSnippetsParams struct {
	Exact      bool
	Text       string
	MessageIds []pgtype.UUID
	MailboxIds []pgtype.UUID
}

type SearchSnippetsRow struct {
	ID      pgtype.UUID
	Snippet string
}

// Plain-text markers (U+27E6 and U+27E7) delimit the matches; they are stripped from the source
// first so the text itself can never fake a highlight. The client turns them into text segments.
func (q *Queries) SearchSnippets(ctx context.Context, arg SearchSnippetsParams) ([]SearchSnippetsRow, error) {
	rows, err := q.db.Query(ctx, searchSnippets,
		arg.Exact,
		arg.Text,
		arg.MessageIds,
		arg.MailboxIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSnippetsRow{}
	for rows.Next() {
		var i SearchSnippetsRow
		if err := rows.Scan(&i.ID, &i.Snippet); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSavedView = `-- name: UpdateSavedView :one
UPDATE saved_views SET
    name = COALESCE($1, name),
    filters = COALESCE($2, filters),
    position = COALESCE($3, position),
    owner_user_id = CASE WHEN $4::boolean THEN $5 ELSE owner_user_id END,
    team_id = CASE WHEN $4::boolean THEN $6 ELSE team_id END,
    updated_at = now()
WHERE id = $7
RETURNING id, name, owner_user_id, team_id, created_by, filters, sort, position, created_at, updated_at
`

type UpdateSavedViewParams struct {
	Name        pgtype.Text
	Filters     []byte
	Position    pgtype.Int4
	SetScope    bool
	OwnerUserID pgtype.UUID
	TeamID      pgtype.UUID
	ID          pgtype.UUID
}

func (q *Queries) UpdateSavedView(ctx context.Context, arg UpdateSavedViewParams) (SavedView, error) {
	row := q.db.QueryRow(ctx, updateSavedView,
		arg.Name,
		arg.Filters,
		arg.Position,
		arg.SetScope,
		arg.OwnerUserID,
		arg.TeamID,
		arg.ID,
	)
	var i SavedView
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.TeamID,
		&i.CreatedBy,
		&i.Filters,
		&i.Sort,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
