// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: send.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const sendCancelOutbound = `-- name: SendCancelOutbound :execrows
UPDATE outbound SET status = 'cancelled', updated_at = now()
WHERE message_id = $1 AND status = 'queued'
`

func (q *Queries) SendCancelOutbound(ctx context.Context, messageID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, sendCancelOutbound, messageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sendClaimOutbound = `-- name: SendClaimOutbound :one
UPDATE outbound
SET status = 'sending', attempt = attempt + 1, last_attempt_at = $1, updated_at = $1
WHERE message_id = $2
  AND status IN ('queued', 'retry')
  AND scheduled_at <= $1
  AND (next_attempt_at IS NULL OR next_attempt_at <= $1)
RETURNING message_id, idempotency_key, status, scheduled_at, attempt, last_attempt_at, next_attempt_at, smtp_response, error, dsn_status, sent_at, created_by, updated_at, extra_headers
`

type SendClaimOutboundParams struct {
	Now       pgtype.Timestamptz
	MessageID pgtype.UUID
}

func (q *Queries) SendClaimOutbound(ctx context.Context, arg SendClaimOutboundParams) (Outbound, error) {
	row := q.db.QueryRow(ctx, sendClaimOutbound, arg.Now, arg.MessageID)
	var i Outbound
	err := row.Scan(
		&i.MessageID,
		&i.IdempotencyKey,
		&i.Status,
		&i.ScheduledAt,
		&i.Attempt,
		&i.LastAttemptAt,
		&i.NextAttemptAt,
		&i.SmtpResponse,
		&i.Error,
		&i.DsnStatus,
		&i.SentAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.ExtraHeaders,
	)
	return i, err
}

const sendGetEnqueuedByKey = `-- name: SendGetEnqueuedByKey :one
SELECT o.message_id, m.message_id_header
FROM outbound o JOIN messages m ON m.id = o.message_id
WHERE o.idempotency_key = $1
`

type SendGetEnqueuedByKeyRow struct {
	MessageID       pgtype.UUID
	MessageIDHeader string
}

func (q *Queries) SendGetEnqueuedByKey(ctx context.Context, idempotencyKey pgtype.UUID) (SendGetEnqueuedByKeyRow, error) {
	row := q.db.QueryRow(ctx, sendGetEnqueuedByKey, idempotencyKey)
	var i SendGetEnqueuedByKeyRow
	err := row.Scan(&i.MessageID, &i.MessageIDHeader)
	return i, err
}

const sendGetMailbox = `-- name: SendGetMailbox :one
SELECT id, name, email_address, display_name, transport, auth_type, imap_host, imap_port, imap_tls, imap_username, imap_secret_enc, smtp_host, smtp_port, smtp_tls, smtp_username, smtp_secret_enc, oauth_token_enc, oauth_expires_at, inbound_secret_enc, sent_folder, mark_seen, send_delay_seconds, sync_state, sync_error, sync_state_changed_at, last_synced_at, created_at, updated_at, disabled_at, allow_internal_host, oauth_connected_at, auto_assign_mode, default_sla_policy_id, business_hours_id FROM mailboxes WHERE id = $1
`

func (q *Queries) SendGetMailbox(ctx context.Context, id pgtype.UUID) (Mailbox, error) {
	row := q.db.QueryRow(ctx, sendGetMailbox, id)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailAddress,
		&i.DisplayName,
		&i.Transport,
		&i.AuthType,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapTls,
		&i.ImapUsername,
		&i.ImapSecretEnc,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpTls,
		&i.SmtpUsername,
		&i.SmtpSecretEnc,
		&i.OauthTokenEnc,
		&i.OauthExpiresAt,
		&i.InboundSecretEnc,
		&i.SentFolder,
		&i.MarkSeen,
		&i.SendDelaySeconds,
		&i.SyncState,
		&i.SyncError,
		&i.SyncStateChangedAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
		&i.AllowInternalHost,
		&i.OauthConnectedAt,
		&i.AutoAssignMode,
		&i.DefaultSlaPolicyID,
		&i.BusinessHoursID,
	)
	return i, err
}

const sendGetMessage = `-- name: SendGetMessage :one
SELECT id, conversation_id, mailbox_id, kind, direction, raw_message_id, raw_sha256, message_id_header, message_id_hash, in_reply_to, references_hdr, from_addr, from_name, to_addrs, cc_addrs, bcc_addrs, reply_to, subject, sent_at, received_at, body_text, body_html, auto_submitted, is_bounce, author_user_id, created_at, deleted_at, fts, auth_results, is_bulk FROM messages WHERE id = $1 AND kind = 'email' AND direction = 'out'
`

func (q *Queries) SendGetMessage(ctx context.Context, id pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, sendGetMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.MailboxID,
		&i.Kind,
		&i.Direction,
		&i.RawMessageID,
		&i.RawSha256,
		&i.MessageIDHeader,
		&i.MessageIDHash,
		&i.InReplyTo,
		&i.ReferencesHdr,
		&i.FromAddr,
		&i.FromName,
		&i.ToAddrs,
		&i.CcAddrs,
		&i.BccAddrs,
		&i.ReplyTo,
		&i.Subject,
		&i.SentAt,
		&i.ReceivedAt,
		&i.BodyText,
		&i.BodyHtml,
		&i.AutoSubmitted,
		&i.IsBounce,
		&i.AuthorUserID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Fts,
		&i.AuthResults,
		&i.IsBulk,
	)
	return i, err
}

const sendGetOutbound = `-- name: SendGetOutbound :one
SELECT message_id, idempotency_key, status, scheduled_at, attempt, last_attempt_at, next_attempt_at, smtp_response, error, dsn_status, sent_at, created_by, updated_at, extra_headers FROM outbound WHERE message_id = $1
`

func (q *Queries) SendGetOutbound(ctx context.Context, messageID pgtype.UUID) (Outbound, error) {
	row := q.db.QueryRow(ctx, sendGetOutbound, messageID)
	var i Outbound
	err := row.Scan(
		&i.MessageID,
		&i.IdempotencyKey,
		&i.Status,
		&i.ScheduledAt,
		&i.Attempt,
		&i.LastAttemptAt,
		&i.NextAttemptAt,
		&i.SmtpResponse,
		&i.Error,
		&i.DsnStatus,
		&i.SentAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.ExtraHeaders,
	)
	return i, err
}

const sendInsertAttachment = `-- name: SendInsertAttachment :exec
INSERT INTO attachments (message_id, filename, declared_type, size_bytes, sha256, blob_key, content_id, disposition)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type SendInsertAttachmentParams struct {
	MessageID    pgtype.UUID
	Filename     string
	DeclaredType string
	SizeBytes    int64
	Sha256       []byte
	BlobKey      string
	ContentID    string
	Disposition  string
}

func (q *Queries) SendInsertAttachment(ctx context.Context, arg SendInsertAttachmentParams) error {
	_, err := q.db.Exec(ctx, sendInsertAttachment,
		arg.MessageID,
		arg.Filename,
		arg.DeclaredType,
		arg.SizeBytes,
		arg.Sha256,
		arg.BlobKey,
		arg.ContentID,
		arg.Disposition,
	)
	return err
}

const sendInsertMessage = `-- name: SendInsertMessage :one
INSERT INTO messages (
    conversation_id, mailbox_id, kind, direction, message_id_header, message_id_hash,
    in_reply_to, references_hdr, from_addr, from_name, to_addrs, cc_addrs, bcc_addrs,
    subject, body_text, body_html, auto_submitted, author_user_id
) VALUES ($1, $2, 'email', 'out', $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id
`

type SendInsertMessageParams struct {
	ConversationID  pgtype.UUID
	MailboxID       pgtype.UUID
	MessageIDHeader string
	MessageIDHash   []byte
	InReplyTo       string
	ReferencesHdr   []string
	FromAddr        string
	FromName        string
	ToAddrs         []byte
	CcAddrs         []byte
	BccAddrs        []byte
	Subject         string
	BodyText        string
	BodyHtml        string
	AutoSubmitted   bool
	AuthorUserID    pgtype.UUID
}

func (q *Queries) SendInsertMessage(ctx context.Context, arg SendInsertMessageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, sendInsertMessage,
		arg.ConversationID,
		arg.MailboxID,
		arg.MessageIDHeader,
		arg.MessageIDHash,
		arg.InReplyTo,
		arg.ReferencesHdr,
		arg.FromAddr,
		arg.FromName,
		arg.ToAddrs,
		arg.CcAddrs,
		arg.BccAddrs,
		arg.Subject,
		arg.BodyText,
		arg.BodyHtml,
		arg.AutoSubmitted,
		arg.AuthorUserID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const sendInsertOutbound = `-- name: SendInsertOutbound :exec
INSERT INTO outbound (message_id, idempotency_key, scheduled_at, created_by, extra_headers)
VALUES ($1, $2, $3, $4, $5)
`

type SendInsertOutboundParams struct {
	MessageID      pgtype.UUID
	IdempotencyKey pgtype.UUID
	ScheduledAt    pgtype.Timestamptz
	CreatedBy      pgtype.UUID
	ExtraHeaders   []byte
}

func (q *Queries) SendInsertOutbound(ctx context.Context, arg SendInsertOutboundParams) error {
	_, err := q.db.Exec(ctx, sendInsertOutbound,
		arg.MessageID,
		arg.IdempotencyKey,
		arg.ScheduledAt,
		arg.CreatedBy,
		arg.ExtraHeaders,
	)
	return err
}

const sendInsertThreadRef = `-- name: SendInsertThreadRef :exec
INSERT INTO thread_refs (mailbox_id, message_id_hash, conversation_id)
VALUES ($1, $2, $3)
ON CONFLICT (mailbox_id, message_id_hash) DO NOTHING
`

type SendInsertThreadRefParams struct {
	MailboxID      pgtype.UUID
	MessageIDHash  []byte
	ConversationID pgtype.UUID
}

func (q *Queries) SendInsertThreadRef(ctx context.Context, arg SendInsertThreadRefParams) error {
	_, err := q.db.Exec(ctx, sendInsertThreadRef, arg.MailboxID, arg.MessageIDHash, arg.ConversationID)
	return err
}

const sendListAttachments = `-- name: SendListAttachments :many
SELECT id, message_id, filename, declared_type, sniffed_type, size_bytes, sha256, blob_key, content_id, disposition, scan_status, scan_detail, created_at FROM attachments WHERE message_id = $1 ORDER BY created_at, id
`

func (q *Queries) SendListAttachments(ctx context.Context, messageID pgtype.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, sendListAttachments, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Filename,
			&i.DeclaredType,
			&i.SniffedType,
			&i.SizeBytes,
			&i.Sha256,
			&i.BlobKey,
			&i.ContentID,
			&i.Disposition,
			&i.ScanStatus,
			&i.ScanDetail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sendRecordConversationReply = `-- name: SendRecordConversationReply :exec
UPDATE conversations c
SET message_count      = c.message_count + 1,
    last_message_at    = greatest(c.last_message_at, $1::timestamptz),
    last_outbound_at   = $1::timestamptz,
    first_responded_at = CASE WHEN m.auto_submitted THEN c.first_responded_at
                              ELSE coalesce(c.first_responded_at, $1::timestamptz) END,
    first_response_met_at = CASE WHEN m.auto_submitted THEN c.first_response_met_at
                                 ELSE coalesce(c.first_response_met_at, $1::timestamptz) END,
    preview            = left(regexp_replace(m.body_text, '\s+', ' ', 'g'), 200),
    version            = c.version + 1,
    updated_at         = now()
FROM messages m
WHERE m.id = $2 AND c.id = m.conversation_id
`

type SendRecordConversationReplyParams struct {
	SentAt    pgtype.Timestamptz
	MessageID pgtype.UUID
}

// Counts a delivered reply on its conversation; queued or cancelled replies do not count
// towards response times, and neither does an automatic reply: only a person answering meets
// the first-response SLA.
func (q *Queries) SendRecordConversationReply(ctx context.Context, arg SendRecordConversationReplyParams) error {
	_, err := q.db.Exec(ctx, sendRecordConversationReply, arg.SentAt, arg.MessageID)
	return err
}

const sendSetMessageSentAt = `-- name: SendSetMessageSentAt :exec
UPDATE messages SET sent_at = $2 WHERE id = $1
`

type SendSetMessageSentAtParams struct {
	ID     pgtype.UUID
	SentAt pgtype.Timestamptz
}

func (q *Queries) SendSetMessageSentAt(ctx context.Context, arg SendSetMessageSentAtParams) error {
	_, err := q.db.Exec(ctx, sendSetMessageSentAt, arg.ID, arg.SentAt)
	return err
}

const sendSetOutboundResult = `-- name: SendSetOutboundResult :execrows
UPDATE outbound
SET status = $1, smtp_response = $2, error = $3,
    next_attempt_at = $4, sent_at = $5, updated_at = $6
WHERE message_id = $7 AND status IN ('queued', 'retry', 'sending')
`

type SendSetOutboundResultParams struct {
	Status        string
	SmtpResponse  string
	Error         string
	NextAttemptAt pgtype.Timestamptz
	SentAt        pgtype.Timestamptz
	Now           pgtype.Timestamptz
	MessageID     pgtype.UUID
}

func (q *Queries) SendSetOutboundResult(ctx context.Context, arg SendSetOutboundResultParams) (int64, error) {
	result, err := q.db.Exec(ctx, sendSetOutboundResult,
		arg.Status,
		arg.SmtpResponse,
		arg.Error,
		arg.NextAttemptAt,
		arg.SentAt,
		arg.Now,
		arg.MessageID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
