// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbq

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, csrf_token, mfa_pending, idle_expires_at, expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, token_hash, csrf_token, mfa_pending, created_at, last_seen_at, idle_expires_at, expires_at, ip, user_agent, revoked_at, idp_mfa
`

type CreateSessionParams struct {
	UserID        pgtype.UUID
	TokenHash     []byte
	CsrfToken     string
	MfaPending    bool
	IdleExpiresAt pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	Ip            *netip.Addr
	UserAgent     string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.CsrfToken,
		arg.MfaPending,
		arg.IdleExpiresAt,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfToken,
		&i.MfaPending,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.IdleExpiresAt,
		&i.ExpiresAt,
		&i.Ip,
		&i.UserAgent,
		&i.RevokedAt,
		&i.IdpMfa,
	)
	return i, err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT sessions.id, sessions.user_id, sessions.token_hash, sessions.csrf_token, sessions.mfa_pending, sessions.created_at, sessions.last_seen_at, sessions.idle_expires_at, sessions.expires_at, sessions.ip, sessions.user_agent, sessions.revoked_at, sessions.idp_mfa, users.id, users.email, users.name, users.role, users.password_hash, users.password_changed_at, users.password_must_change, users.totp_secret_enc, users.totp_enabled_at, users.totp_last_step, users.failed_login_count, users.locked_until, users.last_login_at, users.theme, users.deactivated_at, users.created_at, users.updated_at, users.temp_password_expires_at, users.invited_at, users.email_notify_mentions, users.email_notify_assignments, users.max_open, users.availability, users.last_auto_assigned_at, users.custom_role_id, users.permissions, users.unread_since, users.email_notify_replies
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1
  AND sessions.revoked_at IS NULL
  AND sessions.expires_at > now()
  AND sessions.idle_expires_at > now()
  AND users.deactivated_at IS NULL
`

type GetActiveSessionRow struct {
	Session Session
	User    User
}

func (q *Queries) GetActiveSession(ctx context.Context, tokenHash []byte) (GetActiveSessionRow, error) {
	row := q.db.QueryRow(ctx, getActiveSession, tokenHash)
	var i GetActiveSessionRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.TokenHash,
		&i.Session.CsrfToken,
		&i.Session.MfaPending,
		&i.Session.CreatedAt,
		&i.Session.LastSeenAt,
		&i.Session.IdleExpiresAt,
		&i.Session.ExpiresAt,
		&i.Session.Ip,
		&i.Session.UserAgent,
		&i.Session.RevokedAt,
		&i.Session.IdpMfa,
		&i.User.ID,
		&i.User.Email,
		&i.User.Name,
		&i.User.Role,
		&i.User.PasswordHash,
		&i.User.PasswordChangedAt,
		&i.User.PasswordMustChange,
		&i.User.TotpSecretEnc,
		&i.User.TotpEnabledAt,
		&i.User.TotpLastStep,
		&i.User.FailedLoginCount,
		&i.User.LockedUntil,
		&i.User.LastLoginAt,
		&i.User.Theme,
		&i.User.DeactivatedAt,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.TempPasswordExpiresAt,
		&i.User.InvitedAt,
		&i.User.EmailNotifyMentions,
		&i.User.EmailNotifyAssignments,
		&i.User.MaxOpen,
		&i.User.Availability,
		&i.User.LastAutoAssignedAt,
		&i.User.CustomRoleID,
		&i.User.Permissions,
		&i.User.UnreadSince,
		&i.User.EmailNotifyReplies,
	)
	return i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, user_id, token_hash, csrf_token, mfa_pending, created_at, last_seen_at, idle_expires_at, expires_at, ip, user_agent, revoked_at, idp_mfa FROM sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND mfa_pending = false
  AND expires_at > now()
  AND idle_expires_at > now()
ORDER BY last_seen_at DESC
`

func (q *Queries) ListUserSessions(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.CsrfToken,
			&i.MfaPending,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.IdleExpiresAt,
			&i.ExpiresAt,
			&i.Ip,
			&i.UserAgent,
			&i.RevokedAt,
			&i.IdpMfa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeIdPMFASessions = `-- name: RevokeIdPMFASessions :execrows
UPDATE sessions SET revoked_at = now() WHERE idp_mfa AND revoked_at IS NULL
`

func (q *Queries) RevokeIdPMFASessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, revokeIdPMFASessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeUserSession = `-- name: RevokeUserSession :execrows
UPDATE sessions SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeUserSessionParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserSessions = `-- name: RevokeUserSessions :execrows
UPDATE sessions SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL AND id <> $2::uuid
`

type RevokeUserSessionsParams struct {
	UserID   pgtype.UUID
	ExceptID pgtype.UUID
}

func (q *Queries) RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserSessions, arg.UserID, arg.ExceptID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now(), idle_expires_at = $2
WHERE id = $1 AND revoked_at IS NULL
`

type TouchSessionParams struct {
	ID            pgtype.UUID
	IdleExpiresAt pgtype.Timestamptz
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.IdleExpiresAt)
	return err
}
