// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sso.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSSOUser = `-- name: CreateSSOUser :one
INSERT INTO users (email, name, role, custom_role_id, permissions, password_hash)
VALUES (
    $1, $2, $3, $4,
    COALESCE((SELECT custom_roles.permissions FROM custom_roles WHERE custom_roles.id = $4), '{}'),
    $5
)
RETURNING id, email, name, role, password_hash, password_changed_at, password_must_change, totp_secret_enc, totp_enabled_at, totp_last_step, failed_login_count, locked_until, last_login_at, theme, deactivated_at, created_at, updated_at, temp_password_expires_at, invited_at, email_notify_mentions, email_notify_assignments, max_open, availability, last_auto_assigned_at, custom_role_id, permissions, unread_since, email_notify_replies, push_notify_mentions, push_notify_assignments, push_notify_replies, push_notify_sla
`

type CreateSSOUserParams struct {
	Email        string
	Name         string
	Role         string
	CustomRoleID pgtype.UUID
	PasswordHash string
}

func (q *Queries) CreateSSOUser(ctx context.Context, arg CreateSSOUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createSSOUser,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.CustomRoleID,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.PasswordMustChange,
		&i.TotpSecretEnc,
		&i.TotpEnabledAt,
		&i.TotpLastStep,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.Theme,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TempPasswordExpiresAt,
		&i.InvitedAt,
		&i.EmailNotifyMentions,
		&i.EmailNotifyAssignments,
		&i.MaxOpen,
		&i.Availability,
		&i.LastAutoAssignedAt,
		&i.CustomRoleID,
		&i.Permissions,
		&i.UnreadSince,
		&i.EmailNotifyReplies,
		&i.PushNotifyMentions,
		&i.PushNotifyAssignments,
		&i.PushNotifyReplies,
		&i.PushNotifySla,
	)
	return i, err
}

const getSSOSettings = `-- name: GetSSOSettings :one
SELECT singleton, enabled, issuer_url, client_id, client_secret_enc, allowed_domains, button_label, required, auto_provision, default_role, default_custom_role_id, trust_idp_mfa, trust_missing_email_verified, allow_internal_issuer, updated_by, updated_at FROM sso_settings WHERE singleton
`

func (q *Queries) GetSSOSettings(ctx context.Context) (SsoSetting, error) {
	row := q.db.QueryRow(ctx, getSSOSettings)
	var i SsoSetting
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.AllowedDomains,
		&i.ButtonLabel,
		&i.Required,
		&i.AutoProvision,
		&i.DefaultRole,
		&i.DefaultCustomRoleID,
		&i.TrustIdpMfa,
		&i.TrustMissingEmailVerified,
		&i.AllowInternalIssuer,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getSSOSettingsForShare = `-- name: GetSSOSettingsForShare :one
SELECT singleton, enabled, issuer_url, client_id, client_secret_enc, allowed_domains, button_label, required, auto_provision, default_role, default_custom_role_id, trust_idp_mfa, trust_missing_email_verified, allow_internal_issuer, updated_by, updated_at FROM sso_settings WHERE singleton FOR SHARE
`

// Read in the login transaction: waits for a settings change in flight, so a session is never
// marked as MFA-backed on trust that was withdrawn a moment earlier.
func (q *Queries) GetSSOSettingsForShare(ctx context.Context) (SsoSetting, error) {
	row := q.db.QueryRow(ctx, getSSOSettingsForShare)
	var i SsoSetting
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.AllowedDomains,
		&i.ButtonLabel,
		&i.Required,
		&i.AutoProvision,
		&i.DefaultRole,
		&i.DefaultCustomRoleID,
		&i.TrustIdpMfa,
		&i.TrustMissingEmailVerified,
		&i.AllowInternalIssuer,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const markSessionIdPMFA = `-- name: MarkSessionIdPMFA :exec
UPDATE sessions SET idp_mfa = true WHERE id = $1
`

func (q *Queries) MarkSessionIdPMFA(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markSessionIdPMFA, id)
	return err
}

const upsertSSOSettings = `-- name: UpsertSSOSettings :one
INSERT INTO sso_settings (
    singleton, enabled, issuer_url, client_id, client_secret_enc, allowed_domains, button_label, required,
    auto_provision, default_role, default_custom_role_id, trust_idp_mfa, trust_missing_email_verified, allow_internal_issuer,
    updated_by, updated_at
) VALUES (
    true, $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14, now()
)
ON CONFLICT (singleton) DO UPDATE SET
    enabled = EXCLUDED.enabled,
    issuer_url = EXCLUDED.issuer_url,
    client_id = EXCLUDED.client_id,
    client_secret_enc = COALESCE(EXCLUDED.client_secret_enc, sso_settings.client_secret_enc),
    allowed_domains = EXCLUDED.allowed_domains,
    button_label = EXCLUDED.button_label,
    required = EXCLUDED.required,
    auto_provision = EXCLUDED.auto_provision,
    default_role = EXCLUDED.default_role,
    default_custom_role_id = EXCLUDED.default_custom_role_id,
    trust_idp_mfa = EXCLUDED.trust_idp_mfa,
    trust_missing_email_verified = EXCLUDED.trust_missing_email_verified,
    allow_internal_issuer = EXCLUDED.allow_internal_issuer,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
RETURNING singleton, enabled, issuer_url, client_id, client_secret_enc, allowed_domains, button_label, required, auto_provision, default_role, default_custom_role_id, trust_idp_mfa, trust_missing_email_verified, allow_internal_issuer, updated_by, updated_at
`

type UpsertSSOSettingsParams struct {
	Enabled                   bool
	IssuerUrl                 string
	ClientID                  string
	ClientSecretEnc           []byte
	AllowedDomains            []string
	ButtonLabel               string
	Required                  bool
	AutoProvision             bool
	DefaultRole               string
	DefaultCustomRoleID       pgtype.UUID
	TrustIdpMfa               bool
	TrustMissingEmailVerified bool
	AllowInternalIssuer       bool
	UpdatedBy                 pgtype.UUID
}

// A NULL secret keeps the stored one: the secret is write-only.
func (q *Queries) UpsertSSOSettings(ctx context.Context, arg UpsertSSOSettingsParams) (SsoSetting, error) {
	row := q.db.QueryRow(ctx, upsertSSOSettings,
		arg.Enabled,
		arg.IssuerUrl,
		arg.ClientID,
		arg.ClientSecretEnc,
		arg.AllowedDomains,
		arg.ButtonLabel,
		arg.Required,
		arg.AutoProvision,
		arg.DefaultRole,
		arg.DefaultCustomRoleID,
		arg.TrustIdpMfa,
		arg.TrustMissingEmailVerified,
		arg.AllowInternalIssuer,
		arg.UpdatedBy,
	)
	var i SsoSetting
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.AllowedDomains,
		&i.ButtonLabel,
		&i.Required,
		&i.AutoProvision,
		&i.DefaultRole,
		&i.DefaultCustomRoleID,
		&i.TrustIdpMfa,
		&i.TrustMissingEmailVerified,
		&i.AllowInternalIssuer,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
