// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMembers = `-- name: AddTeamMembers :exec
INSERT INTO team_members (team_id, user_id)
SELECT $1, unnest($2::uuid[])
`

type AddTeamMembersParams struct {
	TeamID  pgtype.UUID
	UserIds []pgtype.UUID
}

func (q *Queries) AddTeamMembers(ctx context.Context, arg AddTeamMembersParams) error {
	_, err := q.db.Exec(ctx, addTeamMembers, arg.TeamID, arg.UserIds)
	return err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateTeam(ctx context.Context, name string) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, name)
	var i Team
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :execrows
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTeam, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTeamMembers = `-- name: DeleteTeamMembers :exec
DELETE FROM team_members WHERE team_id = $1
`

func (q *Queries) DeleteTeamMembers(ctx context.Context, teamID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeamMembers, teamID)
	return err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, created_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id pgtype.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTeamForUpdate = `-- name: GetTeamForUpdate :one
SELECT id, name, created_at FROM teams WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetTeamForUpdate(ctx context.Context, id pgtype.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamForUpdate, id)
	var i Team
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listTeamMemberIDs = `-- name: ListTeamMemberIDs :many
SELECT user_id FROM team_members WHERE team_id = $1
`

func (q *Queries) ListTeamMemberIDs(ctx context.Context, teamID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listTeamMemberIDs, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT teams.id, teams.name, teams.created_at, count(team_members.user_id)::integer AS member_count
FROM teams
LEFT JOIN team_members ON team_members.team_id = teams.id
GROUP BY teams.id
ORDER BY lower(teams.name)
`

type ListTeamsRow struct {
	ID          pgtype.UUID
	Name        string
	CreatedAt   pgtype.Timestamptz
	MemberCount int32
}

func (q *Queries) ListTeams(ctx context.Context) ([]ListTeamsRow, error) {
	rows, err := q.db.Query(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsRow{}
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTeamIDs = `-- name: ListUserTeamIDs :many
SELECT team_id FROM team_members WHERE user_id = $1
`

func (q *Queries) ListUserTeamIDs(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listUserTeamIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var team_id pgtype.UUID
		if err := rows.Scan(&team_id); err != nil {
			return nil, err
		}
		items = append(items, team_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameTeam = `-- name: RenameTeam :one
UPDATE teams SET name = $2 WHERE id = $1 RETURNING id, name, created_at
`

type RenameTeamParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) RenameTeam(ctx context.Context, arg RenameTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, renameTeam, arg.ID, arg.Name)
	var i Team
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
