// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: threading.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const conversationInMailbox = `-- name: ConversationInMailbox :one
SELECT EXISTS (SELECT 1 FROM conversations WHERE id = $1 AND mailbox_id = $2)
`

type ConversationInMailboxParams struct {
	ID        pgtype.UUID
	MailboxID pgtype.UUID
}

func (q *Queries) ConversationInMailbox(ctx context.Context, arg ConversationInMailboxParams) (bool, error) {
	row := q.db.QueryRow(ctx, conversationInMailbox, arg.ID, arg.MailboxID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listSubjectCandidates = `-- name: ListSubjectCandidates :many
SELECT
    c.id,
    c.status,
    c.last_message_at,
    c.resolved_at,
    ARRAY(
        SELECT DISTINCT p.addr
        FROM (
            SELECT lower(m.from_addr) AS addr
            FROM messages m
            WHERE m.conversation_id = c.id AND m.kind = 'email' AND m.deleted_at IS NULL
            UNION ALL
            SELECT lower(e.value ->> 'address')
            FROM messages m, jsonb_array_elements(m.to_addrs || m.cc_addrs) AS e
            WHERE m.conversation_id = c.id AND m.kind = 'email' AND m.deleted_at IS NULL
        ) p
        WHERE p.addr <> ''
    )::text[] AS participants
FROM conversations c
WHERE c.mailbox_id = $1
  AND c.subject_normalized = $2
  AND c.last_message_at >= $3
  AND c.deleted_at IS NULL
  AND c.status <> 'spam'
ORDER BY c.last_message_at DESC
LIMIT 20
`

type ListSubjectCandidatesParams struct {
	MailboxID         pgtype.UUID
	SubjectNormalized string
	LastMessageAt     pgtype.Timestamptz
}

type ListSubjectCandidatesRow struct {
	ID            pgtype.UUID
	Status        string
	LastMessageAt pgtype.Timestamptz
	ResolvedAt    pgtype.Timestamptz
	Participants  []string
}

func (q *Queries) ListSubjectCandidates(ctx context.Context, arg ListSubjectCandidatesParams) ([]ListSubjectCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listSubjectCandidates, arg.MailboxID, arg.SubjectNormalized, arg.LastMessageAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubjectCandidatesRow{}
	for rows.Next() {
		var i ListSubjectCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.LastMessageAt,
			&i.ResolvedAt,
			&i.Participants,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadRefConversations = `-- name: ListThreadRefConversations :many
SELECT message_id_hash, conversation_id
FROM thread_refs
WHERE mailbox_id = $1 AND message_id_hash = ANY($2::bytea[])
`

type ListThreadRefConversationsParams struct {
	MailboxID pgtype.UUID
	Hashes    [][]byte
}

type ListThreadRefConversationsRow struct {
	MessageIDHash  []byte
	ConversationID pgtype.UUID
}

func (q *Queries) ListThreadRefConversations(ctx context.Context, arg ListThreadRefConversationsParams) ([]ListThreadRefConversationsRow, error) {
	rows, err := q.db.Query(ctx, listThreadRefConversations, arg.MailboxID, arg.Hashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListThreadRefConversationsRow{}
	for rows.Next() {
		var i ListThreadRefConversationsRow
		if err := rows.Scan(&i.MessageIDHash, &i.ConversationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
