// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trash.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const trashGetInfo = `-- name: TrashGetInfo :one
SELECT c.deleted_at, users.id AS deleted_by_id, users.name AS deleted_by_name
FROM conversations c
LEFT JOIN users ON users.id = c.deleted_by
WHERE c.id = $1 AND c.mailbox_id = ANY($2::uuid[]) AND c.deleted_at IS NOT NULL
`

type TrashGetInfoParams struct {
	ID         pgtype.UUID
	MailboxIds []pgtype.UUID
}

type TrashGetInfoRow struct {
	DeletedAt     pgtype.Timestamptz
	DeletedByID   pgtype.UUID
	DeletedByName pgtype.Text
}

func (q *Queries) TrashGetInfo(ctx context.Context, arg TrashGetInfoParams) (TrashGetInfoRow, error) {
	row := q.db.QueryRow(ctx, trashGetInfo, arg.ID, arg.MailboxIds)
	var i TrashGetInfoRow
	err := row.Scan(&i.DeletedAt, &i.DeletedByID, &i.DeletedByName)
	return i, err
}

const trashListPage = `-- name: TrashListPage :many
SELECT
    c.id, c.number, c.subject, c.status, c.preview, c.last_message_at, c.message_count, c.deleted_at,
    mailboxes.id AS mailbox_id, mailboxes.name AS mailbox_name,
    contacts.id AS contact_id, contacts.name AS contact_name, COALESCE(contact_address.email, '')::text AS contact_email,
    users.id AS deleted_by_id, users.name AS deleted_by_name
FROM conversations c
JOIN mailboxes ON mailboxes.id = c.mailbox_id
LEFT JOIN contacts ON contacts.id = c.contact_id
LEFT JOIN LATERAL (
    SELECT contact_addresses.email FROM contact_addresses
    WHERE contact_addresses.contact_id = contacts.id
    ORDER BY contact_addresses.is_primary DESC, contact_addresses.email
    LIMIT 1
) AS contact_address ON true
LEFT JOIN users ON users.id = c.deleted_by
WHERE c.mailbox_id = ANY($1::uuid[]) AND c.deleted_at IS NOT NULL
    AND ($2::timestamptz IS NULL OR (c.deleted_at, c.id) < ($2::timestamptz, $3::uuid))
ORDER BY c.deleted_at DESC, c.id DESC
LIMIT $4::integer
`

type TrashListPageParams struct {
	MailboxIds []pgtype.UUID
	CursorAt   pgtype.Timestamptz
	CursorID   pgtype.UUID
	PageSize   int32
}

type TrashListPageRow struct {
	ID            pgtype.UUID
	Number        int64
	Subject       string
	Status        string
	Preview       string
	LastMessageAt pgtype.Timestamptz
	MessageCount  int32
	DeletedAt     pgtype.Timestamptz
	MailboxID     pgtype.UUID
	MailboxName   string
	ContactID     pgtype.UUID
	ContactName   pgtype.Text
	ContactEmail  string
	DeletedByID   pgtype.UUID
	DeletedByName pgtype.Text
}

func (q *Queries) TrashListPage(ctx context.Context, arg TrashListPageParams) ([]TrashListPageRow, error) {
	rows, err := q.db.Query(ctx, trashListPage,
		arg.MailboxIds,
		arg.CursorAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrashListPageRow{}
	for rows.Next() {
		var i TrashListPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Subject,
			&i.Status,
			&i.Preview,
			&i.LastMessageAt,
			&i.MessageCount,
			&i.DeletedAt,
			&i.MailboxID,
			&i.MailboxName,
			&i.ContactID,
			&i.ContactName,
			&i.ContactEmail,
			&i.DeletedByID,
			&i.DeletedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trashLockDeleted = `-- name: TrashLockDeleted :one
SELECT id, mailbox_id FROM conversations
WHERE id = $1 AND mailbox_id = ANY($2::uuid[]) AND deleted_at IS NOT NULL
FOR UPDATE
`

type TrashLockDeletedParams struct {
	ID         pgtype.UUID
	MailboxIds []pgtype.UUID
}

type TrashLockDeletedRow struct {
	ID        pgtype.UUID
	MailboxID pgtype.UUID
}

func (q *Queries) TrashLockDeleted(ctx context.Context, arg TrashLockDeletedParams) (TrashLockDeletedRow, error) {
	row := q.db.QueryRow(ctx, trashLockDeleted, arg.ID, arg.MailboxIds)
	var i TrashLockDeletedRow
	err := row.Scan(&i.ID, &i.MailboxID)
	return i, err
}

const trashLockForPurge = `-- name: TrashLockForPurge :many
SELECT c.id, EXISTS (
    SELECT 1 FROM outbound o JOIN messages m ON m.id = o.message_id
    WHERE m.conversation_id = c.id AND o.status IN ('queued', 'sending', 'retry', 'uncertain'))::boolean AS sending
FROM conversations c
WHERE c.id = ANY($1::uuid[]) AND c.mailbox_id = ANY($2::uuid[]) AND c.deleted_at IS NOT NULL
ORDER BY c.id
FOR UPDATE OF c
`

type TrashLockForPurgeParams struct {
	Ids        []pgtype.UUID
	MailboxIds []pgtype.UUID
}

type TrashLockForPurgeRow struct {
	ID      pgtype.UUID
	Sending bool
}

// The given conversations that are in the trash of the mailboxes. sending marks the ones with
// mail still on its way out; they stay, because the send job reads them.
func (q *Queries) TrashLockForPurge(ctx context.Context, arg TrashLockForPurgeParams) ([]TrashLockForPurgeRow, error) {
	rows, err := q.db.Query(ctx, trashLockForPurge, arg.Ids, arg.MailboxIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrashLockForPurgeRow{}
	for rows.Next() {
		var i TrashLockForPurgeRow
		if err := rows.Scan(&i.ID, &i.Sending); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trashMarkDeleted = `-- name: TrashMarkDeleted :one

UPDATE conversations SET deleted_at = now(), deleted_by = $1, version = version + 1, updated_at = now()
WHERE id = $2
RETURNING version
`

type TrashMarkDeletedParams struct {
	DeletedBy pgtype.UUID
	ID        pgtype.UUID
}

// The trash: conversations with deleted_at set. Moving to the trash locks through
// LockConversationForUpdate; everything here works on rows that are already in it.
func (q *Queries) TrashMarkDeleted(ctx context.Context, arg TrashMarkDeletedParams) (int32, error) {
	row := q.db.QueryRow(ctx, trashMarkDeleted, arg.DeletedBy, arg.ID)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const trashPickExpired = `-- name: TrashPickExpired :many
SELECT c.id FROM conversations c
WHERE c.mailbox_id = $1 AND c.deleted_at < $2::timestamptz
  AND NOT EXISTS (
      SELECT 1 FROM outbound o JOIN messages m ON m.id = o.message_id
      WHERE m.conversation_id = c.id AND o.status IN ('queued', 'sending', 'retry', 'uncertain'))
ORDER BY c.id
LIMIT $3::integer
FOR UPDATE OF c SKIP LOCKED
`

type TrashPickExpiredParams struct {
	MailboxID pgtype.UUID
	Before    pgtype.Timestamptz
	BatchSize int32
}

// Conversations of one mailbox that went into the trash before the cutoff; same exclusions as
// RetentionPickConversations.
func (q *Queries) TrashPickExpired(ctx context.Context, arg TrashPickExpiredParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, trashPickExpired, arg.MailboxID, arg.Before, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trashPreviewExpired = `-- name: TrashPreviewExpired :one
WITH picked AS (
    SELECT c.id FROM conversations c
    WHERE c.mailbox_id = $1 AND c.deleted_at < $2::timestamptz
      AND NOT EXISTS (
          SELECT 1 FROM outbound o JOIN messages m ON m.id = o.message_id
          WHERE m.conversation_id = c.id AND o.status IN ('queued', 'sending', 'retry', 'uncertain'))
)
SELECT (SELECT count(*) FROM picked)::bigint AS conversations,
       (SELECT count(*) FROM messages WHERE conversation_id IN (SELECT id FROM picked))::bigint AS messages,
       (SELECT count(*) FROM attachments a JOIN messages m ON m.id = a.message_id
         WHERE m.conversation_id IN (SELECT id FROM picked))::bigint AS attachments,
       (SELECT COALESCE(sum(a.size_bytes), 0) FROM attachments a JOIN messages m ON m.id = a.message_id
         WHERE m.conversation_id IN (SELECT id FROM picked))::bigint AS attachment_bytes
`

type TrashPreviewExpiredParams struct {
	MailboxID pgtype.UUID
	Before    pgtype.Timestamptz
}

type TrashPreviewExpiredRow struct {
	Conversations   int64
	Messages        int64
	Attachments     int64
	AttachmentBytes int64
}

// The counting twin of TrashPickExpired; keep the predicates identical.
func (q *Queries) TrashPreviewExpired(ctx context.Context, arg TrashPreviewExpiredParams) (TrashPreviewExpiredRow, error) {
	row := q.db.QueryRow(ctx, trashPreviewExpired, arg.MailboxID, arg.Before)
	var i TrashPreviewExpiredRow
	err := row.Scan(
		&i.Conversations,
		&i.Messages,
		&i.Attachments,
		&i.AttachmentBytes,
	)
	return i, err
}

const trashRestore = `-- name: TrashRestore :one
UPDATE conversations SET deleted_at = NULL, deleted_by = NULL, version = version + 1, updated_at = now()
WHERE id = $1
RETURNING version
`

func (q *Queries) TrashRestore(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, trashRestore, id)
	var version int32
	err := row.Scan(&version)
	return version, err
}
