// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: unread.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConversationAssignee = `-- name: GetConversationAssignee :one
SELECT assignee_user_id FROM conversations WHERE id = $1
`

func (q *Queries) GetConversationAssignee(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getConversationAssignee, id)
	var assignee_user_id pgtype.UUID
	err := row.Scan(&assignee_user_id)
	return assignee_user_id, err
}

const inboxUnreadMineCount = `-- name: InboxUnreadMineCount :one
SELECT count(*)::integer
FROM conversations
JOIN users ON users.id = $1
LEFT JOIN conversation_reads ON conversation_reads.conversation_id = conversations.id
    AND conversation_reads.user_id = $1
WHERE conversations.assignee_user_id = $1
    AND conversations.mailbox_id = ANY($2::uuid[])
    AND conversations.status = 'open' AND conversations.deleted_at IS NULL
    AND (conversations.snoozed_until IS NULL OR conversations.snoozed_until <= now())
    AND (COALESCE(conversation_reads.marked_unread, false) OR EXISTS (
        SELECT 1 FROM messages
        WHERE messages.conversation_id = conversations.id AND messages.deleted_at IS NULL
            AND messages.created_at > COALESCE(conversation_reads.last_read_at, users.unread_since)
            AND ((messages.kind = 'email' AND messages.direction = 'in')
                OR (messages.kind = 'note' AND messages.author_user_id IS DISTINCT FROM $1))))
`

type InboxUnreadMineCountParams struct {
	UserID     pgtype.UUID
	MailboxIds []pgtype.UUID
}

func (q *Queries) InboxUnreadMineCount(ctx context.Context, arg InboxUnreadMineCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, inboxUnreadMineCount, arg.UserID, arg.MailboxIds)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listUnreadConversationIDs = `-- name: ListUnreadConversationIDs :many
SELECT conversations.id
FROM conversations
JOIN users ON users.id = $1
LEFT JOIN conversation_reads ON conversation_reads.conversation_id = conversations.id
    AND conversation_reads.user_id = $1
WHERE conversations.id = ANY($2::uuid[])
    AND (COALESCE(conversation_reads.marked_unread, false) OR EXISTS (
        SELECT 1 FROM messages
        WHERE messages.conversation_id = conversations.id AND messages.deleted_at IS NULL
            AND messages.created_at > COALESCE(conversation_reads.last_read_at, users.unread_since)
            AND ((messages.kind = 'email' AND messages.direction = 'in')
                OR (messages.kind = 'note' AND messages.author_user_id IS DISTINCT FROM $1))))
`

type ListUnreadConversationIDsParams struct {
	UserID pgtype.UUID
	Ids    []pgtype.UUID
}

func (q *Queries) ListUnreadConversationIDs(ctx context.Context, arg ListUnreadConversationIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listUnreadConversationIDs, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConversationRead = `-- name: MarkConversationRead :exec

INSERT INTO conversation_reads (user_id, conversation_id, last_read_at, marked_unread)
VALUES ($1, $2, now(), false)
ON CONFLICT (user_id, conversation_id)
DO UPDATE SET last_read_at = now(), marked_unread = false
`

type MarkConversationReadParams struct {
	UserID         pgtype.UUID
	ConversationID pgtype.UUID
}

// Per-agent read state. A conversation is unread for a user when they marked it unread, or a
// customer message or a note by someone else arrived after they last read it (or, without a
// read row, after users.unread_since). created_at is the insert time, unlike received_at which
// follows the mail headers and can be far in the past.
func (q *Queries) MarkConversationRead(ctx context.Context, arg MarkConversationReadParams) error {
	_, err := q.db.Exec(ctx, markConversationRead, arg.UserID, arg.ConversationID)
	return err
}

const markConversationUnread = `-- name: MarkConversationUnread :exec
INSERT INTO conversation_reads (user_id, conversation_id, last_read_at, marked_unread)
VALUES ($1, $2, now(), true)
ON CONFLICT (user_id, conversation_id)
DO UPDATE SET marked_unread = true
`

type MarkConversationUnreadParams struct {
	UserID         pgtype.UUID
	ConversationID pgtype.UUID
}

func (q *Queries) MarkConversationUnread(ctx context.Context, arg MarkConversationUnreadParams) error {
	_, err := q.db.Exec(ctx, markConversationUnread, arg.UserID, arg.ConversationID)
	return err
}
