export const webhookEvents = [
  { value: 'conversation.created', label: 'Gesprek aangemaakt' },
  { value: 'conversation.updated', label: 'Gesprek gewijzigd' },
  { value: 'conversation.status_changed', label: 'Status van gesprek gewijzigd' },
  { value: 'conversation.assigned', label: 'Gesprek toegewezen' },
  { value: 'conversation.automation', label: 'Regel: webhook-actie' },
  { value: 'message.created', label: 'Bericht ontvangen' },
  { value: 'message.sent', label: 'Bericht verzonden' },
  { value: 'message.failed', label: 'Bericht niet verzonden' },
  { value: 'contact.created', label: 'Contact aangemaakt' },
] as const

const eventLabels: Record<string, string> = {
  ...Object.fromEntries(webhookEvents.map((e) => [e.value, e.label])),
  'webhook.test': 'Testbericht',
}

export const eventLabel = (event: string) => eventLabels[event] ?? event

export type DeliveryStatus = 'pending' | 'retrying' | 'succeeded' | 'failed'

export const deliveryStatusLabel: Record<DeliveryStatus, string> = {
  pending: 'In wachtrij',
  retrying: 'Opnieuw proberen',
  succeeded: 'Afgeleverd',
  failed: 'Mislukt',
}

const deliveryErrors: Record<string, string> = {
  http_status: 'De ontvanger gaf een foutcode terug.',
  blocked_destination: 'Adres geweigerd: het verwijst naar een intern netwerk.',
  timeout: 'De ontvanger reageerde niet binnen 10 seconden.',
  tls_error: 'Beveiligde verbinding mislukt.',
  dns_error: 'De servernaam is niet gevonden.',
  connection_failed: 'Geen verbinding met de ontvanger.',
  webhook_disabled: 'De webhook staat uit.',
}

export const deliveryErrorLabel = (code: string) => deliveryErrors[code] ?? 'Onbekende fout.'

export const disabledReasonLabel = (reason: string) =>
  reason === 'too_many_failures' ? 'Uitgezet na 50 mislukte pogingen achter elkaar.' : 'Uitgezet.'

// Audit actions are shown by group; the filter matches on the prefix.
export const auditGroups = [
  { prefix: '', label: 'Alle acties' },
  { prefix: 'auth.', label: 'Inloggen en beveiliging' },
  { prefix: 'user.', label: 'Gebruikers' },
  { prefix: 'team.', label: 'Teams' },
  { prefix: 'mailbox.', label: 'Mailboxen' },
  { prefix: 'conversations.', label: 'Gesprekken' },
  { prefix: 'blocklist.', label: 'Blokkeerlijst' },
  { prefix: 'settings.', label: 'Instellingen' },
  { prefix: 'api_token.', label: 'API-tokens' },
  { prefix: 'webhook.', label: 'Webhooks' },
  { prefix: 'automation.', label: 'Automatisering' },
  { prefix: 'contact.', label: 'Contacten' },
  { prefix: 'campaign.', label: 'Campagnes' },
  { prefix: 'kb.', label: 'Kennisbank' },
  { prefix: 'template.', label: 'Standaardantwoorden' },
  { prefix: 'label.', label: 'Labels' },
  { prefix: 'role.', label: 'Rollen' },
  { prefix: 'job.', label: 'Taken' },
  { prefix: 'raw_message.', label: 'Opgeslagen mail' },
  { prefix: 'audit.', label: 'Auditlog' },
] as const

const auditActions: Record<string, string> = {
  'auth.login': 'Ingelogd',
  'auth.login_failed': 'Inloggen mislukt',
  'auth.account_locked': 'Account tijdelijk geblokkeerd',
  'auth.mfa_failed': 'Tweestapscode onjuist',
  'auth.logout': 'Uitgelogd',
  'auth.logout_others': 'Andere sessies afgemeld',
  'auth.session_revoked': 'Sessie afgemeld',
  'auth.password_changed': 'Wachtwoord gewijzigd',
  'auth.mfa_enabled': 'Tweestapsverificatie ingeschakeld',
  'auth.mfa_disabled': 'Tweestapsverificatie uitgeschakeld',
  'auth.recovery_codes_regenerated': 'Herstelcodes vernieuwd',
  'user.created': 'Gebruiker aangemaakt',
  'user.renamed': 'Gebruiker hernoemd',
  'user.role_changed': 'Rol gewijzigd',
  'user.deactivated': 'Gebruiker gedeactiveerd',
  'user.reactivated': 'Gebruiker geheractiveerd',
  'user.password_reset': 'Wachtwoord gereset',
  'user.mfa_reset': 'Tweestapsverificatie gereset',
  'team.created': 'Team aangemaakt',
  'team.renamed': 'Team hernoemd',
  'team.deleted': 'Team verwijderd',
  'team.members_changed': 'Teamleden gewijzigd',
  'settings.security_changed': 'Beveiligingsinstellingen gewijzigd',
  'mailbox.created': 'Mailbox aangemaakt',
  'mailbox.updated': 'Mailbox gewijzigd',
  'mailbox.disabled': 'Mailbox uitgeschakeld',
  'mailbox.enabled': 'Mailbox ingeschakeld',
  'mailbox.secret_changed': 'Wachtwoord van mailbox gewijzigd',
  'mailbox.access_changed': 'Toegang tot mailbox gewijzigd',
  'mailbox.stored_secret_tested': 'Verbinding getest met het opgeslagen wachtwoord van een mailbox',
  'mailbox.internal_host_changed': 'Interne mailserver toegestaan of ingetrokken',
  'api_token.created': 'API-token aangemaakt',
  'api_token.revoked': 'API-token ingetrokken',
  'webhook.created': 'Webhook aangemaakt',
  'webhook.updated': 'Webhook gewijzigd',
  'webhook.deleted': 'Webhook verwijderd',
  'webhook.tested': 'Testbericht verstuurd',
  'webhook.delivery_resent': 'Aflevering opnieuw verstuurd',
  'webhook.auto_disabled': 'Webhook automatisch uitgezet',
  'automation.rule_created': 'Regel aangemaakt',
  'automation.rule_updated': 'Regel gewijzigd',
  'automation.rule_deleted': 'Regel verwijderd',
  'automation.rules_reordered': 'Volgorde van regels gewijzigd',
  'automation.sla_policy_created': 'SLA-beleid aangemaakt',
  'automation.sla_policy_updated': 'SLA-beleid gewijzigd',
  'automation.sla_policy_deleted': 'SLA-beleid verwijderd',
  'automation.business_hours_created': 'Werktijdenschema aangemaakt',
  'automation.business_hours_updated': 'Werktijdenschema gewijzigd',
  'automation.business_hours_deleted': 'Werktijdenschema verwijderd',
  'automation.macro_created': 'Macro aangemaakt',
  'automation.macro_updated': 'Macro gewijzigd',
  'automation.macro_deleted': 'Macro verwijderd',
  'automation.settings_changed': 'Automatiseringsinstellingen gewijzigd',
  'automation.mailbox_changed': 'Toewijzing of SLA van mailbox gewijzigd',
  'automation.capacity_changed': 'Capaciteit van agent gewijzigd',
  'job.retried': 'Taak opnieuw gestart',
  'raw_message.retried': 'Opgeslagen mail opnieuw verwerkt',
  'audit.exported': 'Auditlog geëxporteerd',
  'user.invited': 'Gebruiker uitgenodigd',
  'user.invitation_resent': 'Uitnodiging opnieuw verstuurd',
  'user.invitation_revoked': 'Uitnodiging ingetrokken',
  'user.invitation_accepted': 'Uitnodiging geaccepteerd',
  'auth.password_reset_requested': 'Wachtwoordherstel aangevraagd',
  'auth.password_reset_completed': 'Wachtwoord hersteld via e-mail',
  'mailbox.oauth_connected': 'Mailbox gekoppeld via OAuth',
  'mailbox.oauth_failed': 'Koppelen via OAuth mislukt',
  'settings.retention_changed': 'Bewaartermijnen gewijzigd',
  'retention.purged': 'Opgeruimd volgens bewaartermijn',
  'audit.purged': 'Oude auditregels opgeruimd',
  'uploads.purged': 'Verlopen uploads opgeruimd',
  'keys.rotated': 'Versleutelingssleutels vernieuwd',
  'blobs.orphans_deleted': 'Losse bestanden opgeruimd',
  'contact.created': 'Contact aangemaakt',
  'contact.updated': 'Contact gewijzigd',
  'contact.merged': 'Contacten samengevoegd',
  'contact.erased': 'Contact gewist',
  'contact.erase_incomplete': 'Contact gewist, opruimen onvolledig',
  'contact.exported': 'Contacten geëxporteerd',
  'contact.data_export_requested': 'Gegevensexport aangevraagd',
  'contact.data_export_downloaded': 'Gegevensexport gedownload',
  'contact.import_started': 'Contactimport gestart',
  'contact.unsubscribed': 'Contact afgemeld voor campagnes',
  'contact.resubscribed': 'Afmelding van contact opgeheven',
  'contact.address_reactivated': 'Onbereikbaar adres weer in gebruik genomen',
  'organization.created': 'Organisatie aangemaakt',
  'organization.updated': 'Organisatie gewijzigd',
  'custom_attribute.created': 'Veld aangemaakt',
  'custom_attribute.updated': 'Veld gewijzigd',
  'custom_attribute.deleted': 'Veld verwijderd',
  'contact_segment.created': 'Segment aangemaakt',
  'contact_segment.updated': 'Segment gewijzigd',
  'contact_segment.deleted': 'Segment verwijderd',
  'template.created': 'Standaardantwoord aangemaakt',
  'template.updated': 'Standaardantwoord gewijzigd',
  'template.deleted': 'Standaardantwoord verwijderd',
  'label.created': 'Label aangemaakt',
  'label.updated': 'Label gewijzigd',
  'label.deleted': 'Label verwijderd',
  'kb.portal_updated': 'Openbare kennisbank gewijzigd',
  'kb.category_created': 'Categorie aangemaakt',
  'kb.category_updated': 'Categorie gewijzigd',
  'kb.category_deleted': 'Categorie verwijderd',
  'kb.article_published': 'Artikel gepubliceerd',
  'kb.article_unpublished': 'Artikel teruggezet naar concept',
  'kb.article_archived': 'Artikel gearchiveerd',
  'kb.article_deleted': 'Artikel verwijderd',
  'role.created': 'Rol aangemaakt',
  'role.updated': 'Rol gewijzigd',
  'role.deleted': 'Rol verwijderd',
  'campaign.created': 'Campagne aangemaakt',
  'campaign.updated': 'Campagne gewijzigd',
  'campaign.deleted': 'Campagne verwijderd',
  'campaign.started': 'Campagne gestart',
  'campaign.scheduled': 'Campagne ingepland',
  'campaign.paused': 'Campagne gepauzeerd',
  'campaign.resumed': 'Campagne hervat',
  'campaign.cancelled': 'Campagne geannuleerd',
  'campaign.test_sent': 'Testmail van campagne verstuurd',
  'campaign.report_exported': 'Campagnerapport geëxporteerd',
  'mailbox.signature_changed': 'Handtekening van mailbox gewijzigd',
  'mailbox.sender_images_allowed': 'Externe afbeeldingen van afzender toegestaan',
  'mailbox.csat_changed': 'Tevredenheidsenquête van mailbox gewijzigd',
  'settings.email_changed': 'E-mailinstellingen gewijzigd',
  'settings.sso_changed': 'SSO-instellingen gewijzigd',
  'settings.reports_changed': 'Rapportage-instellingen gewijzigd',
  'report.exported': 'Rapport geëxporteerd',
  'conversations.purged': 'Gesprekken definitief verwijderd',
  'blocklist.added': 'Afzender geblokkeerd',
  'blocklist.removed': 'Blokkering opgeheven',
}

const auditTargets: Record<string, string> = {
  user: 'Gebruiker',
  team: 'Team',
  role: 'Rol',
  mailbox: 'Mailbox',
  label: 'Label',
  template: 'Standaardantwoord',
  rule: 'Regel',
  macro: 'Macro',
  sla_policy: 'SLA-beleid',
  business_hours: 'Werktijden',
  contact: 'Contact',
  organization: 'Organisatie',
  custom_attribute: 'Veld',
  contact_segment: 'Segment',
  kb_article: 'Artikel',
  kb_category: 'Categorie',
  kb_portal: 'Kennisbank',
  campaign: 'Campagne',
  api_token: 'API-token',
  webhook: 'Webhook',
  job: 'Taak',
  raw_message: 'Opgeslagen mail',
  audit_log: 'Auditlog',
  blocked_sender: 'Geblokkeerde afzender',
}

// What an entry acted on: the readable name from its metadata when there is one, else the type
// and the start of the id.
export function auditTarget(type: string, id: string, metadata: Record<string, unknown>): string {
  if (!type) return '—'
  const label = auditTargets[type] ?? type
  const named = [metadata.name, metadata.title, metadata.key, metadata.pattern].find((v): v is string => typeof v === 'string' && v !== '')
  return named ? `${label}: ${named}` : id ? `${label} ${id.slice(0, 8)}` : label
}

export const auditActionLabel = (action: string) => auditActions[action] ?? action
