package send

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/riverqueue/river"

	"echoo/internal/db/dbq"
	"echoo/internal/jobs"
	"echoo/internal/mail"
)

const (
	pgUniqueViolation    = "23505"
	idempotencyKeyUnique = "outbound_idempotency_key_key"
)

// ErrNotCancellable is returned by Cancel when the message is no longer waiting to be sent.
var ErrNotCancellable = errors.New("message is no longer queued")

// AttachmentRef points at a blob that is already stored.
type AttachmentRef struct {
	Filename    string
	ContentType string
	ContentID   string // required when Inline
	Inline      bool
	Size        int64
	SHA256      []byte
	BlobKey     string
}

// EnqueueParams describe one reply or new message. The sender is the mailbox itself.
type EnqueueParams struct {
	ConversationID pgtype.UUID
	MailboxID      pgtype.UUID
	// IdempotencyKey is generated by the client; reusing it returns the earlier message.
	IdempotencyKey pgtype.UUID
	AuthorUserID   pgtype.UUID // invalid for system-generated mail
	To, Cc, Bcc    []mail.Address
	Subject        string
	Text, HTML     string
	InReplyTo      string // without angle brackets
	References     []string
	AutoReplied    bool
	Attachments    []AttachmentRef
	Headers        []Header
}

// Enqueued identifies the queued message. Duplicate is set when the idempotency key was
// used before and nothing new was queued.
type Enqueued struct {
	MessageID       pgtype.UUID
	MessageIDHeader string
	Duplicate       bool
}

// Enqueue stores the message, its outbound row and the send job in tx, so all three commit
// or none does. The job is scheduled after the mailbox's undo-send delay.
func Enqueue(ctx context.Context, tx pgx.Tx, client *river.Client[pgx.Tx], p EnqueueParams) (Enqueued, error) {
	q := dbq.New(tx)
	mb, err := q.SendGetMailbox(ctx, p.MailboxID)
	if err != nil {
		return Enqueued{}, fmt.Errorf("load mailbox: %w", err)
	}
	_, domain, ok := strings.Cut(mb.EmailAddress, "@")
	if !ok {
		return Enqueued{}, fmt.Errorf("mailbox address %q has no domain", mb.ID.String())
	}
	messageID, err := mail.NewOutboundMessageID(p.ConversationID.Bytes, domain)
	if err != nil {
		return Enqueued{}, fmt.Errorf("generate message id: %w", err)
	}
	now := time.Now().UTC()
	if err := p.outgoing(mb, messageID, now).validate(); err != nil {
		return Enqueued{}, err
	}
	scheduledAt := now.Add(time.Duration(mb.SendDelaySeconds) * time.Second)

	id, err := insertQueued(ctx, tx, p, mb, messageID, scheduledAt)
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) && pgErr.Code == pgUniqueViolation && pgErr.ConstraintName == idempotencyKeyUnique {
		existing, err := q.SendGetEnqueuedByKey(ctx, p.IdempotencyKey)
		if err != nil {
			return Enqueued{}, fmt.Errorf("load earlier message: %w", err)
		}
		return Enqueued{MessageID: existing.MessageID, MessageIDHeader: existing.MessageIDHeader, Duplicate: true}, nil
	}
	if err != nil {
		return Enqueued{}, err
	}
	// River only promotes scheduled jobs every few seconds; without an undo delay the job is
	// inserted as available so the reply leaves immediately. The outbound row stays the
	// source of truth for when a send is due.
	opts := &river.InsertOpts{}
	if mb.SendDelaySeconds > 0 {
		opts.ScheduledAt = scheduledAt
	}
	_, err = client.InsertTx(ctx, tx, jobs.SendOutbound{MessageID: id.String()}, opts)
	if err != nil {
		return Enqueued{}, fmt.Errorf("enqueue send job: %w", err)
	}
	return Enqueued{MessageID: id, MessageIDHeader: messageID}, nil
}

func (p EnqueueParams) outgoing(mb dbq.Mailbox, messageID string, now time.Time) Outgoing {
	out := Outgoing{
		From:        mail.Address{Name: mb.DisplayName, Address: mb.EmailAddress},
		To:          p.To,
		Cc:          p.Cc,
		Bcc:         p.Bcc,
		Subject:     p.Subject,
		MessageID:   messageID,
		InReplyTo:   p.InReplyTo,
		References:  p.References,
		Date:        now,
		Text:        p.Text,
		HTML:        p.HTML,
		AutoReplied: p.AutoReplied,
		Headers:     p.Headers,
	}
	for _, a := range p.Attachments {
		out.Attachments = append(out.Attachments, mail.Attachment{
			Filename: a.Filename, DeclaredType: a.ContentType, ContentID: a.ContentID, Inline: a.Inline,
		})
	}
	return out
}

// insertQueued runs in a savepoint: a unique violation on the idempotency key aborts the
// statement, and rolling the savepoint back keeps the caller's transaction usable and free of
// the half-inserted message.
func insertQueued(ctx context.Context, tx pgx.Tx, p EnqueueParams, mb dbq.Mailbox, messageID string, scheduledAt time.Time) (id pgtype.UUID, err error) {
	sp, err := tx.Begin(ctx)
	if err != nil {
		return id, fmt.Errorf("begin savepoint: %w", err)
	}
	defer func() {
		if err != nil {
			if rbErr := sp.Rollback(ctx); rbErr != nil && !errors.Is(rbErr, pgx.ErrTxClosed) {
				err = errors.Join(err, rbErr)
			}
		}
	}()
	q := dbq.New(sp)

	to, cc, bcc, err := marshalRecipients(p)
	if err != nil {
		return id, err
	}
	hash := mail.HashMessageID(mail.NormalizeMessageID(messageID))
	id, err = q.SendInsertMessage(ctx, dbq.SendInsertMessageParams{
		ConversationID: p.ConversationID, MailboxID: p.MailboxID,
		MessageIDHeader: messageID, MessageIDHash: hash,
		InReplyTo: p.InReplyTo, ReferencesHdr: nonNil(p.References),
		FromAddr: mb.EmailAddress, FromName: mb.DisplayName,
		ToAddrs: to, CcAddrs: cc, BccAddrs: bcc,
		Subject: p.Subject, BodyText: p.Text, BodyHtml: p.HTML,
		AutoSubmitted: p.AutoReplied, AuthorUserID: p.AuthorUserID,
	})
	if err != nil {
		return id, fmt.Errorf("insert message: %w", err)
	}
	headers, err := json.Marshal(nonNilHeaders(p.Headers))
	if err != nil {
		return id, fmt.Errorf("marshal headers: %w", err)
	}
	err = q.SendInsertOutbound(ctx, dbq.SendInsertOutboundParams{
		MessageID: id, IdempotencyKey: p.IdempotencyKey, ScheduledAt: ts(scheduledAt), CreatedBy: p.AuthorUserID,
		ExtraHeaders: headers,
	})
	if err != nil {
		return id, fmt.Errorf("insert outbound: %w", err)
	}
	// Replies to this message must thread even before we ever see the message again.
	err = q.SendInsertThreadRef(ctx, dbq.SendInsertThreadRefParams{
		MailboxID: p.MailboxID, MessageIDHash: hash, ConversationID: p.ConversationID,
	})
	if err != nil {
		return id, fmt.Errorf("insert thread ref: %w", err)
	}
	for _, a := range p.Attachments {
		disposition := "attachment"
		if a.Inline {
			disposition = "inline"
		}
		err = q.SendInsertAttachment(ctx, dbq.SendInsertAttachmentParams{
			MessageID: id, Filename: a.Filename, DeclaredType: a.ContentType, SizeBytes: a.Size,
			Sha256: a.SHA256, BlobKey: a.BlobKey, ContentID: a.ContentID, Disposition: disposition,
		})
		if err != nil {
			return id, fmt.Errorf("insert attachment: %w", err)
		}
	}
	if err = sp.Commit(ctx); err != nil {
		return id, fmt.Errorf("release savepoint: %w", err)
	}
	return id, nil
}

func marshalRecipients(p EnqueueParams) (to, cc, bcc []byte, err error) {
	var out [3][]byte
	for i, list := range [][]mail.Address{p.To, p.Cc, p.Bcc} {
		if list == nil {
			list = []mail.Address{}
		}
		if out[i], err = json.Marshal(list); err != nil {
			return nil, nil, nil, fmt.Errorf("marshal recipients: %w", err)
		}
	}
	return out[0], out[1], out[2], nil
}

func nonNilHeaders(h []Header) []Header {
	if h == nil {
		return []Header{}
	}
	return h
}

func nonNil(s []string) []string {
	if s == nil {
		return []string{}
	}
	return s
}

// Cancel implements undo send: it succeeds only while the message is still queued. Any job
// that is already scheduled becomes a no-op.
func Cancel(ctx context.Context, tx pgx.Tx, messageID pgtype.UUID) error {
	n, err := dbq.New(tx).SendCancelOutbound(ctx, messageID)
	if err != nil {
		return fmt.Errorf("cancel outbound: %w", err)
	}
	if n == 0 {
		return ErrNotCancellable
	}
	return nil
}
